//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laavor
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CheckFit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckFit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasePackage.Checks.CheckFit", typeof(CheckFit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHaSURBVHic7dWxTVxhFAXhectK7gCXQEZRTmgCyV5BEwiJjpw4cwcsHTi6bsBstu+3NPOlNznBSHdj5gb4DjwAt8TgA3gBThszT8Dj4kFZ43lj5h34unpJljhvzMzqFVnnsHpA1ioAueOF2zfg115DclX3wNu/DpcC+M22/bzOnuxq5stnp16AXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA3uSURBVHic7Z15sB1Vncc/v5fwCCEkoEwkjODCDMiiUixqMTLjQrlQIosadq1BJWwDmIgZjYICLpTghlKDZChRISCCKIqKiCiIhQiCWBhFHEHAEDFkQiBAkvf1j2/f6pub9+67W/ftvrc/VSlen9u3+8c9v+5zfsv5nUCaApwBzANmUzEMLAcuBD4WSGcBH+6zQBX94exAWgY8r9+SVPSFRwNJ/Zaion+M9FuAiv5SKcCQM7XJZ8cAv8lLkIpMeRlw8XgfNFOA3xNxRzbyVOSKtOlEH1VDwJBTKcCQUynAkFMpwJBTKcCQUynAkFMpwJBTKcCQUynAkFMpwJBTKcCQUynAICI1i/FsQKUAg4Z0CLAU [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AquaSelected {
            get {
                return ResourceManager.GetString("AquaSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHcSURBVHic7da9TQNRGAXR8Y9E4ICQEiwSSoBe6IMACkBUQDHkJGR0wNIBkQkMGXbmfUgzR9roS660I68BVsADMAG7HsUz/bzz1e/LvwM2xGID3ADLBfABXIzdk0GmBfufhEgtRw/IWAUgtz5yuwXe5hqSk7oCnv86HAvgHXg9yZzM7ezQoU+AXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA3/SURBVHic7Z15lBxFHcc/s7O5E85AOCQSg5ySKFGQcD08OeSSI4EIEUQjdyBA5BA5FI2AIMghXjwEBG8QFTCCnD4RUDGCRsUAQjYhWWIScuzu7PjHt+pV7+z07M5MT09Pd33f6zfdc3TX9O9bVb/6XQ2QBy4HlgBFv2ViW2JknrfC/zwwCo+sYBSwH9CWAzqAcc1tj0eTsCSHhgSPjKKt2Q3waC48ATKO9gqfnQQ8H1dDPBqKScB3y31QiQD/AJ5tSHM84sawsA/8FJBxeAJkHJ4AGYcnQMbhCZBxeAJkHJ4AGYcnQMbhCZBxeAJkHJ4AGYcnQDoxZLBf9ARIH44CXgR2GewPwgIHpzaidR4NxQyg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlackSelected {
            get {
                return ResourceManager.GetString("BlackSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHXSURBVHic7dUxLkVRFEbhdR+JQs8QRGNQGpOQINR6kRiMXqMzA88MVMcEeN27R7LW1+7mL1ayFxgHwA1wBZwQgy/gCbhbYNwD15MHZY6HBcYncDp7SabYLjDG7BWZZzN7QOYqALnDHbdL4H2tIdmrC+Dlt8OuAD5gedvPnqxrHP116QXIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAIDSURBVHic7dUhTkNBGEXh+782QdRUgQYEgRC2wCboBjCsghBYAJ6QsAF2gcfgEKSWorCoYQN9sm/EOZ/9zU3mJFPJapbDdpeqmyT7EcFPWnvKuu5nOTx/SOU2yaL3Kk1mkarLLGuoHK2+kxz0XqQuNkN8fLKDofcC9WUAcPPxU7tO1cd0U7QzrV0k9bLtNB5A5TNfr+87G6XpHF/tpW0/+QXAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDark {
            get {
                return ResourceManager.GetString("BlueDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABPJSURBVHic7Z17lBxVncc/v1s9eRCQJCZEkEe6J7xCUIFVXMVjXJXDussrmZ4EMIiAvF8SIAsIhIjsohgVFxTCm4WQ6UlUgrxDIkQ9Hg+oC7IQ5wEhkgRCyDuT6a772z9u9WOGJCaZ7qru6fqcU6e6bnVX/bp+3/u799ate0sg7ZHUGxA5F9iLmHrgXVTvpFNu9EiOm4FwHTAkaqtiQmMIIl9kqBghlV4BjIraophIWGmInV/PjDJRWxATLbEA6pzEtnfpmYj8b3imxFQM1U+A3Lu1XdsWgPAG7ZmXKmZUTHg0Ng1Et74rLgLqnFgAdU4sgDonFkCdEwugzokFUOfEAqhzYgHUObEA6pxYAHVOLIA6 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDarkSelected {
            get {
                return ResourceManager.GetString("BlueDarkSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAH/SURBVHic7dWxTcNQGEXh+4wlNkh6N3SUjMIASChLgAhjICQGCJsg0dDRpE82oEA/C+DSfsU5X/s3V/KRXzsc6qJNeapkl2QTEZxb8lLHPI81ZZ/kofcirWpTyWNNaUNL7nuvUR8tuR+SbHsPUTfbofcC9WUAcOPcobXcVfK15hgtoyXXVXn77zYbQH7zfXvTPhdbpdW8f9Tl3L/eJwDOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLight {
            get {
                return ResourceManager.GetString("BlueLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABTESURBVHic7Z15mB1VmYff36nbnQWChCWAjAtBZCACmu4ERNQn+rigwyCQ3DSLoixGNmFAiTCoAVeGcRhFZBUVgaRvh6CEQUQwQhDH9O2wCCKokREViCGEkKVzq+p888ep290Ji1n6Lp2u93nquXW3qu/W+Z3znfrOOd9VqWSRxvNFgxnAOHKGA0sFV9kSLizYeGYBFzTaopy6Ms7g8zYeOcHJjbYmpzEITnbALo02JKdh7OIabUFOY8kFMMwpvNIbEicYPFxPY3Jqg2B/M657ufdeUQCkPF6crJ6aWZVTN7oW2YhXautzFzDMyQUwzMkFMMzJBTDMyQUwzMkFMMzJBTDMyQUwzMkFMMzJBTDMyQUw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLightSelected {
            get {
                return ResourceManager.GetString("BlueLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAYAAABV7bNHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAJEwAACRMBlIFZXwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAb2SURBVHic7dx/jFxVFQfwz922YiFSsYBolYpoCFEQKdrEmkpSExvEBGtaWmpBWqRWpFJaWYyC1fBLG/BHoYixaCj4A6tUDUptSVRKwF+pihaICFakChYFKv2x7fb6x3mTmS7tzu7Mm23ZnW9yM/tm3r3n7HfuPffcc868RJ6Hz+Nl2qjFFnQm8nPa5OwLWxI5728tDmQM73F9L9btD0UOILwTE2quc65pi/eTUgcQ8uJaTjr2tzoHOtoE1UGboDpoE1QHbYLqoE1QHbQJAnkGefbePmkTJH8IKzBxb58OcYLyh7EcD+Gje7tjCBOU5+EmbMM00ta93TVECcqXYBkS5pE27OvOIUhQ7hTxL7iJtKK3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSelected {
            get {
                return ResourceManager.GetString("BlueSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAIDSURBVHic7dUxLkVRFEbhf18v0dI8Q9AZDROQvJgEwTB4iQEwFo3OEGhoFWwTeLd89xRrfe1u/uSs5NTFcx/0V24ruUqyjgg+O3mo49yv6jt3Sa5HL9Ki1pXc1Hdq6s5m9BqN0Z3NlORk9BANczKNXqCxDABuNXfozmUd5G3JMdqP/s1ZVZ523WYDyJT3l0297m2VFnP+2Ifp3Te/ADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSky {
            get {
                return ResourceManager.GetString("BlueSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABP3SURBVHic7Z15lFxVncc/v/uqk7BJgmxBURgXVhdw3PHIHJfDOMNi0lUJaBRIeglgQBAZQKBBhhlcUNGQrk4ACQMhXZ2oBEFAFiXo8XBwGRhGUHREJAECCYEkna569zt/3Ffd1U0iWWrr9Pv0eadevVdd71fv972/u99n2V5FWs0lBh3A3qSMBZ4T5G0Sl2ZsDV3AVxptUUpd2dvgIluDOYm2RluT0hgk2hywT6MNSWkY+7hGW5DSWFIBjHEymzshcapF/Hc9jUmpDYp5pxnXbercZgWA4/FCmz1cM6tS6kZrj8ajTZ9Ls4AxTiqAMU4qgDFOKoAxTiqAMU4qgDFOKoAxTiqAMU4qgDFOKoAxTiqA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSkySelected {
            get {
                return ResourceManager.GetString("BlueSkySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAIgSURBVHic7dUxalRRGIbh7z8TsEifVANjFRjUztpVuAEluAFbMZomhRuQQBaQvdgoCFYqVhkbsbOYOW5grt3cg7zv0/5c+OC+3Fu3T/vi6+cfryv9RVInEUDf9NT7++vlm8Xjev62kldJHY+epbnUcSVPfv383VqS89FzNMx5S3I6eoWGOW2jF2gsA4A7mjr0nmeLRf845xgdxnZbj6pys+82HUDbfXn5afXhcLM0l6sH3+5V3/+x9xcAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABJGSURBVHic7Z17eJxVncc/3zPpLS0tCFSonaTl3kxaL0X3WVdXXH3U9VFUlIogugtqVbBAaRIuj5AVhSYpsovLowjyCC53LyAKCltALrqoeKGdFrTQJmmxtogINKRN5nz3j5nUUnpJ2pnJTPJ+/przvue855u835n3Pbff0S3HO7V6RfeFwvNBU0kYBXiD0ZUzG9L/kXqjTv2S4IugicMtK6FcaKLgbc9tfD4E4NPDLSdh2Ph0AF493CoSho1Xh+FWkDC8JAYY5dTs7ITNKamUHyunmITSkMtpjsQ1Ozq3cwOE+MSiZTMeLZ2shHKxuHHNOHnHP/bJI2CUkxhglJMYYJSTGGCUkxhglJMYYJSTGGCU [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueVioletSelected {
            get {
                return ResourceManager.GetString("BlueVioletSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAILSURBVHic7dWxSkJxGIbx9xyFCPfcXSSDhqAt6Cq6gUCC7iFML6A9BC+gy2iNloagpV0dnBvsdAM6ev7B8/zWb3mHB77q5Sadz+9MktwlOYkIVkmeR4NMO2fHmSV5SNIrPErt6SW5Xm9S10nGpdeomHGdpF96hYrp16UXqCwDgOvuO1RNbqvko80xOowmOW+qLHbd9gbQdPI1ecv74WapLY+XOcrv7psvAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAM [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABNySURBVHic7Z19uFRVvcc/v7Xn8KKgSCbZiylZKirJmYPWzfvofar7+HRv6mOBaFmmJmqlBRGJwlnnQJRZVHatDNO0my9g3ArTxAwTjIdgDpbGTfPlZiaiiMibcGb2+t0/1po5wwESODOzZ87sz3n2M3vvedm/s3/f9b7Wb8u8cUSrn6YdmAgcQkoz8CJww6iRdETHDqYTmA7sn7BRKbVjf+CUl17BGODTSVuTkhifNsCIpK1ISYwRJmkLUpIlFUCTk9ndG6JcIPCnWhqTUh0URqtw067e260ANOLx9hXkqmdWSq2wYxmI2/V7aRHQ5KQCaHJSATQ5qQCanFQATU4qgCYnFUCTkwqgyUkF0OSkAmhy [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrownSelected {
            get {
                return ResourceManager.GetString("BrownSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAICSURBVHic7dWxaWNBGEXhO88CB87XJRhGsC1sLwazVRi9lapYDC5AvTjZQOASLFXg6HcDfqHewJ7zpT8DNzgw7Xg83pxOp12S30l+RATnJH97739uttvtPslzkrvBo7SeuyS/LpfLNCV5Gr1GwzxNSe5Hr9Aw99PoBRrLAOA2S4fW2mNr7d+aY3QdVfWzql6/uy0GUFXvu93u7XqztJZ5nm+Xbn4BcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAICSURBVHic7dUxTgJRGEXhOzMkFlY00tMQG0tWwEpMiJswMURre0PiAliGJYHGzmZ62IEFeW6AKeGZnPO1f3OLk/eazWbTTafTlyRPSe4igmOSj77vV81ut3tN8lx7kap4a5Msa69QNcs2yaT2ClUzaWsvUF0GADcaOjRN85jk+4pbdDkPpZTPc4fBAE6n0898Pt9fbpOuZbvd3rTt+cfeLwDOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLight {
            get {
                return ResourceManager.GetString("GrayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABTASURBVHic7Z17lBxVncc/v1s9kwSSgQCCoChEkUcATXf1ZIzxaI7o4bgreFCHgCIIyFNBwchRBOQhu4ii4rKKIArs8hiRVUEQJI4CopmunhgwrrzGFZGXgCETmKSr6v72j7o16UxmQh79zNTnnDrddaur6td1v/f9u7ekr6/PmzVr1nnAicDOZEwGngOuHBoaOl+CILgQ+FKzLcpoChcZ4JPNtiKjaXzSALs024qMprGLabYFGc0lE8AkJzfRARE5FniwgbZk1I8DVfWa8Q5MKIA4jh/u7u4u18+mjEYxMDAwxZjxM/usCJjkZAKY5GQCmORkApjkZAKY5GQCmORkApjkZAKY5GQCmORkApjkZAKY [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLightSelected {
            get {
                return ResourceManager.GetString("GrayLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABY8SURBVHic7Z17lBxVnce/v1vVPd2TmZ7px0xAFhUR2UwUVtFVFPSo64N1XQUxIKggiBF5GoRATLpvdwIBo7CiCAFkFUFgWMEFREEREcSzLr5WNkpUFkSdZDLpZ3q6uqruvftH3Zp0hokkmenXTH3OqdPd1d23ft2/733f+ysaHR01Nm3alAGwHMAwAhYC4wA2joyMZI2lS5fmAKwBsKjNRgW0jkUA3rJt2zbGAJzRbmsC2sYZDMDidlsR0DYWs3ZbENBeAgEscMzdvUFEpxHR/7TSmIDmoJQ6TCl100zv7VYASqmnMpnMz5tnVkCr4Jz37O69oApY4AQCWOAEAljgBAJY4AQCWOAEAljgBAJY4AQC [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GraySelected {
            get {
                return ResourceManager.GetString("GraySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAH1SURBVHic7dWxaRxhGAbh2T2Bg8utEoRkUAvqxYnBPZiTVIBzI1ABLsO5EgUGd+CTKnC0bkAb3v6gmSf9WHhhB/6Jn+z4zQH4AnwkBi/AD6642/GJe+AbsB88KtvZAze8Mk/c8hc4H70oQxxn+vlm5/PoBRmrAOTOVi8Tn5l43nBLTmXhmoXHt07rASz84cDTyUZlO7d8WDv1BMgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAIFSURBVHic7dUhTkNBGEXh+782QdRUgS4IAiFsgU3QDWBYBSGwADwhYQPsAo/BIUgtRWFRwwZ4sm/EOZ/9zU3mJFNZZ7Zqua3KdZL9iOC7tTxuKnez1VnuK7lJsui9SpNZVOViWRnqcJ2vJAe9F6mL7RAfn+xg6L1AfRkA3Hz00nJVlfcJt2hHWst5Ks//3UYDqOTj8yVvu5ulqRxdZq+N3PwC4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDark {
            get {
                return ResourceManager.GetString("GreenDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAH1SURBVHic7dYhbtRBHEfxN7tNEGuqQHcrGgxX4C4YTkFIOQCeNOEweAwOQWrZKixquACL2/+QvPexP/MVL5kZwJ4b3jN4CzwnBk9MPvHI/Z4bPjB4BxxWr8pmDgxec81ucOQn8GL1oixxGhyZq1dknd3qAVmrAOSu/nF7w+DbZktyOZNXwOe/nc4HMPjOD75ealM2dMuzcz+9ngC5ApArALkCkCsAuQKQKwC5ApArALkCkCsAuQKQKwC5ApArALkCkCsAuQKQKwC5ApArALkCkCsAuQKQKwC5ApArALkCkCsAuQKQKwC5ApArALkCkCsAuQKQKwC5ApArALkCkCsAuQKQKwC5ApArALkCkCsAuQKQ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkness {
            get {
                return ResourceManager.GetString("GreenDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA72SURBVHic7d17mF1VecfxzzqTDCFRwk0IEULOmQgIeEXtU6sFW55qfbxiGyOItmpFkcpNTKmPoGhRqmKL5VEEebyUuyKIEiXGIBdbVKyKVcC5hBBoQAwRCbnOWf1j7TmZTDIzZ2bOdc7+/jV7nX155+zfPnut9V5WQJeicwUnYT85ncCjoksM+GiXovMEH8acZluV0zDmCI62p0JQshb7N9uinKbwSFASm21FTvMoNNuAnOaSC6DDmTHGZ+8Q/LJhluTUj+i5uHxXH40ugOA+fe6ul005DaTHbqP19PJXQIeTC6DDyQXQ4eQC6HByAXQ4uQA6nFwAHU4ugA4nF0CHkwugw8kF0OHkApiOHDOmk28H [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarknessSelected {
            get {
                return ResourceManager.GetString("GreenDarknessSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABPfSURBVHic7Z15lFxVncc/v/uqsxAYAhIiyJKqjiwhLsC4jXiM43IYZ1hMuioBjSIgmyhKhAwgW3SYwQUVBx0MgsBASFcnKkEQEBIh6vF4QB2QgdgLhEgSCBCydrrq3d/8cW8t3SRMkq56r6rrfc555713X/V7v36/792XJ2QJ0sqVIpwN7E9CK/CiKjf2CVcH6anME7gcGBe3VQmRMU6ED44XjGSyrAEmxm1RQiysNSTOb2UmmrgtSIiXRAAtTmqHV5TTRfifCG1JqBOqvB3h5u1d26EABJ7pyfNY/cxKiIr2DkbrDq4lWUCLkwigxUkE0OIkAmhxEgG0OIkAWpxEAC1OIoAWJxFAi5MIoMVJBNDi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkSelected {
            get {
                return ResourceManager.GetString("GreenDarkSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHYSURBVHic7dUxLkVRFEbhdR+JQs8QRGNQGpOQINR6kRiMXqMzA88MVMcEeN27R7LW1+7mL1ayFwYHwA1wBZwQgy/gCbhbGNwD15MHZY6HhcEncDp7SabYLgzG7BWZZzN7QOYqALnDHbdL4H2tIdmrC+Dlt8OuAD5YeNvPnqxqcPTXqRcgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUgVwByBSBX [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLight {
            get {
                return ResourceManager.GetString("GreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA7CSURBVHic7d17tCRVdQbwX907AwwCGd4gEQWMCKhEUYkm6CKJiY8YxCBPlURMkPebSUaW8jBGRMSEIATQRRAQMKIyxiiPEEBlhYAYJBpGJSAKAwwDDu+ZuXPyxz51u6en+869c/t5u75etbrrdHXV7trfOWefvfc5VUhG8XEcii1UGAY8in/CaYXkDJzSY4Eq9AafKCSLsGWvJanQEzxSSFKvpajQO4z0WoAKvUVFgCHHrAm++xDu7pYgFTqK1+CLzb6YiAD3KtzZGXkqdBXJuq2+qrqAIUdFgCFHRYAhR0WAIUdFgCFHRYAhR0WAIUdFgCFHRYAhR0WAIUdFgCFHRYCZiGT2ZA+tCDDTkOyDn0h2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLightSelected {
            get {
                return ResourceManager.GetString("GreenLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABDTSURBVHic7d15vF1VdQfw7773JSRMBVQGKSBSpASBKlpn+VDrQK3VKEIEFQQ1AiIIShAh77yAAlKlDsgUqSLI1IIFiopgCkH81DqXoqJSKiohhICRQPLeu3f3j33u8IZAkvfu9N75fT77c8859wzr3vVbe6+999rrBNcou0c/5mNbBaYDluMicwyU7WURTsdmHRaqQPuwGfb3sFKQWYbtOi1RgY7goZJC+dMZ25U6LUGBzqIgwDRH3zq/CY4U/KyNshRoFaJ9RJeO99W6CRD9Ur8ftkyoAu1DZpN1fVU0AdMcBQGmOQoCTHMUBJjmKAgwzVEQYJqjIMA0R0GAaY6CANMcBQGmOQoCTHMUBJiKuMiM [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenSelected {
            get {
                return ResourceManager.GetString("GreenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAH2SURBVHic7dWxbRRRHAbx2fVJpHZyLsEZ3dAAwrgJEHYZlpE7IiGjA84JTgng0cBtePckZn7pP/mkN9pdxjsuuOILcAfsicEL8MgvHnZccg98mjwo57UHPnPJsoyP/ASuZy/KFIeVHt/sep29IHMVgNxu87Lwnj98P+OWnMoFbxk8HzttB/CXH8tXvp1sVM5m3PKG5fitX4BcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAH5SURBVHic7dXBSQNBHEbxb9aApIGkhEAOVmIVgtiEktVUIYEUkHPa8OIhYAlJA8HT2MDuMTvge7/rn4Hv8GBKPRzuMj9tkrwkWUQElySfua7fZ5mf+iSvjQdpWoskb5mfSpfkufUaNfPcJVm2XqFmll3rBWrLAOBm46fylFK+p5uim6n1Ian7odN4AKX+lMfN181GaTL12N+nDt/8AuAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLight {
            get {
                return ResourceManager.GetString("OrangeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABCnSURBVHic7Z17fJTVmce/zzshEIyAiAh4q1eUWrVi3c+6dZVPbetCJkHajRRL3UUrXlhQKKVKSU4Cotbbrl0+lkr5FLuCBuWSGS5CkQpoVytdW/qhuMVVKSpSRVQgMcm8z/5x3kkgkGQmmXlnJvN+/9Fz3nN5yPxm3nN7niNaUxOiaHslMBEYSEA+sBeYT92wqgKKthvgxxk2KMBfBgKzKNouDvD9TFsTkDG+7wAnZ9qKgIxxspNpCwIySyCAPKeg7UcyAZE/+mdKQNpQvQh04bEetS0A0TekpHJr2owK8A2Nmp7osZ8Fr4A8JxBAnhMIIM8JBJDnBALIcwIB5DmBAPKcQAB5TiCAPCcQQJ4TCCDP [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLightSelected {
            get {
                return ResourceManager.GetString("OrangeLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABGnSURBVHic7d15lFxlmcfxz1vVSQjCmCBbUBHcgMEVl9HBo4fx6OCMouIEEAaNMV2dwCAaQRRZggyMGzIOAunuEBERxHjAQxgVBHMgDJ6ZEccFjwquoBBiIIGwhHTXfeeP91Z1ddOJWbq29P2ec0/XvXXr3qfv83ufd39viLOVzXQ2+rCngsnAavRb65weMyzCGW02qKC17IkzzRBCrFiFvdptUUFbeLCkcP5kZq9Suy0oaC+FACY5PZv8Jpir6qcttKWgWZS9TLR0vK82LYDMr8ISdzbNqIKWEXtNE8b/rsgCJjmFACY5hQAmOYUAJjmFACY5hQAmOYUAJjmFACY5hQAmOYUAJjmFACY5hQB2QGLF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeSelected {
            get {
                return ResourceManager.GetString("OrangeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHoSURBVHic7dWxTcNQGEXha8cSGyR9mnSUDESTJZBCBEtEkRiAUZDT0NGkxtmAAj0WsOnsV5zztX9zJR/5NSXvq2R7SLJPso4IbklOyfXYlPQvSZ5qL1IVr01J/51kU3uJqhja+PHJNm3tBarLAOC66VPzmORzsSWa031S3sYO/wTw+9Xk4TLXIi2n5ONu6mfvEwBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAH9SURBVHic7dWxTcNQGEXh+xxLbBD6NHSUjMIASIglQIQxokgZIGyClIaOJj1sQIF+FohL+xXnfO3fXMlHfq2Ox1Xa5jWVpyTriOAnLbvU+W1MbbZJnnsv0qLWqbykNm1Iy2PvNeqk5XFIct17h7q5HnovUF8GADdOXlp7SOVzwS2aS8ttqg6XTtMB5O+r3d+d5tqk5dT7x9XUz94nAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADOAOAMAM4A4AwAzgDgDADO [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLight {
            get {
                return ResourceManager.GetString("PinkLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABRKSURBVHic7Z15lBxVvcc/v1udDRLWAIKigCKrKLOEiLyjOS6Hw3sQDmR6QgRlUcImIIgcQFaR9xBFxYeKIAg8SaYnxCUIAmJUEB+ZmSCyKFt8IhKWEEL2dFfd7/vjVvd0AolZZnrJ1OecOt1V1VX16/p97++udctUKETYHpcipgI7kjEUeBXjBjTv8hza4zLgK/W2KKOm7Ii4GO1hDuPz9bYmo04Yn3fATvW2I6Nu7OTqbUFGfckEMMTJrXWP2YmIP9fQlozBwjgA6ea327V2AZA8bflxfYNlU0btUPecEWsL9lkWMMTJBDDEyQQwxMkEMMTJBDDEyQQwxMkEMMTJBDDEyQQwxMkEMMTJBDDEyQSw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLightSelected {
            get {
                return ResourceManager.GetString("PinkLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABIXSURBVHic7Z15mBT1mcc/b/VwKaCIiMejEYxhvdfpGSRGN2GTdV2fTTwXiUfiEcUDT4zIEqNgdNdoNDFhlXisRzzAeEQTvIJEUXdlevCM64lHjILhEARh+qh3/3h/1VPTzODAdFd1T9fneerpql9XV71d7/d3HyXK7BSMvASYAGxDQj3wCTATFk0TJXMZ8KO4LUqIhZ+IklkMDI/bkoRYWOKROL+eGe7FbUFCvCQCqHMauv5KTgJejsyShEqyN+gtnX2xAQEU3hBGt1bKooToUBb06yqxT7KAOicRQJ2TCKDOSQRQ5yQCqHMSAdQ5iQDqnEQAdU4igDonEUCdkwigzkkE0AtR5m2gj6cjiQB6GUrr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkSelected {
            get {
                return ResourceManager.GetString("PinkSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAIBSURBVHic7dU9SgNRGEbhdyYBi/RmCcEJuAX3IgQhe5D8LMBeAlmAy7C3sQi4hGRWYHXdQKbMXPCcp/248BYHbvORj8kpp02SlyT3EcElyXuXbjdZZrlP8ppkVnmUxjNL8tSnb9skq9prVM2qTTKvvULVzNvaC1SXAcBNhw5NmucmzfeYY3QbJeWxpByv3QYDKCk/m2y+bjdLY9lmezd08wuAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4Az [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABJdSURBVHic7Z13kBzVncc/v+7ZVUASIDI2GBkfQQhMOIwDV+Aydql8RyiMl2SCRRAiW0IIJHbnzUqIIIxt+cCHSQbOBBHOJhpxgAHBlYsCBzgdmQNzSEIChIRgtT3dv/vjvd7pHXbFSjvTM7PTn62une7p6f7N/L7v/V5uWcACfzGL88BkYEsymoH3gGvGM77g78ZunUA7sFGNjcpIj42AA5az3POAU2ptTUbNOMUDtqq1FRk1Yyuv1hZk1JZMAE1Orr83BJkkyN/SNCajOii6h6I39PVevwJQ9OU8+eeqZ1ZGWhjMsP7ey0JAk5MJoMnJBNDkZAJocjIBNDmZAJqcTABNTiaAJicTQJOTCaDJyQTQ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PurpleSelected {
            get {
                return ResourceManager.GetString("PurpleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHYSURBVHic7dUxLkVRFEbhdR+JQs8QRGNQGpOQINR6kRiMXqMzA88MVMcEeN27R7LW1+7mL1aylwEHwA1wBZwQgy/gCbhbBtwD15MHZY6HZcAncDp7SabYLgPG7BWZZzN7QOYqALnDHbdL4H2tIdmrC+Dlt8OuAD4WeNvPnqxpwNFft16AXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBcAcgVgFwByBWAXAHIFYBc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHySURBVHic7dXBSQNRGEXh+8aAHZgShFlYlBBsQsloqpCABdiLGxcDlpB04Oq3gcwy88Bzvu3Pg7s48Fp9ft5knvdJnpLcRQTnJO8Zx9dN5nlK8tx5kNZ1l+Ql89yGJLvea9TNbkiy7b1C3WyH3gvUlwHAbRYvrT2mte8Vt+haqh5S9XHptBxA1U/b77+uNkqrqWm6Xbr5BcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLight {
            get {
                return ResourceManager.GetString("RedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABJlSURBVHic7Z15lFTVncc/v/eqmyWAgCsmGo0Zlw4alzFmcY7mxORwMqN4jGlR4xJcEBc0IKJAd91qFheMSchghuASdeKCyiSuEQeJSpyT49EsOj3uTogjoIgIgk1X1fvNH/e+ftUbNnTVq6qu9znnnar36tV7v6rf997f3Z/o0qU+ra1pYBKwBwm1wHvAYhoaMilaWw0wu8wGJcTLHkATra3iAReU25qEsnGBB+xZbisSysaeXrktSCgviQBqnFSvn4hMROSvMdqSUCpUD0P1tp4+6l0Aqq9KOv1CyYxKiA01ZlBvnyUhoMZJBFDjJAKocRIB1DiJAGqcRAA1TiKAGicRQI2TCKDGSQRQ4yQCqHES [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLightSelected {
            get {
                return ResourceManager.GetString("RedLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA62SURBVHic7Z15lBxVFcZ/byYhBEIMS8KmyCarEGUVFD1RUQERguwBooAGCIGwRgOHJUFkD4ossh0MiwkKAkFkjxCRI7IoRJCgCALZSEIIW8gs1z++V1ZNp7szM91dXd31vnPqTFd1ddWdut97775777vlDFqBs4FRwBAC8oD5wC+Bc53BRODMOgsUUB+c5wzmAmvXW5KAumCeM7B6SxFQP7TUW4CA+iIQIOfoU+a7I4Hn0xIkoKbYFrix2BflCPCyg2dqI09AmjDoV+q7MATkHIEAOUcgQM4RCJBzBALkHIEAOUcgQM4RCJBzBALkHIEAOUcgQM4RCNCEMOjb3XMDAZoMBvsDLxls3d0fWIlt19qK [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedSelected {
            get {
                return ResourceManager.GetString("RedSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAIOSURBVHic7dUxThtRGEXh+z9bSgPteAl0WU4WEMmiZAMgYAmUyJIX4KwlTboswW6hocAvG8iUnidxztf+zZXm6E0dDofV6u342JPbJFNEcKrk9fN687yu99NTT+5HL9Kipp481PupWnrfjl6jQXrftko2o3dojEo2bfQIjWUAcOu5Q6/87J/nP0uO0WXUqn2vnv3/brMBJOe/P7Z3vy81Ssv5tX/5NvfY+wuAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABJnSURBVHic7Z17eJxlmcZ/9ztpWkpLgUI5CCiCoIh4QN1rXV1l5VKXS6g07YgcxCYpEZpOoYgsssJ4QlkUJAcxNEmlK6dJUkAUBKxVDrro6oqwiivIqSitba20hbbJvPf+MRNoC22SJjOTaeb3V77vew/3le+e7/C+7/N8ymQyicS6FZcaGoBpVBgLrBS0ZSfv94UqrV+ZNvx7qRVVKCrTDJ/X+pUK2HNKraZCibDnBMF+pdZRoTQI9gulFlGhtFQMMMap2t4Bi1pn42+LKaZCYVAiHCPT+WrHtmsAiH9Izpn/q0KJqlA8ujqvHr+9i33lFjDGqRhgjFMxwBinYoAxTsUAY5yKAcY4FQOMcSoGGONU [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TanSelected {
            get {
                return ResourceManager.GetString("TanSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAH+SURBVHic7dU9SgNRGEbhdyYBi/RmCcEJuAX3IgQhe5D8LMBeAlmAy7C3sQi4hGRWYHXdQKbMXPCcp/248BYHbpOPj0lOp02SlyT3EcElyXu6bjfJcrlP8ppkVnmUxjNL8pS+b9skq9prVM2qTTKvvULVzNvaC1SXAcBNBy9N85ym+R5xi26llMeUcrx2Gg6glJ9sNl83G6XxbLd3Qye/ADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABIvSURBVHic7Z15kBv1lcc/r1szPjDGNqdJIDhkOYwhHEvIwRakQlKu7HIUIeYKR8xhbMAQG2MwzOin8cEZJyELWYcrwIbDgDfhDLDgAA5bKQpywHq52TgstrExxmAzHkn99o/XPa0Zz8DYI7WkUX+quqRutbqf9Pv+fu93vhYWLvRZujQLTAJ2IKUReA9YwNixOZ999mkDWoCtqmxUSnJsBRzGqlWeB5xVbWtSqsZZHrBjta1IqRo7etW2IKW6pAJocDK9fiIyEZG/JmhLSqVQ3Q/VW3r6qHcBqL5KNvtCxYxKSQ7nBvX2UeoCGpxUAA1OKoAGJxVAg5MKoMFJBdDgpAJocFIBNDipABqcVAANTiqA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TurquoiseSelected {
            get {
                return ResourceManager.GetString("TurquoiseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHbSURBVHic7dWxTQNhEAXh9x+W6MCU4IyiSNwEElimCcsSHZGQ0QHnDoiWBvBlvkWa+dJNXjDSjqq6S/KSZJ9kGxFckpySHEZVHZM8Nw9Sj7dRVd9JHrqXqMU8qqq6V6jP1D1AvQwAbrNwe0ryudYQ3dRjkve/DksBfI0xPm6zR2uqqvtrN18AnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHAGQCcAcAZAJwBwBkAnAHA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA9ISURBVHic7Z15lBxVFcZ/d2ayIcEEsoAIClEjoKIiIlH04L5jFAmLiooKIYadBAMHWVxYRNCIIrhgZBM0KFFUBBGCcMQgCHEhCrIoJDEMELaQWT7/uK+smk53Z2a6u7p6+n3n1Omu6u6q23W/99599953yyR1Ap8HDgamENEOWA18GzjZJJ0KnNBkgSKagy+YpJXA1GZLEtEUrDJJarYUEc1DR7MFiGguIgHaHF1VPvskcGdegkQ0FK8Avlfug2oEuNvMbmuMPBF5QtKYSp/FIaDNEQnQ5ogEaHNEArQ5IgHaHJEAbY5IgDZHJECbIxKgzREJ0OaIBGhzRAKMQEgaNdjvRgKMMEjaG/ibpJ0G8/1I [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhiteSelected {
            get {
                return ResourceManager.GetString("WhiteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHaSURBVHic7dWxTVxhFAXhectK7gCXQEZRTmgCyV5BEwiJjpw4cwcsHTi6bsBstu+3NPOlNznBSHeb4Qb4DjwAt8TgA3gBTtsMT8Dj4kFZ43mb4R34unpJljhvM8zqFVnnsHpA1ioAueOF2zfg115DclX3wNu/DpcC+L1t/LzOnuxphi+f3XoBcgUgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUgVwByBSBXAHIFIFcAcgUg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHoSURBVHic7dWxTcNQGEXh+xxLbJD0adJRMhBNlkCCCJaIIjEAoyCnoaNJjbMBBXosEJf2K8752r+5ko/8Sv3IKts8J9knWUcE1yTHXHIodchrkqfWi9TEW6lDfpJsWi9RE2MXPz7Zpmu9QG0ZAFw/eSl5TPK13BTN6D4177cO0wH85bs85DzbJC2mfuZu6l/vEwBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcAcAYAZwBwBgBnAHAGAGcA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDark {
            get {
                return ResourceManager.GetString("YellowDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA91SURBVHic7d17lF1lecfxz3smDAFCgtxBAQEBBbyQmYmUYpVVW63LK7YRQbRFC3IpV5EiFVApSlVssSxFkCVYuQRFEAUFY5SLlcyZIOK1YkCKFlBj5JaQzJynf+ydk8mQTM7MnOuc/V0ra51373fv98ns3zn7vTzP86ZYoMcezsEx2F5BN/AYLrHUh1KUfQT/0mqLClrCeSnKHsEOrbakoCU8WlI8/G5mh1KrLShoLYUAupwZGzyTHIUfNc+UggbyEuHy9Z3YsABG/CLNM9QwkwqaRiy26YZ+64tXQJdTCKDLKQTQ5RQC6HIKAXQ5hQC6nEIAXU4hgC6nEECXUwigyykE0OUUApiGxKJx1njGUAhg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDarkSelected {
            get {
                return ResourceManager.GetString("YellowDarkSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAIGSURBVHic7dWxTSNhFEXh+wZL5EYyJZBRzhawCU2wAspASBTgrYVkMzpYI2E2JfGjAU/o+cWe86VPI13pP9JU9/Ys+7pL+iaVTfT/67wl9Zh1P6yy7/tUbkdv0oIqm6R/Zd9V/bH9m87l6E0aoLKbfHywzuU0eoPGMgC41eyl6meq/yy4RafSdZ3u52On+QAOea2LHy8nG6XF9Pvv89Txm78AOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4A4AzADgDgDMAOAOAMwA4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLight {
            get {
                return ResourceManager.GetString("YellowLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABSRSURBVHic7Z15lFxVncc/v/uqu5NAoJckIAwoIjKAgIqOy4AexjMqOqhAUgmLgoBGNkFQIgxCQFGRcRhEZBUVgaSrIyhhAJGYQRDPOLijCCqiKIQkXdWELJ169e53/rivqjsxkSxdW/p9zqlTVa9evfur+n3v7+73mVSIKNpFoNkY08jY9hFLwa6jVxfnKGouxgXNtimjgRjTQJ+iKDOVCksQOzXbpowmYDznMuePY8ROrtk2ZDSXTADjnNxGPzE7EdMvG2hLRr2QHYB004Y+2rgAPI9bX/4ndTMqo2FocKAL2/BnWREwzskEMM7JBDDOyQQwzskEMM7JBDDOyQQwzskEMM7JBDDOyQQwzskEMM7J [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLightSelected {
            get {
                return ResourceManager.GetString("YellowLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA8FSURBVHic7Z159F3TFcc/J78kEhUSQ4SgphJTza0GtbSrmk5alBhqnhJp0BBZDTVFlWKpqjGoGmJqUUE1qGUoi5rFMoSYiVRMUSK/4ds/9rm/e3N/773f8N677773znetu9679913735vf885++y9z75OogU4CTgcGE5AM2A+cAlwipOYBpxQY4ECaoPTnMQ8YOVaSxJQE7zvJFRrKQJqh361FiCgtggEaHL0L/HZQcCzWQkSUFV8Hbii0AelCPCSczxRHXkCsoTEUsU+C0NAkyMQoMkRCNDkCARocgQCNDkCAZocgQBNjkCAJkcgQJMjEKDJEQjQ5AgEaEBIDOjpuYEADQaJnwMvSGzUk/MDARoI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowSelected {
            get {
                return ResourceManager.GetString("YellowSelected", resourceCulture);
            }
        }
    }
}
