//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laavor
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Like {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Like() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasePackage.Icons.Like", typeof(Like).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1pjFzHtd5XVXft7tvbTPfsJIfriKskUpYoUdTIkiwxWizJaDu2n4OXlxfhIYDz4AAOYiCAx0B+BPlhBEmABMR7QBI4i0jbsCI7EaT3nmQ/a7FMitTC4SpyxGX2pXt6u1tV5cftSw7JGZJDztIc9Qdc9My90/fW3PrOqVOnzjlF0MBCggCgW7ZsYVNTU4plWQwAyuWyv379eu+dd97hAOTyNvFqkOVuwAoC3bJli5JKpaKapqUNw0gxxqKcc+k4Tt627XHbtvOHDx92APDlbmyIBgEWBnT79u1ma2trNhqNdicSiY3JZLJb1/VmKaU/PT09WCgUPpuenu4fHh4ePHz4cBkBCZZdGyjL [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z1pbF3Heff/M3PWe+65G3m5ipK4SbQkU7YlR1Zty1K8Kq9t2DJuXMRpgaKJ36BAELRAgwYoEBboh6IfjLdogbZGAiQFWrSSbThx0ga226heFMUSJdkyKdGUZIrizkve/d6zzrwfxMNQG7VykcQfcCHxnHtm5p75zzMzz2wEK9xKCAC6ceNGlslkJNM0GQCUSiWvra3N3b9/vw9ALG0SL4QsdQLuIOjGjRuleDxuKIqS0DQtzhgzfN8Xtm1nLctKW5aV7e7utgH4S53YgBUB3BpoZ2enXldXV2MYRnM0Gl0Xi8WaVVWtFkJ4+Xx+JJfLfZ7P53vHxsZGuru7SzgvgiW3BtJSJ+AOgO7c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAN9AAADfQBfbmbgQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z1ZjFzHee//tZyt93X2nZvEEUlJlCVZipxRJNlkLDmJ5Xbsazi5hhFlg7M85N4AftAYDvIQBMZNjDxEsAEHWWCTthPES+RIEWlJtkhJ3CTOkKK4jDicvZfpvc9SVffhcMihuJPDmeFwfkBjevr0Oaf61L++qvq+WghWWUgIANrf388KhQIPh8MMAKrVqrd27Vp39+7dAoBa2iReCFnqBKwgaH9/P4/H40Fd1xO6HkwwpoWkVLJet4u23ZhxnGJh3759NgCx1ImdY1UACwPdvHmz1dS0rtkwWF8olLjLsiK9nJtJQHqe1xiv1YqHy+XpwxMTxfGDB3dX4Itgya0BX+oErADoo49+KphI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15cFzHfee/3f3OefPmAmYGGAAkQYI3RUoidVAHRUmWbcaWSlZ27GyOzSabqJzUZrNJVWqTVCpGandra/eP1NZmq5JlOSknW3tYjFPx2o4dH7IcyTpJkRIJkOAJgsDgxtwz7+ru/WMwEMETvACQxKdqCsB7eP163u/bv+7+9fEIVridEAB069atLJ/PK7ZtMwCoVqtBT0+P/8Ybb3AAcmmzOB+y1Bm4h6Bbt25V4vG4pWlawjCMOGPM4pxL13ULjuNMOY5TOHTokAuAL3Vmm6wI4PZAt2/fbra1taUsy+qORqMbYrFYt67rrVLKoFQq5YrF4rFSqdQ/NjaWO3ToUBUNESy5N1CWOgP3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDark {
            get {
                return ResourceManager.GetString("BlueDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1Jk1vXleZ3hzdgeJiBnJlMTiKVnCRSlihRcqpll62yrVK5A65wRWjTC+3cEV54rfQ/6LXWtbEY0REVHR1RUbUouj3JKtKkJDIlcSaTzHnAjDfcoRcPIJNkkpkkkzkRXxAEEu8B9+Gd75577jnnnkvQwVqCAKDDw8NscXGRO47DAKBer4s9e/YEp0+flgD0xl7i/SAbfQHbCHR4eJin0+mYaZoZ27bTjLGYlFJ7nldyXXfOdd3S2bNnPQByoy+2jQ4B1gb08OHDke7u7kIsFhtKJpP7UqnUkGVZOa21qFQqE+Vy+UKlUhmbmpqaOHv2bB0hCTZcG/CNvoBtADoyMhJNp9MDmUzmeFdX [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLight {
            get {
                return ResourceManager.GetString("BlueLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1ZcFxXet53zrlb9+3b+4YGQBLcSXCRRGo0lCgNxprxjDKesWZcbceuuCqVB1VenCo/+Hngp7zmLQkrL6nyi8VKqlxxKlN2xdY4Ho9GI4raCIoUF5AAGjvQe9/lLHm43SQokiBIglhIfFXNBvt233O6/+/85z///5//EOxgPUEA0OHhYba8vKw5jsMAoNVq8f379wcffPCBAKA2t4v3gmx2B54j0OHhYS2VStmGYaQty0oxxmwhhPI8r+q67oLrutULFy54AMRmd7aHHQKsD+iJEycixWIxb9v2UCKROJhMJodM08wqpXi9Xq/UarUv6/X62MzMTOXChQsthCTYdG2gbXYHngPQkZGR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSky {
            get {
                return ResourceManager.GetString("BlueSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1ZbFxXeub3n3PXqrq1kVXcRVKbJcuS3C15kVf2mhid7jhBVwaZSd4SIy8dIBjkccZMME/zNI8DPwbIAGNNJhkgg/TiTtxLuj2O1JIX0bJWauG+1V53Ocs8VBUtWRuphaSo+oACyVtV917e/zvf+c9//vMfQgcPEwSAHThwgK+srBie53EAqNVqYvfu3dH7778vAejNvcWbQZt9A9sI7MCBA0Ymk4lblpV1HCfDOY9LKXUQBEXf9xd93y+ePHkyACA3+2bb6BDg4YAdOnTI7e3tzcfj8dFUKrU3nU6P2rbdrbUW5XJ5ulQqfVoulydmZ2enT548WUOTBJuuBsZm38A2ABsbG4tlMpmh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANsAAADbABfWVZ+gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15jFxHft+/VfXOfn33dM9Mz0EOObzESxKpgyuJS62s3VVibbQyeh1fQRaxBceA7TiAkRgIsuPYCIL8sQjiAAkEG0gCbGCLtrFrybGzXu/K2l2tDlKkJHJ4D2fIua8+X7+zqvJHd8+S4nA4JIczQ3I+QM909+t+r/rVt371q19dBBusJAQA3b17NysWi0osFmMAYNt22N/fH7z99tscgFzbJF4PWesEPEDQ3bt3K6lUytI0LW0YRooxZnHOped5Jdd1Z13XLR0/ftwDwNc6sS02BLAy0H379pkdHR05y7L6EonE9mQy2afrepuUMqxUKuPlcvlUpVIZnJycHD9+/LiNhgjW3Booa52A [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAN9AAADfQBfbmbgQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z3Jc9xHdudfLr+l6ld7oRYUdpAgQYKiRFJqi5LcTfdimz3TrZ5D9a0nxhddJhwT/gsa/g/mrLsv4skO+zIXyxEz0VK32FK3REgCCJDYCyjUvvy2zHxzYP1gkARJcANAsD4RFUXWr34LKr/58uXLl5kE+rxICADQmZkZVqvVeDQaZQAAnU5HnD592v/0008lAODRPuL9kKN+gBMEnZmZ4clk0tJ1PWWaZpIxZkkp0XXduuM4O47j1G/evOkCgDzqhw3oC+DFQC9evBjK5/NZy7Im4vH4mUgkMsY5H0BEz7btUqvVmms2m3OlUmnj5s2bHbgngiO3BvyoH+AEQK9duxZOJpMj2Wz2nVwu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAB8vSURBVHic7X1ZcxzHtebJpbKquruqekdjBwiCIg1RpERI3CnIGs+MPGOHxhHtCT/cV715IvzgZ8H/YJ71E8R/ME9ySLZkXvKSuiJBSgQpECCxN9B715LLPKALAkiQBEgQa38RCDS60JXZdb48J/OckycRtLCdQACAh4aGyPLyMrUsiwAA1Go1fvTo0eCrr74SAKB2t4vrgXa7AwcIeGhoiCYSiShjLGkYRoIQEhVCKM/ziq7rLrquW7xx44YHAGK3OxuiRYDtAX7nnXfMXC6XjUaj/Y7jHIvH4/26rqeVUrxcLk+XSqXb5XJ5bHZ2dvrGjRs1WCHBrmsDutsdOADAIyMjkUQi0Z1MJofb2tou9PX1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLight {
            get {
                return ResourceManager.GetString("GrayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAN9AAADfQBfbmbgQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15bFzXfe+/Z7nbzNzZh/smUoslWpZlObZjxwldO4nV2F3iTl6CIC2KoOmGdPmjeAXyh1ik6B9FEbw26B/PSIAUaItEStK+bHVq11ZsJ5YsS5ZskZJlSaTEnZzhcNY7dznnvD8oypS1UgtJSfxQBEdzl3PuPd+zn/P7EaxxMyEAaG9vLysUCty2bQYA1Wo1WL9+vb93714BQK1sFC+ErHQE7iBob28vTyQSYV3Xk3pYTzLCIlJJ6dSdoltxZzzPKxw8eNAFIFY6sgusCeDmQO+77z6rob2h0TCN7kg4co9lW+u4zlMAgsANxmul2tFyuXx04szE+OHDhyuYF8GKlwZ8pSNwB0Afe+yx [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15cFxHft+/3f3OefPmAmYGGAAkQYI3RUoitRJ1UtJqd+ldqbRyZtfxEceOrVqn4jh2lSu2y5WFK0mlkj9cqThVdli2a+1UjhW9Lm9217veQ6u1tDpJkRJJkOAJgsDgxtwz7+ru/DEzEA+Q4AmAJD4sFAfv4b3X8/rbv/71ry+CFW4nBADdunUry+fzim3bDACq1WrQ19fnv/HGGxyAXNokXgpZ6gTcQ9CtW7cq8Xjc0jQtYRhGnDFmcc6l67oFx3GmHccpHDx40AXAlzqxLVYEcHug27dvNzs6OlKWZfVGo9ENsVisV9f1dillUCqVcsVi8WipVBoYHx/PHTx4sIqGCJbcGihLnYB7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDark {
            get {
                return ResourceManager.GetString("GreenDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15cFzHfee/3f3OefPmAmZwkwQJHiIlUBJJU7QkirSsg46kkukdOxs7ySaxVU5qs05SlYq9lVojlewfmz9cqSRVSbHslOOtZGPRclmRFTuSLMnWLZIiRREgQZAQCOK+5p55R7/u/QMYiAd4kwBI4lM1Bcx7M/16Xn/fr3/964tgiesJAUA3bNjAMpmMYts2A4BSqcTb2tr8119/PQAgFzaLZ0MWOgO3EHTDhg1KPB63NE1LGIYRZ4xZQRBI13WzjuNMOI6TPXDggAsgWOjMVlkSwPWBtre3m/X19SnLslqj0eiaWCzWqut6rZSS5/P5oVwudySfz3eNjIwMHThwoIRpESy4NVAWOgO3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkness {
            get {
                return ResourceManager.GetString("GreenDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z17bFzHfe+/M3Oee/bsi9zlWxIlUaL1tC05tmJbpmo7thrbtRVsUiRpcXubGkGB3qAFWjRAgbBA/yj6R3DRFuiFkABt0Ra1lQRxnbSBnYfixI5jS5ZsmZSolymJ79e+d89rZu4f5DKURD1IUSQl7Wf+IHfP7szsme/8ZuY3j0NQYykhAOjWrVtZJpNRbNtmAFAqlYKNGzf6hw8f5gDkymbxcshKZ+Augm7dulWJx+OWpmkJwzDijDGLcy5d1806jjPhOE726NGjLgC+0pmtUhPA0kB37NhhNjY2pizLao9Go5tisVi7ruv1Usogn88P5XK5j/P5fO/IyMjQ0aNHS5gWwYpbA2WlM3AX [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLight {
            get {
                return ResourceManager.GetString("GreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAN9AAADfQBfbmbgQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15cF3Xfd+/Z7nL23fsIBZuoiBSoihLsmTZlOVFjC3HjfLcpBm3zXiqtum4k/zRZSZ/6HnS6R+dTqYTT//RJDPukkwsJs60iV0nViRGki3JEhdJBLiIC0iAWB/w9uW+e8/59Y8LkiDFBeACgCA+M2+Ad5dzzrvne3/nnN/ZGDa4kzAAfGhoSBQKBRmJRAQA1Go1b8uWLe6BAwcUAFrdJF4JW+0ErCP40NCQTCQSIdM0k6GQmTSYCBNp7TQbpWbVmS21WoWDBw86ANRqJ/YicrUTsE7gu3btCmztbWsX0hpMxsIPREOBAduQKQ14zZY3UarWj85UKkcj6pGJA0eOVOGLYNWtwYYAbh/+ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z3ZcxxHfue/mVlnV1ef6AbQAEiAl0iBhyRSM6LEkTGhGY/luTSz0eOwIyZiYx/0NhsxD34e+D/YZz17HyxGbIR31xFe+8HyxtqjkcWhLoKHSPDAfffddeSxD9UNgiRAAiQIgGB/Ihpo9FFZqPzmLzN/+ctfEXTYTggAOjw8zFZWVjTXdRkA1Ot1fuTIkfCTTz4RANTunuKDkN0+gX0EHR4e1tLptGMYRsayrDRjzBFCKN/3S57nLXqeV7p06ZIPQOz2ybbpCGB7oKdPn7Z7enryjuMMJZPJY6lUasg0zS6lFK9UKtPlcvmbSqUyNjs7O33p0qU6IhHsujXQdvsE9gF0ZGQklk6nBzKZ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLight {
            get {
                return ResourceManager.GetString("OrangeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z1ZkBzHeef/edTR9z33iZPEEARJ0CRFmvJQFCXCEmWv5db6CK3tUCx31xvasB921xF+YCu8Txsbjg0r9oVhR2hjj7AIW46wZa9sySIsyiIpCrwBQiBxCAPM1d3Td3dVV2V++1AzwAAYAANwMDMYzA9RMY2qrsrsyn9+mfnlxbDNWsIA8ImJCVGpVGQsFhMA0Gq1/F27dnlHjhxRAGhjo3g5bKMjsIXgExMTMpVKRUzTTEfMSNoQRpQ0abfj1hzXKda6tcrRo0ddAGqjI7vEtgDWBn7//feHdvfs7hWW2JGOpu+Jh+LjtrQzGtp3fGe61q69P9+Yf782U5s+8vaRJgIRbLg1kBsdgS0A [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z3Jc1zHnee/mfm2Wl6tqMJOEFwkUlwlUpYoUTI8sttWu+1We6Lc0R3hyxx064nog8+G/4M569wXixET0TExER3dh5bHm6wmTdoSIYmkSIogsS+111sy8zeHVwVxAQiQBAEQrE9EsYr1XtV7qPzm75f5++XC0GUzYQD4kSNHxPLysuG6rgCARqMhDxw4EH700UcKAG3vLd4L2+4b2EXwI0eOGNlsNmFZVs5xnKwQIqGUIt/3y57nLXieV75w4YIPQG33zXboCmBz4MePH4/19fUVE4nEaDqdfiGTyYzatt1DRLJarU5VKpXPqtXqxMzMzNSFCxcaiESw7dbA2O4b2AXwsbGxeDabHc7l [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLight {
            get {
                return ResourceManager.GetString("PinkLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAN9AAADfQBfbmbgQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15bFxJft+/VfWu7td3s7vJpijeuo+ZkWZntDOj1Xh2vZbjWc+O0XZgewMEsSdGgIXjAEZiIMDSSP7KH0aCBEgyiIEkgINkZBveK7HXTnZ87O7MrDTSHDqogyIl3mSzz9fvrKr80d0caURJ1EVSUn+ABsl+7Pdev/rWr6p+Vb9fEXR4mBAAdO/evaxUKinRaJQBgGVZwcjIiP/uu+9yAHJzb/FmyGbfwBME3bt3r5JMJk1N01KGYSQZYybnXLquW3YcZ9lxnPKpU6dcAHyzb7ZNRwAPB3rgwIFQd3d31jTNwXg8viORSAzqut4lpQyq1epspVL5tFqtnpufn589deqUhaYINt0aKJt9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOAgAADgIBzzqDegAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z1pbFzXeff/55y7zp07GznDTRRFipIYrbYlx1Zsy1S9qrFd2+kkQZIWb9+mfoMCQdACLRqgQFigH4p+CN6iBdoaCdAWbdFISd44TtrAThvFiR3HlizZMqldpiTu2+wzdz3n/XBnKEqiFsrcJM0PuBhyLu89h/f8z3Oe85zlEtRZTAgAumXLFpbJZCTTNBkAlEolr7u72z148KAPQKxsFi+HrHQG7iDoli1bpHg8biiKktA0Lc4YM3zfF7ZtZy3LmrIsK3v48GEbgL/Sma1RF8DiQLdv3643NzenDMPojEajG2OxWKeqqo1CCC+fz4/kcrkP8/n8wNjY2Mjhw4dLCESw4tZAWukM3AHQ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z3ZcxzHnee/mVlXd3X13Q2ggcZFkCIJHpJIWaJFyfDIHlthW5a90Z7wRDhiYx/05o3wg58F/wf7rOeZB4sRG+HZccQcDyNvrMeyRjRlSQRvgCSIGw303XVl5j5UN3iBJECCAAj0J6IDjaruyurKb/4y85e/zCTosJUQAHR0dJStrq4qlmUxAKjX6/7IyIj3ySefcAByZ2/xfshO38Aego6OjiqJRMLUNC1pGEaCMWZyzqXjOCXbtpdt2y6dP3/eAcB3+mbbdASwNdATJ06Euru7s6ZpDsVisUPxeHxI1/W0lNKvVCqz5XL560qlMjE/Pz97/vz5OgIR7Lg1UHb6BvYAdGxsLJxIJPLJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLight {
            get {
                return ResourceManager.GetString("RedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1Zc1xHlt53Mu9WdevWiioUCjs3kYRISiK7R2x1azhuj8ey3R3yRFQ75qFf9TaOmId5bsw/8LN+gvjoNzvskSN62m2N1GRLJCTuC/algNrrLrn4oQCIC0CCJIgCQXwRIMCqe29m1fny5MlzTp4kHGI3QQDYxMQEX1tbMzzP4wDQarXEsWPHoi+//FIC0L3t4uOgXnfgAIFNTEwYmUzGtSwr6zhOhnPuSil1EARV3/dXfN+vfvPNNwEA2evObuCQALsDdvbs2VixWCy4rjueSqVOpNPpcdu2+7TWol6vz9VqtWv1en1qYWFh7ptvvmmhS4KeawOj1x04AGCXLl2KZzKZ4Ww2e6G/v/9n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15jFxHft+/VfWu7td3T/fM9HA4J+9LEqmVuDqWsiyv6VhrrYxeB7Y3QBBbMAI4jgMYiYEAO0byV/4wgiRAAsEBkgAOYtE2vN7dxF5f8rG7klYUqYM3OZzhXD1HT5+v31lV+aO7R6Q4JGfI4cyQ7A/Q4LBfv/fqvfrWr87frwg6bCQEAD1w4AArlUpKNBplAGBZVjA6Ouq/++67HIDc2iTeCtnqBDxG0AMHDijJZNLUNC1lGEaSMWZyzqXrumXHcZYcxymfPn3aBcC3OrFtOgLYGOjhw4dDPT09WdM0h+Lx+O5EIjGk63qXlDKoVquzlUrls2q1er5QKMyePn3aQlMEW24NlK1OwGMA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z1ZcFTXnf+/59z93r63N7WW1oIkxGIEMhiwwQZHMTYJiXGIazrOOOPxw1R5npIq11TNSx6iWWtqHqYy8zAzYbbKy8zE2JNyyDgTkrH9t52Y2DDY2BIIsQkkIdDSanXf7rue839ArQgQEqtagD5VlKS+fc893PM9v9/v7ARL3EkIANre3i5ks1nRNE0BAGzbDtra2vx33303BMArm8UrIZXOwH0EbW9vF+PxuCHLckJV1bggCEYYhtx13QnHcUYdx5k4fPiwCyCsdGbLLAngzkA7Ojq02traasMwWiKRyEpVVVsAVBFCgiAIhkql0ueTk5M9w8PDQ4cPH7ZxWQQVtwZipTNwH0A7Ozv1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X17kBzHed/v6+6Z2Zndu917H4ADDgQBEgRICCT40Ju0LMqWaEmxGNiSWJZk+ZFSJalUUrLiVKoiMYlVKZeTSlKxlZJtKWLiKCLskiIpilKSRZCyJMskKPGBI0EegQNwwOGw997b18x0f/mjd7B7h3sC98LhflVTezfv6e/rr79Xf03YwoqCmQmAHBgYUL7vSyEEDQ0NcRAE8d69e2MAhoh4vd8zgVzvF9gsYGZ66KGHlO/7/ujoaGscxzvCMNxVqVR6giBoI6JUPp/n8fFx3dbWxsePH98QTEDr/QKbAbVery5cuNAchuGOOI73xnG8TwjRbYxJEVFRSnmWmfu01v25XC6/bdu2ChGZ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1pjFzXld53731rVb3auqt6Z7NJNklxl0hZokTRLcuyzLGlkTUoT2yPg2wjDAI4EwcYJAMEcA+SX/kxCJIACYgZIAkmi8WZwTieSQx7ZiyPLVuWSZFa2CTFRc2t96X2estd8uNVNbcmu5tsdjeb9QGvq6tevXdvvfvdc88995xzCZpYThAAdOfOnWx2dlZzHIcBQKVS4Vu2bAnefvttAUCtbhVvBVntCqwj0J07d2qpVCpqGEbasqwUYywqhFCe5+Vd151yXTd/4sQJD4BY7co20CTA8oDu2bPHbm9vz0aj0b5EIrE1mUz2mabZqpTixWJxpFAofFwsFofGxsZGTpw4UUFIglWXBtpq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDark {
            get {
                return ResourceManager.GetString("YellowDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANxgAADcYB2XtpVgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1JcxxHlub33GPLjIxckYmdBLhIJMFFEqmFJZaEKtUi1aJW11hWWY1ZXeagW49ZH/os9D+Ys859adFsrHt6xrqn22yKvVWrVWKRVSVCEkmRFBfsSwK5xeLLHCITAkmQBEkQAMH8zNIyEZEZHgj/3nvu7z1/TuhgI0EA2MjICF9cXDQ8z+MAUK/Xxb59+6IzZ85IAHprb/F20FbfwA4CGxkZMXK5nGtZVt5xnBzn3JVS6iAIKr7vz/m+Xzl79mwAQG71zbbRIcDGgB09ejTR09NTcl13OJPJPJfNZodt2+7SWovl5eWJpaWlz5aXl8enpqYmzp49W0dMgi3XBsZW38AOABsdHU3mcrnB [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLight {
            get {
                return ResourceManager.GetString("YellowLight", resourceCulture);
            }
        }
    }
}
