//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laavor
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchLeft {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchLeft() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasePackage.Icons.SearchLeft", typeof(SearchLeft).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X15kBxXmefvvcys++xWt/pSd6vbsmTL8omlsfEhjFnAtrA5FoaZGGMDdjAMhvFG7Awx/7hNwMaCJ9YM7ELYsIHhDwZQrBkjH2Bh1LYXe33IRpbV6LCkvlst9VVHVuX53v6RlV1Z2VnVVdWXbPoX8SKzq6teZeX3e9/3ve9970uCdyfIGnwnX4PvXHGsxY2sBZWuj1RxXiu4x3klwb/rSXG+EaDc9RDH0S1s4npPpXM3ygmZe/yv3LFcn+8KnA8E8LoGL4GTKlq5z1aCl7CZ6zWvVu6z7r7Pa6wVAcoJ3S1IWjinjr+9jl7vdX+X8zWv0ezVWJmj+7wcKZw4L8mwmgSoRuhugdp/C46/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQFAAAEBQBJ3S+wgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAB7ESURBVHic7Z1bjBzHlaa/zLp2VfWN7qZWZJMiRZmkIVki1brYMCCNCXk9mIVhATKk3XnQrheDwWDgmQcDfp1HAx7BHgiwsLsYPch6sOHBGl7BsAxhNLJWgGTvyoQsy5ZJUTRNUk2yu9nd1XW/5zxEnayo6Mi694VW/UAgs7K7srLq/HHOiRMnTjjcmnB24TO9XfjMbcdu/JD9oNPzOT2c9wvPct5J8Lc8KfYaAYKex9GOprAd4386nZsIErJn+VvQMeietwT2AgFsz2ATuNNDC3pvJ9iE3TCu2VrQe81772nsFgGChG4K0m2eu9pr29H2v+Zn6ddsvdnWGgFH8zyIFDr2JBl2kgC9CN0UqLwOaa/N [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP/gAAD/4BstaVKgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X17cB3VmefvnO6+76uXJduyZUt+P2T8wMYECOBAsgQmBEImpioPZ1JZlh2ykK3MpvaPzQymdje1eUymqMlMZtmZbGC3MoU9bIAQJqR4iEcMwTbYgOUHloVkyZIs6Ur32e9z9o9zW7dvq+/VvbIky0G/qlPdt6Xb3be/3/m+73znO18TXJkgl+Ga/DJcc9ZxOR5kNSh3f6SC/WrBffbLCf6KJ8V8I0Cp+yGurVfYxPM/5fa9KCVk7vO3UttS57wiMB8I4HcPfgInFbRS3y0HP2EzzzG/Vuq73nPPa1wuApQSuleQNL9PXZ/9tn7/672W+5hfb/ZrrMTWu1+KFG7MSzLMJQEqEbpXoM5n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1pkCTHdd73sqr67p7pua/dnZ09sTfOBUCQWFIiRZOGQEoydYZEiCZDpkU6wg6Hw2ErsPjjsENhS7KkcICWQzR/yEFuiBIJiAyJAjCgCFAUuQCBBRa72GP2mPvuo+7KTP+orpmamuqZ7pnZA+R8ETlV3dNdlV3vy5cvX758SXhvgu7APeUduOctx514kM1grfpRA+fNQsacryX49zwp7jYC1KsPhY5RYVPkM2udR1FPyDLmf/WO9a75nsDdQIC4OsQJnBoo9b67FuKELSLvxZV6341e+67GnSJAPaFHBclq5yz0Ou4Y99novcLvxbXmuCLqHKPn9UgRxl1JhttJgEaEHhVo8FoJvY4W [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDark {
            get {
                return ResourceManager.GetString("BlueDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X15mB1Xdefv3FvbW7tfd6ulVrd2S7YlyxvGioMxIjCZxGAgJEOWmbAksZPxh53km2zfZOaznJBlgISZkEDshAQymWSCMk5AxiyOrTYOEDCyMcbCkmytLbVa6u3ttd47f1TV63rV9V6/14skQ/++76rqlV7Xq6rzu+ece+65pwivTtBl+E15GX5zxXE5HmQ3aHd91MF+t5AJ++0E/6onxZVGgFbXQ5FtXNgU+067/ThaCVkm/F+rbatzvipwJRAg6RqSBE4dtFZ/2w5JwhaxY0mt1d/Gz31F43IRoJXQ44JkwT6LfE7aJn03/lvRY0m9OamJFtv4fitSRHFFkuFSEqAToccFGn7mkc/x [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLight {
            get {
                return ResourceManager.GetString("BlueLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1pkBzXceaXr46+e7rnAuYAMLhJgAQpUiQMiZIgWZJlyZRkry3LG7YlWpbCoRBlex1r7/qPQIcdYVsblr3ysaR3HVr90K6FWHllUpRNmsJQB7WiCFEgCJA4iHMwwGCuvrvOl/ujuqZraqpnuucAQGq+iBdV3dPzurrye/ky8+XLIrw+QTfhO/kmfOea42bcyE6w2PVRG+edgiPOFxP8654UtxoBWl0PBY5hYVPoM4udh9FKyBzxt1bHVn2+LnArECDqGqIETm20Vv+7GKKELUPvRbVW/xvu+5bGzSJAK6GHBSka5yLwOuoY9dnwdwXfixrNUU22OIbPW5EiiFuSDDeSAO0IPSxQ/7US [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSky {
            get {
                return ResourceManager.GetString("BlueSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1rcFzHdeZ3+r7mDQxAggQJvp8iKSmyJTFK5IRybMdex7FdThw7u7WO149yVJE3+6jspnazon7tbuWHdxNvNnLKKeexySa0XbalWIllh7ATR2vHtB4UKVGUBD7wIAmAwLzu3Ff32R93LnBxcQeYAQGScvBVdd07g0FPzz1fnz59+vRpwhsTdAu+k2/Bd645bsWD7AZLtY86uO8WnHK/lODf8KS43QjQrj0UuyaFTYnPLHWfRDshc8rf2l3b1fmGwO1AgLQ2pAmcOijt/ncppAlbJd5LK+3+N1n3bY1bRYB2Qk8KUrTuRex12jXts8nvir+X1pvTimpzTd63I0UctyUZbiYBOhF6UqDR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP/gAAD/4BstaVKgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1pkBzHdeaXmXX0PdNzAYMZXINjcJAEAR7QQUrQYUmWliLXa0te2yGLlsXwypYc3lh7fxLcHxux4djDazt2Sdth2bG+hF3JNCjRlkxhaFu0JRGkCAggARAYADOY++iz7szcH9XVU1NTPdM9BwBK80VkVHXNdFV2vS9fvnz58iXBOxPkDjxT3oFnbjjuxItsBcvVjzRx3ipkzPlygn/Hk+JuI0Cj+pDQMSpsEvmf5c6jaCRkGfO3RsdG93xH4G4gQFwd4gROmiiNvrsc4oQtItfiSqPvRu99V+NOEaCR0KOCpLVzGvocd4z73+izwtfiWnNcEQ2O0fNGpAjjriTD7SRAM0KPCjT4zEKf [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQFAAAEBQBJ3S+wgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1pjBzHleYXkZlVWWdXsQ/2QfFoHqJJSqQOWrauaQmiTNGQvDBW9KxhQLZhCQthvD/9c9HYn7s/BlgssBgZBizYWhjqNbzWYIYCDK2bCx+QRhdpsileIrvJPtlXXXlnxP6ojGJWdtbZB5t2f0Ags6q7sqLyffHixYv3XhLcnyD34Dv5PfjOdce9uJGtoF7/SBPnrYKHnNcT/H1Pis1GgFr9Ib5jUNgk8D/1zoOoJWQe8rdax1rXvC+wGQgQ1ocwgZMmWq3P1kOYsFngvbBW67PBa29q3CsC1BJ6UJDUO6e+12HHsP8Nfpf/vbDRHNZYjWPwvBYp/NiUZNhIAjQj9KBAxWvJ9zrYJNQm [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X17bFxXue+39trvvedlu3Yc23m4cZo29BVKQ5XSE1SpuiotoCLBEYg+4FAuFc3lj8I/gJqiCl1VFehSdEtyKaKl3KqYW9GbwkGUNj4EaM/JTXvaUNM0TdIkjh0n48fM7PdjrfuHZ032bO95+hG3+Cct7e3xeHtmf7/vsb71rW8jeH8CXYT/SS/C/1xyXIwb2QrqfT7UxHmroAnn9QT/vifFSiNArc+DIse4sFHsPfXO46glZJrwu1rHWtd8X2AlECDpMyQJHDUxav1tPSQJm8ReSxq1/jZ+7RWNi0WAWkKPC5Irn3ORn5OOSe+N/6/oa0nanDRIjWP8vBYpoliRZFhOAjQj9LhA2c84 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLight {
            get {
                return ResourceManager.GetString("GrayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQFAAAEBQBJ3S+wgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1rcBzXdeZ3bz/micHgxTcJgKRIipBFUqQky1FkyrEtxymtXXFMJ64tRU7ZcWoT+Yersj9Xyv5IlTeOU66Ka7OxN7GddRKTGz/iWFrHlgI5shxboiRSFChKJCGAAPHGYF79vvfsj5ke9DR6gBkQACkbH+tWN4Yz3T1zvnvOueeeey7D2xPsJtyTbsI91x0344dsBcs9H2vivFVQxPlygn/bk+JWI0Cj52GBY1jYLPSe5c7DaCRkivi/RsdG13xb4FYgQNQzRAmcNdEafXY5RAlbhl6Lao0+G772LY2bRYBGQg8LklfPeeDvqGPUe8P3Cr4W1ZujmmxwDJ83IkUQtyQZNpIAzQg9LFD/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1pkCTHdd73sqr67p7pua/dnZ09sTfOBUCQWFIiRZOGQEoydYZECCZDpkU6wg6Hw2ErsPjjsENhS7KkcICWQzR/yEFuiBIJiAyJAjCgCFAUuACBBRZ7z+7s3HcfdVdm+kd39VbXVM90z84eIOeLyKjqmumq7Hpfvnz58uVLwvsTdAeeKe/AM2857sSLbAVr1Y+aOG8VMuJ8LcG/70lxtxGgUX0ocAwLm0L/s9Z5GI2ELCP+1ujY6J7vC9wNBIiqQ5TAqYnS6LtrIUrYInQtqjT6bvjedzXuFAEaCT0sSFY9Z4HPUceo/w0/K3gtqjVHFdHgGD5vRIog7koy3E4CNCP0sED9z0rgc7go [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDark {
            get {
                return ResourceManager.GetString("GreenDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X15jBzXeefvvarqu3um5+Tcw+Ep3ockypIs0bIdK/JqJdtZORsvvFG8Fhwn9gJZBIvFbiDqn2ADI4fXMRbSOrAjYB1YhB0rVCQ4tsSxN5LtKBRNUqR4Dzn33WfdVe/tH9XVU11TPdM9B0nJ8wMeqrpnuqq6v9/73ve+933fI3h/gtyGe/LbcM91x+34IevBUs9HajivFzzgfCnBv+9JcacRoNrzEM/RL2zi+5+lzv2oJmQe8Ldqx2rXfF/gTiBA0DMECZzU0Kp9dikECZv53gtq1T7rv/YdjdtFgGpC9wuSls6p53XQMeh//ffyvhfUm4Maq3L0n1cjhRd3JBluJQFqEbpfoO5rwfPa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkness {
            get {
                return ResourceManager.GetString("GreenDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z17kBxXfe8/p7vn/diXduWVVm/bki3bki3bwsYYY8gFTBwbkoIk1CU4xC5CMLlJVe5N3X8sp5LU5VJJIAk3ZYcUhKpLLlaFxBHYAQNaSGECRjaysKyH9VqttFppX/Oefp1z/5jp2Z7ent2Z1eph2G/Xqe6Zne3p6d/3/M7v/M7v92vBmxPiCnynugLfeclxJW5kJ5jv+kQbx51ChRzPJ/g3PSmuNgK0uh7h2weFLQKfme84iFZCViF/a7Vvdc43Ba4GAoRdQ5jARRut1f/OhzBhy8B7Ya3V/wbPfVXjShGgldCDgtTqx5rvddg+7LPB7/K/F9abw5pssQ8etyKFH1clGS4nAdoRelCg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLight {
            get {
                return ResourceManager.GetString("GreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1plBzXdd53X1X13j3dswGzDwYrCS7gCpGmKEiWbJkSRFpyJC8nsmiZPIoiylHOSeKTPwR97Jw4SiKv8SHtHDP+ocTCsWwaFCmJpjCSLMoiCXEBAREAscyGmcGsvVXX+l5+VFVPdU31TPcsACjNd847Vd3TU9v93n333XfvLcK7E3QNzimuwTk3HdfiQTaDla6PGthvFiJkfyXBv+tJcb0RoN71kG8bFDYFfrPSfhD1hCxC/lZvW++Y7wpcDwQIu4YwgVMDrd7/roQwYfPAd2Gt3v8Gj31d41oRoJ7Qg4Jk7j7zfQ7bhv02eC7/d2G9OazxOtvgfj1S+HFdkuFqEqARoQcF6n2WfJ+D [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1pcB3XdeZ3bu9vAx42EiS4gaQWklotiZFHtmlFSbxEshMndpYa24ojVcpl2UnNTGYqlSpTM1nHM1EmniQjOalypqbsJKwokSVLjhWZkJNYjmRalilRIimJBAiCBAkQeGvv986P7n7o1+gHvIeFhGR8Vbe6XwOvX3ef7557zrnnnia8NUFX4DfFFfjNVceVeJCdYKHrozb2O4VI2V9I8G95Uqw1ArS6Hoptk8KmxP8stJ9EKyGLlL+12rY651sCa4EAadeQJnBqo7X67kJIEzZPHEtrrb6bPPeaxpUiQCuhJwXJwn0W+5y2Tfvf5G/Fj6X15rTGW2yT+61IEceaJMPlJEA7Qk8KNPos [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLight {
            get {
                return ResourceManager.GetString("OrangeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1rcBzXdeZ3bnfPewYzAAEQD4IgIIqSqLcsMlIkmbbldSybtux47TipyJIdqRzHsqOt2sSVP4Jd9tY6Sq2deNcuydmK4h+OY9bKkSlLjhiZkLWWVg9KpijCfIgkngRB4jXvft67P3oa6Gn0DGYGD1I2vqpb3Rh0336c75577rnnnia8M0EX4ZriIlxzzXExXmQ9qHZ/VMN+vRA++9UE/44nxaVGgEr3Q66tV9jkOabavheVhCx8/ldpW6nOdwQuBQL43YOfwKmGUuncavATNvf85lcqneut+5LGxSJAJaF7BclK+8z1t9/W71jvtdy/+bVmv8IrbL37lUjhxiVJhvUkQC1C9wrU+Vty [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1pdBzXdeZ336ulqzegARAkCHAXKYkUtVkWo1iW6diTSWTLdpyMs8zESxIpGR1LSc5kO5PJEZU4m+3EM3FiR0qc2JmMMzEzSmzK8qJIhKzYji1TskyLFkmJK0gQJLbea31vflQVUF2obnRjISEZ3zmPVSh2v66u+7377r3vvtuEVyboCnymvAKfuey4Eg+yE7S6P2rjvFPIhPNWgn/Fk2KlEaDZ/VDkGBc2xV7T6jyOZkKWCf/X7Nisz1cEVgIBku4hSeDURmv23lZIEraIXUtqzd4b73tF40oRoJnQ44JkwTmL/J10THpt/LOi15JGc1ITTY7x82akiGJFkuFyEqAdoccFGv7NI3/H [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLight {
            get {
                return ResourceManager.GetString("PinkLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQEwAAEBMBdTAYvQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1pkFzXdd537tv69TY9KzGYwTZYBS4AV2ghJUhRLIoqiopiS47tkkXLYjmKpVSlKv5LMD9SlXIljuO4EtJWWXJZtiwkkinKom2Z5jBlydYCUgQIkACIbTDALJit17fee/Pj9et5/eb1TPcsACjNh7r1Xjd6Xr9+57vnnnPuuecS3pmgW/Cd8hZ854bjVjzITrDc/VEb551CJpwvJ/h3PCluNwK0uh+KHOPCpthnljuPo5WQZcL/tTq2uuY7ArcDAZLuIUng1EZr9bfLIUnYIvZeUmv1t/Fr39a4VQRoJfS4IFn9nEVeJx2TPhv/ruh7Sb05qYkWx/h5K1JEcVuS4WYSoB2hxwUavlYi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQFAAAEBQBJ3S+wgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X17kBxXee/vnO6e98zO7EuWJe1DkmVba1uSLUvYOEbmZWKuAsXDBOpexwQMFMFQUJV7U/f+YZHKTZUDIXALbrhAJY5TIUFKAAcQ4WGzfhI/ZMvCXlnWY7XSrva9s/PqnunHOfePM2enp7dnd2Z3drWG/VWd6p7Wqufx/c73fec73/c1wRsT5DK8J78M77niuBw/ZCNY6POROs4bBfc5X0jwb3hSrDUC1Po8xHX0Cpt4/mahcy9qCZn7/FutY617viGwFgjg9xn8BE7qGLX+70LwEzbzXPMbtf6v995rGpeLALWE7hUkLZ9T12u/o9/fet/Lfc1vNvsNVuPoPa9FCjfWJBlWkwD1CN0r [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X15cBzXeefvvb7nwgxAgAQBXqBIHdR9seSibNqxE9mObHkT28mm1pbiWJVyWfb6n2Rr/zGVSqo2661ydr3rlORNlbyVcuywVl6JiqS1ViFkJ3IimZZ1kBIvkQBBHCRIYM6+37d/9DTQaPQMZgYACcn4Vb3qxgDo6Znv977rfe9rhvcm2FV4T7oK77nquBpfZDtodn+shfN2QQnnzQT/nifFWiNAo/thkWNc2Cz2N83O42gkZEr4XaNjo2u+J7AWCJB0D0kCZy2MRv/bDEnCFrHXkkaj/41fe03jahGgkdDjguT1cx75OemY9Lfx94q+ljSbk4ZocIyfNyJFFGuSDFeSAK0IPS7Q8Gcp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLight {
            get {
                return ResourceManager.GetString("RedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1plBzXdd5336uq3nv2wTZYiJUEwFUUIUoMDSWSLVviobJJsk+OLUeW4shafOJjJ07sCMyJnMT2iazIiU3Zx1ZO4uUIlmKJlBhLljGyI9mWBFEkRZgAF2yDAQaYrbfq2t67+VFdPTU11TPdM4OF0nyHj1Xd06iurvu9e++77777CK9O0E34Tr4J33ndcTMeZC9Y7v6oi/NewSnnywn+VU+KW40Ane6HYseksCnxmeXOk+gkZE75W6djp2u+KnArECDtHtIETl20Tv92OaQJWyfeS2ud/m3y2rc0bhYBOgk9KUjROhex12nHtM8mvyv+XlpvTmu6wzF53okUcdySZLiRBOhG6EmBRq9l [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1pcFzXdeZ379t7QzdAgMTCDVxFSiK1MpIlm/J4Ylku2ZosdmaccqR4rMp4Yk/VVE3+ivozVVOpmUwmmZqSElfsVJzEZkWJLMdK4iiEUrET26FkkiIk7iRArAQI9Pb2e+/86Pcarx9eA91YuNj4qm69h0b369fvfPfcc84991yCuxPkNnynuA3fue64HQ+yHSx1f6SF83YhEs6XEvxdT4o7jQDN7odEjnFhk9h7ljqPo5mQRcL/mh2bXfOuwJ1AgKR7SBI4aaE1++xSSBI2j72W1Jp9Nn7tOxq3iwDNhB4XJA3OaeTvpGPSe+PfFX0tqTcnNd7kGD9vRooo7kgy3EoCtCL0uEDDv6XI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7V1rkBvVlf5uP6TWc0bz0HjeY4/fBoPtYC8EE4d4AwEcIJssm2xBIMFslsLOspUKVKo2TFKprSSkNtls7bImu7UkqaVSdtYJmAALCzMGAsTGxsYPPBk/5iHPy/OSRi11q7vv3R+jlls9LY2kmbFNar6qW91qSd0tne+ee+6555wm+GiCXIZrsstwzXnH5fgji0G++yMF7BcL5rCfT/AfeVJcaQTIdT/EsrULm9g+k2/fjlxCZg7v5drmOudHAlcCAZzuwUngpICW67v54CRsajvm1HJ9137uKxqXiwC5hG4XJJfe5yyvnbZOn7Vfy3rMqTc7NZpja9/PRQorrkgyXEoCFCJ0u0DN17zl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b1plF3XdR747TPc4U316gFVRGFGAQQsQBJJQRI1tCUokbsdy/EUQ5aTbseOE3pSPHQ7S3Y8kGi7O57t1WspCZW0QycrVodod2JbseKIDoFoaaBEihKpKpMgJmKoV0ChXr2qN9x37z3n7P5x3616VSgMhYmkVN9ad70a77S/s88+++zzHcIbEzT4DTPf2ZMTrfbjO3uR1wlWfdLXEa5p6CNHjiz+bmJiYvHrmZkZOnTo0JovdOzYMYyMjCxe4MCBAwwAjz766DLDryDHG54UrzcCLN7PasaemJigQQOPjY1RvV6n/fv3Y3p6evF/G43G4teVSuWaz7iwsMAAUKvVlhmy0Wjw2NgYA0C9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQBQAAEAUBvCdM7AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1pcBzXde53bi+zD2YAEiQIcANXiZIoUTZpWYtp2dlkK1KclJ04FVuyIz3Hz3LivGz1lhKVclJJnBc7cRKXlORZcdWzn82KEoeynFiRCFvxKlMyRRMWSXEDQYIgsc3S0/u970d3Az2NnsEMFpKy8VXd6sZgprfz3XPPPfec04TXJ+gqnFNchXMuOa7Gg2wHza6PWthvFyJmv5ngX/ekuNYI0Oh6KLSNCpsi32m2H0UjIYuY/zXaNjrm6wLXAgHiriFO4NRCa/TbZogTNo98Ftca/TZ67GsaV4sAjYQeFSTz91no77ht3Hej5wp/Fteb4xpvsI3uNyJFGNckGa4kAVoRelSgwd9S6O9o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDark {
            get {
                return ResourceManager.GetString("YellowDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQ0QAAENEB0NwSzgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAB/oSURBVHic7X15uB1Fmfevejl99nO37AshIYSQhbAEYlgMi8jgKPCAgChxBFzRT0BnRnSecQYd/UQYUHTmw2FTEbJADIg4DMygAgJuCCMBCReyrzf37Gsv9f3R3edU160+2z03uZec3/PUc7au6j79/up936q36m2CiQ3SgTq0jTbaqTMu0c4NPBRodJ2Ee22mTiNQwftGgp9wxBivBPC7Ll7QvMDrEaHRf/UTMmWK37F+gh/3hBhPBBBdCys8/r3os+g3vr4fWGHy7/nC/yaq59f+uMKhJoCf0OsJWHK+l5jPRPBeRAi/czYSOAVgca/8940IIjrfIcehIECzQucFzL7WK6I6fubBRSNhW8x7k3vP [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLight {
            get {
                return ResourceManager.GetString("YellowLight", resourceCulture);
            }
        }
    }
}
