//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laavor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CheckAllonsy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckAllonsy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasePackage.Checks.CheckAllonsy", typeof(CheckAllonsy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA2NSURBVHic7Z3bj+NIFcZ/ZTtOd/o60z0zIGDY1Y4ECBCLeEe8wl/Fn8Yj4oWLBIKF3YVZdtnLXHumpy9JXDzYJzmp2I4TJ2k7rk+K+nLKVWXX5++cOi5XDBrWGsAAERAD/exnDER9CPBoOuwNjIERcAvcZJ8hMMYYqwub6WHWACGwBxzFcBbAeQCnBg6ClAwhYDwLmolk+mNk4TqBiyG8CODZDbwELoFbjEnkmAiQwY+Agz48iuC9GD7owff34GEMRyHEQUoA0MTxaBKsBTuG8QiubuHlDXxxC58G8PEVfAa8wNobjBkDROrOP+zBD0L4MIYPj+HJPfjWCRwPoB9DEEEQg43AxmBLu+Kxddj0Y0eQ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z1Zcxu9tp4f9MSZomZbsmbK+5xKUjmp3Kdym/yq/LRcpnKT4VR2nbP3p8GyZMsSRYlzj0Au0CCbFCWRkgf5s5eqixTR7AZ6Lbx418ICKMiKUgIQgAN4QC599QAnBxa/5bWLCiABYiAEgvSIgAQhVPZkMfqaEoAN5IGKB8sWrFhQE1CytDHYgPhtBa9T5OglVuBLaEfQtKARwC3QA0KEkOY7DmCU7wClHKw7sOvBgQs7eVjzoGKDZ2kDgKzh/JbXJEqBSiCJYRDCbQCfQjix4GgAH4EmSgUIkQA4mZ5fduEvNvyTB/9UhfoivFmAahFyHlgOWB4oB5QH6tGq/JbvLkofKgbZh6gNvSY0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AquaSelected {
            get {
                return ResourceManager.GetString("AquaSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA87SURBVHic7V1rj+NIFT31cNlx0kk/0tusgIUVIyEECBASH/k+/2J/yvw1/gAIpAVpYRnUswu7O9M9s/1IJ3a5ig/xdSqO7by77Y6PFPVMbrlcrjo+99Z1ucIwD5Z+JAAFwE//KgDS932OFnWHnUwmCQANIAIwST8xgASAdQuz3L8FgADAkVLqjHM+5JwfM8a6nHM/tTPOWx7UEcYYADAAtLV2bIy5ieP4mnP+bjKZvAdwjykpDB0j079013d937+QUv5UKfUzz/N+EgTBR0qpIyGE4pwLp3yL+sFaa22SJInW+iGKoveTyeS/URS95px/+fDw8AbANaaKkADTQac7v+d53s+FEL9VSv223++/ODk5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAB/zSURBVHic7X1pUxtJ1vXJWrUvIMAG25g2dpvxOv3GdDhits/9L56f0j9teiJmPk3jbm9gMJYRu0D7Wqol3w/ollNFSSpJYOOGE0EAyqpUVubNc5e8mcXQC9b9UQBoAPTubw2Aouu6hGtcdnDDMGwAFoAOAKP7YwKwAXDxYub5WwYQAhDXNG1akqSMJEkpxlhUkiS9W84k6VoOLiMcxwEAB4DFOW87jlM1TbMoSdKJYRglAA2cCoVD9yjd3zTro7quzymKclfTtHuqqi6GQqFZTdPisixrkiTJwvXXuHzgnHNu27ZtWVar0+mUDMPY73Q6WUmStlqt1g6AIk4ZwQZOB51mfkxV1e9lWX6uadrzRCKx [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlackSelected {
            get {
                return ResourceManager.GetString("BlackSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA6ZSURBVHic7Z1dj+S4dYYfUhRVXf09XT3jIPbYCw8QB4kRB7kPfGv/Kv80Xwa+SWLAhr3OeuNZ2/HuzvTM9Ex/VJUk5kI6VWyVpPqulrr0AoXqblIkRb56z+EhxVY8gFOAAgxggSj/toCJIjQdmg43HJIAMTAChvlnDCSgnJ9ZedcpIAB6wLG1XGjNQGvOlOJQa6I8XemOBo1EmmZfQOwc92nK9XjMlda8GQ55B9wAI1CpXGOyLydP/WEU8cIYfmAtPwxDvt/r8dxajoMAqzVBfp1HnA4NgnMOlyQkcczdaMS74ZC/jkZ8qTVf3N3xFXAFbggqATDek38UhvxDEPATa/nJyQmvzs/5zukpJ/0+kbVo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABcSSURBVHic7V1bjxzHdf7OqerLzOyN5FKyHcFRYBpBoACxIQTIU+BX+91AfoF/B/+Jf0Be8hME5CkvRgxDDuD4EomOIoukSPGy3JmuOicP1T3T3dPd092zS85o5gDk7k5XnzpV9dW51WUIVSLgIeGjTy2AGN4loFmM66sYJrJJZBhH2m1aZDq38HDGQWgBfTOHi+Z48DjDJ594AFouTpXff/ITg0/vp7hMTmNk91ijSyZckMWMmROIGoCJzdtt05H6kXgApAJVp4JrEf8iA33Ni8WTeeSe4fr8Nf7nwwXwUIp3aPnz419YPF3MkuT1+9ZGH8ZR/IMojv46Tcx7sbGnxtiYWQ2IASg1SnCkd0ykKqpe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDark {
            get {
                return ResourceManager.GetString("BlueDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b1Zr2NJtt/3WxGxB05nyKGqesB1GyrBMK4BS7gwoCdBr9K7AH0CfY7+JvoAfvFHuICf/CJYEK4NX7eu1F11s3M4I2dy74ilh4i9ucnDw0OezKrKrK4FZJKHDMaOYcU/1hQrhG0S+L3w13/ngBxfF8ggZznPsZkrMmv4hT5vWle6cnhqWxNkjS5W1NmKbz9U/O3fekC7xWXr/b/6V5a/e13yqhjlVC+NZq+McCGOgTGmIKgFI8b+uH36hY6j4AHRgGqtgWUIflwhN2a9vlpl9S3L8xn/7Xdr+H1ofiPt69/8e8f1elAUs6+dy36XZ/k/yfLsfygL+1Vu3chalxujFjGAyt4W/EI/MYlq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDarkSelected {
            get {
                return ResourceManager.GetString("BlueDarkSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABGzSURBVHic7Z1bjxzHdcd/51T1zHJJmowlShaSKA5EIEjsIA4EJG+BPoWf81H0OfIV9JBHv+rBQJ4MIwkgBAriBHYsK5ItiZTIvUx3nTx0VU91TffMLLlLTu/0H5jdme6q03U5tzp1aaEHEzPko0/wfMHi7JTlPccCZbEKeF+jLJlxwAgBw9M0F9QWuLyz5GJ1xsWjC1YffEAjIpanl/TFzOTjj3Ffwom7z32peKMJvCnwUOEuxhLBiazzzDg8BCNooDbhPAhPJfBVA7/3NV8/ec6zf/yASxEJKb1A2/n/9Av8W467q5q3VfmhV95zwp+J8pYq9wUWGE4VzGYmOESIYBawYDQmnIXA18H4LMB/W+C/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLight {
            get {
                return ResourceManager.GetString("BlueLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3ZchzLlp75uceQcyIxj4mBBE91t2YrM13KzlPoWo+i59Ar1APotmQmM12V2loynequPpxAzEAmkHOM7rpwj8jIRAIESO69ubm5aLQEkBEePiz/fa1/LfcQzIgWWiP+7i+4XONPqpTqDj4SP1a4boKkxE/5jkUpNC5pGpJoRVQpEcYTwvWQ+M9/JhVC6OL1IvtBay3+/u9xbqDsNGgIj9VUsSagJaGGpoTAEWJ6z0/5/kRplFQkWhAoQV8ouincugl3vTGj//BnIiGEyq4XYAb/P/0D7oZDLU7YlJJDV/LaERwIyYaUNAT4aBwpQeufSvA9ihBordBKk2rBRCnulOZcwXuteKsjPvn7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLightSelected {
            get {
                return ResourceManager.GetString("BlueLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z3ZchzJkp6/iNxqR2Hl1mxuwBnJJDONTPeyuT1vMY8yjzaXupJMks3I5kxzaTbZxA7UXrmF6yIyKrMKhaUAkg026WbFAisyIyPTPf743cMjUjEnogAF+EAIRMV3CPhRhOaH3HeROCYHMiAB4uKTAjkoqR6sKucpwANqQDsM2dSaLa3pKkVTa6KiXOkfZnAvxRj7BWQiTI2hn6acas1xHHMGjIAElHHn+PZLXK9vRhEPfJ/nYcirIOBZrcZOGNL2PEKt8YrzKobzQ+6RiAiS5+RZxiRJOItjfk8S3mrN68mE34BTkBhUDuBXen4rCPg7z+Pvw5C/73TYXV/n4doanUaDKAzRvo8OQ8T3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSelected {
            get {
                return ResourceManager.GetString("BlueSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABOcSURBVHic7Z3rjhzHdYC/U1U9M3sjaZOUZCdxlJhAYCRGbATIvwR6CeUR8hpmXiN/8gB6iDi/8s9GEtgBlItjCYoVkxLNFcndnemukx9d1V1d03Pbndmd3e0DkLvbferU5Zw6t7q00AGV58+RX4DjKaNSGR8VjN5ZRkWFs4phzAB7DLMKRanslFJGTM/ecFEoFy9Omf30J1SIaIovzW+q8tHfYZ8+ZTJ2nMwsjwvlCcIjHEdGGStYI0mZAfYLPCh4VUqU80o5Ffh6Krwsz3n18Ii3H/6a6fPn4mORmpmq8rd/j5uOOHrreb8QPhxZvl9Y/tAK7znLiRNGQQBQBiHYRxBQBa0qqgrOqopXVcX/Tit+ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSky {
            get {
                return ResourceManager.GetString("BlueSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3bchw7l9/5A5CZlXVk8UyRok6b/NqOGcfYMRG+80S/RM8jzGt4+zV84wfoh3DP1dyNY+xwO7r9bUlbWweeyTpnZSaAuQAyK6t4LInan7Y+QUEVWYlE4rDwx1r/tYAUzCUrfv4Z8d8hYJMot9SaIdFYEYWaQFkkNX6kbzhlGotFq5RcRKSTIdPQMj3tk/3Dv0cjhK3mF+Vv1oq//Q+ozU3iWkA7U6yHlg0EXQKa0lKzoKSo3PMjfVvJgAVjLTmWRFv6Ai5SwVmecLnSZPTiV9KffxamuMUNprXi//qPBGlEc2TYDgUvIsVPoeK5EmwFinYgiLwAYPkhBN9iEmAtWK3RGiZac6k1H1PN [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSkySelected {
            get {
                return ResourceManager.GetString("BlueSkySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABjtSURBVHic7V3bjiTHcT0nMqt6umf2puWSulASDS1gGLJgCTL8aOhJgD/AfjPgPxH9GX7yB/AXDFgC/CoLtgEaoGhLFkGJEi/LHe3OrSsz/JCZVVnVVdXV3bNz2ekAlpyuzIq8nYyIzIyMIlqkfBcgvvu+BVCWTmZzzkt34Eu/tBZ2KTOU2NPNpHMAVqCuKpx4V53h/GJpeX5/bs+PZ28vf/JTOIKav8P0h0L5jz/6qcGnbx48OHjznixPH3vhGzD60Ig9dKIzem8o5ErJe7o5pOq9aqWKM614DOEXhH52dsJnF2fLl/j1Oxfvgj5lj4Op/Kcf/tyeuMeHF17fmln7jinMd+QA3zYWb0op98SgBGCE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3ZjiTJkqb3iaqa+R57Ru5bVXEIojngDIbgJdFXA/AByDsCfJM5fAxe8QH6FQZgD8Db5oALesjTp7srKyu32MPDN1tUhReq5kusHll5qvJUlQKZHm6mrqaL6K+/iIqKCStJ5Q8g/NXfOyDPvWl1pJP7dshD5RyuMi1yfk9fZyoAZ1BfZ94EX88oyspJsdFxxbD1rPp3f4sXRJd/I80fisr//Nd/azncb2+29wemmu4GI3tY3bLG9bzRloRgxYhcefLv6etJqiGo1qrMtJYhRk4EPZpN5LScVWO+f1X+AQlN9jSYKv/Lv/k7N/G7vTLow5Zzr2xmvzVtXlrHvsnNwFhywBqJwvILNe/3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueVioletSelected {
            get {
                return ResourceManager.GetString("BlueVioletSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABp5SURBVHic7V1Lrx3Hcf6qqmfOuQ9ekiIl2Ymt2DCBJLCBOPAiu0CrAPY+PyO/wcpfyC6/wfustQsQwHAecBD4GcuRJetBiZTI+5jpqiy6Z07Po2fmHN5L3qt7CuDlmZme7uqqr6u6qx9D6BK9AxC+CwegPD/C6tijtBVKO4eDWzH2dK3JM0z8uSdDTYyL6hznTw5wfneF6sfvwhNgaXpqfhhA//g2BB9jXaxxB6vygSo/lILvEdERwCszCDEI2OPgepICCgVQq7czIn2qqB7Xyp+U/vyzi0M8w7u4eAfQ5o0GAPTPP4D7wONI3OpNLty33Lr8jrjiz6Rcv8FFeUdYShALMQDbAGdP14eMYGRm6r33 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b1LjyxJlt/3O2bm7vHOyNd9VFV3z4gNkMIQEIVZaCfMSgC518fQZ2DrK2inzzB7rWcngABBSgIFamY4nOnqqro3b74z3u5mRwsz9/CIjIjMvHWr+lZ1GapuRHq4m5vZOfY/Dzt2TNgs8jsQ/gIH5Ms+xcCTa0GuSxyuMPxSPuviDWr90otSiWFVLlnedVkeFZT/9m/wAtq+X+ovCvK//hWWD3SyDkOK/DQEc2YzMxaRPphCFSsGgV/44PMsAQIBqILXhUi4D5TXVTCXuV/erHpM+RtWv4NQP1EzgPzvf4n7ztO3rnhtMvdnrpP/M+uy39i888pk+dAamyPGigF0zTi/lM+nqKCiqsF7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrownSelected {
            get {
                return ResourceManager.GetString("BrownSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA7VSURBVHic7V1rjhy3Ea4ii+yemX3IWslSkMRxYAFBkARxICA/A//SDXwerY/hM+whDF8gQRI4AZSHAxuOpFjSaNfa3ZnuJis/tjnicLp7nque3uEHCJrZ7uKrPlYVi+wehGng8fExAgABgB6Px8ne3p5mZs3MBAACIrYaxhiWUhpELBAxy/N8fHp6Oj48PMwfP35sEJH9+9F9YGb87LPPJACkSql9ADiy1t6RUt5CxAEAJMwsEREhYpthAaCw1o4Q8cxa+6ooihda62GWZecAkB0fH1t3s1Mmfv755/T06dOBlPKeEOJDIvpISvkzKeX7Qoh9KaUGAFnqP5JgC8HMjIhsrTXGmEtr7dAY898sy742 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA35SURBVHic7V3fjxy3kf6qyO6eXUvaRSRbMXKnyzkGgsABLgc/5C3Yv8L/pP8AvfrBr0bu7mFx8OFyhwTR6RRHjiWtdnu6WZWHbY443O6envXuDlvDDxA008Mmi6yPxWLxxxLWQapKp6en9sWLF+Xh4WFljCmZuRQR27YtV1WFjHQhImqtdXVdtyKyrKqqPj8/r+u6bk5OThwRaZie/AdVpa+++soAWNy/f/9+URQPReQRgGMAH6hqRUSGiAgZyUJVRURaIrogolci8hLAd23bfv/27duzk5OTJRGJT0/dS/TNN99YY8wHbds+ZuafM/MviOifmPkjZr4PoFRVw8xQ1UyCBEFEKiKqqo6IzkXke1V9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLight {
            get {
                return ResourceManager.GetString("GrayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X3bchtLst3Kqr4AIAne7wRJaW8fh2NOhI9jHvzm2F8xPzkfMK/zMK8Tx3bE7OMYj2dLJHgDSRB3oC9V6YfqajSaDRKgKAmSmBESIAjorqrMWpW5KiubMCnEzPTrr786jUbDq1QqvpTSE0J4WmsnjmPh+z7eZHFFa82O46ggCGKtdej7fjAcDoMgCKJffvlFERFnv0/2DTPTn//8ZwmgtLKysuK67qbWegvAGoAlZvaJSBIR4U0WVphZa61jIhoRUUdr3QRwF8fxw2Aw6P/yyy8hEWn7fUp+RH/9618dKeVSHMe7QohTIcRPRHQihNgRQqwA8JhZCiHAzG9GsIBCRKy1ZmZWRDTUWj8w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLightSelected {
            get {
                return ResourceManager.GetString("GrayLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X3JkuTItd3xAUMEYo6MnCqrusnXZjKZnpmejAvttOQf8Hu6+Bn8ht5zrR3N3uZpMMpISqLYXV1ZOcQ8IgC4uxYORziQiMyInCqrK69ZVmRlwAEfrh+/99zrDoK8kPfv3xMAHIC7Xq+9Wq3mKqVcpRQHQPEqL1qEEIoxJgghCSEkiuN4PZlM1s1mM/7+++8FIUTZ1xPzi1KK/P73v2cAfMdx6gC6UsoDxliLEBIA8JRSjBBC8CovWSSAREoZEkKmUsphkiR913VHURQtAETv37+X5mIzmOQPf/gD//TpU8AYO6KUfss5/yfG2DeMsUNKaZ0x5gJg6fi/KsELFKWUIoQoKaUQQqyklCMh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GraySelected {
            get {
                return ResourceManager.GetString("GraySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABWUSURBVHic7V3NjiS5cf4iyMysruru6Z7pmZFhey1BA1iGBViGDr4ZOhmQ7n4MPYPGj+Fn0N1n3wzoIsuGDEO2JGtXP/s3szuz09NdlckIH5jMYmZlZv12d5Uqow9VXWSQwWAwIhhkRhLqQHgJAmABpJgiwylSKFIobIaMMcB+g4NOzdSBUIAwQ44p3mCKR8jxIzgQNK5O1TcF4Z9gAIyQ4CxF+oSFr9jwBRFNGJxBYUAgxiAH+wgC8R9AoaK3QvI2l/w1F/z5NJ1+gRmuAczw0lcE5gJA+GdY/AGTzGTPLduvpzb9ZmKSvxiZ0bOU0zNjTMpgU2JQs/MB9gAUqqTqxLnCFTczmX0xddPfz2azX+cu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABp+SURBVHic7V1LkyS3cf4yE1Xd0/PY2d3hUpYlmgxtyHZIEZZDB98cvEp3/QXf/B/2N+hv+OZfwKt9kR9Bh0OWKJmUaIrLXe4O9zHTVcj0AajqeqCqq+ex28PpjJiY7gIKSAAfMhOJBJrQJsIj0I8+hgOQ+xIz2kd+9gq5ZHCZzBg72mpaFjCHc18KSiUs7TXOywznDx+j+OgjeADWzE/Nzx9+CPn4HcxPZjhEkd+3jE8IfOxA+8w8U4OAQYIdDraRPBRkUDOUCjtTr6eg4ulyyV9l5fnXZ3fw8vfvY4lH0OqdCgD003+Ae7LE/uzl7F2XufezPP9BnmV/MZP5A3H5oTjJ2ViIAVgLODvaFiKYmpl6 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDark {
            get {
                return ResourceManager.GetString("GreenDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABX3SURBVHic7V1br+S4cf6qSEl9+tznnJmxEWdjwwMEwSaIDQN5DPK6r/kF/in7T/JXnMe8xEgAJ4Bje53Z9WbXO7edyzmnW2JVHijq1lJLfTmXnlYtFjPTpKgi62NVsVikCHUiAIRPYQHEcEhAiHGDGAY2iRLGSA+b5tCZnTlkyCCYQzFDhhmeIcWv4ABotTrV/v5PMPgNJrjEcYz4gpUvmfiMLB0ycwKBAUBsRhw8RBInAEGgyFT0RkTepkhf8ZxfzKLZa9zgA/6IOQAJz1Dx5y9g8RKHSZI8tdb+OI7in0Zx9FeTZPIkNvGxMSZmZpM/QS3vH+n+SVVUnTiXZdn1PJ2/ns1nX89n8y/SLP39dXb9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkness {
            get {
                return ResourceManager.GetString("GreenDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z3ZjiRJdp4/W9w99lxrmYUjDtiQKJCAKPBCdwJvyXfhO/AZ9ES8FW+0ABQEajgke3qpqtwzY3V3s6MLM3P3iIzIjMyq6q7uKisUIiN8M7Nzzn9WM1esNwUo/gwL5DgKFDlLcgy2yArNl/ZptxJZ2ZWjpsZTIqyoWfEVFX+PA6R7ulr7+68w/CM9Thnn5Cda9KlW+lBZNdRaF3gMoLT5wgefYvPOg8Ij1OJl6b2/ragudanPV9nqiiUz/pUS8Oka1Xz+JZYLhkVRvLLW/nGe5X+S5dm/6xW9l7nJx8aYXGtt4hVqy/O/tB+/iXgR552r63pRVuXVqlx9V67Kf6nq6p8X9eIPzLnkO1aA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarknessSelected {
            get {
                return ResourceManager.GetString("GreenDarknessSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3JziU5luf3OyTN7M7f6B4ekVnV2egAGo2SoC40oKVQ29oK6H2v9Bz5Jv0AeonSUhs1pEZJUCm7hszISB+++c5mRh4tSLNrd/oGd49Ij8wg4H7vd41mRvIc/s9IUtguwq+Rv/p7HJD7mkKG5KsFuc1wmS0MP5cvupQV6lj72lIHodQl6zpj/e0Hqr/7Ozyg3frS/f43f4P9+1f0LgvGVPmFZuZSMKcOGRpjiqBYDGL5mQ++xOIJiBJUqQO6Cj48INVNWZqrrF7frk6Y//OvKPk1obmnYQD5D/8L7rpkWMyLr1zmfpXl+b/Js+xfFbb32rp8bJ3NjRorBtAtxvm5fClF0KCqwXtf+3pZ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkSelected {
            get {
                return ResourceManager.GetString("GreenDarkSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA6dSURBVHic7Z3bk9vIdcZ/3Wg0OJy7hiM5FVv2llUVpxJXnMp7yq/2X+U/zY8pvyRxlV32OuuNtbbj3ZVG0khzIXHpPBCH0wQB8M4BhvhQKo54Go1G94fvnL6gqfDhUIACDGCBKP+0gImINB2aDjdkmAIJMAKG+b8YSFE4P7F6OA0FBEAPOLbYC40eaPSZQh1qdJTblabjQRORkY0/IHG4+4zsOia+0ug3Q4bvgBtghBonhPGTLo1vgMOI6IXB/MBifxgSfr9H77nFHgcEVqOD/DxFhybCOZxLSdOE5G7E6N2Q4V9HjL7U6C/uuPsKuMIxRJECGO/JPwoJ/yEg+InF/uSEk1fnnH/nlNOTPv3IYrXB [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLight {
            get {
                return ResourceManager.GetString("GreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z1Xkxu7e+Z/QKO7mYecpHSUR8d27brWW3u/5dvdT+WP5sst32wqu7z2X+HoSEcjTWIOHfDuBRpkk8OJGh2NwsticYZAN9GNFw+eNwCtKIugAAUYIALi4jMCTEys+Sm3XWTGLAcyIAFmxTsFchRSrqwWh6GAAKgAzYhoS6O3NbqtUHWNjotypfmpB7dRLNZ9QCbI1GL7KemxRh/OmJ0AIyBBuYrgRrrvfAPUY+I7BvMkInoeEj6uUNmNiJoBQaTRQXGc4qfcRhFBJCfPM7JJQnIyY/ZHQvJao19OmPwOHCPMUOQApjTyGyHhXwUEfxcR/V2L1l6Hzt0NNlo1anFEpA1GR0RiMBIRyblN [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLightSelected {
            get {
                return ResourceManager.GetString("GreenLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b1JjyXJlt/3O2bm7ne+N4bMyBpedTf5AFIQAVHgQjuBKwHkXh+Dn4FPH0OfofdaayegN6QkNCF0s/ux36shI2O88+BudrQwd79+b9wYc6isqjxZiahId3O34dj/jHZc2CXhDwjggJQ1GT1SlBTFZWSGL/R5k0fXdu0RCoQNOWvGrBmS8x/xCNq8Xer/U4T/DQu0SOinpCcmmFNjzUhEugaToVgEMXzhg8+RAiH+gEKDroKESR7ya1OYy3W6vmHDHNjwh3gjbBlA+N9x/EQ3s9mZM+4vU5f+88Qmf9GyrdepSfvW2tRgbNlC9l/+hT4DUlRF1QfvC18sN2Fzs/brHzebzR9zn//DMiz/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenSelected {
            get {
                return ResourceManager.GetString("GreenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABROSURBVHic7Z1LsyQ3Vsd/R1Jm3Wc/3A8zwBhPjIPHMBEMwYIdwRb28xXY8Rmmvw87FqxZz2YGCBOEYWbAZozddrftdnffe6syJRaSMpVZmVmZdau6q1x1Im73valHHkl/nXN0dKQUEnIgPEH4EMMjcl4y44ScjJwFBpkpjrTbpHGomxJLwZw5BTfc54a7LPgZpQguzS7xlzD4mqecUHCJyh9g1ENQ9xA5BzVDoXEIHHGwm2T9P44C667BvsAuniPqS+TmK17xiveZyxOfEQIAHAh/h+GMc25m76LN++j8h5jsD8hOHqPzS5TOQWkUeBAcaedIcDjnsGVJWVxRzr+iuPmU+fw3uMWvuLn6BMVzvuJG [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABNUSURBVHic7Z1LjyS5ccd/QTKz+jEv7exDgu31CruAYViAZejgm7Enn3y1v45GH8P+CnO3r7oJ8EV+wIKxlmVbgqSV9jE7s9vTj6pk+JBkJpOVWZXV1d1VNZ3/mUZVZZLBRwQjgkEmU0igIOgz4TkOKHGXM04elFRacqUOh2HCfqOoFLEV57JA5Ao/v2T+8pJ3Hs/5+IeViGiaXOIXVRV+/CPLZxzxqHiI8JQr/zbWPgE5BWYYtajIUqET9geCR1mAvwB5hfovmS8+pypf8K2rMz7mSuSZb5MDqgj/8PeOd397irHvUZoPMO5DxP4xxr6LMQ8RWyJYEFAmIdhHiCoqivoKqnMq/wKtfkN19T8sqv/G [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLight {
            get {
                return ResourceManager.GetString("OrangeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3Jkiy5tp73Ad5Fn5GRfbv7OkYTzUQaB5zJ7kgjTaXX4eFjSK9w5tL0zmjGCUnRdHh5Wbup3WSf0XfeARoA7uERGZHdbqtqr6rckenhDodjLfxY68cCXFAQDQL9V8HfcAEfNwyo1HxS7RNpFxfJT/mxxUs1wkmZiAQhIlQcEvdCttZi/uHfpUIIXTxdZL9orQX/+O8dLinR8OoINojUJo7TBFEFAqR20ELcuOlP+XFEoNAkoKYg+mjVJk6uSP0O69GIfyAS4q9qdjqgNYL/6/902T6tIp0dfPkU6b5AOE+QzjZS1hGOj8ABAZqfRvAjitAaLTRapZBOSFUHnZ6QRm9J0tc46gMpbSb/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLightSelected {
            get {
                return ResourceManager.GetString("OrangeLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3Hsly51uf3A7BN+uMPvSfrqlsdoe7ogWYKTaV5v4Jmeoa+76OZBhpr3JN28X3Run2LxWIV3fHpcxtgaQDszJ158jiaKl6SKyKZPLkdgLXwXxbYihoJKP6K4p+I2CNhREqDhJiEggiVan7Q100GQWcWR0lOTknGFhkbFPx7rFJI/XRV/Scw33BAg5IuOtkh0rugN1GqDTpFYxAU/JCDr5Oc/0cocTIDN8AVJyh9hMpOGTPmMbn6qz8RggAIKP4PIlq0ydJbmOgxJnlGFD8ibuxjki7aJKANGrwQ/KCvjhSCiOCsxZZTbH5Kmb0lz39Bip/Jpr+hOeGUTP1fWAA1n/kf6FLEf6ER/2uS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeSelected {
            get {
                return ResourceManager.GetString("OrangeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA2CSURBVHic7Z3bc+Q4FcZ/st3upHOdSWYGChh2a6cKKKBYineKV/ir+NN4pHjhUgUFC7sLs+yyl7lmJpOkLxYP8mnLatvtdncndlvfVm8yObIkS5+/c3SxWmFBoxWggAiIgWH6MwYihgR4tB2aG2bAFBgDN+lnAswUStuJVXaVVkAI7AFHxJwRcE7AKYoDAoapXXkatBTJ/P9TNNckXDDhBQHPuOElcAmMFSqRSyKYd34EHDDkERHvEfMBA77PHg+JOSIkJiBMr1N4tBEajWbGjClXjHnJDV8w5lMCPuaKz4AXGn2jUDOAyHryDxnwA0I+JOZDjnnCPb7FCceMGBITEBEQo4nQxOjKqnjcPjSGAlMS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABGeSURBVHic7Z3brhzHdYa/tarmwE1SJEJSspBEcSACQeLYcSDAl4Gewtd5FD9HXkEP4FsHMJArJ0gCMICARIEdyYqkiOZhc++Z6a6Vi+7qrq7pnpl9Imf29E9szkx31arTX6tWraquFhIYCGbCZ888fDPl7GTGPTcFnbIKHl8ozBixxwjBwJeUiwILS+7MFqzOFjxZrPj001JELA0u8YuZCb/6leNb5rj795HJI8rwGOEhyl2wGYhDRNZTHbE3CBbQUGByTpCXSPieku/wxXNevDnl7z9dikiIwQXqxv+H33jed3dZFR+g+kO8foyTP0P0fVTvI0zBHKpgNpJgHyFiWDCClZicEcJzgn1F4Ass/Ce2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLight {
            get {
                return ResourceManager.GetString("PinkLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3HbiRLt9/7i0hXnrboXXez9wc5SMIB7p0J31NofB/lPMd9hTPQUNMzEKCRIOgK99PB0W7HpjfF8pU2QoNIV8Uim2R37829uxdBFFmZGRlmrX8sFxGCEmkQaC34h7/ZcOkyqXk0LBekS6Rs7FiCx096waSUBjshCWK0Cql6AdEkoB1E/PWviRBCl28X2R9aa8E//qPFFRWsZhPhrJCoVQSLSOqgPRAWQoi7b/1JL4aUVkgVo4WPEn2E6pBwjR3f0huP+H/+GgohVHa7gHTw/9//ZrNm1YnidaQ8wJZvsMQ+Qq4hZROBC9pCStD6JxO8RBJCo5VG6QQtJih1i9KnKD6g1Tt0+Bl3r8Pk [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLightSelected {
            get {
                return ResourceManager.GetString("PinkLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z1Zcxs7t54foCfOoibKlqyZ9M6ppConlftUbs+/yE/JT8tlrpJKTuVLzne2hi1LtkZKnNkTkAt0k02KGijZ3vK2F4umTHSj0Y2Fd71rYQEUZESjBSAAG3ABL/l0ARsPyS9566LxiYEICAA/eYdALBA6e7AYn6UFYAE5oIzLMpIVJFUERSReUi5+qcEbFTX6N0IzRNEmpInkGp9boAcEAqHSU2wYdb4NFPFYw2YHl30ctslRw6WMhYvESs4T/JK3KBqNJiYmYkDALT6fCThCcsCAT0BTo32BiAHszMgv4fAbFv+Iyz9Soc4i71igQgEPF4mNxEVjo3HRjzbll3x/0RgViFD0CWnTo8k1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkSelected {
            get {
                return ResourceManager.GetString("PinkSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABWCSURBVHic7V1LjyS5cf4iyMysrurpee6ODNvrFTSAbViAZejgm+GTAPuun+HfsK2fod+wd519E6CLX5BhyJZkrSxpV9qZ2Z7d7q6uTEb4QDJflZn16kfVVgbQ3dVFBhkMxotBJpPQBDrHOQGwANIb3GSnOE0VmirUIgNjhL0GB6fmxjgCFQRa5MhvLnBx8xiP84/wkSOQ1utT/KBQ+gF+YABMEiSPkOK5sLwwbJ4Q0QyMTKGGQDSKwZ6ClL8LUZmT0DvJ5U3BxefpTfp2gcUlgMU5ziWiRAGgH+KH9nf43cxk5iVb/tCm9lsmMX9mJuZ9TvmRMSYFw5BHoXbfIzw8KFRJScWJc4W7loW8dTfut4vF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3ZjiRJlp75yaKqtpu5uXt4LFlVSbCAwWBmMCQa4CXBqwb4ALznm3TyMfgM9RBEv8AQM4OeBmqmu5pZmRkRvtm+qarImQtRVVMzNzdfIiIjMjOOI9I9zVRUZTnyn1WOKnZJfcd3CrBAvGGTdOjEgsSCWBI0X+mLJocTszFOoXKFSjOyzYTJpk8/+zv+zimU1K9X5R+CqP/CfzFAIyLqEnPqtT8z2gyUUm00iSBGodRXNvhCyVf/zb34tfJq6jN/m+v8Ot7Eo5R0AaTf8Z0vm5QMoP4r/9W+5W3bJOZCW/2tje2/NpH5g2mYFzrWXWNMjMao0ETtP/srfX4SRJQo8c47l7uVT/3IbdxP [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PurpleSelected {
            get {
                return ResourceManager.GetString("PurpleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA6HSURBVHic7Z3bk+O4dcZ/AElQrb5Pa2acSjLxlqcqTiWuOJX3lF/tv8p/mh9Tfsmlyqlkk/XGs7bj3Z3pmemZvkgiiTxApwlRJHVXkxK/Kpa6dUAABD5+5wAEIYUHCwp3hIAB4smnAULiWNOh6bAMhymQACNgODnGQKrA+olVfhYKCIAecIoxV2g9QOsLlDpG63hiV+iOB41ElgFkQIK1D2TZDePxNVq/ZTh8D9wCI+XSAO5Ol84PgWPi+CVh+EOM+RFR9Ff0ei8w5pQgMGgdTM5TdGgiLNZa0jQlSe4Zjd4zHP6R0ehrtP6K+/tvgGsLQwUpQOjd+SdE0V8TBD/FmJ9ydvaay8sfcH5+Rr8fY4wm [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA4/SURBVHic7Z3ZjhzJdYa/WHLpquaiIWc4guyRDBEQBNmwjAF8aehq3kDPM9Rj6Bn4EMK8gAXbkATQtiRIGA3H4rCnKXZ3LZkRvsgKZmRUZtbarMqu+IFCL5kntvNHnBMnlhJ4sCB49kwAGkiZTjPOz1OsTbFWA5KI40ZZWpQqEaJAiBnz+ZTLyykPHsz5/PNSCGH914X7xVor+MUvFJCTJPeARxjzGKUeIsQYyLBWIYQg4phhgAJjJgjxBmNeUxSvSNMLZrMrYCaePTPuZQGLnv/LX2q++mqMUk+Q8gdo/UOU+j5KfYSU91AqBRSV/iMJjhHWWoSwGFNSljcYc0FZ/oXZ7A+U5f9izJ+B1/zmN1Px [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLight {
            get {
                return ResourceManager.GetString("RedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z3XchzLdqa/zHLtLRxB0IM8oZiZGE0oYi4ndHXeQM9zth5Dz3AeQqEXGMWMQhrpaNNsWpBotHdlMnMusqq7utEA4UiCm1wRHTBdWZVm5Z9r/WtlliAnBgS//CIAF/AJw4BKxccYH2NcQPJTbrcoZXAchRAJQkTEcchgEFKvx/zpT0oIYfKXi+wXY4zg7//eAQp4XhVoo/UWjtNAiDIQYIyDEIKfcptFAwlazxFiiNZdkqSD7/eIogkQiV9+0dnFAtKZ/w//4PLhQxnH2UXKh7juExznAY6zg5RVHMcHHOz4/1SC2yjGGIQwaK1QaobWPZR6TxS9RKnnaP0G6PKv/xqKP/9ZAYgU9h2C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLightSelected {
            get {
                return ResourceManager.GetString("RedLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z1ZcyM7c6YfoDbuErX1dnpX97FjxjGemPsJ39q/yj/NlxO+mS38hefz6eX0qtbKnawNORcokEWKkii1ulu9ZEQFJaKqiAISb76ZSKAUJRFQ2MMHQiAqPkPAJ4o0v+SmixDHOZABCRAXRwrkCqR8sppdhQI8oAI0CcNNtN5C63WUqqN1VJQr9C89uJFiDIABMkQmGNMjTY/R+pA4PgGGQKLsOYAd6a7zfaBOFN3C9x8Rhk8JgodUKjuEYRPPC9HaK65T/JKbKIKIkOc5WTYmSU6I4w8kySu0fsF4/BY4FogV5AB+aeQ3CILf8by/Jwz/nlZrl3b7NmtrLWq1iDDU+L4mDAXfF8JQzq3K [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedSelected {
            get {
                return ResourceManager.GetString("RedSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABgISURBVHic7V3bjhzJcT0RmVXdPUMuKXG52vVlvbYIGL5oLcGA3mQIfvAfSM/+E1G/oV/gR0h+0pNt2AZWgGBbtgRp19qVKA45l+6ujPBDXirr1l3dPcOZUVeA7OmuzIrKy8mIyMjMKEKTSJ8/pxd/CYvPn5ZWdaaPihLLdbm2Yq0qAzNMdFdpCXFW56U4qbi6cOvVwupy/VKXT79xtv72t7/niEjzOyh+UVX60fe/bz5/+nRu3rEPSeUJObwLy48ZdArBDOQMEVP3wRPdBXIACBBVqdThig2dOSe/dU6/sIW+fCVfnP/j/2JFz59LvIcA3/k/+MEP7HvlxelaZl8pC/qI2XzVsP0TZn6PmB8SUwnA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X3ZkiNJdt257rFhTSAB5J7V1cOWybRwRJrM+EYZTQ/6A/JZf8Lmb/AX5iNIPfFJkkkymxmjScPpriUXAIl9icX96sHdAwEkkAlkVU1X9ZSbVWZWhMPh4X79+LmL3yCsF+Lvv6df/Vt46HYCjznkIz9AnAappz2PWQAhvpbPtcTQyuMo0EpnIpurNCl5HKcDjjt/Pk7/6q/+VhERFz9B7g9mpn/8u7+T3U4nknWvRqxbpNCGJxoCVIFGCFKSSNDjL/5aPoeiABCgmXXGCkshaayUflCKe57Pg5Huzf7rD0jo+++1+wwBZvL//u//3jsJ5pVUh6eBT6+FkH8ihfeNEOKEhKiRoACAJBJg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TanSelected {
            get {
                return ResourceManager.GetString("TanSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABUASURBVHic7V3bjuRGcj0RmSSrq3q656rRwra8ix3AMGzDawjwo7FPAvYD9t1/otnP2G/QRyz0A17YhtaA7LUMybKk1cy0ZjR9qSIzwg/MZCVZJOvSVd3VUwyg0VXFjLyejIiMjEwS6kR4/pwAWAApptMMx8cpVFOo2gxgDLTf5JxOjXEgKkA0Q55P8fr1FKenOT7+2IFI4+RUfVIl/OY3BsAISXIvBR6xyGM25j4RTRjIoGpARAMK9pNk/q9QkSshepOLvOKieDFN0zPMZucAZnj+XAIPVf9/+1uLb76ZZMY8tcw/Ta39eWLMX46MeS9lvmeMSRkwIIr5BtonUlUlUifiCucuZyJnU+f+bzabfZE7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z3JjiS5lp4/Dmbmc7h7DBk5VN3b0gUkQQIkoRfaCVo1IO37MfQMXf0Y/Qx3r7V2AnrTGtBCqyVd9a0hKzNj8HkyM5JakDQ39/AYc6isqmTC4ZFOoxmHw/+c8/OQJthNgm++EYAGUjabjE4nxbkU53QGki/p807GuI1SBiFKhMgpig2TyYajo4K/+AuDEK5+uaj+ck7wl3+pgAZJ0k3hWFp7IpXqCyHaEjKcUwghvkjB55ns9qt01q6tENPC2mtZlpebNB2R5wsg55tvbCwjqu+/+ivNjz+2M6WeaSl/m2r9jxOlftNQ6iyVsquUSiUohKiX+5I+p+Scc0I4Y60pjVnl1o42xrzO8/z/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TurquoiseSelected {
            get {
                return ResourceManager.GetString("TurquoiseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAr2SURBVHic7Z1tbxu5Ecf/M1zJsZ3EQZzEV7RNU1yAomiBXtH3/WrJx+urAu2LFg3QXpHLtXeNe2kebMne5Uxf7FKmKO5GkvWwEvkDBNm7XC45HA7J4YMIHqpKAAhAAWAI4KD5HjbXGJm+owAsgArANYCr5lMCsESkfmCaPFUXvgFwB8A9AKcAHgF4AOAYtTIYESHmrAd9RETAzAKgstaOjTEfAPwA4BzAOwAXAK6JSNwzBEwKv0Bd0GcAngH4UkR+BuCJqt5DbQWM/1ymdygAVVVLRCMiesfM/7LWfm2M+TuAb1ArxBURWQAovJp/tyzLXwwGg69E5CtVfa6qX6jqfdS1n1WVAaiIaPOyTP9QIhIi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z3ZcuPItp6/TICjSFHzPA/dccKO8HH43q+2+zH2I/nOYUeHwz67NE+lmTNADJm+ABIEIVIlqaSSqkqrQ02VCIJA5so///XnygVByrTWAhCADeSBQvyaj/8m+bSPbhoIgQDwgF784wOhEEKnDxbJp6LOt4AiUAWmgRlgAhgjcgZLKSWk/PSDj2hKKaSUCgjCMHQty2oCd8ANcA90AE8IocxnBCSdbxN19DywAWwrpdaBOa11lQgFrPTnPu3DmQa01joUQjhCiHsp5XkYhgeWZe0BJ0QO0RNChAB2auRXfN//M5fL/btS6t+11jta6wWt9TjR6JdaawlopZSOv+zTPp5pIYQSQvhCiI5S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhiteSelected {
            get {
                return ResourceManager.GetString("WhiteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA1wSURBVHic7Z3bk9w4FcZ/st3umZ5LJplJAgWE3dpUAQUUS/FO8Qp/FX8ajxQvXKqgYGF3Icsue0kmySSTmemLxYN82rLadrvvdltfldOZPrIkS5+/cyTLaoUFrVGAAiIgBvrpZ2y+6wd4NB0a7ibAGBgCd+kxAiZKoe3EanqW6fwQOABOID6H4AKCM1BHEPRTuwLPg2YikX/GoG8huYLRJQTP4e4lcA0MlTIJwdzp0vkRcAT9xxC9B/EH0Ps+HDyC+ATCGIIwPU/h0URo0BomExjfwPAl3H0Bw08h+BhuPgMuteZOKSYAkXXnH0PvBxB+CPGHcPoU7n8L7p3CoA9xAFEAsYZIm0+PZkFjCDBO4N0I [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABLaSURBVHic7Z1bjyO5dcd/h2SVunt6bjs9MzaSbOx4gSSwgTjwQ96CfU0+QL5FvkO+Tz6AX/2QpwCBkwBeBJvYTnbjzXovszuzM9PdUhVPHkiWqFKVVFLfpFGdgUZqkUUekn+eGy8SMlIQFOEjHF9QcsIES4mhxOOoJoYJI+0yeRR3WXNJhWfKhEvOueSSGR9Si6B5dkkfVBF+gQWOuM99ivIJ3pyBeQRyDzUTBIsgYG69XSMNIQ+Kx1MheoH4V/jZCzBfUV1+w1ve8CFTEXx6QiAO/r/gsNyjmjzHuB9gyh8hxR9jjp5hyvtgS9RYDKBz4Iy0QyQoXhWta6Q6x0+/QS8/g+lv8bNfMz3/lPd5wT9x [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDark {
            get {
                return ResourceManager.GetString("YellowDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3ZblvL1t/7q5odG5HqG0uWZNny2giSIAkC5DL4bvMCuc6j5H3OA+T2BMjtOUESZCf4spcbWbJltaTYzq5GLqomOUlREmXLXt5eHoBAijU5WVVj1H+0VVNRIgGFoPgrPmeE1IjwCNGEGHyySBPxi35kMgh+nBOTYUiIiBkQE5PyD+RKIeXLVfFGBMX/iwdUaNAgCFcxeg30Eqg6oiMUHgoF+ruP6xfNQwYEgyFDyRBlbjDpFegLsviaPj3+gUQpTPENBY75/x8+HnWyaBPtv0CHr1DBPrqygQ4b4IWI9tCAjAXnF/1ApBCMCJLnqGyASa6R+CMkbzHp7ySDD+xxxX8hVv+eHMAXy0yP [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDarkSelected {
            get {
                return ResourceManager.GetString("YellowDarkSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+QAACPkBIHobXgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABDJSURBVHic7Z3djmRHUsd/kZmnqqe7Z2fsmbHXwhgjj4RYQCxC4hItL8E1j+Ln4BV8wStwBzcIAZK1mGVBXq3X+Gs84+mvqjoZXJzMc/J8VVd3VbfrTOVfqq7qOnniZGRERkRGfpSQQBUBFT79xPGMGYuLOW+dzlgwQ5aOhTPMydhreEUpKcsVK10we3DF6+UV7z9bwi9KEdG0tMQPqirwj5avvz7ixD7EyxNW5VOQxxhzgmeOYEGk/9CM/YH3qFmheon1r1jJd7jyG8S94NuXZ3z4dwsR8bG0QBT+3zt454Rvlu9izIc49xFq/wCRd1DzECMzFAsG0KwEewlRUMX7EtELxL8A/wWl/x9U/xv0N7w9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLight {
            get {
                return ResourceManager.GetString("YellowLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3Zchy71t/5A3KqmcV5nql9Ps92OMKXDvdL9HU/ip/Dr/C9hO+6b7ojbIeP7eMtkaI4jzVXjkBfIDMrq1ikOEh7SzpcESWWsjKRQGLhv9b6YwEpKIjWCNCCv/6jzSIu4dBjtuYS4iIim9CWeLzLDy1Ko0lIkphYh7jlgF4UsLEYwX9IhBC6eLbIvmitBfxni+vrElWrjhLzxMkCiCZSVlF4CCwQ4uFN3+XHEaXQMkZrH0t1iMUddnKDsO+5bffZ+b9CIYTKzhaQdf5/smGpyk20jJQ72PY+2tpGiCW0rCOFi8YCCeh3JfghRWjQGqUShB4i1D2oMxJ1iNYfQX9hzr2DYSDE/5mYK7KR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLightSelected {
            get {
                return ResourceManager.GetString("YellowLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI+AAACPgB8j35ugAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z1Zcxs9l99/6JW7RK22JFsbrWdSSVUmlftUbudb5KPko+UyV0llqjIzed/HkrzIsiRK4s5egVygQTYpSiYl24+8nKoWKaIbjcY5+J8FB2hBjpRCAAJwAA/ws09P/+Zb/KbnTgrCFEiACAizIwZSIVD5k8XoKs18GygAVfBWwVoDaxlEGSw/KxfwWw6eJ0nzJwEVgOxAfANWE8JboA9EQugTQY90w3wHKIO/Cc4eeIfg7kJhA7wq2B5Ydnad4Dc9R1KgFKQpJEOIbiH8BNEJWG9h+AG4UYpQCFIAJzfyK+D+AfY/gvePUGtA/QUs1aDkg2eBY4GnwFH68zc9L1JoAUgkDGLo9OGmCdfH [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowSelected {
            get {
                return ResourceManager.GetString("YellowSelected", resourceCulture);
            }
        }
    }
}
