//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laavor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExpanderAllonsy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpanderAllonsy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasePackage.Expander.ExpanderAllonsy", typeof(ExpanderAllonsy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtEAAACACAYAAADNhDV8AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI1AAACNQBu2JXWQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z1ZcxxXmp6fk1l7Yd8KIECQFClSpEiKIsVFXEVSC0fd6m1iPOG5cDh84Qjf+A94HLavxr/AvvHFOMKesCemp2emp8dWt8fqTT0jWVJLlEiJItUUKW4AARBrYamqTF9kJnCQrEJVAbVkAt8TkaxCbfnWQVbh5Zfv+Y7Cj20rwHA3U9u829RTzxEEQRAEQRCE8GO7W8G3We4GStngN8QrBtoEou4WS0LUdq4btnP/088VBEEQBEEQhPBiA7aCgoL8POSAJXfLu5tjspWyIytPW2WgY0AiCakCpBQkgVgEIjhGWiEmWhAEQRAEQdg82AosBfk8LMVgwYDsAmSBefcxnpHGMdGOgfZMdAxI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15bBznmaefOvomKZG6TFESJVkSKV+KFMlOfDtW7MiXrMOyKMl2nGP+WGCAxQILzGKBXQwwWASLCTC7i8EGk0k8mZnMJDNJxpkc441ix3bsOLES27EdHxPHsmXTkizrosSzj9o/qj7yY7Hvru6ubr4PUOomu45ffSx1//qt93tfAx3HMbxnprdY2qJ+ZyAIgiAIgiAI7YXjLVnfkvMWMAwHwM6zsTLOEW+JJiDquOuajvs6iJEWBEEQBEEQ2gMHcAzIGpAZhzQwhfuYBjKAg+OAYTgzBtqNPivzHAXiCUhmIWlAAojaMybaQAy0IAiCIAiC0B44BuQMyGRgKgoTJoxNwBgw7q3jmmhU [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AquaSelected {
            get {
                return ResourceManager.GetString("AquaSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d1ZcxtXdgfw/729ocF9XySKskRttiRnnHEmk5dkqvKQykOe8g3yno+QVD5PqpKaKXvsGUUbtVO2LFmWZYkjSqREUdzFBcTSy80DcFuXLezE0gDPrwpFEkv36SYIHhycey/Dfiz3lecumnKR1zEQQgghhBDSXkTu4oUufu4i7wM9z4Nl4mzkLqZt26YQQgfAhRA8dz9KpAkhhBBCSDsQAARjzGOMuclk0gGQAeDkLm7uPgAg1ASa4UPybAKI2bYd9zwvzhizAZi6rsskmoESaEIIIYQQ0h4EY8xnjLmu62ZM00xxzvdSqdQegGTuPkESLRNomRBzZJPnuGVZXYyxHtM0e3Rd7+Kcxxhj [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d3Zk1zVfQfw7zl362U02qURkkAWIjYgC5sECgLlAuPE5SyVSvySVKpSlYdUHlJJ5TVLJfEfkNc8G2sZexASIDkQkCUbXMY4GARBRhKDpAHtI400Mz293eXkofs0V1e99+3p2z3fT1XXjGa67/3dM62ZX//6d84RuJOofpTVmxG66a8JEBERERGNFlW9+ZFbUL3p+8Cs82CdOFvVm51Op22llAlAKqVk9X5MpImIiIhoFCgASgjhCyG8QqHgAigDcKs3r3ofAFDhBFrgi+TZBpBKp9MZ3/czQog0ANs0TZ1ECzCBJiIiIqLRoIQQgRDC8zyvbNt2UUqZLxaLeQCF6n1qSbROoHVCLFFJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlackSelected {
            get {
                return ResourceManager.GetString("BlackSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d3ZcxzXdfjx7+3uWQECxEaAoESRlEiK1EKJIsVFJEVSJLVQjmU7capclVTlT0hVqvKYX36Pecz7r/IUVzmxS7G8S44XKbFsyZRkkpIokjI3AcS+YwazdPfvoediGsNZgQGmBzifqq7BMtN9ptEAzpw5917FEq7KfWDkNtO36a8phBBCCCGEWF/c3GYXbE5uA5QLYBV5sE6cQ7ktHIsRdl0swHBdjNz9JJEWQgghhBDrgQu4SmErRTaZJAOkgUxuy3r3cQHl+hJoV5FPnsNANBYjbtvElSIGhC1rMYlWSAIthBBCCCHWB1cpHKXIZrOkw2EWDIPEwgIJIJm7Ty6JXqxAuzohNvCS53gk [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtEAAACACAYAAADNhDV8AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI1AAACNQBu2JXWQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3ZkxzHle75HfeIyMwq7AAJEFwEUiRICQAXkSAgECQhiJuaoqTe7u2+M3dmbMxmHsds5mFexq5199v8DWPzMjZzr9l0T3ffXiQ1Wy2JrY2X+woJ4AYSAAHUhtqzKjPC/cyDR2RGZuUSuWehzs8IVmVFhLtHZIT75yeOn0PYCAF/rPDoboW5ssYOo1G0GpGvMLmqYCICtjc4TBAEQRAEQRA2K8uA9hjLPiMggwllsKQN9gYGb81b4C8tQADAQPxbCiegj0BjNu+joH1oExQ0+azKPqxS7CsFALC2/lhBEARBEARB2JwoxSiFTB4ZinS0ZmyIbVQG6TKKsxE+2RYBf8VwIprTQrgqoIEA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDark {
            get {
                return ResourceManager.GetString("BlueDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b1psCXFlef5P+4ecZf3HgmZrJKQEAKEQBIIhBYQYhGSQAghsUmQmSQgqW1sbD50zXR/aGuzqZLN9HRPmc2MTU+PTXVVd6mrq1StvbQikARiFSAEiH0RCCSWTMhMXm5vuTfC/cwHj7j7EvfeuMvLd37G5eW94eHusfo/Thw/h9AM+T9XK5x5mMLuqsYhVmPZacSBwtySgo0JWIAgCIIgCIIgHBzsB7Rh7A8YIVmUlcU+bbEptHho0QHfdolMZqAmmGsQcLXCqdDYVQxQ0gG0DUvkQjbWwCnFgVIAAOda1xUEQRAEQRCEtYdSjErEZMhSrOMV6yLMUxUuilA5EOH5+Rj4DsMLaG4UwXXx [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDarkSelected {
            get {
                return ResourceManager.GetString("BlueDarkSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b35jyRHluf3eeYeEZmRR+SddZDFqiKLZPMuks0qklUki2ST7GkOe2clQvuH7GIXAnYxrT9Agn6VIAiCoIUASoCEHYyOkXZmIU33YHpGzavJbh5Fsu5kVt53RriZfnD3CI9IjyvP8Kr3AaoiM9zd/LmZudvXXz57JtThxDn46CPMwllMfgXPG8MzG3gDBUx5A7PhIUMoiqIoiqIoyr1DJcCVA9zoMQJvnSA/TDA0R3D1KvbDD7EiAOIAJHmgc04++gjDk3ibN8gNTZFzhrzbIL/t8PMDmKCMKQBlU3+soiiKoiiKomSOLbA5XM7h8AisoeIbyp5je32O8uAG5dWfU/niV7g//3MciKuK [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLight {
            get {
                return ResourceManager.GetString("BlueLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b35kxzHlef5eR5HZmVVAVWFGyAOggABkiJ1kJKogxIoURQpUrxB4iCl/gdm9sedH7t/mNnZne61tV3bnbHeHes1mxnbMWNvz5iN1rZbarXU06Nu9ailVkviJZIASBAESBDEXVdmuM8PEZEZmRV5VWVVZVS9j1lWHhHh8cLDI/wbr54/F5pw4hy8/DLm8n5MeB3Pm8IzM3ijJUx1BjPjIeMoiqIoiqIoytqhFuGqEW5yO5E3TRRuIBq/RHTqFPboUawIgDgAyW7onJOXX8ZwF97sewTjWwmcIXQzhPMOPxzFRFVMCaia5m0VRVEURVEUpXDMgQ1wgcPhEVlDzTdUPcf89CWqYzNUbzxK [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLightSelected {
            get {
                return ResourceManager.GetString("BlueLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15jFzlma+f72y1ddt4xxgwGC/NEhwcCAmQAMEJYTGbjcG4seMQ8sdIVxqNFOmORpq5kaJRNLqR7ox0NdFkApckJGQdCIEwOBAgECeQOAQMmARiYjBesd3t7qqu7Zz7x6mv63S59qXrVPX7SEdVXVXnfL/zdXX1r97zfu+rmIKnCneMwmYGNv2YQhAEQRAEQRD6C6+w5Us2t7ABygOwyuysjbNd2JxYDMfzsADD8zAKrxMjLQiCIAiCIPQDHuApRV4pcqkUWSADZAtbzn+NBygvYKA9RdE8O0A0FiOezxNXihjgWNakiVaIgRYEQRAEQRD6A08pXKXI5XJkHIcJwyA5MUESSBVeUzDR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSelected {
            get {
                return ResourceManager.GetString("BlueSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b1ZcBzHuuf3y8yq7sZOAATBReImidKRRO0SSYmkKOpIOtLZ7pk78rXDfnX40eHwyzjmYc7xmx/84BdH2GHH+MUR9ihshz0xN+7E3JgZe86de3btG7UckeICEACxEGt3VaYfqqq7utEr0A10A98vguxGV1VWZlV25r++/vL7FGU4hYN330OPzqPzGUxoMHYB4w+hV0J0sI4aGkIQBEEQBEEQ9gT374OXw/l5nBom1JbQhISZPOH8KPafvYtVCkA5AFV2tHPq3ffQgMldxzcH8cN1MtYjEwZ4OovWFg1gAxTZnW6eIAiCIAiCILSJjehFe7hCiFMZQhMQWCioAvmCo7AcUhg8TPDeZzh+ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSky {
            get {
                return ResourceManager.GetString("BlueSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b1pkCTXtd/3OzeXqq7unhUYYDDYl5kBSBAEATySIEECIB8IEOsAGACDGQAUFQ5/ctj+Zn0SGbbDkp4VtiNkhf0kh2xHSCE9SE8KS/Z7XECCK0gCJLHvxDLALMBgMGv3dFdl3usPmVmVlV1rd1V3Vff5RVRXdWXmXfJm3fzXqXPPEZpwgoPdT2I2HsNUQ7zYw7PH8YJpzEyMieaQ6WkURVEURVEUZVVw6hT4ZVxQxck6YmOJvZg4rBIf24j9q91YEQBxANJ0tHOy+0kM4JXfJ/DOIojnCK1PGEf4poQxFgNgI4TScndPURRFURRFUQbEfPJkfFwtxklI7EVEFmpSo1pz1E7H1KbOJXry [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSkySelected {
            get {
                return ResourceManager.GetString("BlueSkySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtEAAACACAYAAADNhDV8AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI1AAACNQBu2JXWQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3ZkxzXlf/3PfdmVlVXb+gNG7GRhEQRICmSIAGCBPdNotbR/KiYX9jhf+AX4bAf/GBHOEbyg9/95gg/+MGOcNh02A7H+BczmhmJMxrtQ4kSSYxIkCBI7OgVvVdV3nv8cDOzsqqytu5aG+cjgV1VmXnvuUtmnjx57jmEKhhMP8Q76rUzD6ibizN6dGJEZzfXtBnzFJc8tW2Ion0nqg8WBEEQBEEQhCFjNfyb08wFZXk0P2YKWyWzsbplDs2cMFMPwL79DqxTgokBgJIFMJjeAdTF0xf1qA58T034gR3JaCr5RIEPP6/YFBUABLbyWEEQBEEQBEEYVjwFDojZN77R1gTW+qUt2i56lC1m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b1psCTFtef5P8c9IvPmvbVTBUUVUECxCCQQQmhBPAQSSELsBcVSRSEkzYzNlzGbmS9jM/OhpZlp6+l5bdbW1tNjr/uNTbeNjfX0NK+1Pb0ngTaeNtAGElCF2ItiKaiiqPUumRnhZz5ERGZkZuS+3Mhb54cV996MCPfjHh4ex08eP4fQCAkE9+FRvunqC/jgkQ1mdvWMKSycNOGcZalaXgqJkpNXQ1EURVEURVGmlxPxz6IRKbOT2dJcWF6shmecWAwrG7aF6y6A2/koXKQAkwAApQsQCD0K8L7L95lZE3iWV3uBm/EdTvo+WwuvxBJWGCggcGWCoiiKoiiKokw5liEBiXihFxoXBs55 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueVioletSelected {
            get {
                return ResourceManager.GetString("BlueVioletSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b1ZkFzXla73r733OZlZVajCSICgOACcxXkGSILzIFFSa+im7HvjXkc4/OgnRzjiPvihWy9+8KMjHOHwi5/c4WvdG3KrW9fqllotUWpKLTZnAiLBCcRcKFSh5qrMPHsvP+xzsnI4mXlyzgLWFwFUVebZwxn3v9dZey1CLcQAfvg61K4voA7ugJ5cgF4rQKMIhQJU0YJ2QBAEQRAEQRCuDlYA5DR4cxWcn4Cd3IBd2w17/QrsrsNwr/8YjvymDABUXZgB+vHrUCdOQK9qBFMKASYQwhZCEJucgYJlBQCRqy0rCIIgCIIgCNsRo8ARgY0jq5iiCBtlFaBUvILyfBHlYw8hOvFj8F95Ac0V [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b1psCRXlef5P+e6eyzvZaYyU7sECCGQQIAWtkIgQCBWLYgUKVAqMyUBVR/mw1jNjPWHnjGbKWbKymqqbWysu62tq7sWhq4qiipV0SAWCQkEAgkJ7btS+65UKvflLRHh95754O4RHhEeER57vJfnZ/nyvQj3u7pfv+ceP/ccQjMkAK7aDF7/PPjkNTBz+2AWSjCogFECVyxoDRRFURRFURRldXAYQMFAlo9AimXYuSXYhQ2wJx2GXX863OYb4Cg6VQCA0okFoBs2g594AuaIgT/P8FFGAFsKQOIVPDCsMACErjmtoiiKoiiKoqxEPIaEBPEcWRYKQyzV2Ee1sh+1vRXULjwP4RM3QP4k [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrownSelected {
            get {
                return ResourceManager.GetString("BrownSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d1JcxxHejfwf2ZWdaOxgwAXkKIkUhQpiaI4JIdDSCTFRaSGVJgajx1ihL+Gr3OwdPHFX8AxF18dMReHI+yIOdgHx3hiPO+ExBFFakiIi7gBIBYCaDR6q8p8D+hsFoq9dwG94P+LQGDprqqsp7u6n048mSmwnjDG4Pr163JkZETu3r1b9fX1qVQqpQBIADKbzYqBgQEQEREREXWDZDKJeDxuMpmM6enp8fv6+vxUKuWPj4/7IyMj+osvvtBCCAAwACCCGxtjxG9+8xt5+/ZttbKy4vb397sAYoUvJx6PS6wl0vA8T4CIiIiIqMM5jmM8zzOO4/hSSs/zvLyUMpfNZvPz8/P5s2fPerdv [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d1bcxtHegbgt7tnAOIMgieJsmQdLa1kyytZK1GyZB28K5/W64uNk5v8jVylauP9BfkBucylc5PKVnKxF95UpXar4tpa27GtWsuWbYo6UBSPEAECmOnOBTHQcDQABiQoAOT7VKlIApgDBtOYbz593S2wkTDG4OOPP5aHDx+WxWJRFQoFVS6XVTwel+VyWSqlBIiIiIiIdhDXdY3rumbPnj1uqVRys9msOz8/7965c0d/+OGHWggBAAYALP+CXvB86tQpNTMzY4+Pj9sAYgBia2trVjqdlrVaTQKAlJKBNBERERENtEqlAtu2jVLKKKXcUqnkSClrxWKxWiwWa+l0ugbA+eijj8xHH30E [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLight {
            get {
                return ResourceManager.GetString("GrayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d3bbxzXfQfw7zlnZvbG5VWiSEmUZEa0bClVEritnTSO5SCOL7Jl2bIkSrSV/6CvfXVfWqAI+tKHFgWKvvShgIP2oQHaxE3tXlykQRqgaez6IlF360pRFCUud3fmnD5whxqOZnZnubvcC78fgCD3MjNnZue3+9vD35wjsJYwxuC9996Tk5OTcnFxUQ0PD6tCoaBSqZQsFApSKSVARERERNRDPM8znueZsbExb2lpyevv7/fm5ua82dlZffz4cS2EAAADAFZwQT95PnDggLpy5Yo9OjpqA3AAOMvLy1ZfX58sl8sSAKSUTKSJiIiIqKsVi0XYtm2UUkYp5S0tLblSyvLi4mJpcXGx3NfX [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLightSelected {
            get {
                return ResourceManager.GetString("GrayLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d3pkxRHej/wb2ZWVV8zjBgQaBBaoxUroUUHu5Iciyz0W2yJXRnJi8AgNDBY8l/gt35lKexwOLyv/GJf+HjjN36xitg3doTX2FbEei2HFolF3AgECJA4xAzHnH1UVf5eTGdTXVT39FF9fz8RE3N0V1XW09XdT+c8mSlQTmitsWfPHrl8+XK5Zs0alclk1NzcnAIgAchcLieGh4dBRERERNQPZmZmkEgkdDab1clk0stkMt7c3Jw3NjbmLV++3N+9e7cvhAAADQAiuLHWWnzwwQfy1KlTanZ21h4aGrIBOMUvK5FISCwm0nBdV4CIiIiIqMdZlqVd19WWZXlSStd13YKUMp/L5QpTU1OF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GraySelected {
            get {
                return ResourceManager.GetString("GraySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3ZkxzHleb7HfeIyKUKhZ1YKFIESJAEN5AgQAIEQYKrKFIcbSOOTZvNmM2fMGZjNg/3YVov92Ee5+nafZmnkd2e7jZOs1u7Wi2J3ZREiiKbBDdwAQgQexVqXzIj3M99iIzIyKxcIrNyiaw6v7KyWiLC3eOkR8TnJ44fJ9RCYACvQGErFPZCYwwai9AAFACFEgibIAiCIAiCIAjrg3kAOTBWwMjDYAwGizDYA4OtsPgBLAgAwAAqv0YwCH8NhQ+hsQAX43ABeAUUPAY7yEExWAEAgrpjBUEQBEEQBGEUccAIwOSQIUXBcrDsQ6GMEnxMwcdJBPgQjL8EA2AnPpBBeAUK90ID8DCOfAGF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtEAAACACAYAAADNhDV8AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI1AAACNQBu2JXWQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b35kxzXle/3PedmZlV1Ywe4LyIpbhLATSQICARJCOKmoShpFr038+xnOxxh/+gI+wf/4ngxM7/5b3D4F4f9XoRnPDNvFo1Go5HE0fq47xLAnQBIoNEN9F7dVZn3Hv9ws9auJWuvBs6HBNBdmXnvzVuZN8/95rnnELZC+D744b3gS2WYXRam6GCSEDy7DrYJCDtbHKUoiqIoiqIo25VVwASQ1RASEewMw64Y2P0R7GuLcPgLOBAAQACkP9YgfB98EDALeYQFg9BYRIYKIZcldAwOWRgAnNtyrKIoiqIoiqJsS5ghpRgSENnEUGLdRryDUCaDcnEByYc7kOAvIfBGtNQbwlUDGkAUB8gn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDark {
            get {
                return ResourceManager.GetString("GreenDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtEAAACACAYAAADNhDV8AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI1AAACNQBu2JXWQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3bkxzVtef/XXvnpapaNyQBAnETdywJZIOQLCQEAiP5YIwv50z85sQv5mEe5nEefy8TJ06ct/k3Jn4zEzETY/v4gm0OB4MxmAMGDAJsSQgEkpDUre5WX6urKnPvNQ9ZmXXpunddslrro1BI3VW5c2dW5t7f/NbaaxFWQwAUHoXCDDQ2QSMPjRAKE1AwoAbbCIIgCIIgCMJ4o8FYBMODQQ4GCzDYBoP3YQHY8rsYwCpBHAno3dCYhossXGh4WZ11WbELC8UuKwCAFTEtCIIgCIIgrBMUGEUwOWQopHDFrATYgBIIJeQR4ixCRAKaAXC1EK4IaMBDgEw2zOaMY3KO42QZ7DnkONBQzExY [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkness {
            get {
                return ResourceManager.GetString("GreenDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b17kCVVvef7/a2Vj/2o7qZpniKCiNgDCgI+AQUERVCEQwMK/bIFT9yYuH/M45w/Jk7EzDViztwTJ2JuxJyJiXGuo1yPjyOCCiLYPA+vFgRplDfYHBBou2m6u6jqql21d+Zav/tH7sz9qP1+5q76fbSimtqZa63MnZnru775W79FqIXKvxXOhsIBaKyGRgEaIRTyUDDJNoIgCIIgCIKwPNBgHALDg0EOBrMwWAeDp2AB2PJWDGCJGCYACqdBYz9cZOFCw8tS1mOHHVgodlkBAKwIaUEQBEEQBGEZoMAogskhQyGFC2YhwBRKsAhQRIBdCBGJZwbA1SK4Ip4BDwEyWTebM4HJOY6TZbDn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarknessSelected {
            get {
                return ResourceManager.GetString("GreenDarknessSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b1plCXFlef5v2bm/paIICGTVRISYhMCSSAQWkCIBCEBQgiJTYLMJAFJffr0mQ9dM90f+vQ5U6Uz09M9dc70nOnpOVNd1VWa6ipVa9+FQBKIVYAQIPZdILFkQiZEbrG8525254O7v/C3u7/nb4mI+4PIiPfcNjd3N7t2/dq9hGYIAHAV1BmHQL1Zhz7IQi866NCDmlmAsiEIcxAEQRAEQRCEtcF+QBvwfg/sE2xVwe7TsJt82Afn4fBtuFhKZiARmFcgXAV1CqB3l+FVNDxt4ZOr+MaycQrKU6wAwLm2vIIgCIIgCIKw6lAKXAvAhsiGmkLrloJZQt0FCGoHEDw/ixDfASMSoDktBDeE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkSelected {
            get {
                return ResourceManager.GetString("GreenDarkSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d3pc1vXefjx77kLNlKkSIkiJdmyJFuSZVuWLUvWYkmWF9mJ5TRbm85kpp3pn9CZzvRlf/297Mu+/01fNTNpk3HjOGkSp47jpHFiR7YjKbYsyda+UNw3gFjuPb8XwIEuIawkQFyQzwcDcQFw73OvQPDhg+ecowjSqMJnVuFqB67mewohhBBCCCFWFl24eiVXv3AFhQZwyjzYJM5u4RqJE49otANYGm0V7ieJtBBCCCGEWAk0oBXKU6hcilQWyADZwjUHaDSg8kmxeZjiXvIcAWJx4gkPL6FQcSDi4JgkWiEJtBBCCCGEWBm0QvkKlcuRy0SIzFtYyXnmk0CqcJ98Eo2pQOeTZ5NAR4BE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLight {
            get {
                return ResourceManager.GetString("GreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d15jFzVnejx77lbbd023jEGDMbYzRIcHAgJS4DghLAvBoOhseMQ8sdITxqNFOmNRpp5kaJRNHqR3oz09KJHAo8kJGQdCIEwOBAgEBJIHAJmSyAmBmMbG9vd7q2We8/7o+qUb5drX7puVf8+paKbrqp7f/d0ufpXv/rdcxRhGlX4zipc7dDV/EwhhBBCCCFEf9GFq19yDQpXUGgAp8yDTeLsFq5egoSn0Q5gabRVuJ8k0kIIIYQQoh9oQCuUr1C5SSazQAbIFq45QKMBlU+KzcMUR5JnD4gnSCR9/KRCJQDPwTFJtEISaCGEEEII0R+0QgUKlcuRy3h4UxbWxBRTE8Bk4T75JBpTgc4n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLightSelected {
            get {
                return ResourceManager.GetString("GreenLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b15sBzVlef/PffmUsuThBYWgTEGA1aDzeYVG4xlYzCbjRHIRkjC8tJ/zB+/6JiY/qNjImba8evp6OiJ+aMnYmJ6fl4It5f20vZA44UGQxsMxmYzi9jBYhOS0Iae3qv3qirvPb8/sjIra9+rst47nxcv3pKZ9548dTPz3JPnnkOohcAANkNhNRROhEYeGvPQABQAhSIIKyAIgiAIgiAIS4OjAHwwFsHIwCAPg3kYrIfBaljcAAsCADCAyq8RDMJPoPAMNObgYgYuAC+LrMdgBz4UgxUAIKg7VhAEQRAEQRCmEQeMAEwOGVIULAQLZSiUUEQZB1HGxQjwDBh/DQbATnwgg7AZCmdDA/Aw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenSelected {
            get {
                return ResourceManager.GetString("GreenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3Xk9xInuf5cQcQESmYSWaSTIoqFskqltaKosgqluwS3dNidnrN9uzObv+ENVuzu7V72Jl7uId9ur2Xezq7pxvbnZ6x3u0ROzPd29PT09O6FEuzNHUyM5mKqSIA93sAEIGIDIGIDJn8fczIiMgA4A4POPDFD1//uSKBBYUFvo9mF5o8DgEOO3Fw0CyjyaEQBEEQBEEQhO3EOpYMFpeALAGzBGQImMfwZxgUKLBAuRi2oPgjNOCQw2MSj3Uy+EMZXOui0CirAQhESAuCIAiCIAjbAAeLj0WrAE/5rK0V8MijKOBQ4Bo+D2D5Y6wC68brFcXzAzhcJ4NPjtWhYTLBMJ4aQpMhcEMRra3C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtEAAACACAYAAADNhDV8AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI1AAACNQBu2JXWQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b37jxxXluf3OfdGZlZlvVhVJKv4FNVSSy1Sz6ZIvUg9WlI/NJre7cV0L2D45/0H1oYBw8B2w4D9P6xh2D95YY8Xhn8wjFl7PD07s/PoGfV0Sy1260mJpEgWWUXW+5UZ9/qHiMiMzMpHZFVWVWbV+QBkZmVE3Lj3xCO/cfLcc4Q6vPfCn/7M8HDckD9pOTlkCVcsGxhKGIINgZFo5dH6rRVFURRFURSlj1hM3ixBseApr3vMQIgdCsmvhIycCPly3PHTnzpEEPAAkm4jEtB/auCaZX05x8hwjiJ5NoMc5XKOXMEQYigApbKgKIqiKIqiKAeBXOBxZY8EId6UKZVLWLNJLtgkvFFm+WqZ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLight {
            get {
                return ResourceManager.GetString("OrangeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b1psCTVlaD53etLLO+93BdygUzWTIQQAoFKSIUEJYSEQIIEMskNJM2P+Tc2/bP7V0k2M21lXVNmM2NWs1S39WJj0z1W6qlus66xUWmvUqlKEkJIYknWhMwkF8hMcn9LRPi988OX8PDw2N6LeLG885nFi3jh7veee3w7fuLccxQpLCishe/u01xYq/G3OmydcgiuOSygKaGZXVAwE26wCkEQBEEQBEEYTy7HH65AuWCpzVt0McCZCvCvBcxsCTi61rB3r0EpFFgAlW7DWqv47nc1vOYwf9VjZtqjjM9VfDQuXkEToCkA1ZpCEARBEARBEMYdz7WYmkW5AVbXqNaqOLrC7EKV6fNVrj5Q [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLightSelected {
            get {
                return ResourceManager.GetString("OrangeLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b15sCTVfe/5OSeXWu7tHWiaBpq9GyGxGbSghUVICLHT0NBNAwJb74+JmIgXEzER8+JFzNgTjhmPYxzxZl44nud50ejZ8pMlyyM9WdaChSVWWSCExCIQS7M13fS+3a0qM8/8kZlVWXVryarKqsq69/eJqFtVtzLPOXkyT+Y3f/k7v58igQGFAbahWYOmgoWPxWosLDTH0RRRCIIgCIIgCMJSYh6Di8HGp4DPAXxcfA4T8A0CFCgwQKMYNqC4Gw1YFHFYh8M8Ll7JxTY2Co0yGgBfhLQgCIIgCIKwBLAweBi08nGUx9xcFYcKiioWVfbicRGG38coMHa8Xk08X4TFPlw8isyWyrh+GUeV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeSelected {
            get {
                return ResourceManager.GetString("OrangeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d1ZcxxXltjx/82sHUsRa2GhuICrRFHcxUUkxUWUWqKmt/GMIybCDvsjOGIi7DfHzIMf/DZ+dUz4qSdi7O7omd7c4+7pnu6eaWlaUksiKZESqeZOAgRA7FstmX7IvKhEoVaglizg/BSlAlBVmSeTCeDg1Ln3KjxsbOV+aLg303PTX1MIIYQQQgixsdjuLZNzs9wbCmUDBPK8WCfOQfcWIkoImwBgYGO4z5NEWgghhBBCbARO8qzIoEizQApIAin3lgZsGxuFsgPZV9mKbPIcAiJEiZEhhiIKhAgsJ9EKSaCFEEIIIcTGYKOwUKRJkyTEIgbzLDIPLLjPSeMk2k4F2k2edQIdAmKEaUMR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b35jyRHluf3eeYeEXlH3lkHWawqskg27yLZrCJZRbJINo9pDntnJUr6Q7SQIGB3p/UHSNCvEgRBELQQQAmQsIPRMdLOLFbTPZieUfNqks2jSNbFSmblfWeEm+kHd4/wiPC48gyveh+gKjLD3c2fm5u5ff3ls2dCAgeCc/Dhh4bFs4b8qoc37mE2PQYLhtKmYdMThlEURVEURVGUu4dy4CgFjrFjAd5GQH4kYHg+4OpVywcfWEQQcACSPM45J3z4oYHHPbZu5BiezuFMHreZZ8f55AcNQclQAEpGUk+uKIqiKIqiKJlhG2zOkXMOvABryvimhOd22JgvMbRZYu3dMp//2vHnf+4EXEUE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLight {
            get {
                return ResourceManager.GetString("PinkLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3ZkxzXlaf5netLZEZmApmJHSAWggQBkiK1kJKohRK1kyLFDQSIjVL9AzPz2P3WpYdeZrpqbGzGZrqtZtqqzWbGps1YU91mrbGpkkolVatVpWqVVCpJ3EQSAAmCAAmC2HOL8Hv7wd0jPCI8tszIzPDM85kFMiLc/frx68v9xcG55wgZHAjOwYsvGq7sN4Q3PLxpDzPrMVYyVGYNs54wgaIoiqIoiqKsHaqRoxI5prZHeDMR4YaIicsRp09bjhyxiCDgACS7nXNOePFFA/d6zL0TMLE1wJkQNxuy4HzCMUNUMZSAipHcnSuKoiiKoihKYZgHGzgC58CLsKaKbyp4boGZyxXGZyvcfKzK [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLightSelected {
            get {
                return ResourceManager.GetString("PinkLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15kBzVnec/LzMr6+rW0bpotaSWhKRuccmSJbA5hZHB4hI6EGpJwGCP54+NmIiNjdiI2diI3ZiIiQ3Hxjhidjcm1jEem/HMeMaesT14fAxrGQwYjI0wYMAcY4xA0EhCoKOlvurK/SPzdWVX111ZXVnVvw+RVHVV5nvffFWq+tYvf+/3FD4cHOXdNbzN9G36MYUgCIIgCIIgdBaOt2ULtpy3oVAOgFXkYG2cI95mE8fGwQIMHAxvPzHSgiAIgiAIQifgmmdFFkWGcdJACkh7WwZwHBwUyrHyRzmKvHm2gRhxEmRJoIgDNtaUiVaIgRYEQRAEQRA6AwdFDkWGDClsJjAYY4IxYNzbJ4Nr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkSelected {
            get {
                return ResourceManager.GetString("PinkSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3ZkxzXleb5nXvdPSJyRWJfuAFcQIoLRJAQQYIguIukRG3V4li32YzZ/Alj1mYzZvVQ0ks9TD/NPLXVyzxNWfeo2lStKnUtaqmrVCqWihIXkQBJACQBglgSyAW5Z0a433vmwZfwiIw9IzI8Ms8PBovMjHC/x29cd//u8XPPIVRCDMZbeEtNYEIdxEE9jGG9jGUNQAFQRRRpFKMQBEEQBEEQhK3AIhaRQ47XsMZ55M0whs0yls0BHDATmLA/xA8tgQCAAYQ/xTCYfoKfqI/xsV7CkjuCEReAhwI8MJwccgoMBQABAlrXuiAIgiAIgiAMGA4cDhCwQ45RpIJgNfAVVKmIoj+DGf80Tgcf [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b1psBzVle/7X3tnZk1HEhoQSIDNIEAGDBhDt8GArW7AxoDNYAkQkkDu9v3wPjluxP3QcSPes+N2dHR0x/vQL6Lj3Xvd3Q734Ntt3/a1r902jdu8xjY2Zh40MQoQSALNR2eqqtx7vQ85VFZV1niqTmWds36KozqnqnLvlSt3Zq69cu21CPUQg7EFW9RKrFTrsV6XUNLTmNYAFABVRpmWYRkEQRAEQRAEYTFwGqeRQ47nMMd55E0JJTONabMO68xKrLSbsdkSCAAYQPBbBIPpe/ie2oM9egpT7gQmXAAeCvDAcHLIKTAUAPjwqal3QRAEQRAEQRgzHDjsw2eHHKNI+f6sX1VQlTLK1WM4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PurpleSelected {
            get {
                return ResourceManager.GetString("PurpleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d3ZcxzXdfjx7+1lNoAAARAECEoUSYmkKImiRJHiIpIiJVEb5XhLnCpXJVX5E1KVqjzml99jHvP+qzzFVU7sUiwvsS1HtiXHsiVTkklKokhKXEFi34HBLN39e+i5mMZgVmCA6QHOp6o5AGam+0yzARycOfdeRYAHKvehkdvMwKa/phBCCCGEEGJ98XKbU7C5uQ3l349V5Mk6cbZzW4R4PILnWYCB5xm5x0kiLYQQQggh1gM/eVbKQaksyWQGSAOZ3JYFPA8/ibYCz1Lkk+cIECMeT+A4CZSKAxEsSyfRCkmghRBCCCHE+uChlItSWbLZNJHIPIYxx/z8HJDMPSZLsAKdS551Ah0BEkSj [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtEAAACACAYAAADNhDV8AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI1AAACNQBu2JXWQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z1ZcxtXmqafkwtAAFzEndSukrxosS3bkixbkmWVJbvK43ZNdYQ9N/0vuq8mJqLtm57/UH0zV90RU9Mx0Rd90T1dMVU9NV1dnnK1N8mWJVkWtVAUSXFfAGTmmYtEkkkQS4JIEgu/JwKBJZEnT37IBN788J7vKIrQWis++sigt9dg716TTMZkackEDMAgm1V0dRWvJgiCIAiCIAity8ICJJOa1VVNR4dLJuOytOQyOurS2+vx4YceSqFAA6jwulprxS9/aXDjhsniok1npw0ksCwbx7FJJn0hDeA4atPGBUEQBEEQBKEVsSyN42gsy8UwHBwnj2HksKwcY2MOly453Lih+fhjrUBbwXpr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLight {
            get {
                return ResourceManager.GetString("RedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d1bkBvXeeDx/zl9wW2GQw5vGpISSZESSVP3i2PJlizasmxZkkWKJsWLKFt536o8bp4iVVIpV7yp2jy4auOkajcPm9qKt1ypSrbiSLYSx1EiS6J1JakrKZLiTSRFcsi5AOjusw89PejpATAApjEDYL5fFWowAPr06Q+X+XDm63MUMQYUxsDu3ZolSzSrVlkUChYjIxagAU2xqOjvRwghhBBCiJ5w9SpkMobxcUM261Mo+IyM+AwN+SxZErBrV4BSKDAAKr6tMUbxs59pDh+2uHbNoa/PAdyJi00mEybRAJ6nEEIIIYQQotvZtsHzDLbto7WH55XRukSxWObixTIPPOBx+LDh+eeNAmNH [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLightSelected {
            get {
                return ResourceManager.GetString("RedLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d15jFzVnejx77lbbd023jEGDMZLswQHB0LCEiA4IeyLwWDc2HEI+WOkJ41GivRGI828SNEoGr1Ib0Z6etEjgUcSErIOhEAYHAgQiBNIHAJmSyAmBmMbr93uru6u5d73x63Tdbu69rrVdav695HK1UvVvb86Xe7+1a9+5xxFgAeq8KFRuJiBi/6aQgghhBBCiN7iFS75kotbuKD872OVubNOnO3CxSGRcPA8CzDwPKNwO0mkhRBCCCFEL/CTZ6XyKJVjbCwLZIBs4ZIDPA8/ibYC91IUk2cHiJNIJMnnkyiVABwsSyfRCkmghRBCCCFEb/BQykWpHLlcBscZxzDSjI+ngbHCbXIEK9CF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedSelected {
            get {
                return ResourceManager.GetString("RedSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtEAAACACAYAAADNhDV8AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI1AAACNQBu2JXWQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b1ZkxxXluf3P+dej4jMyEzkAhAASZAgiywWAYJLgQAKBLgC7NpYvUhdehi9j76ANPPYRUkfo2XzNmoZJT3JNFZm6nWse6qtatpYza2KLBIgdiD3PTPC/R49XHcPjwiPLdeIzPMjkRkZ4X793Ovb30+cew6hARGhjz76iOfn57lQuG+MKRvmoilXI65GwjYoUOM6iqIoiqIoijLohNWKVCslmRgLI+PGo0IURaOVSvTNxIT7+c9/7ogIAAQA6gRxIqCBz83Gt+Vg9KgNxJQKgSAIHQJXEI7WhYvFIqphqGJaURRFURRFORAENhIXRQIJIhfY0K6jaoarlSAaqUQLC+HKiRPh559/Lr/4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3ZkxzXdef/PefezKqu7gbQ2MEVIimKhESKlmib1EITskRTIimSIkESC5f5C/w682QxYvyLcOg3DzMPmgiPJyZifhE/R5gT9oMdYYuyKduyZM2ihQQBElxAgAABkNhBoJeqzHvm4WZmZVVlVVd1V3VVdZ8PohpVlZn3nrtk5slT555DaIREBK+88gpfvHiRw/C0MWbSMJfMZC3mWixsg5CgKIqiKIqiKKuIqFaVWrUsM+ui2LgNcRjH8XS1Gh+dmXF79uxxRAQAAgANyrCI0CuvvMLAYTN/fDKY3mwDMeVQFmoh28C6UNjOCaNUQi2KVJFWFEVRFEVRxp7AxuLiWCBB7AIb2TnUTKVW [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TanSelected {
            get {
                return ResourceManager.GetString("TanSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3ZcxxHlub7HfeIyAUgQHBftJGiRO0skaJEiaKovSRVqbae0tiM2b1m90+4ZmM2Y9YPXXrph5mne5/G+uU+3baZqR6rnuqunu6urpru6mp1taq0lLhIIiWK4gaAWIgdyIwIP/MQ4YnIRO7IREYC52cGA5CZEX7C0yPi8xPHzyGUQ2AG3nlHYWRE4cABjYEBjcVFDUABUCgUCNu2QRAEQRAEQRA2BfPzQCbDWFlhZLMhBgZCLC6G2L8/xMiIwQ9/aEAEAAwAVLYxM+HHP1a4eFFjYcHF4KALwMsBHgMOMhnFkZAGgoAgCIIgCIIgCP2O4zCCgMlxQlIqWA4CH0oVUSj4mJryceZMgIsX [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z1rsB3Vdef/a+/dfV5XEnogkACbhwAZMGAMicHIthLAxoANyBKgF8iJ82E+uaZqPqSmasauSaVSSc2HTFVqHs7E5UniSeyJx44dm+CYCbaxsXgLvXgKSaAHel/d1zmne6/50N3n9jm3z/vV5971qzp1H6d779Wrd3evvXrttQjVEJiBTZsUli5VWL1ao1DQmJzUABQAhWKRsGgRBEEQBEEQBGFecP48kMkwZmYY2ayPQsHH5KSPVat8LF1qsXGjBREAMABQ1c7MhO9+V2HvXo2JCQdjYw4ANwe4DBhkMooDQxrwPIIgCIIgCIIgjDrGMDyPyRiflPKmPa8MpUooFss4daqMdes87N3L [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TurquoiseSelected {
            get {
                return ResourceManager.GetString("TurquoiseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z3rcxRXesaf07e5aXS/IUBcFgP2Ci82xmt7Y5x1lrWzttml1rtb5f2UD/mafMuH/AVJ1VblT0gqqXJVnKwvZcPaBgMGzB1swF6MsYHgBSQECAlpZvp2Tj5oTtNq5q4eTbf0/qqmdJmZ7qePekbPvP2c9zDMhQkhAEAp3lTfTQGg3L9/n2WzWRAEQRAEQRDEIkJMTk6Kjo4OF4D/xos3MMYEALA5zxKCoWicx8bG9IGBAR2Akc/nDcaYxhiTxvqh5xIEQRAEQRBE3DBNE4lEQgAQQgg3mUw6AGwA1vj4uN3X12cDcAAIAIIxJjwT7DfPAAwAyUKhkFYUJe04TooxZjiOowFQGGPMcRwy [rest of string was truncated]&quot;;.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z17jFzVfce/5z5mdmZf3rXxAwPB2IkNNji4McXYsampLQfiOA0JjwC1TIra/tH2j0pVVUWqVKnqH5Wq/lcpPGyv15AYmwLmWUwcF0xCEjkYYeSC65QAMfiBMbvzuK9z+sfOGd+9ntmdmb2zc2f3+5GudnZm7jnfe+bOzHd+93d+R2A0QikFAEZpM0ObAcAYGhoS3d3dIIQQQgghZAqhLly4oHp7ewMA4U2WNgghFACIUXspJVAyzp9++qk9Z84cG0CqUCikhBCWEEIb60v2JYQQQgghpN1wHAfpdFoBUEqpoKOjwwfgAXDPnDnjXXbZZR4AH4ACoIQQqmyCw+YZQApAR7FYzBqGkfV9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhiteSelected {
            get {
                return ResourceManager.GetString("WhiteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d1ZkxxXdtjx/82stVf0Wr2QWBorCYJYCBALARALQQ4JajZZcoQi7LA/giMUYb85pAc/+E1+dSj8NIqQPRMjzeaRZzSjmZGG1JAckgBIgAQ42IFu9L4vtaQfMm9XdnbtVV2V2X1+Ecmq7qrKPJXM7j44de69ChfLQjl3DWczXZv+nkIIIYQQQojNxXK2tGfLOBtKYQGEcrxYJ85hZ4tAPAJWyH7MMpznSSIthBBCCCE2Ayd5VmlQKVhMAitA0tlSgGVZdhK9mkA71WedPEeAGMSbIN0EKm5/L6STaIUk0EIIIYQQYnOwQGXs5Dm1ApElMBZgaQFYdJ6Tsp/nVKCd5Fkn0BGgCaKtoNoh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtEAAACACAYAAADNhDV8AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI1AAACNQBu2JXWQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3ZkyTXlZ/53evuseS+ZxZqBVBYqwoooFCFQqGwgwAIkE2y26gx6WFMpgeZ6UXvspkxdT+MzfwFMy9jYzNmMzKNWhSl7qYkNNUCySa7BTTABkAsxFpA7ZmVmZX7EhF+7zy4e6RHZOwZmeGRdT4gKiIjfDl+3a/7z4+fe46iDGtR/Cmae9As4zCCwzoOaTTraBxU+TyCIAiCIAiC0PX4WHwsHj5ZfAbwmcPnaww/xqBAgQVw4/MVBfQJHK7iMYEHpMhkPdatRx+avNUAaBHTgiAIgiAIwj5gE/CwOFgc5aNVAb2eZ5kcHjn6KAAF/hhr/zgQ0kUhXCKgIcU6Gcj2gN+DdbOkbArjumg0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDark {
            get {
                return ResourceManager.GetString("YellowDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b17sBzVnef5OScf9bj36nEl9EQIhITEw2AwGBs/ABsb834IhIQENN3t+WMiZmNjIzZ2NzZipztiYrZjontjdyY2pqN73F5Pt3vcY3ePPba73aaN8QPjNja2MWCwQRICIQn0lu6rqjLP/pGZVVl5s95Vt7Lu/X0i6lbdqsxzfnkyT+Y3f/k7v6OIYUBhgC+j2YLmHBaTWMxgkUMzg8ZCIQiCIAiCIAiLCQ+Dh2EdHtN4LMPjBB778XkYHwUKDIBdt2Iknq/E4m0c1uAALhRcZo3NOJqy0QBoEdKCIAiCIAjCiDMHOBgsDJbymFYV9EyZc5Q4R5lxykCFP8CYPwhEdFUEG4OqimdwmSEP [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDarkSelected {
            get {
                return ResourceManager.GetString("YellowDarkSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b35jxxXlt/7OTcil8ra9yKL4k5qpUSJkkiJi0it3SNZM54HGf5D3gP8HmC423+AAf9qwDAMvMWAYMB4fm/g53UMe6bnzbTd2lpSi9pIcSvVvldlZsT1DxGRGRkVudTGWvJ8uqnMjOXeG/fG8o1T554jxLAgWAsff2z4aNbwY9ahw3HIGAfTaTAlw+Kq0NONoiiKoiiKohwKFoDusmWuZOnq9xhwPMh60O3B9z585IMgggWQ+L7WWoGPDeAwsZYh153BtVmKNospukjWIJ6BHKyXJK1+RVEURVEURTlQ5HzLWsaSxSPnl/HdEmWnSHGlxHxXibNLZX79peVXv7ICtiKCa8TzJFnyHXnK [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLight {
            get {
                return ResourceManager.GetString("YellowLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b3ZkyTXlZ/5netLREZm1pK1L6h9JVkAsZEESYBFEgQJYinsqA3s/gdkehqzflPzQWY91moz2dgsstbMSGMzspEZWlKbTcumRTaXFodkU+wm2QCxEWBVoRagCoVC7VmZEeH3zoO7R3p4eiyZkWvE+ayiIsKX63fxcP/5yXPPETI4EJyDV181vHjVcCb0GPI8AuNhhg2mZrh5R1gxiqIoiqIoiqL0BTeA0brjWs0xsjpizIsgjGA0glMWXrQgiOAAJLuvc07gVQN4XJoIKI0G+C6k6kJM1UdCg0QGSjBZk6LjK4qiKIqiKMqyomQdE4EjJKJk61i/Rt2rUh2vcX2kxp5bdb77puOP/9gJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLightSelected {
            get {
                return ResourceManager.GetString("YellowLightSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAtAAAACACAYAAAAiRl5CAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAI0AAACNABRJ/QSwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15jBzXfec/r44+5+AML5FDckiK5Ax10aRJydYti5ZMXRQPURySkiI7zh8LBFgssEAWC+wiQLAwFjGQ3UWwRhxbcRIndmI7cnxEa1qyJEuWLcqSLMk6YlmkKI1IihKPIefso/aPqjdd09N3V09X9/w+QLF7uqve+9brZve3f/V7v6fw4Tgo767hbaZv048pBEEQBEEQBKG9cLwtk7dlvQ2lcACsAgdr42x7WwTiEXAs9znH8PYTIy0IgiAIgiC0A555VhlQaRhPAVNAytvSgOM4romeNtBe9Fmb5wgQg3gCMglQcfcxS5tohRhoQRAEQRAEoT1wQGVd85yegsgEGGMwMQaMe/uk3f28 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowSelected {
            get {
                return ResourceManager.GetString("YellowSelected", resourceCulture);
            }
        }
    }
}
