//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laavor
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArrowsSmoke {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArrowsSmoke() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasePackage.Arrows.ArrowsSmoke", typeof(ArrowsSmoke).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABouSURBVHic7Z13uFxVucZ/K+WkdxJKAgTBQJCAgpEqKHAFgdBFDIIIQgJqQC8qAiJcRY2aqwHFXrDDoxcVy8VCTagiKgpCII30kF5P2ucf71qsNfvMzJlzzsyZSbLf55knsGfvOWvv7/3q+tbakGPngll3zC7F7GnMhtd7ODk6C1HwMzEz//llvYeVo9YoLnjDbBNmE+o9vBy1ggR/EWYzMoI3zFZjdkq9h5ijFpDg31dE48NnBmYH1HuYOaqN8hofPtMxG1bvoeaoJqLGz8oI+xnMmpP/vxOzpnoPN0e1UFrjp2F2GWZ/T459BbMu9R5yjmpAgr+siMY/hNnxmO2H2Zzk+A31HnKOaqC8xo/z54zC [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AquaLeft {
            get {
                return ResourceManager.GetString("AquaLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABszSURBVHic7Z13mF1ltcZ/O8mk90ZCApMICAhi4yoIIgIX4VJEkKAoVUQEEYkIKCBVEAVEpYh6UcSCIDZAiihw6QoSiiQECIRAIJBGeiHz3j/e72N/58yZySQ5bSZnPc959pwy5+y917v6+tYHANKFSCcg9aZB6xlJeyC1IAnpFaTjkXrV+rQaVC2SdkaaHwAQHzOQjm0AYX0haevAdBU9XmqYhvWFpGakySVAIKQXkb6A1FTr02xQJUkahvRAGyAQ0jSkIxtA6Mok9UO6I2H6y0j3FwHhOaTDkXrU+nQbVAmSeiH9MWH4X5D2RLq3CAhTkQ5B6l7rU25QuUnqjvTzhNm3I/VG2hHpHyVMw9ENjdDV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AquaRight {
            get {
                return ResourceManager.GetString("AquaRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABjLSURBVHic7Z15mFTVmcZ/LXQ3++4WQDEIEcUNFzQirkkMamI0GBdM1GhwG5zMONFxXGdiMj6JE7M4eZLomGjMuIyKwRUVxYC4ISqCGyAtmwjSNEsDvdDzx3u+nFO3q6qru28t3dz3eerp7up7q27V9377d86FBDsayoHvA/OAwUW+lgQFhAl+CdDkHlOLekUJCoJ0gm8C6oDJRbyuBHlGOfBd4CNSBd8EbAAmFO/SEuQT5cBFNNd4e3wE7FO0q0uQN2TTeHvMBnYp1gUmyA9M4z8mVdjzgW3B3w8AFUW6xgR5QCaNnwVcDLwdPPcbYKfiXGaCuFGOBBzV+JeA44G9garg+euKc5kJ4kY2jT/VHTMS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlackLeft {
            get {
                return ResourceManager.GetString("BlackLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABngSURBVHic7Z17mF1ldYffmWRmcg8EGAIEkiByiwKi1SBQrUZABeQiqA9FURGQgAoVxSq21WqlVautYEkVQWgRFVEEEauilUtRAoRrAAmEaxKSTEIyuU2c6R/vXn777DmTTCZzZvZMzu959nMmZ87s7LPXb93X9+0RiIuBGcA8YCN1bFM4CugEuoDngHOBlkG9ojoGFG8EViAB4ngGOJs6EbYZvAKF3lU4ngY+CowavEurY6AwFXiE7iToAp4CPgQ0DdbF1TEw2AG4g+ok6AIWAB+gToRhjbHAL0hCfxa4nUoi/BE4DRg5OJdYR63RAlxPEvgNwFuB31FJhMeAU4ERg3OZddQSI4DvkIR9CwaDhwG/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlackRight {
            get {
                return ResourceManager.GetString("BlackRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15gB1VmfZ/76m69/bte3tNAgETSEIEkk6CEBlGZQnjCqKDSqMgyB42R/1mnBF0ZHF0HGbUcfTTb8bRcQRRTCKLrAJCgCSIEhM0fQOYpQMJ2Ujf29vdquq83x9Vt/t2SEKW7k4I9/kj6a7qqjp13ue823nPKaGGNxdmz43Rlf0UwqdxOUv2d3tqGCUMCv5LwGQAlHvc/duqGkYcFcFns19CIsGH8DD6YE0DHKyYPTdGrus8VL4MTN3ubC/IJ1gz74EaAQ42zJ4bo6vrIkS+CENGfAWrsPZDdP7yeYAaAQ4W7HrEV7AE8T/C6ru2VA7UCPBGx+CI/xIwqerMCuBoIA6A6Dzq5EI65per [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDarkLeft {
            get {
                return ResourceManager.GetString("BlueDarkLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15nB1Vmfe/z6mqu/R+O+kkhECSTghJ32ZRQGEEzcgiOoJE00GGAXEURFZBxGVcGJdBRkEUB4YIiIoiNMEZUUBfVBSGRQmEpTsBkk5nAZJ00vf2crvvUnWe94+6t7uzACHpDexfPvfTdSvVXefU8zvPdp5zSgCoX3IV6MvY8htpvzXLBP5uIMxpOhHlXkAQXgb9NpJZyur7cmPduAmMPAyiWaAbAGU6Kj/AVqymfvF5zH1/dGybN4GRhgAw59RG1N4HzNjh/zcAV0+YhrcuZOBo9odnIs79wPxdXLcOlW9RW3Mry5cWRq11ExhxyHbf5i+aRM69B+GoV7l+Lcg3SdT8bIIIbw3ITmem [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDarkRight {
            get {
                return ResourceManager.GetString("BlueDarkRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABneSURBVHic7Z15mFxVmcZ/N0l3ts4OQQhLMBISIEFBZIugwghCIquIASIDQgAZXAYFGUEYRYySkYC7IuIOjw4qLgNKAiHsIipKhJB938i+dLZv/njP6XOquqq6umvt5L7PU08nt+6tOre+91vPd86FFHsYrAHscrCXwIbUejQpqoYWwc8BM/f6Va1HlaLiyCl4A9sGNrHWo0tRMVgD2ASwWVmCN7D1YGfUeoQpKgJrAPtIDo33r1lgI2o9yhRlR0GN96+nwAbXeqQpyooWjZ+bJeyXwZqj/z8A1ljr0aYoG/Jq/AywK8D+Fh37GliXWo84RVlgDU7A2Ro/Hew9YG8Bmx8d/2ytR5yiLCio8ePcOcPB [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLeft {
            get {
                return ResourceManager.GetString("BlueLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15eJ1Vtf8/a7/vOSdnyNimFCilQBEpINCmYBUFLjhBUUGS0iIIKIPiBa/itYxtFdQqo6hX7nX4qSglKderIAgoBUpBaAIKggOlA52HtBlOcqb33ev3x/ue5LR0CG2SDuT7PMDDGXL2u/d3r+/ea629tjCEdxTuadZItXIhwhdxmSy7u0FDGByUDPz1wCHhy791d2ejhjDw6Bl4uB7pGXiAgiiPDBFgH8U9zRqpUaYq3Igwdou3O1U5r2GiPDwkAfsY7mnWSA18RuE62GzGF7HIwFnn1sk/AIYIsI+gZ8YLN8JbZnwA4VnX5exzjpV1xZeGJGAvR8mMv16FMSVv/Q14FxAFEGjUMi44 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLightLeft {
            get {
                return ResourceManager.GetString("BlueLightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z13nF5Vtfe/a5/zlClPpqVMSA89iIUZigUJgigIFiAD6NUr9943eFVEQEFsBFABFUSC8IIIIipkhnIVL3h50cgVKWaGIhKahBIgIZOpTz9lr/ePc57JpFGngfP7fPL5zHNynpldfnutvdZeey0BWNGl54vyYj7L5ccfKCUm8U8Dae/SD6PcCgjwosB5NXVccdjOUh7vxk1i9GHEUgIG4887KFycG+AfHZ36+Vuf1NR4Nm4Sow8BuH6Vvs0ItwGzt/j/tcAFk6rhrQup/HDj/TovtPwe2G0b7z2rwnf7lZ+f0Cr+2DVvEqMNGf7hpvu0KTDcgvDu7bz/tCrf6ReunSTCWwOy5YNfPKQ1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLightRight {
            get {
                return ResourceManager.GetString("BlueLightRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABrMSURBVHic7Z13mF1ltcZ/O8nMpPeEhIRMAiIEEBtXQIoRcjFcAiII2ICAiAgiEpRyAaWJRAnGAiheC6IoICIKIsgVuXQBCUUCAUJCCS2NkF5m3T/eb2V/Z8+ZzCQ5ZZ/JWc9znj2nzDl77/Wuvr71AQA2BewUsO7UaXMjmwDWAmZgr4KdDNZU7bOqU8XIxoEtCgDwx8tgJ9aBsNmQ7RSYbpnHS3XTsNmQNYPNKAICA5sN9gWwhmqfZZ3KSjYI7P42QGBgs8COrQOhU5P1ArsjYvorYPdlgPA82CSwbtU+2zqVhawJ7KaI4X8C2x/sngwQZoIdCda12mdcp5KTdQX7RcTs2+UM2p5gfy9iGo6va4RO [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueRight {
            get {
                return ResourceManager.GetString("BlueRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOwAAEDsBw5IxTAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z13nF1Vtce/a59z29zpKSZIk+KTBARRVGyI2BBQSiYUpZOZCVGwoFIEJioqSkcgk1ieBYVMEBWUB1ICIUH08SwQlCIkpELK1Dtzyzl7vT/2uTN30pgkM5NJmN/nk08+c+695+yz12+vtffaa60tjOINhfpmjbUqZyB8HsuxsqMbNIrhQYngLwPeAoDwO3/HNmsUQ42i4FvhMiQSvENBlftGNcAuivpmja1XThXhcmC/DT7uFOWUuY3yx1EC7GKob9bYejhT4FLoN+KLeNHCcXc1yL8BRgmwi+B1RnwRiwLLCXdPl9eKF0YJsJOjZMRfBuxd8tEzwFuBOIAqc6WW01umSr7096OTwJ0U [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSkyLeft {
            get {
                return ResourceManager.GetString("BlueSkyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z17fF1Vmfe/z9r7nJN7m95oS+kFUKAw6gy+KqNoFVCYscilJ4iOF0ZpKwoIKninggqoFCiXNmm5ySDQUJzxhsMLAuOMgzPyimgLgnKXAmmTNMnJyTln7/V7/9g7aXrj1tzA/D4f6MnOTrLWXr/9/NZ61rOexwCamnWhjGdqMzRfe5L1MY6/Glh+lY7E+BlgwDMSFxTKtNx2mpVGu3HjGH44iT6gK/16phkr6nL8aVGLTjlqhXKj2bhxDD8M4ISVOsg7bgNmbff9pzAuGpeG1y6s/8NxazQniPk5sP9O7nvCjG9NFNe2LLHKyDVvHMMNG/zFsZdrcpjhx8Ahu7j/MTO+OVFcP06E1wZs [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSkyRight {
            get {
                return ResourceManager.GetString("BlueSkyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b15nF1VlT2+1r73zTUnBQQqlQBRSSqoiBO2Cja2bYu2osav4owDCDaokAEQk6goCShiq639a/XTDt026da2ndqRSUDENAqpQgUzVYUQKpXU/IZ7716/P957SQVCCKRSCVDrj+RT97577z7nrL33Ofvscw4xjacUvnLy71LD5SPfIfkHw9BezUMt0DSmBrsbXpcBOLZ2+fvhoRRqGgcf9YYfKukyQMdOuBVR+sm0BXiS4isn/y41VGp/C8HLBczb865G4PbmJffM/vE0AZ5kqDb8ke8EdCl2m/pdIHAfLXnNxXcf+8fa39N4MmDfGl8FwVsRlM9cfNe8B3dfm8YTGhM0/jIAc3fdINZB [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueVioletLeft {
            get {
                return ResourceManager.GetString("BlueVioletLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b15nF5leT5+Xfc57zZrJpOdmWQSgiSZiFqolVpqWtBaKy7V0NpWq21/6NcFZUvAjVEUSAIRgUJBXKi1KlHbqlXrBxVbK25p2WaCEiGZCRCSzP7u55z7+v3xvpMMEGTLTAY61+cDnPfhvPM+y/Xcy7PcNwFgc/fuTSAeLOb9+p5dy8uYxf8ZcHP3wCsBfQsAATwI8bJstXzDWTuPqxztys1i6mEkygDG6p+XgLqqnMns3NTd/86rVt6bOZqVm8XUgwCwZXX/Whm+DaDjUf9/ANQVs6rhuQtOPFy++r5lbqnvAFp1mNd2E/h4S/bhz719+0nRdFZwFlMLTv5wyao97WGQfAPgyY/z/v0g [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueVioletRight {
            get {
                return ResourceManager.GetString("BlueVioletRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15gFxVlf8/575Xe6/Zu5OwBsQEhaSDiLJ0CCoKKuiEnyCoyL4Mzs/RYScVFJVxGQd/OoOjzgDiQkZQ2WRNhRAQSScBIagQSCBJBZqk9+6qeu/d8/vjvepUYpYm6e6E0N8/srxa3q13vme555x7rzCCdxRubiK2XvicKpe6PifL7h7QCIYHFYK/Gtg/uvw7d3cOagRDj7Lg88rVaL/gATwR7h+xAHspbm4ilhdOR7kWmLLFy10In8ku4b4RAuxluLmJWB4+D1wFm2l8GS8BH8+28BeAEQLsJdiBxodQnsDn1OyzvFG+NEKAtzkqNP5qYL+Kl54DDgbi0f/voMBZ2ecpVX5+JAh8m6Ks [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrownLeft {
            get {
                return ResourceManager.GetString("BrownLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15gFxVlf8/575XS2/pLCTp7iwkIYjQyJIOAgpaIQHBERUcUEdBGBUQBBQF3IAKIMiouMDAgIgLOghxmZ+gMg6QRlAE0iEBkrCEJBDSna3X6uqu5b17fn/cV+lOSCBAb0B/oamqx+uud9/53rPdc88TgPQcrhGhWau4Kd1IjlG8bSDpORyL8GdAgGaB74zr5ObzVpMf7osbxeDDYMgBXdHnOoUft1WzOt3A2T+eTWI4L24Ugw8BSM9lf5S/AFN3+P/rBb4/ahreupDSmysPZs/AcA/wzp2c94Io364Rfn5mE8Whu7xRDDak/4er3s2EguUulMN3cf5ahCtrldtGifDWgOx44LsHUJGN [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrownRight {
            get {
                return ResourceManager.GetString("BrownRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X15fFXVtf937X3umOEmBBAEcWi1EBzq0EGflctQW6191VfhtVqrbR2xte91EkTIDkhbX61t6dNf6e+172OtrxZebauidSInIqKtU1UixQEQwmAIyU1yk3vvOXuv98c+J7kgQQhJGMz388kncE/Oufvsvea19tqEIbyvsHjx4sjWrVu/zMxfdxznAjrQAxrC4KBo4ecAODb4+M9DBHCYo5eFBwCPiL4xRACHKRYvXhzZsmXLFwHMBfDBXS63A/iCUuqhIQI4zBAs/OUAbsLOHB/iDQCfVUqtAYAhAjhM8B4cH+JpABcppd4JPxgigEMcRRw/B8AxRZdeBXACgGjw/yUALlNKFYrvHyKA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLeft {
            get {
                return ResourceManager.GetString("GrayLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X17nBxVlf/3nFtdPd09PY8kE14xEAgCiSHMdE8giEAWRIWgoMIKCiIoD+EHrqI8BEJUVAREfLDsrrof1+eaXV1EZUElPAyQTPdkUYLGhLxDMpNM5tUz1V1ddc7vj6qadMYkTJKZSQjz/Xz6k0xVP27dc+459zwvYQxvKuRyuZiqXk5EN1iWNZf294DGMDqoIPznAUwJLz9q7c9BjWHkEREewOeJaErFrbKqPj4mAQ5ShIS/hIjuBDB10O1eVf1Qc3Pzb8cY4CBDLpeLAfgogNuxXdRXYiWA87PZ7F8BYEwFHCSIVjyAna14AAARPW9Z1oUzZ85sH7g2WgMcw8igYsV/HsBRFbdeBvBW [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLightLeft {
            get {
                return ResourceManager.GetString("GrayLightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X15mFxllf57zr23lu6uXpNOQjorCYmJCklVJxGHIQiiICiMBmfG0dFZIoMogg6IW4IoyyiIgjBERHFDg8uMoDj8dIIjJiFdlQ0TIEAStoSk00u6upa7fOf8/ri3Op2NLb2B/T5PP1V1u5bv3u/csy8EALlc7npV3ZXP528/7bTTyhjFXwwol8u9U1V/A4AA7AJwXV1d3YqZM2e6w7y2UQwBWETKAHqi18cB+Ob+/fufzGazFz3xxBPxYVzbKIYABABtbW1vJKL7AbQc8v9nAdwwKhpev6DKk/Xr108Rkd8CmH2E9z1NRF9R1e9lMhl/6JY3isEG9X/x8MMPNzHzvUT0lqO8f4eqfpmI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLightRight {
            get {
                return ResourceManager.GetString("GrayLightRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X15nB1Vlf/3nFuv3tLd6SSdNEkM2WRNIzDCjKJEq5OA4CiiTjLDOC7MKCjriLIIJKkOMRiViMEJA6Kjg2siOqMg6A+Tl8ENFQ1KN1tIwpaQpdfXr997VXXv+f1x70s6IQECvYH9/Xzy6a5K9XtVdb73nHPPOfdcAoAwDFcQ0TYRuSUMwzJG8VcDCsPwDAA/BUAAthHR58aNG3frJZdcUhnmexvFEIABlAH0uOMpIrKqo6NjUxiGF6xatSo9jPc2iiEAAUAYhscBuBvA1P3+/2kiumHUNLx2QdVfli1bNj1JknsAHHOA654kos9OmjTpG+eff348dLc3isEG9T9Yvnx5QxRFPwFwykGu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayRight {
            get {
                return ResourceManager.GetString("GrayRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15nFxVmfe/z7m3qrq6es9CwASSEIGkkyBEBheWMK4IOqg0CoLsu6O+M84IKhBcxmFGHUdffWccxxlBFOmwySaLEJYkosQETVdYsnQgIRvpql5rufee5/3j3ttdHZKQpbsTQv8+8En3rb51zz3P7zzbec45wijeUphzGYmOHJ8V+JwLp8u+btAoRgYVgv8qMAVA4R53H7drFMOMWPC5HF+VSPARPKM8OKoBDlDMuYxEvoOzVbgOmLbNx90In159Ow+MEuAAw5zLSHR0cL4IX2HwiI+x0lo+2n4HzwOMEuAAwRuM+BiLxOfjq+5ic3xhlABvclSM+K8Ckys+Wg4cASQBRLm9SjivrZVy [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkLeft {
            get {
                return ResourceManager.GetString("GreenDarkLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d15nGRVeTfw77lVvffMdPewiGGbnhEF3GAkxo3FJRpFA24RguybYNQ3MVGMUTGLMVFjzGvebL6+gqhxQwKCArKvyjiggoqzIQMDDDPVs/VWVfe8f9xbS/cszNLLMPTv8+lZqurePnWf37Oe55zDDJ5ZWKjFPGfpt9ghfidM93hmMEVYqMVapwr+EvNAdEVxekc1g0lHTfAlfynkgs9QlrhmxgLsqVioxYCTRH+FBePe3YB3WebqGQLsacg0/jTBRxij8TUskXqzFX4FMwTYU7Btja/hDsGJlnqi9kIyNaObwaQhi+rPVvKg6Csawv8FRuufC76pw3HNwmeGAE9fLNRivlOVPCD4Txyc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarknessLeft {
            get {
                return ResourceManager.GetString("GreenDarknessLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d15mGRVeT/wz7lV1ctMz/R0DwwoA0x3j2yDYoQEMaAk4r7EJRKNcYsKCAIRFU1+0cQlUZJoNEYIiLtGjVGToHEJ7iiijCyCbLOyOQPMVM/Se9U9vz/Oreqenmbv7unB/j7Pfbqq+nbXvff9nnc773lPCfQ6T5dVOl2jX808fovQ55l65XpFfe7Q50wrte7py5rH7CATDGM7iB4t+he5NXqdPk+ERz4C6HOk6JtYPun3t+EDchfaYHi2L24eM4/QfNXjYMG3cNgU520U/Z1un7La2Kxd3TxmHGGXd4dZasQlguPu5fz1eK8un50nwiMDYbdP9rPQQl/D04pP7sBGPGnCWWsF73Wgz/nB [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarknessRight {
            get {
                return ResourceManager.GetString("GreenDarknessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15nBx1mf/fz7equnvu6ckJBJLMhECmh0tAZAWNAgquKCATRZbDVRE5BRWP36qsxyKr4oELSwREUTmGwK4ooIsKgiJKIBwzCZBMEhIg10z3HN3TR9X3+f1R1XOEcATmAubzek2mp6cyXd96Pt/nrqcEoHEJl6I8Z6u4at115JnCmwbS1MrRCncAIvAcyrcly9LVd1KY6JObwtjDiJIHegEUdlXhR7aa1Y0nctaCY4hP8PlNYYwhAE0fpkUtdwJztvv9BuB7U6bhjQspv5h/AnPF4S5g7x0ct16FbzXUc93ypZTG7/SmMNaQ4T/sfTzTCi63Cxz6IsevRfhmsp7rp4jwxoBs/8asU6iq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkRight {
            get {
                return ResourceManager.GetString("GreenDarkRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d15mFxVnT7wz7lVvWbphLDKpqioAUHADRdoFhUFd2EERXFhERycn+MMoAIV3IZxGUdHZ3RGZ1xQB0ZQWRQEUmEVBQEFFNklECBkT6eXqrrn98e51V0JScjS3QnQ7/N0Ol3LrVP3+57vfs4JJvDMwre0ecT7RB9VdljY1OOZwDhhRPCfwnOKR39e3pRjmsA4oCn4eSsJHmqCX05ogKcrvqXNPEfidDxvlWeX4d0qLpkgwNMNSfDvxyetPOObuBtvVvFnmCDA0wVrn/FNXIe3q3is+cAEAZ7qGJnxn8KzW565Dbuivfj7XBytYqj17RNO4FMVzRk/7wkz/lrB90QfNSL8b+BkFfmql5nQ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLeft {
            get {
                return ResourceManager.GetString("GreenLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABnYSURBVHic7Z15mFxVmcZ/N519X0hYEkgADQQICIrs4AAqBsImAgmCSCSLKDgOgwwIRh10EDIaUNwdN1yYcdBBdEAlLElAGAZFZUvIvkP2tbN9/vGe0+fc21Xd1d1VXZXOffvpp5Oqe6vOvd/7rec750KOvQtGF4wJGC9gDK32cHK0F4Lg52ENP7+s9rByVBqFBW8Y2zEmVXt4OSoFCf4qjDkZwRvGBowx1R5ijkpAgv9IAY33P3MwDq/2MHOUG01rvP+ZhTGk2kPNUU4EjZ+fEfZfMOqj//8co2u1h5ujXCiu8TMxrsX4c/TaVzE6VXvIOcoBCf7aAhr/JMaZGG/BWBi9/ulqDzlHOdC0xo91x4zE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLightLeft {
            get {
                return ResourceManager.GetString("GreenLightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABrkSURBVHic7Z15mBxV1cZ/lWSSyb6HhCyTiEAwiBtKhIgIfIgSkEXAjVVEBBGJCCggqyAKGJVF1A9FUBBERcEgosAHgURZwiIJIWQDIoHs+2SSOd8f771zb1f3TCaT7unqSZ955qnpZbqq+rxnP/dcADCuxjgLo5YqbWdkHIzRiGEYb2CcidGt3JdVpfYiYz+MFQ4A/uc1jNOrQNheyNjdMT39s7BqGrYXMuowZhYAgWHMx/gSRk25L7NKpSRjIMYTzYDAMOZinFwFQkcmoyfGgxHTX8eYmgLCHIwTMbqU+3KrVAoyumH8MWL4nzE+gfFYCgizMY7D6FzuS65SscnojPHLiNl/w6jFmIDxzwKm4dSq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLightRight {
            get {
                return ResourceManager.GetString("GreenLightRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d15nGRldT/+93OrepmenYFhQLZBFGVQiRKFBLQGRkS/oqIB49e4JREVECIKrkCxuBAViRj4gko0YoygJj/FQPJiaQIuKCAgA8gyw77NPtNrddV9fn88t6p7hpmRge6eBvvDq6m6d6qr773n85xznvOcc54Aqs4SPCq6QNWASfzJIKg6FP+FgEcFXzLbhY4zuJWvbRLjgAwDWFsc7yj6upXuVXW0r+vYitc2iXFAAFV743LstMG/PyT46qRpeP4itN6daVd1V+AlG/ncA4LPm+c7PmRo3K5uEmOOsN7RF8xR8zPsv4nPL8WZdvC9SSI8PxCecubLpur1H3h9ceYRPIC/GPGp+3AmLlZV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenRight {
            get {
                return ResourceManager.GetString("GreenRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d15mJxVlT/wz32rek8nJCwCsimisrj/UFEUFVcWFTUOoCCydEAUdUTZBIKKioqCCCZNxAVRR2YGHVwGREA2RR/GZcRxAxJIICzZ0+mt6r2/P+5b1dUhSyfp7gTo7/OQpt6qt+q+937vOfece865wQSeUohdmgRHiz4oc0jY3A2awPigYeDPwjPSRT8ub95mTWCsMWzgYzHwCYOCn09IgCcpioE/QnQ2nrXa2ysEh4fZfjZBgCcZYpcmvA9nMmzG1/BPHBq6/RUmCPAkwXpmfA13yBwWZnmkdmGCAE9wNMz4s7Bbw1t/xrPRDIIfWuyocLWBxvuz8WnmBEYbsUtTnOFo/AWXqw1+dLuo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLeft {
            get {
                return ResourceManager.GetString("OrangeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z13nF1V1fe/a59z29zpk4EEQhIICoQmIio2QCyQzCQUwyMoiCiEouCrKAmQ5ExoohTB8oiP+jwWLOR5VNIUBEIIAUGxgYhISUIahGTanbntnL3eP865dyaNtJlJ4f4+H8qcc8+9++z122utvfbaawsVvKmgf7orxqo15yH6OXBbZFc3qIKhQT/BXwMcCIBwb4UAezk2K/gQRVQ+XyHAXgr9010xVq8+G5gOHLzR7W7g49LqLagQYC9DJPhPAVez4Ygv4QWgVVq95wAqBNhLsJURX8JjFDldzvBeK12oEGAPR3nEC9egjOl36xngrUAcAOEeejlXzvIK/Z+vEGAPxRZHvLAElR+Bfg44 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLightLeft {
            get {
                return ResourceManager.GetString("OrangeLightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15gFxVlf8/575XVV29pruzdEJWQIHEbQYGzE9RkIAsCWExcRlFHOcHDrIIyA7JC3tEIgKCREQRFQyLkg7I8AORcRl0yAhKwiY7JIGk19pfvXfP74/3qtMJHcjSW7C/+SNVr19V3fvO955z77nnniMA2uotBllDrd4kB3pFRvAPA9H7vEOx3A8IsAaRKzGNS+XwU0tD3bgRDDwMliLQHb+fgOq1hO1/1+XeSXr/tamhbNwIBh4CoCu8D6D8Gpi42d9fA7l6xDS8dyGVF3rfpVOwwQPAnn3c9wrIZYxv+bHsc2J58Jo3goGG9H6j91zeTMJvBWZu4f6XEC6lZfxtI0R4b0A2v6D/eVUN [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLightRight {
            get {
                return ResourceManager.GetString("OrangeLightRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d15mFxlnS/wz3uqekt3h3Q2QggkAR1E3O7odcdhBBUdcA+j40VBSIIIIqiAKxFUQCUgQSAdQBl0UOMyM66XB7cZx2WuzIAbDLiwaAiEpJP0Xst57x/nVHV1SDCQ3oL9fZ6GqpPq6nPO+z2/7f0tAeIKF4s2KFsbPmvINP5iEOJKR4u+hYANgos06w5rDE/2yU1j/JEIhrA9f79QdLlhv43LnRpP1zKZJzeN8UeAeIqnSH0bi3b49/tEl0yrhscvQu1FPMliBd/Bk3byuXtEHxV8NnQrT9zpTWO8ERrfxLebo+zreN4uPv8H0UcEN0wT4fGBsOOBeLx2rb4meEl+6E+4B89v+NjvRB+x [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeRight {
            get {
                return ResourceManager.GetString("OrangeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABpOSURBVHic7Z15vFVV2ce/iwuX6TIrhqBiGoIBFkaOqalvmopzZg5kmoBWaL2W5JS+ZUbJW2TZaGWzfuq1oklLcABFzawsTZB5BpnHy/S8f/zWaq+z77nnnnvvOfccYP8+n/O5cM7e56y9n98zrmetDRn2KRjWwbBrDHvJsP6VHk+GNkIk+LmGmX/9qtLjylBmNCJ4M2y7YWMrPb4MZYIX/GjDZqcEb4ZtMOysSo8xQxngBf/hPBofXrMNG1zpcWYoMZrQ+PCaYVjfSo81QwkRafy8lLBfNqw++v9DhtVWerwZSoQCGj/dsGsN+3v03tcMa1fpMWcoAbzgr82j8U8Zdqphhxu2IHr/tkqPOUMJ0ITG [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLeft {
            get {
                return ResourceManager.GetString("PinkLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15mFxVtfZ/a59TVV1Dj0mHACEEEkQCCCQdMIoCF0cICkh3SBAElEHxglfxEsYkKmqUUdQr9zp8KkrohutVEASEACFM6QYFwYGQgYTMnZ6qu7qqztnr++Ocqu4OGZqkuzPQ7/P0kyfn1KnaZ+93r7XXsNcWhvGugt7ZGKFSzwP5MrjTZFc3aBhDg14Dfy1wUHj59+6ubNQwBh89A8+1IAf1upVH9KFhAuyl0DsbI1TpDJTrQSZsdrsD1bOlbsqDwypgL0Mw8HwO5Rp6RH1vLMFwmpxV8w+AYQLsJeiZ8XI9sPmMDyHP4LpnyJlHrS9cGVYBezh6zfhrURnX69bfgPcAUQCEerTkXDnz [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLightLeft {
            get {
                return ResourceManager.GetString("PinkLightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z13nF5Vtfe/a5/zlGmZljIhPfRgZYamIkEQBUEUmAH06oWrb/CqiKCC2BiKAldBJAgXRBBRITOUq3jBy1UjV6SYGYpIaBJKKCGTqU8/Za/3j3OeySQkhDINnF8++WTOyXme2fvs315r77VXEQBd0X0+oi+Qy1wux+9fZAr/NBDt6P4w6K2AAC8gnEdV7RVyyI6liW7cFMYeBrFFYCi+3g7lYrKD/9DOrs/rrU+kJrJxUxh7CIBev+ptGLkNmLvZ/68FLphSDW9dSPkHvfG+BYT2d8AuW3juGVS+y4D+TE5o8ceveVMYa8jIC73p3kYCcwvIPlt5/ilUz2FArp0iwlsDsvkN/fmDVaT9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLightRight {
            get {
                return ResourceManager.GetString("PinkLightRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABtaSURBVHic7Z13mJxl1cZ/b5LdhPROQhI2kS6IDRUBEYEPUYoUARtVRAQRiQgooDRBFBCVIuqHIigIYgMMIgp8EIpSQpGEACEhEAikkV7I3t8f9/PkfWZ2drNJZnZmkznXNdfslJ23nPv085wHAKGLhU4W6kGdNiwS2luoWUhCrwqdJNS92udVpw4iod2E5gUAxMd0oRPqQNhASGi7wHQVPV6um4YNhISahCaWAIGEpgp9Saih2udZpwqS0CChB1sBgYSmCB1TB8J6TEK9hO5KmP6K0PgiILwgdJRQt2qfb50qQELdhf6UMPyvQp8Qur8ICJOFDhfqWu1zrlOZSair0K8SZv9dqIfQLkL/KmEajqtr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkRight {
            get {
                return ResourceManager.GetString("PinkRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15nB1llfe/56m69/btPSsJhMgiGDoIsqgDIrlJQBFRQSUjuICyg6LjxhpSHUBlxOXFV2ZwRudVRDEZcWEThPQNIYmoSFAIGAghkBBCZ+lOb3epes77x1PVfROSkKW7s9C/fPJJ+lZX3afqnOfs55QwhDcVbuO21Ku8+hlFP+/jnya7ekFDGBxUEP4a4MD4498NMcBeji0QHqAsyBeGGGAvxW3cllrFqrOA6cBbNzncAXwiILhviAH2MsSEPwe4mo13fILngQ8FBM8CDDHAXoI32PEJFgBnBASvJR8MMcAejoodfw1wQMWhp4BDgXT88yzg0wFBqfL8IQbYQ7GVHT9fkJ8q+nngiPiz [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PurpleLeft {
            get {
                return ResourceManager.GetString("PurpleLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15lB1Vtf8/+1TdobvT6YxNEkJIImMahJ+ggg/0NgkIiggqUX4uFRxACYMiICoJ1SGCqCAGDA9wRp+SiL6foPhcIbkICj4GGZIOQ0gCZE56SHq4U9XZvz/q3OQGkpBAT0B/1+p1+1ZX31tV+3v23mfvffYRgIDge8DaoQy99RIuyTGItw0kIDgZ+AsgwFpBvqvo7QFBvp+vbRB9AAPkga3u/ThF5wLLm2iaMZe5qf67tEH0BQRgNrMbLPZeYL9X/H21ID9Q9NZBjfDWhJR/mcOc/UPCe4FDd3Lei8A1Yxn78/M4r9RnVzeIXodUvgkIRgB3A+/bxfmrBJkzhjG/GiTCWwPyygPf5/s1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PurpleRight {
            get {
                return ResourceManager.GetString("PurpleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABnESURBVHic7Z15mFxVmcZ/N3s6e4BgSIBgICwmqCgioKDAqANEAVGRJSJIElwC4ziCbMFRZBAyGhfUcUVnVHh0UOMGSiKQQAARFQVJIPtKCNmXDkk+/3jPxz11u7q6uru2Tu77PPV0UnVv1an63m893zkHcuxVMOhpcKnBEwYj6j2eHDVCJPgFBhYeP6v3uHJUGa0I3gx2GEyq9/hyVAlB8BMM5mcEbwYbDU6v9xhzVAFB8B8qovH+mG9wRL3HmaPCaEPj/THHYFi9x5qjgog0fmFG2E8aNEf/v9OgV73Hm6NCKKHxsw0uM/hL9NxXDLrVe8w5KoAg+MuKaPwDBqcYHGqwOHr+unqPOUcF0IbGjw/X [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLeft {
            get {
                return ResourceManager.GetString("RedLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15mB1Vmf8/76m6W+/ZgEAIyKKQIAgOKo4SEIZhHUGBEZRFQHbRUTAJIenqJIjIjsKI4/Ioog6ZERGBQREIgSAqPzcIOySQkEDs9JJe7lJ13t8fp6rv7SSddJLuzsL9Pk8/eVL3Vt1T533Pu5/3CFW8q6B33JFixYozUb0U3z9etvSAqhgZVBB+BvCe+PK9VQbYzjEA4QFKiHyxygDbKfSOO1IsX34aMBPYa42PVwOfkSB4oMoA2xliwp8FXEn/FZ/gFeAECYIXAKoMsJ1gAys+wULgJAmCd5ILVQbYxlGx4mcAu1d89CzwXiAd//9u4AwJgmLl/VUG2EaxnhX/JCI/QvVSYP/42m3A [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLightLeft {
            get {
                return ResourceManager.GetString("RedLightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15mF1VlfZ/a59zh5pSSSpUBjICCqRw6IZH5NPYCAEnUBQTp3ZqbbFBQVDmDKeSMEQkYEAiEVFEBRLRdqb54oBTa3/SopKADCGAJGSouW7d6Zy9vj/2OVW3kgpkqClY7/PkSd1Tt+49+6x3r7XX2muvJQAaBCsR2YrqrRIEBcbwDwPRIHgz8BNAgK2IXMuECWvl/POLI3xvYxgGGKAAdMavp6G6mtbWJzQIztXVqzMjeG9jGAYIgAbBccBPgem7/f5ZRK4fMw0vXUjyg65YMYswvA84ZoD3PY3IVUyZ8nU555zy8N3eGIYaUvlCr766gVLph8BJe3n/U8AKpk69c4wILw3I7hf0uutq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLightRight {
            get {
                return ResourceManager.GetString("RedLightRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABrdSURBVHic7Z15fFxl1ce/t2na0HRNF1q6pBGRYrG4oLIKUkSUgggComJBFBFEpC4gi6yyKGCVpW6vvigKolVRsIoo+kKhVZFSkJYWgbJUCt1o0yVJm/P+8XuePs/cTNIkZGbupHM+n/nc3JnJ3Jl7fmc/z3kAMLjG4GyDGiq0Y5HB4QatBmbwosFZBv1L/b0qVCQyONhgrQOAfzxvcEYFCDsIGezpmG6px3MV07CDkEG9waI8IDCDZw0+ZVBd6u9ZoQKSwXCDB9sBgRk8bfCJChB6MRnUGtwTMf0Fg7kpIDxlcLJB31J/3woVgAz6G/w6YvhvDd5ncH8KCEsMTjKoKvV3rlAPk0GVwY8iZv/RoMbg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedRight {
            get {
                return ResourceManager.GetString("RedRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X17gJVltf7zrPfbt9lzYQZGQRFNzYo0s4517IaeOt20oyhQWd4AxQtgF0utFOhkHSszAS1SoOupZtRSS7OLioplnX7WwThdvICAIrdhZvaemb33963n98eegcEAUYbByzzz13x7f99e33qfd633Xe9610sM4WWFBQsWpEZE5dMlTPdUdAL3tkBDGBxsaXjgswBeAQCQbon2rlhD2NPY2vDlz6qv4auoCLhjyAK8RLFgwYJUU1T6MMHLABy67afshOFDE86afvsQAV5iWLBgQaopVTmD0mewbY/vwyMwfGDCWTP+CgBDBHiJYOc9vg98wFJh/Mmnn7duy5VBkm8Iewhbezw+C+igfh89 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TanLeft {
            get {
                return ResourceManager.GetString("TanLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7X1pgFxllfbznHurqqvXdHeWDmQFZAk46qefyucgKIvLgCAh7egoEqJBgYTFBXcacEMlQHcIk5AEERTtLA6jo46DIjPOqDMyooaIImBIJJBOL+nq6lruvef5flR1aCDIlnQa7OdPOrdvdb3L857znvOe9xwCwLrVXVcSeDgX1K9cuHBhERP4qwE3rr7uzU7/HgAKeNiAL2bzWvXWpUtL+7txE9j3sEReBDAIAAQOENA5XMc/rlvdde73Ojsz+7l9E9jHIABsXH3tUU77PoAZT/j9VghXTaiGFy848sOG1ctni/oBgMP38N4WQJ/rjTNfPeecc6Kxa94E9jU4+j8bb1reqljfEXD0U7z/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TanRight {
            get {
                return ResourceManager.GetString("TanRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15nFxllfe/57m3qro63V2dFQIBWWRLEARcBlSoJKAgqKDCCC6grILivG6sIbcDqIy4vMwrMzCjM4ooJiMubIKQVAhJREWCQkAwhEBCIJ2l9+6quvc57x/PvV3VIXu6Owv1+3z600lV31tP3XOes5/zCDW8uXDbbSlee+0zqH4B3z9NdvR6ahgmVAh/DbB//Opvagywu2PDhAcoI/LFGgPsrrjtthQrV54NTAPeut67ncAnCIL7awywu8ER/lzgagbu+AT/AD5EEDwHUGOA3QWb3vEJFgBnEASrkhdqDLCro7LjrwH2q3rnaeBgIB3/fybwaYKgVH15jQF2VWx8x89H5MeofgE4In7t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TurquoiseLeft {
            get {
                return ResourceManager.GetString("TurquoiseLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15mB1VtfZ/a1edoad0QpImCSGTzI3CFT4BBT0ZQPACol6iXD8RHEAJg6IMIkmqA4K5SkRAuCByVfQqQfReQUG/kBzECSUQhg5TSJiSkKE7nfR0hqq9vj92VQ+QQAI9Af0+T54+dVJdXVXr3WutvdbaawsAQbAQkXWo3kgQFBjGOwZCEBwL/B4QYB0i32bUqJs499ziIN/bMAYABigA2+LjCaheQ3PzKoLgLK65JjOI9zaMAYAAEAQHAncDE1/x/y8ictWwaXj7Qro+XX75ZMLwHmC/7Zz3PCLfYty4H3PmmeUBu7th9Duk19EVV4ymVLoTOGIH568BLmf8+FuHifD2gLzqm+98p4r2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TurquoiseRight {
            get {
                return ResourceManager.GetString("TurquoiseRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABpzSURBVHic7Z13lGRVucV/Z3KO5DgIkiQoiERFgSdITiKCIIIwAyqgD4VHEp6ios5TQDEHzLD0oWJ4qGSGKKKiIGkSE5iBYXLoSfv9sc/xnqqu7q7ururqmam9Vq+euXVv9bn321883zkXmtigIKm/pHMkPSlpy0aPp4keQib4ySrwy0aPq4k6ow3BS9JKSeMbPb4m6oQo+DMlPa/WWCTpyEaPsYk6IAr+gxU0PuF5STs3epxN1BgdaHzCJEmbNHqsTdQQmcZPKRP2U5Jasv/fKmlAo8fbRI3QjsY/KOlcSX/Ljn1FUp9Gj7mJGiAK/twKGn+/pEMk7SBpWnb8ykaPuYkaoAONPyaes6OkGfH4ajXT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhiteLeft {
            get {
                return ResourceManager.GetString("WhiteLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABt9SURBVHic7Z15vJ3Tuce/K8lJQuZRSEhCFaXaqttSQxVXuYYqRSdjVZWiQtGL1lRDi+qAVkfVaktVW9RQLa6aiiaGCkGImEUSkXk4v/vHb628a++zz8lg77P3Sfbz+ezPe/Zw9n7f9/k987OeBYCkCyQdJ6k3TVq9SNKuklpleknSMZJ61fu8mtRJJGkHSTNVSlMlHdUEwmpCkjaLTC+nF5qmYTUhSaMlTawAAkl6XtIXJbXU+zybVEOSNETSve2AQJImSzqsCYRVmCT1kXRbxvQXJd1TBoRnJB0iqUe9z7dJNSBJvSRdnzH8L5J2k3R3GRAmSTpQUvd6n3OTqkySukv6RcbsWyX1lrStpH9UMA1H [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhiteRight {
            get {
                return ResourceManager.GetString("WhiteRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d17vJxVdTfw735mzsy55koQFLmjogKSnIAoglRrLWALVqxQRcQKKL7Qi1ZABeK1qKjYarWttvXSi7a1Fi8FFZCbQE6gWvEGQsI9gdxPznXm2e8fz545c0ISQnLOSQjnx2dI8sw8M/vZ67fX2mvttdcOpvG0QuzTJjpd8E5lJ4Yd3aBpTA1aBP9e7Jcuf6u8Ixs1jclHU/C8V2gKHkZF35vWALsokuBPFbwfB2709nrRG8JC350mwC6G2KcNb8ZFjBvxDdyN14Rev4RpE7CLoDnibXLEFwhuVnZyOMyKsUvTeEqjZcS/F/u2vPUzPAeV9O+v6/Cm8AIjrfdnU9HIaUw8Yp+2uNjp+Dn+ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDarkLeft {
            get {
                return ResourceManager.GetString("YellowDarkLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d15nF5VfT/w97nPrEkme0KAkBBAEbAuJCwuVBTcwaU0WLVSbftDi6KCyuIGigpUQRSEgohS6gYuta6lKrUiCJmBAAoIyA4CIeusz3bP749zn2cmIZFtZjLgfHgNM/fmPs89557v/X7Pdw8Qe5wqul+vc8NLDZnEXwxC7PEq0U8QcD9OMcN54RnKW3lskxgHZHJD2FAcb4cvWu+22O2IeKv2rTi2SYwDAsQVni34KRZu8u/34LRJ0fD0RWj8Ea+xWO5neNZmrrtL8GnR18Iy1fEb3iTGGmHkQbzKHJkfCl6whevvEH1KcNEkITw9EDY9Ea8zVdX38fLi1H2Cu0QvHHHZHwWfssF/hJeq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDarkRight {
            get {
                return ResourceManager.GetString("YellowDarkRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABpJSURBVHic7Z13mGRVmcZ/Z3KO5CEMImGAAQWRDAqsIDBIEgmCLAgDyIK6KEgSVtEddVYBxRwww6OLimFRyQwgiKgoCAOTMwyTQ0/69o/3fNxTt6urq7urumpm7vs8/fTMrXurz73f+8XznXOhwGYFM3qbcaEZz5oxqtHjKdBNSAQ/xQyLP79o9LgK1BltCN7MWGPG+EaPr0CdEAV/nhmTc4I3M5aacXyjx1igDoiC/2AZjfefyWbs0ehxFqgx2tF4/5lkxlaNHmuBGiLR+Kk5YT9nRkvy/7vM6NPo8RaoESpo/GNmXGTG35JjXzajR6PHXKAGiIK/qIzGP2LGUWa82YzpyfHrGz3mAjVAOxo/Lp6z [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLeft {
            get {
                return ResourceManager.GetString("YellowLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQPAAAEDwBkdaXMwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7Z15nFxVmf6/z7m3qrq6eqvqhAQJywCKRNwHFTdgcBxlGQXpDgFBQGURB2YUh0UhxBEVBRUVl5lRxx3SIKMojoDsoOiPcUGjgwgJBLJ2V+/dVXXveX9/3NvdlZA93Z0A/eSTP/rce+uee87zvu857/uec8QMnlMw+2qGnuIpiPfjOVo7u0IzmB7UdfyHgb9Ji38Y7sxKzWDqMd7xZT6MxjseoAb66YwGeJbC7KsZeksLMbsE2H+DywNgJ6i04OYZAjzLkEh86V3ILob1JH4Mj+DdMZp1/J8BZgjwLMEWJH4M95MJj1XzcWvGCmYI8AxHncR/GNin7tIfgBcA2eRPLaFoJ0ud1frn3TTV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLightLeft {
            get {
                return ResourceManager.GetString("YellowLightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7b15mCRVlff/OTdyqb0qa+kFegUUaBR9B1/UUaSVRXTADboAHVHG+aGjINIquNOKCqggCsILIoio0NUs4+7LgwIzjqI/mQHUBtmhEZqursyqyszKLeJ+3z8iqnqhm6Wpqi6wvs9TT2XcjMy8Efcb59xz7rnnGIDyq8/G7DGGyxfb0uOrzOLvBqahgcMwfg4Y8BhmZ9HVeonZm2s7u3OzmHo4nFWB0eR4F6RvUijdp/yaD0o/z+7Mzs1i6mEAyl/9EnC/ABZs9f46jHNmVcMLFzb+QoVrF6Pol8Be2zjvYaQv0T38XbP3N6ave7OYatjmBxq9rocw/Anw6u2c/yDSF+kevnKWCC8M2NYN [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLightRight {
            get {
                return ResourceManager.GetString("YellowLightRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB/CAYAAAAn+soHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQOAAAEDgBbisQIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABtXSURBVHic7Z15mFxVtcV/N0lnnicSEuhEQEAQJ56CoCLwEB6DCBIUZRQRQUQiAgookyAKiMog6kMRBwRxAmQQBR6zgoRBEgIEQiAQyETmgfR6f6xz+p6qru50OlVd1Z3a31ff7Rq66t6715732QcAiQslTpToS502LJLYU6JJQhKvSJwg0afa51WnTiKJXSQWBgDExyyJ4+pA2EBIYtvAdBU9Xqqbhg2EJBolppYAgSRelPi8REO1z7NOFSSJERIPtAICScyQOKoOhG5MEgMk7kiY/rLE/UVAeE7iCIle1T7fOlWAJPpI/DFh+F8k9pK4twgI0yUOlehZ7XOuU5lJoqfEzxNm3y7RV2JniX+UMA3H [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowRight {
            get {
                return ResourceManager.GetString("YellowRight", resourceCulture);
            }
        }
    }
}
