//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laavor
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArrowsScratches {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArrowsScratches() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasePackage.Arrows.ArrowsScratches", typeof(ArrowsScratches).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAvhSURBVHic7Z15kFxVFYe/M8kkMANhEUlQJAEcIIEUaAVccIGCwioUChc0gawQksjiIOsgm2iqDNFUAAFJIBaQEioYsAqBUrZCChSrUKAiSyCYMDpGkVBJJGRmuqePf9x5eT09vbz9dvfcr6r/INPvntOc3z33vvvuPQ8cIwfVFlTPQvUlVI+w7Y4jK1RHDQb+dVR18PMcqi22XXOkienxZ5YEvvhzvm0XHWlgevzZVQLvfZ607aojSUzgZ6L6Ro3AK6prUN3dtsuOJKid6os/BVSXuPG/GfADH6THK6q9qM6y7bYjLibVz0J1fcDAK6rvofp526474mACPztk4BXVblQn23bfEZXwqb748xqqB9n+ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AquaLeft {
            get {
                return ResourceManager.GetString("AquaLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA2HSURBVHic7Z15kFTFHcc/vbMcCx6geKBE5bCMB9EQE+MVY0RiNAYrFY3RYCytIiRqLJXyLIQYNVAmKh6FkXCWiRHQEiWFBkoshbK0FFFUVO5LxGAEQdhdduebP3oGZ4aZ3Tfv9Tt2932qtrbm7Xv96zf93X79ft2/XwOAdCjSJKQTSOmASDORhJRFeh7p+3FXKSUqpAtyjV/6sxDpwrirlxI20usVBFAohPORTNxVTQkD6XCkt1sRgZAWI/0CqSbuKqe4RuqONNuDCIS0Eul6pC5xVzvFJVIGaaxHEQhpTU4IdXFXPcUl0o25twGvQvgEaSTSPnFXPcUV0uVIjVWIQEjbcj3IAXFXP8UF0nlIO6oU [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AquaRight {
            get {
                return ResourceManager.GetString("AquaRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAubSURBVHic7Z19bNXVGcc/vb0vLUVawCq+FaTWQsHYJc0c617QRJYwJdMEmBs4BWFM3cYGCirqXkzGnGZu003cS3xZWHTo4nTLNnUZZK+BuRiWDYYOKDAE3SxItbS0d388Pb23t/fl93rO796eT3KjwXvP8+D5/p5zfuc55zlgGUvEgE8AfwNmGPbFopFqpOP/CaSHPr9HBGGpYGLAQkZ2fPbnRnOuWcKkGvgkhTtefV405aAlHKqBJcAuind8GngSqDXjpiVoSoX67M8gsBE7/lcEquOdPPFpoBdYasRTS6BUIx25G2cdnwbeBN5vwllLcFQD1+Ku49NAFzDTgL+WgHAb6rM//wCa9LtsCYI48Cng [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlackLeft {
            get {
                return ResourceManager.GetString("BlackLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA3bSURBVHic7Z17cFTVHcc/+0iWbIAkhJGHkYQkoIhpBKyKgA4SI9VWO6W2VCvt4DilVXSsHR84VmorlbFVQR1tqFSYvqbQjiIdW3BqR6GODkae4gMQBBrjo0mICeRx9/aPXzbZvexmd++e+0hyPzOM3s2955zd893fnsfv9zsgjAWeBc7DY0iyAdCBCPAicLGzzfGwk6uRzjf+2wZ8zcF2edjEGyQWQKwQrgJ8TjXQw1rOBN6mfxHoQD3wTcDvTDM9rCQfeIHUItCBg8DtQMiRlnpYRgB4mPREoAOHESHkOdBWDwv5MTIbSFcI/wV+Agx3orEe1nAD0En6ItCBFsSCjHKgvR4WMB/4gsxEoAMngJXA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlackRight {
            get {
                return ResourceManager.GetString("BlackRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA75SURBVHic7Z17kFTVnYC/c7vnDQwD8giOME8QGoVVK3FrNUUqqRhjYoShI6hEUEQTdHWjgRFBSMJWNqZSibuaRDabyho3wPQA+zBu4qNWk7iaqsVaF2cIj+lmGBWURw8DTDcz0/fsHz13pufVfft2973dPeer4p+ee+/vFOe7v3Puufec40IxjtimUTNtJRWe5ymf/wadB08Lp4uksAOvixpuB7YAV/b/+CZ+z6eVAHnNNo3q9xoQ4jsMVnwMcr0SIC/xuqiRK0BsZtSKH+A1JUBe4XVRLVYi5GZgXtxDhWziklitBMgLEqX6IUiQT+FfuAm26UqAnGag4r9Lojs+yiUk9xHw/cr4QQmQk3hdVHMH [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDarkLeft {
            get {
                return ResourceManager.GetString("BlueDarkLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABEmSURBVHic7Z15dFzVfcc/940WS/KONwxYmjcKm+yYpQ1Q6hMSOC5ZWIr1ZAK1Q2lPoU0amuU0KQ61S8CxS2riJMTExGCWQtHIDrEhUHCxCVtDEgwGGTCSRhY2tqmNjCzJo5l57/aPkSyNNOubt8l+n3Pso3lz7+/+5s13fu++u/xeAIAabQaTz17N5DltdDZ/hM8Jg9L//09B3Ig0dqBqm6lZeKHLfvk4hEDVvgQ8mea9l5FiJZHGzU475eMcAlX7HfCZLGVeBrGctsanAemQXz4OIThdO4UETwLnZC0p2Q4sJ1K3EZYZjnjnYzsCgOmLqhgbfRTJlTlrSNoQ/ASl+15anu6z20EfewkA0LMjTmdd [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDarkRight {
            get {
                return ResourceManager.GetString("BlueDarkRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAtBSURBVHic7Z1pkBXVFcd/d4ZZmME1KJio4DKySWmqiCYhi1Wx/JKlzAcMRtl1NKDRCMpoxCWxKoTEcokbJFouKQwuScXCVEIsKlIm8sGYGBIjMgQYnGAUKECQWd/Jh/v6Tc/Me6/3vv3e3F9VV1Fvuu+5zfn3Obfv1mAZQUgNyLdB/gYy2XRtLKkhtXnH/xtE8sdrWhCWKkZqQGYNcbz7WGy6hpZEkFqQK8o43jleMV1TS6xILciVIO94OF5A1oGMNl1jSyx4hnr3kQNZafN/VVBwvJ8nXkC6QOaYrrUlMlKrHSlbfTpeQPaCfN50zS2RkFqQuQEdLyAdIFNM194SmsCh3n28DXK66TuwhEJGgcwD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLeft {
            get {
                return ResourceManager.GetString("BlueLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA+CSURBVHic7Z1rdBzleYCfd3Z1lw12TMzFCb5gjG0IIK0EbZMc3NCmJ5ALtnclmYsxGJsEKJSLEeZiEjhJIOVAmkDr0BYOpFzWhnNSgnsKScXpSbjYkoNLHYeYGhsDDra52Ja0knZn3v5YzbKWd6XZ2Z3dlTTPL1u7M+8nfc+8323mG8Fn3HCnqjGvi1bgJgPaFofkD1LqQvl4TzSqAWbSAtwOnAKgym+3hfiyL8AY5k5VY34XixS+x2DFpyNwlS/AGCQa1YDMolWV28hQ8SmUX/sCjCGiUQ3oLNokWfFzhvuuQFQHuNQXYAwwUqofggrcu7WR1XeKWL4Ao5i0ir+LEa74QfpRrog0yeP2D3wBRiHR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLightLeft {
            get {
                return ResourceManager.GetString("BlueLightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABEvSURBVHic7Z15nBTlmce/T9UcDDcRjKgxC8b1IEpkZkBNXIOiiWaNrjANhkjW+PlEN9mYj8aP0aALG5UFjQdGo6IEdRPDVA9mI6ImYHDXKzLdgCAgioMgInhxDDBn17N/zNUzTE93V9c10N8//FhV7/s8L1O/fu/3KQCsFXqUFdPHqlboKPIcVhit/70fuMo2WGvFdHFVTMcFW6w8fiFWTL8DPNvNs1dVmDO5VBb7Xag8/iFWTN8AxvaQ5hVRZlWUy/N+FSqPf8iiv+uxiQKeBUanSbtKlTs2lPGnmSK2H4XL4z0CYK3T/hzgKYSLM8jzHsKdu5QFV5dJk8fly+Mx0vY/lqWmjOQehWszzLsFuJdG [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLightRight {
            get {
                return ResourceManager.GetString("BlueLightRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA0XSURBVHic7Z17jBXVHcc/Z+8+WJanpSqVyNNYpVSlKiJVY8St1SqmqabRYhtMLK2v+IhaDIVapRBbFR/RSlmFaGwFG1EaVIgaizU2FkEEVBbKa11QKAvLY1/3/vrHuZe973tn7pk5c3fnk8wfMztzHvd89zdzfr/zAADkRJCFIN8hpDciS0AEJAbyOsh5tksU4htyRbzx04/VIFfaLl2I58iHOQSQLITLQZTtkoZ4gpwE8nEBEQjIGpCfgFTYLnGIcaQOZFkRIhCQLSC3g9TYLnWIUSQCMrdIEQjItrgQam2XPMQocme8N1CsEL4EuRukn+2ShxhDrgfpcCACATkQtyDH2S59iBHkMpBDDkUgIAdB [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueRight {
            get {
                return ResourceManager.GetString("BlueRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA92SURBVHic7Z17lBTVnYC/X/U8gBEVFkHwAYqIiGgWTTZ7VrPmmLNZY3QVaAUEBZ3pGkDFaMQRRSaJWVdzfMREYUZdPbpZsXvAc9Yku+tjN7tn1XhO1l0XXcOa+IAoqEiPHJhXd9Vv/+ipoZlHd3V1d/Vj6vuPmbr1u8z96t5b99a9VwgYNbS2qvH2VBYDt9iwZKspv5VSZyqg+ISjGiLOFcAG4DQAlFfm7uFrgQBVTGurGm9NZaHA93EKPg0V1gQCVCHhqIa0k8Wi3MEwBZ/Gy4EAVUQ4qiHZxxIV7gBmZ7pWlah0sSIQoArIVtUPQlW494yPWd/aKnYgQAWTVvA/IMsT308vQlMsIk87PwgEqEDC [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSkyLeft {
            get {
                return ResourceManager.GetString("BlueSkyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABFvSURBVHic7Z17fFTlmce/zzkzCYSbKCoo0qJ2vYBF3V2t26W6K9vVdr1UcoKXhdYKCWDVrfVTa9GStUJh7WK1CpmJeGFtLZnAWtDFVVapaPnorvVKvSEKiEEFEuWSy2TOs39MApMwk8ycOefMCcz3r8yZ932eN+f85r2/zxEA6z4driHmmDZ3LZ0hb1LkkMEAIMyvBb5vG7xu1ejKSbX6tQKXq4hPiBXRbwOPH/gNL4jN/LrpstL/YhXxC7Gi+iLKWZlT8ILYzK2rYhUi6mPZiviAWIv0WAweB07vJe0rKHPHbGN5dbXYfhSuiPcIwOQlOqClmd8CF2eRZyPCPbtbqFl1vbR6W7wiXiOdf1h1amoT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSkyRight {
            get {
                return ResourceManager.GetString("BlueSkyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABDOSURBVHic7Z17dBzVfce/v5nRayXZJ7axZVm7WtuSsbWWTeKctk6B0B5O09OktBDcYGNewWASkxjb0q5k/NgkNH7IQEKAHoekJwWanBja/tE25xBID4UmlIBDsTSSX1iPFY7fQZIt7Wp37q9/rEZaSbur2dmnVvP5T5qZ+7vn/L7zu797597fEixmDF6wVOrqvYshGiVJrG9oXXycst0pi/RzZB3L3e29X2FgN8DLR/7960HVfrMlgDzGC5ZsdT1fBknfjnD8KAxssQSQhxxZx3Kn2nsXEXZFc/wY9CtLAHnEkXUsd3f0rmcWuwC6Pt69zDhSMJvutwSQB0wV6ifABDp4Ta3a6QUJSwDTmDHH4ztT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueVioletLeft {
            get {
                return ResourceManager.GetString("BlueVioletLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABL7SURBVHic7Z17mFPlnce/v3OSuTqACIjAZGYQLzOZUSq2oq1b+9Sn9VK12+fBbbVoa/s8um3XPuhcoKikVmCSsFCtropSFd12F9Ddiq43VvHK1koFZhJAESbJAF64jkwmk+S8v/0jOpPMJJPk5NwG8vlrcvK+v98753zzXn/vewgAPM49k8HyYmKsaNnu6ESREwYJAAi2P4BwE0vY5nGG1rvru2ebXbAixkDexq4rmaXn0nz3NoHdLb6a9YaXqohhkMcZ/CuAr42Q5m0IWtKyfdoLBGKjClbEGGj5uaGp8bh4DqCZIyVk0PuAWNLnczzjAgmjClhEXwgAvOd8XMlK9E8Ars4hz24Q31cWiT50664z [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueVioletRight {
            get {
                return ResourceManager.GetString("BlueVioletRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA9GSURBVHic7Z17kFTVncc/px/z5CFECDOgQWBAGEVgIJEKYSexKqbWrGs0bAQxgiCj8YHxgeMwAwckZSIVk7CaLcyaymo2lvhI1ZZrZTVZZq2wSpie8RFUCgEFMzPLmxnm0TPT9+wf3Xemp+nHvf24t7vnfv6Zqtvn3t+v5vc9v3PuOeeeI3AYMUhwUcXNwMPAcunjY2GzTw4WsGsZ7g8P8z2gAbg8dHkPPpY6AshjJLhEFTcp2MpQ4MO5222xTw4WsGsZ7iuKWEE5LwJ3ARdHLSgocjJAHrFrGe4PD7EcQT0wK1HxMQWscgSQB8jEqT4cBTyBjzoJmiOAHEYOBf4xEtd4AL8Q3LG5ief1C44AcpBd [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrownLeft {
            get {
                return ResourceManager.GetString("BrownLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABF3SURBVHic7Z17kFTVncc/5/b0PBhGHqI8dYUh5QKLQvcAWlkrWLFY10STyhZusq5sNltbuJusqZhs1CDMmUHGYXEhGA2K8YVsYuFjN4Krq6yOicjqvJCnEZgoqCAiCAPMo/ves3/0PLqb7unbt+9r8H6qpmru7fP49e3vPc/fOScEIGcxZu4YVs8dT1vDxxwh4AuDBoDBLxB8D8V2GWWjjHCFx3YFuISoifI1BZsyfLZFKJZXt7DRdasCXEPIKG8BswcIswVBnWziRUC5ZFeAS4i7L2d8vIhNwIwcYVsR1NHEcxIMF2wLcAEBsOIyyk8X8WsEN5iI0ybgvhEnePDWfXQ5bF+Aw4jefzbMJ7S7jWXA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrownRight {
            get {
                return ResourceManager.GetString("BrownRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA81SURBVHic7Z1tcFRXGcf/d9+ysDYtlMZseAvEJAWqgp1xOlNF+kUdtVVrrQX6ApSS1lbagoWQZJOHhQ5iRtRodeLbOLTaNjJ+Ume02mY6vlRnKmNbiEyAQsh0I5AFN4Zks3vv8cPeGy6bu7v33t37spvz+7g55z5P5vnf55x7XgVwZg1E5AFwH4BnAKwnon8LDvvEsYG+vj7v8ePHvwIgAuBm+ee/AFjLBVDBEJFHEIQvMcaiuBp4NY977XaKYz19fX3eW265ZQOAlwE8BmBBjqJBngEqCDnVrwfQAaC5UPHq6upNXAAVgI5Ur4YB+CaANiKSuADKGFXg96HwGw8ASUEQHunq6npe+YELoAzp6+vz [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLeft {
            get {
                return ResourceManager.GetString("GrayLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA9WSURBVHic7Z17bBzXdYd/Z4bLx3L1LB1JsVLrEdqmZFvizh2KUJ3ALOCmaAKnUVPUkmU9YtlyIrtyZEWiZNlqEqOJHQROWttFkrYw4tRBWbeA0TZAowZrFAqjcGdp0e5CFZhKpiJUsSzXJUVpuI+Z0z+4I6wo7u7s7M7M7nK+/0jOnXPB+91z79yZuUMImDMws5RIJO4H8BUAm4UQ/0V+VyrAfQYGBuRVq1b9CYCnAdwOAMz8cyHEJwMBGphcj/8jAF9DruFnsCcQoAEZGBiQV69efT8zH8HsDQ8AYOafBQI0ELmG35xr+NtKHZ5Op3cEAjQANlL9dYcDeF5RlMNEZAYC1DF5Df91lO7xAJBi5odV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLightLeft {
            get {
                return ResourceManager.GetString("GrayLightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABEUSURBVHic7Z1tdBzVecf/z8xKK8mWbRE7NZByEhmMHQVk7czIoJqTyqExeSXH5wTaurg98AFCUnIIPgViiDkEu3ah5jWFGhxeDmlyBPi0GArFKuYEiNHOHUmWEI6DIxDYBtfERl7Lkna18/SDVkK72tXuzs6b5Pl90sze+zxXO/+998597gsBQDQaXSjL8kbTNO/VNO1tBJw2SAAgSdKDzHw1EXUJIXYahnGR1wULcAcSQnwLwAtZPnuTiLYoirLT7UIFuAcJIdoANE6R5k1m3qSq6ktExG4VLMAdqLOz8+yRkZEXACzLk7YjJYQdRGS6UbgA5yEA2Lt376yRkZH/YObvFpCnF8ADc+fOfeS8884b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLightRight {
            get {
                return ResourceManager.GetString("GrayLightRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABE/SURBVHic7Z17cFzVfcc/Z6W1LEuqZWGChY2JLWdSKxiY4uJkOm7WUyalJCSZzNjT1sVt02FEGkomTsC4trW/XVlCrlOb8AivmldJwhjItBgKBReWhsckmAC2IwewXSMBcmyzWAhZj9Xe0z92V9aud7W7d+9LYj//SHvvefz23u+ee+45v/M7CkBE5gDtwHYR2U+ZTw2+5N9bgW8De0Vkl4h80UWbyjiICoVCX9VaP5Hl3EtKqS3BYHCX41aVcQwlIr8CLp0gzUtAh4g8BWhnzCrjFGrz5s1zR0dHnwAuzpP2daAD+IWIGPabVsYJFMDWrVtrBgYGfgZ8vYA8h5VSt8yaNevO6667bthe88rYjUr9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayRight {
            get {
                return ResourceManager.GetString("GrayRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA8iSURBVHic7Z17lBTVnYC/W93T8wKGAXkER5gnCI3Cqidxz2oOOcmJMSZGGDqCSgRFNEEXNxoYEYUk7MnGnJy8NIlsNscYE2C6gX0YN/FxVvNY9JzFsy7OEB7TzTAqKI8eBpjueXTd/aO7hp5hpruquruqp6e+c/inp6p+93C/+t1b99665cJh7LAFpXYKyyu9PF8xlzc6D3BK2F0mBwvw4aqF24EngCsTv/4l6OWTjgCFzBaUmndpFIJvcbHiLyJZ6whQiPhw1UqWIdjEcBV/kdccAQoJH64awXIh2QTMSXWokDT3CFY6AhQC6VL9YCSSp4Lz2cgWVEeA0czFiv82ae74BD0S7gv5+bX2gyPAaMSH [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkLeft {
            get {
                return ResourceManager.GetString("GreenDarkLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA0VSURBVHic7Z15kBTVHYC/7j1huZZbRNjZ2WWBlUCEUlPRFFWxxIpGMcQq8ORcDzR4ICwI4kFKY8pSEzWBGCtRS1Mc6h9KRdQqJRqxSkiMWgjszuwuKMrh7HLNHmx3/uhpZvaYme6evmb2fVX8M9vdv1e8r3/v9XuvX4OgLyFTzvWU8x/KmOh1YQTukRer+D2Uo8b+fQTIktclEziKTIA5SDwCvd7xS4UAuUke5cwF1tB7xeu8LwTILfIIMA+JNUBVyiMlNtHGfCFAbpAu1SeiAk8QYjWgCAGyG73iHyXdHa/RhsoSwrys/5DvXNkEDpJHgOtjqX6CoTNUjiFzNSH+nfizyADZRR5BbkDlAYxWvMYB [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarknessLeft {
            get {
                return ResourceManager.GetString("GreenDarknessLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA9SSURBVHic7Z17kBxVvcc/p3sf2d1ks0vCK6+d6VmCIaYQUFFzU0iRWuMLbqmUlBi0sCzwSVla4iXiRoSY3GgwKgYJCRC5em8SH5AgCNGAvEqEkAebSDKzs1kSQriEhN3NZufRffxjdndmZ+fZ06/d9KdqqrZ7T//Ome7v/Lr7nN/5HQAIcA4a6wjxbnxOQzQ2oSHRMNDYQoAPuN0kH2cQaHwc2Jrjf88iWUGULU43ysc5BBr/AN5foMyzwDI6eRSQzjTLxykUqvgUsLNAmfnAIwR5iSCfARRnmubjBAKAs2lgIr9FcmXRIySdCH6Owt2EidndQB97UQE4SYLjbKKZWuA/Ch4haAYWIVlMM5IGdtND [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarknessRight {
            get {
                return ResourceManager.GetString("GreenDarknessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABE+SURBVHic7Z17eFTlncc/75nJhCSEmyCIQjIzqbdA8bJbdV2e2urD2latKznB6kJdd5/V3XZ1e3m2XakLa5XC2sXSarFYFC+rayZQC1pdZQXrbWtbETSoMckERAEXCIYkTGbmnHf/yH2Y65lzC5zP88DznDPv+3vfzHzP77zX3+sDqFaZNulsVk2aTVtHE5/gccKg9P/3MwQ3Sp0dIZVN1Qu40OmKediDCKl8BXg6zWevSsGKaAOb7K6Uh32IkMrvgM9lSfMqgmVtDTwLSJvq5WET4nSVU5N9HuCcbAklbAOWRWvZwFJ0e6rnYTUCYOpCKsbGeFzCVbkySGgT8FOli/tbnqXX+ip6WIkPoHsHiY5a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkRight {
            get {
                return ResourceManager.GetString("GreenDarkRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA1uSURBVHic7Z17jFTVHcc/M/tgYRUBgQIqoshboyhRmypZS6JGjKLYVh4qLxcUFSsIC+yyB8RYJT5K1RZqjVWrcQX9x5IWNYykWzVRjFVEgogsKshjhcWVXdid2z/OXGZ25s7cx9y5987s+SSEMPec+/uF3/f+zrnnnkcIRedBEAZuBR4EJiH4MuSzSwovqKOIL/gdUAMMj/1aD4xVAihkBGFCTERjBfHAJzK3yGufFB5QRxHnMxl4DbgL6J2mZJnKAIWETPWTgGpgmGnp7kxTAigEzFN9IhrwGLAEQVQJIJ+JB/4hzJ94gFZC3EktL+k/KAHkI3UUsY3JaFQDQy3WOgTcgOC/iT8qAeQTso2fAizF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLeft {
            get {
                return ResourceManager.GetString("GreenLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAtNSURBVHic7Z17kJZVHcc/Z7nGqoCBYKHihTumf2xaUQ4zNfzTZewPDJI7uCCYmCCsJl4aZiSKwQsgWJnghAnajA02hY2TTCV/EGWUiSwtrG2kAQMIutf31x/nffZ5d/e9PPfzvO+ezzMMzPK+53ee/X3P79zPAUvvQahC+DbCXxDGm86OJSmEPlnH/xPpfP6AUGU6a5Y40SV+ejfH5z5LTWfREge6xN9exPHO8zvTWbVEiXb8LIR3SjheEF5E+ITpLFuioHSoz30yCOts/V8JuI73UuIFoRlhtulsW8KiQ/1shMMeHS8IJxG+YDrrljBox8/x6XhBaESYYDr7lqD4D/W5z9sIV5p+BUsQhL4IcxHe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLightLeft {
            get {
                return ResourceManager.GetString("GreenLightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA1JSURBVHic7Z15kBXFHcc/s2+XdXdRwBCRSHmwGkVCDERUJMaiRMojHpUUViUGTWmVMTFqKRYxqAXxIBBPNJYGBMFoDsCUCAYVPEoxlilFblBXClgONRLuhV32vV/+6HnLvHnnzOuZnrc7n/lr5vX0sf3d3/R0//o3ACAci/AMwkBiuiDCHARBSCEsQDjbdJViwkK41O5897EU4TLT1YsJGuGDPAJIH+8iXGy6mjFBIfRDWF5EBIKwDOEnCFWmqxyjG6E7wssliEAQmhBuQKgxXe0YnQgJhKklikAQNiLcilBnuuoxOhHG2m8DpR7b7Hu6m656jC6EnyO0eRCBIOxGmIxwtOnqx+hAuBhhn0cRCMIe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLightRight {
            get {
                return ResourceManager.GetString("GreenLightRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA9oSURBVHic7Z15kBTVHcc/b2ZPlmNRjCJogCWVACEeOUzKsoKltTEaj0pKY4VgEvMH5rRiDkwQ5u2urEtIIBgVLxCPXCvRKBiNEsUDLSMKciayEEURNNzLsbMz050/enbn6pnpu3uW/vyzOz3v+M30d9779Tt+LwqA5BSmsJApbGcVHxJy3BBJ//09cC2wHslyJJ/30aYQDxG0cAkqK3TeW41gLjGWe25ViGcIJK8CnyuRZjXQjuRJQPXGrBCvENzMKJKsAM4sk3Yt0A48gkRx37QQLxAAzKOBI/wRuMxAnu0IbmU4d/Jj4q5aF+I6ov+/TqJsZg4ww2DedxAsYAh3cwPHXLEuxHVEwRXJDcBvdN/T [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenRight {
            get {
                return ResourceManager.GetString("GreenRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA3uSURBVHic7Z15kBxVHcc/v9nZ3WQjmEDClQhrYAm5xFK8KmJpaaEFXoirSUggx2Z2OSJ3soQcq+IVigIEwm5PAlEsLBG1yiNVoliohWgVRYkRQhAhLG4Qk2ASs8nuzkw//5juyczuHN09090zs+/zF8z2e79Xed/+/X79TkEzblA9RNjLQuAWYJEYvChhN0rjP6qdBqbwZWADcF76R55iOh/RAqhjrDf+MuBr2B2f8wDXaAHUIaqdBiazEGE9+Tr+OE9oAdQRqp0GTmIRivXArKIPC4/SwjItgDqgpKsf9TiKzUxnnfRgagHUMFkd/3VKvfFphlGskjgP2z9oAdQgVoxfbMX4cx0WO4DisxLnT9k/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLeft {
            get {
                return ResourceManager.GetString("OrangeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA+LSURBVHic7Z17cFzVecB/3z70MgYbjG0BBmMjGwwMobhMZgpMKWnx2FoZHOpiMG+DSXiYQDDCluxjxwkFhkdoIENew0DatCqlAT8mQKg7maYhKTFlKLguxAHzkAHbYFmSJe3e+/WP1a52pX3cvdq7D+n+/mK0597vmO93zzn3nHPvFXzGDWpMgHO4HLgbWCYR879S7kr5eI92dASpf/tvgHbg1Pgf+TU7uMAXYAyjxgSYL19FdSOJxKcV4BZfgDFI/IrfeTloG5kSP8QrvgBjCO3oCNLw9jKUNmBuzsJCB71HXusLMAbI29QPK47yADtYI8bYvgBVTEriv0W+Kz5OPyo3Ssv6ZxJ/8AWoQrSjI0jd [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLightLeft {
            get {
                return ResourceManager.GetString("OrangeLightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABFfSURBVHic7Z17dFXVncc/+9xcQhKQR0XFBx2FTkd8wLRO7WMYdWorlYRUZ8k8GLDTTqszbe2q7YgW4e6Eh2HsgFqtD8TXstNOtE7JuREVqo7VumqNLyyoRBSQh4o8JJDHzT2/+eMkJDe5z3PP4wbOZy3WIuecvX+/nPPNfu/fVgDSrE/AYgmKFapav07IUYMBgMXPgG8ivCamNqVJfz5Yt0L8Qkm8bgYi8cF3eA5Ry1RNzAzArxCfUGLqPwCfy/wEzyEspVqvUQrxz7UQP1BiLj4JuuPA1BzPvgwspYVHlNaWD76F+IACkMdvrKLr4H8DM/NIsxnULUTG3KEuvqrTW/dCvEb1/kcaGyMM37AExbw8 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLightRight {
            get {
                return ResourceManager.GetString("OrangeLightRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA/xSURBVHic7Z1/lFTlecc/z8zuArtIIILKj2gUPBaQkNBUk3I4aVJKY1ITT3pojsdArO7eAa168qNGA2a3KgRERUwEdhYQbGpbVpsqUjWQaCroiQmiICgRUEBWaJCfC+yPmXn6x8zszgwzOzP398L9/AP3znuf552933nv+z7v+z4XAL2Fi7SOZVrHWALOKUIAxHgU4WaErRphjRpc7XG9AlxC1ODrwHNnfKJsJMR8aWSN+9UKcAvROn6HcFUPZTagzJUmnnetVgGuIVrLCEI8B4wvUnYzyhyG80tpIOFG5QKcRwD0FvoT40ng2hKu2YXwAMrjEqXT2eoFOI2k/6NTCTOIh4HbS7x2D8pC+hOVhZx2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeRight {
            get {
                return ResourceManager.GetString("OrangeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAwLSURBVHic7Z15kFxVFYe/M5kFZiQsIgkKJIADJJACrYALLlihsAqFwgVNICuEBFkcZB1kE02VEU0FEBACWEBKqGDAKgRK2QopUKxCgYosgWDC6BhFQiWRkJnpnj7+8d6been08vb7uud+qf5jZrrvOZ3zu+fed++754FlzKBoi6KnKfqiooeZ9seSEYqOcwP/mqLqvp5VtMW0b5YUcXv8qWWB97/OMe2jJQXcHn96jcB7rydM+2pJEDfwsxV9vU7gVdFViu5q2mdLAgRI9f5XSdGldvxvAnyBD9LjVdEBReeY9tsSEzfVz1F0bcDAq6LvKvpZ075bYuAGfm7IwKuifYpOMe2/JSIRUr3/9aqiB5j+ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLeft {
            get {
                return ResourceManager.GetString("PinkLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA9OSURBVHic7Z17lBTVmcB/X3XPe0BFFB8k8hARkFVmeoib3eTI6m72RGMSYHoYRJGIjom6Gh8wIIiJnmQ169HsqnvMY/VoorFBz8kxumd13fHsSXwxEFmXsCxZBHwQAR/gQE9Pd9W3fzTd08xMT1dXd1V3z9TvP2aq7neH+6vv3rq36pbgM2rQO9Vg5qZFwG0YtMvC0P9IqSvl4z4aiQRgShuwFjg7+UP9HdtCX/YFGMHonWowa9MClO+TavhMhOt8AUYgGokEkKmLUF3DUA3ff+TLvgAjCI1EAujUdkTXANOHPViIoH1X+gKMAHKm+gGHI9zL1ubVcqdYvgAVTEbD30WuKz5JDPRqCbc8kfqBL0AF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLightLeft {
            get {
                return ResourceManager.GetString("PinkLightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABEWSURBVHic7Z15lFTlmYef995e2TFARB0NqHEhbnQ1RKLHQdEYM4ZE7AJlIKOeE50s5hg9UYMGxigDYwZF42hEgnqSSN8CMxG3CBFPlDjSVYAQcEMUFBU3wAZ6rfvOH9VNdzVV3VW37tZQzz9wb333fb+u+6tv/94PALVWH66xxEJdXPc1ihxSGG3/3IvqlRiyXq34Ml2c+Hqw2SriF6JW/NvAkxk+W4XKXJlctczvTBXxD1Er/gowpps0q1CdTTTyjIioXxkr4g+i1rojofVJ4PQe0q4Fnc2myOMyS2w/MlfEewRAH321LxWtfwT9Tg7PbAHuod/AB+Si45u8zV4Rr5H2/6hlmcjIO1BuzPHZrcBd [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLightRight {
            get {
                return ResourceManager.GetString("PinkLightRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA2wSURBVHic7Z1rkBTVGYafs7OwLAii4gU1IhfLeIvGmBgvxBiRGI3BSkVjNBhLq4yJGkulvBZCjBIoExXUwki4lokR0BIlhQZKLYWytBRRvIsIIiIG4yIIe503P7oHpoeZ3Z7u05fd7adqf0xv9/lOz3nn69PfOd85AAjtJzRd6Egyuh9C84QklBd6Uuj7SdcpIyaEznIbv/RvqdDZSdcvI2KEXqoggGIhnClkkq5rRgQIHSD0WgcikNByoV8I1SRd5wzLCPURWuBDBBL6UOhqobqk651hEaGc0ESfIpDQGlcI9UnXPcMiQte6bwN+hfCp0Bih3ZKue4YlhC4Uaq5CBBLa7HqQPZOuf4YFhM4Q2lql [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkRight {
            get {
                return ResourceManager.GetString("PinkRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA6DSURBVHic7Z19kBT1mcc/PS+7A3tuAIXbXY0imwUBryKnlfPKC7cWVfHqTLxEc4mAL4AIGhUUFJd9YR9WLEO4mBzRpOCSVMq8WNlw+cuzLpor5qzbi6m6SCWKhEJ8Ac7dA3eBISs7uzvd98d0s83svHT3zHT3zPZn/5vt7ueper79PL/+vSoETBkECQF3Ak8AywX5o+KxTwEu0Etv+G3e/irQBVyj/9wHLA0EUMUIElJQ7tDQepgIvJmHwm47FVB+eukNX8u1K4CfAw8Cl+W4NBZkgCpCT/XLgU5gQaHL66lfFQigCrCQ6s1owDeAdkHUQAAVjCnwT1H4jQdIKij3d9P9Y+OHQAAVSC+94UMcWqGh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PurpleLeft {
            get {
                return ResourceManager.GetString("PurpleLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABCGSURBVHic7Z19lFTlfcc/z8wOy7KsLgSji2iFJSdlKcEkNiQnh4qnHmrN6+k50LRU2tqTg21Sc2IS0SI7v5mFdSkp+BoUy4vWJB5A24hWq9SXxJcTxXdcjAJVECEIC7jA7uzsvU//mJllZ5jZuXPnvi3cD3+w987z8pt7v/Pc331efo8CEOQ8YCmwUpBthJwxRLL/3w5cDbwpyGZBvuyjTSEeohIkvqbRjxT57HmFWhYnvtlzq0I8QwnyW+BLQ6R5HmgX5DFAe2NWiFeoJSw5v5/+R4CLy6R9DWgHHhLEdN+0EC9QAMtZXn+c478Avmkhzy6Fum0MY+66lmtT7poX4jYq98cGNkQ76VwKLLSY9wOF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PurpleRight {
            get {
                return ResourceManager.GetString("PurpleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAtNSURBVHic7Z17sFVVHcc/6/IUNMBQtFQQuyKv0WZIK3owk8M/Pcb+wCB5Kt0MNSxfVxMfxUxEMWpBCqkj0GAg1uRgU+QwyVjyB1FmmQh04RZRpg4gyH2eX3+ste/d93Ae+732OXd9ZvYMczhn/9a+v+/6/dZ7g6PfINAg8GWBPwlcZrs8jowQGGAc/3cBMddLAg22y+ZIEVPjZxU53n8tsV1GRwqYGn9dBcd71wu2y+pIEOP4uQKvV3G8CGwWOMN2mR0JECDU+6+CwAqX/+sAn+OD1HgRaBOYZ7vcjpiYUD9PYG9Ax4vAWwIft112RwyM4+eHdLwItApMtF1+R0QihHr/9ZrARbafwREBgYECCwTe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLeft {
            get {
                return ResourceManager.GetString("RedLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA6nSURBVHic7Z1rkBTXdcd/dx67KzYmAklod/XwCrIggVQWkeNSVWKSlFJRKrIUW7ZlQEgCCbGyJYEMFlp2d9iza2QFU3qYWEoh26mUlMQOxvniR1WkKE65yjGuik1cChCCRAAh7QaZFSxe2GFm+ubDdA8zsz0z3T0zPY/t38eZ231u1fn3uafPvbevImDGoEVCwHLgSWCFEvlvVeM+BfiA3r07zIEDnwNiwPXmzz8FlgUCaGK0SAilPo3WI1x0fDaPBgJoQvTu3WEOHlyO1oPYO97ijUAATYQZ6lcAg8CiEs13M3v26kAATYCDUJ/THPgq0K9EjEAADUyW479M6SceII5SD6uhoVetHwIBNCDmGL/S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLightLeft {
            get {
                return ResourceManager.GetString("RedLightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABB9SURBVHic7Z15kBzVfcc/b2aH1WolI2Gu5YrFyuWwBIvYxNjlUiEqxCE4Nq6kIIciJXEKi8Q2LmMbQYR2fjMrLavIkUAGc8jiCrbJgqkYQSCgcNgcZQPmkLLiEDKS0GEQKwkde07/8kfPand25+ju6WN21Z8qlXa6+73fb7q/897rd/yeAVCRE4GlwEojsoGYI4ZE/v8fAF8FXlORtSry2Qh9igkRo5nMF1F9qMi5ZzFmmUmn14buVUxoGBX5FfCZMtc8C7Qj8ogBDcmvmJAwumTJyQwOPgScXeHal4F24AEjYgXvWkwYGABdvryRgwd/AnzZQZrNGLOK6dNvMVdc0ResezFBY4b+0M7OJF1dS4GF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLightRight {
            get {
                return ResourceManager.GetString("RedLightRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA1PSURBVHic7Z17jBXVHcc/Z+8u6+6CoKUilchLY5VSlSo+qDZG3FqtYppiGi200cTS+orVqMVQqFUKaaviI1opCERjC2ik0lCFqLFaY2MRREAFrTxWRKHs8ljYZe/99Y8zl7139j5m5p6ZM7s7n+RmM3Nnzjlzz3d/c87vnPM7AAgcLzBP4Bsk9D4ElgiIQEbgRYFzbZcpISIELncq3/15Q+AK2+VLCBmBt4sIIFcIlwko22VNCAGBEwTeLSMCEVgt8EOBKttlTjCMQIPAMg8iEIGPBW4VqLVd7gSDCKQEZnkUgQh86gihznbZEwwi8EunN+BVCJ8J3CHQ13bZEwwhcK1Auw8RiECLY0GOtV3+BAMI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedRight {
            get {
                return ResourceManager.GetString("RedRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABDbSURBVHic7Z17cFzVfce/v7svvTGS/MQPGVl+QkJL03bahoRp02SAAJZWCzYGvLsyC2hXwibYsrHxkpBJwOUlP6jAthjTJNPFdtsh9UxCGWfaoUCZOhibggMUY4yfkqBaWbZ27z2//iFdeSWtdu9e7d2HdD//6e4553dG53t/53fPk2AyYQgGg9K1MyvuZOARWLDM6Q58RNmulInxhEIhi6X77B1M2ARgIQCA+c2jJ7tuMAUwjgkGg9KSmRV1RPgx1IaPgRmNpgDGIaFQyELhM3cSaCPiNPxl+A1TAOOIUChkkXrOLgPTRoAXJE7NIVEqrzQFMA5I5uqHwUT81JETXRuCwaAwBZDHXG54+knyNx4A [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TanLeft {
            get {
                return ResourceManager.GetString("TanLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABLLSURBVHic7Z17fJTVmcd/z3lnJiEJQUjkIopivdXLR3d1q23XorVatasoIaNbFmoufmIJhGLdtRYts1YQli7ITAKGZBKhavczmaFVtLrKCtbbp+1uUUG8IbeoIZiES0gImZnz7B+T24RMZuad9xac71/JO+c8zzMzvznvOc+5vAQAvvqqiYJ5iZDhVTNKF+xAmq8NAgBIsgfMxZLE+36vZ1Ogxn2N2YGlMQYK1Lp/xEQvDPHaW2BePrO0YpPhUaUxDAp4PX9m4FvDlHkLgpYW3FP+EhGxYZGlMQTyrV87WQRDL4BwRZyy24h46fb9bRtdLpc0JLo0ukMAsGHDiuxRwcxnCbg9gTq7wXBndfKTt1ZU [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TanRight {
            get {
                return ResourceManager.GetString("TanRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA5SSURBVHic7Z19cFXlncc/574kF1JTQGGTaBVJAwLuVLZO1x23bBxmaqe2bqt9EfAFEIlWBQXFkBfyI+K4lK3tstod2LazY1+cpmz/cp1d3R3uOputndnqtIqUQXwB1mTBBAiN5JLce/aPk8O9ua/nnHvvOefePJ+Z/HPznPP7zfy+z+95zvOqoZg+iASAO4DHgZWI/EHz2CWFG/T1BXn77W8B3cA1k7/2A8uVAKoZkQCadju63ksy8Kk8GHTbJ4UL9PUFufbaVcAvgAeAy3KUjKgMUE0YqX4l0AUsKlSa+vo1SgDVQOFUn4oOfAfoQCShBFDJJAP/JIVrPEAMTbuPnp6fmD8oAVQifX1BDh1aha53 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TurquoiseLeft {
            get {
                return ResourceManager.GetString("TurquoiseLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABBKSURBVHic7Z17kFTVncc/p3uaYRiQgWB0FF1hSGUZlmASNySVYsVai3XN5lFbBZtdFnbXrRTuJmsqJBFdZPrXPTAOIQs+g4/w0JjEAuJuBFdXWcXER0VRUXEwCiyCCEEcwOExPT19z/5xp2e6e/p5+74G7uefmXv7nnN+fe+3z/nd8/gdBYDIhcAyYBUiOwk4Zwj1/b0TuA54A5HNiHzRQ5sCXEQRi30Frbfk+ex5lFpONLrZdasCXEMh8jvgC0WueR5oQ+RxQLtjVoBbKJYuvZje3i3A5SWufQ1oAx5BxHDetAA3UACsWFHPqVO/AL5WRpq9KHUHY8bcww03JBy1LsBxVP9/GzaE6ehYBiwqM+17 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TurquoiseRight {
            get {
                return ResourceManager.GetString("TurquoiseRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAx6SURBVHic7Z15rF1VFYe/9drXFp4tBZGCMmOZG9QAcUSURBMUggORoS0gQ5HBImNBARGiiDQFpMhUw6ASEDFBIDKGGBRIqpQUChXUUqmoUOxraN9w77s//9jn9B0edzjn3DPc997+/upwz17r3vXba++zR/CMGyR1STpG0nOS9izbH09BSJoQBP4lDfOUpK6yffPkSFDjjxwR+Cinle2jJweCGn9sk8CHPFa2r54MCQI/W9LLLQIvSXdL2qxsnz0ZECPVR6lJulK+/R/9RAIfp8ZLUr+kOWX77WmTINXPkbQyZuAl6S1Jnyzbd08bBIGfmzDwkrRa0l5l++9JiZKn+igrJO1Y9nfwpEDSREnHSfpr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhiteLeft {
            get {
                return ResourceManager.GetString("WhiteLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA44SURBVHic7Z1/sJxVecc/z+4NN7khIUj4kWDFII4KUiioVCrjWIOlWIrjiG2lsR2cSWkRGJRBKIO5tUCT0SKJWihpCDBWJURHhU6AZISBpA5O+Rl+SLhJbghXjBJzI+Hm/tr99o/zLtlddve+++55f9zc9zOTP/a95z3P2T3fPO95n3POcwCQdIykVZLeT87UQ9I9cpQl3Svpj9NuU05CSPqkGrNR0nlpty8nZiQ91kQA1UI4V5Kl3dacGJB0rKQnJxCBJD0h6TOSCmm3OcczkmZK+kkIEUjSVkmXS+pOu905HpFUlLQ0pAgkqT8Qwoy0257jEUlfknsbCMuvJF0p6dC0257jCUkXShptQwSStFfO [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhiteRight {
            get {
                return ResourceManager.GetString("WhiteRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA37SURBVHic7Z17kFTVncc/v+55MQMI7kR01yQIjghIkOnbSG02KV2zyVaSNca8BJGHIhjRxajBAVE2ibW7mrJMdtVNzCblxjwqxN3aVBKrojG4qZUYpgcl7izL4ooQWbOKxhmBnp7uvmf/6L5NN9OPe2/3fXTP+VRRBbfvOb9T/L7ndx73PEAzaVCKiEqwQiV4TiU4H0CCLpTGe9QOoszhM8CdkHM8imcweL8WQAujFBGG+ATwRSzHl7JRC6AFUTuIMpcrUWyjvOPzL/KUFkALkXf88rzj59V4fQfjrNECaAFshPqS14F7ibFVBFMLoIkpcvyXqF3jAVIorpM4j1oPtACaELWDKOewAmEbcJ7NZG9g [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDarkLeft {
            get {
                return ResourceManager.GetString("YellowDarkLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA/DSURBVHic7Z19lFT1ecc/z8wuuyzvCVpQaxSwhhCK7M6Cop4cDCE2aSTH1iaNhfboOdHmxTTREzVo4BghUFMUkxQLIi/HNi0Q24gWIzR4osS6c4fXIEEICopIg7wtsK9zn/4xs+zMMLNz574v3M85nMPc/d3n+c3c7/29/54fANrEME2xVJN8kogLDzVYrQaqBqYarNUU1wadpwh/EDX4PPBCkb9tQpgvDaz1O1MR/iFq8AYwoYc0m1DmkmCdCOpXxiL8IUYVtwJbe0hzPcKLpEhpkr9UJeZX5iK8RwB0G/3o5N9QbrFwzz7gSQbxlFxFm7fZi/Aa6fqPriLOCOYA91u8dz/wOO0slkm0eJK7CM+R [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDarkRight {
            get {
                return ResourceManager.GetString("YellowDarkRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAv4SURBVHic7Z15jF1VHcc/v+ksMCOlIFJQoCwO0EIDmoILLhgIJigEF7SFrlBaZHGQdZBNtIm12hQQKhQwQCOkWDBBIMoWJKCYoEAqS6HYUh2rSElbKZ2Z9+b9/OPcO3Pn9S13v/e9OZ/k/cH03fP7PX7f8zvnnhUsYwZVWlQ5Q5UXVTk8a38sKaHKOCfwr6mizudZVVqy9s2SIE6NP70s8N7PeVn7aEkAp8afWSPw7ueJrH21xIgT+JmqvF4n8KrKKlV2zdpnSwz4SPXeT0mVxbb9bwI8gfdT41WVflVmZe23JSJOqp+lylqfgVdV3lXls1n7bomAE/jZAQOvqmxUZXLW/ltCEiLVez+vqnJA1r/B [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLeft {
            get {
                return ResourceManager.GetString("YellowLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB+CAYAAADsphmiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAP6gAAD+oBBD8C8gAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA9OSURBVHic7Z17cFz1dcc/Zx+SLNmWdiVjXgE/MYbQ0CbNpNPmQWGSToAEMLuyzMMYDOZZKCTGGINJoG0gZSAPSBySQoFCWBtmWoLbQihpZ1LCTAaS0IQSHNvYYAO2dyVhy1rtvff0j9Wunru6e3fv3Yfu5z+v7v2dMz7f3/n97u8JPtMG1TsCmkys0GTiNd2/5UQAqbZTPu6jmgiSohu4DThx+NefE3njM74AGhjVOwIkT16G6NfJB340co0vgAYkW+NlOegGJg187kFe9AXQQGQDrz0gG4AlxZ+WBIf0El8ADcDUqX7s4yD3EPntepE7LF8AdcyowN/JlDUegDTC5RKJP5b7wRdAHaKaCNLLCmAD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLightLeft {
            get {
                return ResourceManager.GetString("YellowLightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABDkSURBVHic7Z15lFTVncc/v/eqF/auhkZR1MHExDVknIwm43EcIzrRxGUiXWAIOsY50ZmMemJyjAYdGBcCGhecuKFEcRJDv2riRMQl4DLjNiZjQIi4IYIIolBV3Qj0+t5v/qhu6Gq6uqteva2hPudwDu/Vfb/f7Xrfuu++e3/3dwHQT60DNWM9qKnGYyizX2EAUMFdKJcgzmpNW0t0W+OJIderTECIpq1vAk/08dnLoHOldsqSoCtVJjhEM9ZrKCf0U+YlkNlSW/9UYLUqExiiqcXjEfsJYOIAZVegejO1bz0mMssJonJl/EcA9FNrODEeBc4u4Jr3gVuIZx4SubTD19qV8R3p/o+qZZKW2xG9osBr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLightRight {
            get {
                return ResourceManager.GetString("YellowLightRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAB9CAYAAABqMmsMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAPywAAD8sBRFDBggAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA2aSURBVHic7Z17jFTVHcc/Z5cFd0EEJeoqFXkYn1RLrdZXrRWp1VpMU63VYo0m1FatUYnPKNQqhdiqoAYr5RlbK6ARpUELEaMQo1FEUVF5yFPEYuXNsrDz7R/nLswMM7t37pz7mN37STZk7tx7fufO+fK75/7OOb8DgMThEhMkTiKl/SExXUISGYmXJL4fd51SIkLiYq/x8//mS1wSd/1SQkbirSICyBbCRRIm7rqmhIDEkRLvtSICSSyU+IVEVdx1TnGMRGeJmT5EIInlEjdLdIq73ikOkaiWGOVTBJJY6QmhNu66pzhE4lbvbcCvEL6QGCbRJe66pzhC4iqJxhJEIInNngc5OO76pzhA4kKJbSWK [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowRight {
            get {
                return ResourceManager.GetString("YellowRight", resourceCulture);
            }
        }
    }
}
