//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laavor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArrowDown {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArrowDown() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasePackage.Icons.ArrowDown", typeof(ArrowDown).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABQZSURBVHic7Z17kNTVlcc/txkGGIcRAZGHKL5AIsYH6q6PGOOjrHU1rrtlKqsbt5JgTMWsuxt1rawptUxS0ayrEmvVhBgjPlAUjfgABmcYEARRxIiAIoygjjxGYGBmmGEe/d0/zq/HnnZm+vn7/bqH/lR1od2/vr/bc885v3vPOfdcyqRLI9JvkAZT5MBAGhyRbh4kTSrZBycDFwH7kX6Jc51h96+Ij0gDgVujcPF+cCAdifQG0hqkG5Fc2H0s4hNSBOkWpPVOWoo0PvbBjUj1SCuRrg63l0V8QXJINyC9g7QD6Yb4D8d4EtGOVIN0cXg9LZJzbPCvQ3oTKeqkxUiHJl50PdIXSPucVIn0jXB6WyTn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQXQAAEF0BLpgRKgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABWJSURBVHic7Z1pkGNXeYafe3WlVmvtfXpvT5u2Dd6IDSTEwS6gWBIHigKcuAyu/MhGkVRCqpIQKj9TlSKpJJWloJKwBYoUUGYxYTdewB7wBIyN8bTxZMbMeLqne3pTa9eVdO89+fFJM2r1JnVLV1KPnqqumZ7RcqT7ft855zvvOZdgMHgMuBbQ6XK1oAPTQFDPZDI9wNuAKUBrabO6uIGGXOu3Af06sAIkgT8AJlrYsC7NRwMmgT8DUsBa+T8mgZPAHwEjLWlaFzcYBz4InCj9/TI+4HcQVbwD6He9aV2azRjwPqAI3Ad4qx8wDvwIWAJeD0TdbF2XpjIK3K9pWhZ4vPT7NrzAe3VdV16v9wzwWiDs [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABWRSURBVHic7Z1pkJzFecd/Pcces6tZLdKCQLcACyEJMLfK2AGCwdixy05Kdg4H46OwU7kqzpekbMdyKpXKUfmQSuwYu2JjG5sANhgLCxASErolxCGBJHQgdKB777nft7uffOjZ1bLaY3Z25p3Z1fyq9EEz79vdO/1/nn663+fthquknjslQo2Li+USBgkBEF8kf1rh5tQImJZF8jmAEIBO096yVP6usk2qERQtS+SfdY6O9304ZaFsbv2g/FGF2lQjIFpvkj+bslDWX/BF02y5t2WJJKbdLrcF36waQXDJLfLZ+GLxG2bLR4a8oPkq2TJ1qZy87B5ZEHDbapSZtg/J/S1LJd18pawd9qKGGXJX/FqR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAB0jSURBVHic7Z1ncFzXled/93VEzgAJBoAAI0BSEilKDoqWbEkjS6Zl0lrPlGbt2lmvyzO7n9a7VTPlWu+6amo2zKxrq+wt2+uxyxpbVsFyEG1RokgRJMVoggRJ5JxzajQ697tnPzTACCJ2NwLxq8IHdL937339/ve8e8899zyVWPKXj3h9ga1kpv2Oih+FWOMB4Os2il3PJ9ptlVavz78RxUsMu4LAEUAvdfPWiCWHLRSPfh7US96gHwOH8xzgxdBvsPXLn13q5q0RUxRF6gWEfwPaR0BdtDB0zUdWqYnwNVCJpO0eZKy6a6lbukYMKPry8yj5C5DdYHyP9rJqAwAtF1DqfUTewDAPUvz67iVu6hrR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDark {
            get {
                return ResourceManager.GetString("BlueDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABo2SURBVHic7Z15jJ3Vmaef89391ubyhjFgdhqFkOmAuwN0Zzoome4eRDqKurF6MtMoGU9TgWiQEilqqTV/1My0lFGP0pPVacgkMCwxVAUDNrGN8YZtsGMKHANmC2Djpba73/vt25k/vntxuagq31t1tyrXI10Jwa1zzuX7ve95z3vecz7x7BvyIt+i8+jNHO8XwmeRBU+/lMqnXuVSM0JGsSxiruTL1x7hMimlaPXgFmksUkpx4xEuk4Ivd0Cv0tnDmA/FqMM9j/+WS1o9wEUaiRRPvMKlns+3pU8pkSSl3HGtsByPHYT4YiTCVza9JFe2epiLNIZnX+PisMLXkKxNhNh5x7XCUgCiXYyLED9TJP/L [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLight {
            get {
                return ResourceManager.GetString("BlueLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABluSURBVHic7Z15lFXVne8/v3PurQEoiqGAYgYlqGgwGrWxX2LMS7KM3a99USlQu7XjI1IRbfu1a9n9b/350u/1S1byHArsaDSJgSvGQCKIzCgYh2BQAlUUUAxVUPNcdzpn/94f5xYUUMO9VXeqoj5rsVzee885+9T57n32/u3v/m157GW9JeyyqBDeXlsqUcYY9awuV3+b8G2/8pkVcpijcG+b8jeUqZXpwo2RWko2qN0i/DeF+0PCV6w8h/1At7F4dMUsvpPpAo6RQlRFmrkHZZVRgmLxR+u1p6UJYTPKUuDBlet0WabLOUZqWLGOb6nFQwrXWsLmwA+k2QJQ5UMRtio86irfW/my3pTpwo6RXJa/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSky {
            get {
                return ResourceManager.GetString("BlueSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABuMSURBVHic7Z17cBzXdea/c7t7ZoDBkyCJJ0mQIkXSkKjElNeJ43iVdVJO2VH2kVi1m611OU7KSiVV2kiWTMu7W5najWVJtKO1VZJDayUnjuPYkmPZliVSFF8iKZGmCVMiCT4hEXyBJIjXYDA9M919z9k/egCCBEDMAPMCiJ9qSAqY7ntn+run7+O7p+nJD51pMLVZMfSrlvcjIMY8c54IRNW2XWpxDNWn2A4GvJTcW7H20hJAqNiVmye/CISCa7qWOnD+ULFeoJLxVA8xDzF5n39i3cXmYldwnnwi9Hd3dLeYSj0obA5ZSbtHRbqWJ9kyXwfo40p7/2HjusuLi13NefLD395+oYk1/wmI1ptatj/Q [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABmMSURBVHic7Z15dF3Fnee/dd8qyZZXbCcGDNgJYQsJYLbOhCQEaNLpP+g0NJPOdiY5nek+ZzIdZroTYkxepyfpjpvuzISEDJAMYTNgJ2w23m0JY1m2jCxbtgSO5FW2tT695a5Vt6p+88eTiBct70lvk6zPOc/2u+/eqvK53/pV1a9+VYWf37sk8uTf3BjCFBcUq+6/PxADDOM769s57zW/UeoCTVFcetXBv4wB2gAAInnkFw9c+4MSl2mKIvHLv7rmX6Sw+866+IsvXVn35Ndu/HKJyjRFkXjyKzf+7eP3faRm8Lsx+A/fM38oPf7U09+45dbSFG2KQvPU15c+4HPv577wHh289oEAvvvW6S2Su/t9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABl9SURBVHic7Z15cBzXfee/v/e6ew5gZnCQIiGJkkVKWhfXtixH2vKlCFy5YtnZTbmyMTfrOFWpykFvtsxKKdZSpE3xccukZJSK2ohra0mr4mPjRJEc2VFkHbwwPETStLSkRJM+otg6lmR4gAQwd3e/99s/0E0NQYCYGcwFEJ8q/INB93uD/v5+/Y7ve482bNiwwBjTqbX+tVLKYI5Zj1JKALi+o6NjSDCzY4z5PcuyFjEztbpyczSW4BnfQET/MZfLdcvPfOYzpVwudwOAe9Pp9C/S6fRoqys5R8Mg3/evt237L5n5zZ6enkNi5cqVJcdxdgH49wA+o5S6ptW1nKMxKKX6HMf5nDHmQwB2rFy5siQA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABkQSURBVHic7Z17cFxXfce/v3Pu3adWq5VjOySkIU5EEiuJYmkVO0IBq0BDEqCEFAMB2jJ0yru0Mx36r6d/tUMpDB2YppQ3BWKHEAgkxrGj+G1rdy3HiV/xi/CIk9iyJe3j7t7H+fUP7XXW8kparXbvrmR9Zjye0e4959w93/O75/x+v3MuHThwYJVt2zcBeCIej1tYZMGTTCZ1Zn5XOBw+IEzTfDMz3yelvH/9+vWi0Y1bpL4wsySi9wohHsxms3cKZt4NIKeU+sT73ve+dze6gYvUD2amZDJ5LzN/ipkNy7L2idWrV48IIZ5k5jsAPJRKpdY0uqGL1IdkMvlOIcRHANwohHiyr6/vvAAAZt7LzJuY [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLight {
            get {
                return ResourceManager.GetString("GrayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABuPSURBVHic7Z15kCTVfec/v5dZ1df04BlxzAiGYUDgiDFiBMJhWwI8GIUlK1ZaaVdobf/hcOxhKRyx8oa8a0k4JMobllbGrGQJCy1CtuRrjW7EYmaYq5u5wAjECAZxCMQ1F/Qc3V1dVx7v7R9ZWZ1VlZlV1V3VXd3T346Kznz58uXLfN/f7/fe7/3ypXALFzDEKnxeIodmBcsfORRwETOcUgyTRfMhbDZgkMWu2wp6jKCNL0Z4H6tYY/EBKpTYgOG3GOc5xple7DquoGcQPC4iwx8DL7GWHyk+RgWbMeA3gA+Q4/xFruQKeoUc68nyu2iuwbCbj1FRAHhMAF9F+DzCO/lfrFncmq6g67iF9Sjej+HP [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAB1kSURBVHic7Z13bF3Xnec/597X2DspUYUUqUpKcpFlp7jGTmyPY8dxrHgzA88m2NlskJndvza7wAyCzW6AwWyZ2WCBZJFkMwniSRyDcYqVWLYsWc2qEUWqsPfey+MjX7/nt388UVZjf4Wk+AEEiHz3nHsu3/ece8r3/I4q+8vkB3wB79bsDH5X+SNCrLH6+Tr2UjfPOOzJ1Taf37tRwfMjboLAQUAnunxrxJADmKVjfB7F80G/F8Pp4gzgNTSvb/0yn010+daIKapE8azAv0HjCyjOm8OX8eWUYwl8DUVyxm6GxmvoTnRJ14g+JV/mGSX8BcJuDL7XUUGNAaCFc0rxngivGxYvl77G7kQXdo3osvVV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDark {
            get {
                return ResourceManager.GetString("GreenDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABjpSURBVHic7Z15bF3Zfd8/59z7Fr6Fj6tEUlwkSiMHmc0deamTeKaJ0cKt66ZAMokxqP9ymw6MFk2BLgjyZ4Gii2sUqT1IPMi4MQaJDSf2uHZmNLK2kWYRxqMZz8KJZkRJlEiRIvn2/d137zn94/JRJMXlPfJtpPgB+Af57nIe7/f87lm+53eM4EPBg2VfeYA0KUCzz/2AZJwRRrBlLp/z4eHLHGEEEK0u2T4NR3CEETRfJk+3RDIPpJH8Acc41OrS7dNQBEcZRvDvkWSARckkJSSn0HwBh9/mKAdaXcp9GsQnGETzFIJPYXKaSUoGAIMUgSLwTeAtwsyTotjKsu5TZ8YYRPPbwDcw+GPC/II51N0D [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkness {
            get {
                return ResourceManager.GetString("GreenDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABXBSURBVHic7d15kJ3Vmd/xz3t7lbpbsoQkEDIgFonFHoPBYIwNeLBljLENNssYnJkBj2dqklSmaipVSSqp1FQq+SOZcXlcTpxkXM5gY4yxMTbjBQ82mMUgtVpISEItCQlJSEJoAa29L/ee/HHula5a3erb3XfrVn+7VFru+573XL2/53nP+zzPOUdtqP0vgvWCOaY5MwjqBLfPDDMXErwiyAhWCGor3bdpSkxQI7hb8B3BZwg+IUhnf/2o0v2bpoQEieBzgqcE3xTMzX2wMusFBgX/vbK9nKZkBJ8W/ECwSbAs/4M/zHqAIOgT/FnlejlNSQg+mXX7g4K/F8waesDLWS+QERwTfL4yPZ2m6MTH/LeS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLight {
            get {
                return ResourceManager.GetString("GreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABYwSURBVHic7Z15lFTVncc/t6pXlgYEFMUFDUZJiEtckzjRSVxiYuYcJ8fEyT4TzcRkzMnkzJwzSYxhkslJZvTERBLUVkHFJYJxQ9mhkV0U2QRRWvatoXqp7e3v/eaP9xoa6KWq+tWr6qY/5/SBrnrv3Qv3+/vde3/3d+9D7h5fLY9cVskAJxUy47a4TCLm/3LPR+8scX0GiBi5d8LXgEABnrNdJk38eUlrNEBkyKSP/w4jmzj2w3svWCG/vezrJarTABEhv7nsLrnn/Ib232NHvtHSv8Ix6+V/rrq6JDUboOjIb6/4Kq7xIKZxb/tnRwSg7t+/EEvfgKu9JH+5aXxpqjhAsZDff+ZmbP1JHGOpum/P [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABkYSURBVHic7Z15cFzXdae/c1+jsYMAFwAktVgbKUGLZVtO5IwXcSwVJUokLWsEO3bkjCtTI8fjJDOpmtgTh8qT4tTYijJU2WXXME4cx/bYEeVFJLiJIsVNImUtpiyJIrWZEhcQJEhs3Vi6+7175o+HxkYsjUZvAPFV4R9097v39Tv39L3n/O65olse+gAJvZKW+ifk/vsTzDLj0XXriljYcivh0MsG37sIwx1c1LJCXdfku3OzZBddv95h0cm7EO4m7t1oSJTsx2oPVu/jJrkt3x2cJXuoqlD6+nLE/AmqvYT110Y+/dfncKQJ5AaUe3SLe3O+OzpLltj84CdBPotyBYYmud1tC1x+cfFziG4DvQ8r [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLight {
            get {
                return ResourceManager.GetString("OrangeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABJiSURBVHic7Z1pkJzFecd/vfdqpeXQYhRA6ECAxEoIkMQpA+GMCE4VcTnGNthOmVRMpeJKnORDglM5vrhi50MqsePER7AMAgswoAPdq5UWaSUtCAmJFYcW3bd2tcfc55MP3bP3zrwz+x4zs/Ormtpj3re7Z/r/PH093S8yR6plkVRSYkIhX5FyQcr0HzfJn3lcnhIuI/PkqwBaAXGOyHz5B09LVMI1pFF+SIDOof+8WXbKIvm6R2Uq4RKySJ6XG6V55BvXyCMyX/xyl9ztQblKuIAskT+RRonJdPni6BfcIDtlgZyVx2WOy2Ur4TBynyyT+RKSG6Rp7Isa5AG5RUQWymF5Wq5xsXwlHEQekaWyQHrl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABi/SURBVHic7Z1plFzFled/N97LzNpLJVHazdZgQMLIlkoGq2Ubje2DwWNkEEpsMHRzPGfodrunZ770fNXH2XrscR/7DMfjpb0gqQQYt2gQQkL7glRCMiAkVrHYCKHaq3J/L+58eJm1SFWlrKrcqlS/c/JIpzIzIl7GP+6LuPdGPNEnTnwO9a6jk6fl0ZYMM0x79LG2ELP1q5jaEwY/vRirdzLbuUs3bDDlbtwMxUVb1aFJ/j2Ye7CxzxpCehBDHLUPcdM3v1buBs5QPFRV0LY7QL8HmkAzLxm599YOrNkKeguGdbrp2G3lbugMRaK17SuI+TbwFxizVaKrOgOTL3oY0W2oPoSj39JNR28ub0tnKDS6 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLight {
            get {
                return ResourceManager.GetString("PinkLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABoLSURBVHic7Z15dFzVnee/971Xq6TybgzYGDAmDWEJASYBAjQEGhKmT5/uaZNMepI5fZI06ZkTZsKZxBiD/XI6ZNIeTjKHrY8hmbB1IDabMRjb2JaQFxwnBi/IAWw2CyRbu6reerff/FFVQra1lKTaJOvDkQ+qqvfur/S+93fv/d3fvZfdf879sdiUmL5t920Ck5w0rFq0yjyw+gABAO4/9/7vV9ieScrMQ+c99A0AMACAJH3w4AUP3lVZkyYpFw99/qH/LV3ZccyLD37uwe0rL135rQrZNEmZWHnpyn9+YOED9fnfjfz/iIxYLkP5yKNfevTLlTFtklLzyOWP3CoCcb8IxLL8a30C+FHLjzZJX+4V [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQSgAAEEoBNcinnwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABPhSURBVHic7Z1pbFzXdcd/b2Y43BdxkSiuEmXZlmXXqZfCbuq6aVq7sZMCcV0YqWM0QIq2SPsln9oUBQr0i4E0TZMAgdEkgOO4dhs4lmNHlS1ZsmTt3iXZcmVLtkSJIsWdwxlxmeWdfjh3NDMkhxwO571ZPD+AAMmZ996duf973rnnnHsfUlu7QWCLgIcynwkEPAI9ArUerl71Aw8D3QJWvhtXxllMH/cAXwHWeYARYBD4G6Azj20r4zCm87uAbwNBYDT+QqfAcYG/F1ifxzaWcRCBDoF/EDgk0JH8gl/gLwVCAl8VWJfHdpZxAIGNAn8rEBH4mkDFUm94Q2BI4AsCjXlqa5kcI9Au8JjArMBBgfal [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABfoSURBVHic7Z15kFxHfcc/v36zM3toV7e0kmwJ3dL6wBBITMJVAQpMUgRDDA4JSaikIkIIOaoSO5g1LWEKW5CYwgUVh0AIEBxLQExMbFm2rMuWjA9kbOuwLXttrfbW6tpzjte//PFmdmelPWZm59rVfqr2n5k3r/ttf/v3un/961+LbtnyJlTXUF9/n2zaFGeGaY/efXcF7e3vJRR61pBIXAZcR3v7B9VaU+rKzVBYdNs2j5aW3wWuJ5G4xlBZeQDVflQ/icj7Sl3BGQqHqgpHjrwfY/4M1QFUf2Hk85/vRuR+RK4GPqrWXlvqis5QIDZvfg8iNwKrgfvF2tOByY9EnkB1R9IKfFitvbKkFZ0h76i1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLight {
            get {
                return ResourceManager.GetString("RedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABtaSURBVHic7Z1plJzldef/93m3WnuRxKKFRYBDxgSYGJxgJ+Mx48nxHGxZA5g+c2xQEJ3QBDk9gQwm/jR1ZnImEydzMBIS7hBJBuOFBiRkgSSENiSBFIwss8mOgwEJkNDa6q6uetfn3vlQXa2W1Et1d23d6t85/UWqep+n6v0/t57lf+9LnSu/eyF0MrXvo6PvZTIZxhSTnkwmoz592cw5HnqOq7jh2Ao87+o5My4SgGrduSkqi4jQtZc0XqwC92tWlJimjumuI0S6B8R3r3ps8exad3CKikJrVi6bo9m4T5HqaezVR9TChRkPrF4U0JeE+L+ueuLR82vdyykqQ+fjj84KWX+DQNdFprX5pvZ2XwGA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABwWSURBVHic7Z1pkF3Fled/mfctte+LVJIooZ2SwcK0x9ggKMnqBozNZuPpaYdjxjE9g4Nx+INjbLpNCC4Cd2PZ3XaYcEfTnm473B3tNrinYbBZhJYnCa1IQmgrgZBK1L5vb3/v3sz5cKukklTLq6q3Val+EfXlvXsz89b757mZJ0+eFHlbttwa0noFCxa8wmOPxZln7vPii246OjbluVzHZciyFgP30dHxBUxTZrpt86SYl14yaG39IvBwyLLWSXJy9qN1CK2/jhB/nOn2zZNCtBacOXMPUv53tA6j9SGDHTvCbNhgI8Q3gDzq67vx+Voy3dZ5UoAQmxDia8AngJ9imqcdk+/1HkTrN4etwEOY5icy [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABnSSURBVHic7Z17cFzXfd+/v3Ofi90FsdjFYwECfIkgSAriyKM+4knTserJOFMnnnamjVs3j8mjmdidtHVSt25l6y1bUSQ/UtlWXNVu/KzrKrZsS7bjRLFjZ2zXCUXRJCiCACnCIkGBALHP+zzn1z+4F15SeOwu9gFA+MzskAPce+5vcX7ne875nd85l06ePPl7Usp/YRjGLxw9erSIHV5T6FLKfwrgZ4Mg+Bwzv4WIVKeN2qH1HD9+/LeklF8TzHxf5WdvPnHixCMdtWqHtnDixIk/APBxXdefpcoP/oKZ7wQApdTbX/e61320oxbu0DKOHz/+60T0JAChlPpdAQBSynuJCEQEXdc/+Pzzz7+hw3bu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABNtSURBVHic7Z1pbFzXdcd/l5v2fZdlR5a12KpkW7ZjO7YV23WcCElqB22DFA2QIGjTopuTFHbcFm0/9EOXoC2Quk7heHcqW7LsxLasyNRGipJIhRK1UKQoUaS47zs53IbDOf1wHiuKGnLeDN+8NzOaH0BInLfcO3z/c+695557nxF5YiYsCxqzx0+KmwaRb6YDpBmTOwTmOa8rlMJtMv/ImD2jafpLf7nI9//T2wqlcAuRP34VOpsnfPjd8yJ/+QOP6pTCJUR+8I8i3zkd4sDjvyPyoyGRH+3woF4pXEDkh38h8sOAyONPT3LCH5wTeb5T5J+2uVy3FDFG5MXviDw/LPKtwvGfp11/2pUfg38R+PaJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABezSURBVHic7Z35k1bVmcc/z73v0itNg+wiLqACKgpNRIKKxg01uGISM05iZWomMWaS+Q9S89vUVMpUppIqy5poNKPBLSYYRaRp9qUXaEAEZHNBkJ3ufvf3veeZH87b0A29vN39bt30p8qyqt97zj2X+z3nnvOc53mOaHPZLaQiU4H3pIYkwwx5tBE/yj2UlzU7JCKXoyzC5UH9NU6hGzdMblHFRXgYh8cIR252UDYCEQzP8F3uLXQDh8kdqgiN3I/yE5QoSbY4ciuncFiGchPwhDYxr9ANHSZHNPIdHL4PXIPDMpnPaTvkK5tRlqM8g/KoNnBDYVs6TLbRBhbi8CTK0zh8QIQtgP3mSw0tOLwHHEb4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDark {
            get {
                return ResourceManager.GetString("YellowDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQTQAAEE0BZ4wB4AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABeLSURBVHic7Z17kNxVlcc/5/5+3T09mSTzyCQhECAIaIlhXc2uj112pXTVShGzLmR0USktqmTLP9xy/7HKv2YfVW5ZBasoaGAVRZ4TCLDBMHlNQh4kIhgTILyiQIQ8JsnMZJ7d/fv97tk/ft2TmWQe3T3dv+6ZzLcqlaqe/t17+3e/59xzzzn3XNH+pxbh2zrmH3hLpNUyixkP1VZD9wcvIZM6bcikEwT+KnquWqqqUunBzaK8UFWhZ/lS0FXE5jQYGupOYGwvGv8mXQ9eXOkBzqJ8UEXoeuQSCL6D1T66kieNyMo01tuM8mkktlqPr19Y6YHOokwYfOoixL0ZZQXJ5Fa5amXaANAY78TIT8H8Nwn7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLight {
            get {
                return ResourceManager.GetString("YellowLight", resourceCulture);
            }
        }
    }
}
