//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laavor
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Subtraction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Subtraction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasePackage.Icons.Subtraction", typeof(Subtraction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAyfSURBVHic7Z1LjBxHGcd/Vf2YHe+u7cWPOMQQGwWEEoSIEBIyIEBCHBEccuOEFBnOnBFWLkhwg0MOYIkTisiNO4cICXGxCYGExAmLCYnXjr1e787u9PSrisPXtdPz2F2vZ2Z3cddPKvVjZ7rb/f/XV19Vt2sU+8Raq/b7nTpKKTvJ9z3T5aHFHCP8oxhhQHxvhsNnTxGHhJ/EBMNib297IxweuwpYE3+cCcb9bcdDMWgAO7T0JjgkdhTPif/qq69qgDNnziiAxcVF1W63FUAcxyoMQwXglo6iKGx9mWWZBUiSxHY6HXv37t1twd966y0LcOXKFW+C6bPrPR1rgCtXrmiAZ599VgGsra3pNE11URR6 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO8AAADvABseq4VwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA3fSURBVHic7Z1Nc9vGf8c/iycSJJWIlmTHkWLHlxycQ/+9ddx2pqfceughLyGvoadMfO27yKmTmVx77C3tTC7JTJzYkT2xnDi2JVmkKIoE8bjYHkBAICnJtkg9NNjPzM4CILGA8P3ubxdLaCF4R5RS4l33KSOEUPPsr1ksby3mMcKfxQgT4mszXD5vFHFK+HlMMC12sa6NcHmcKmBJ/ONMcNxnJxbFpAHUVK5NcEmcKF4u/rfffmsArK2tCYClpSXhuq4AcBxHWJYlAPI8J0kSVc6jKFIAvu+rwWCg9vb2CsEfPXqkAO7fv69NsHhOvabHGuD+/fsGwN27dwVAr9czwjA0kiQxms2mAGi320atVhO2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQJgAAECYBg7ZMFQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA0wSURBVHic7Z3NjxzHeYef6q+Z2dkVd7Vc0rQIigSMAJECREYQILbhQ4AgJyO6RDByMuLkEMMHx3+AAR5yigEfnItPSXQKHN1y8SFADPikBGBkWSZNEdBKoiTuLndmv2ZnevqrKod3aqfni0vuzu4y7HqAYk33TncP+/ert96q7ulRPCPGGPWs25RRSpnTbO+YL08t5hThT2KEEfGdGS6eY0UcE/40JhgX+2jZGeHieKKAJfGnmWDa32builEDmLHameCCmCmeFf+dd97xANbW1hTA0tKSajQaCiCKIhUEgQKwtSXPc1Ou0zQ1AHEcm06nY7a3t48Ev3fvngG4ffu2M8H8eeI5nWqA27dvewCvvfaa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA80SURBVHic7Z3LjyRHXsc/EfmqVz9quudlz67XWliQbV4+oV0EBySOCAksjntCHEAcuSHmwIm/ghNCWFwQ15VYIdBK4NWuwfZ4bPd47Jl+TFd1vSufEcEhK6uyu6vHM9PV3bOT8ZmJyYqszuyc/H7j94uIrMoUPCfGGPG825QRQpjzbG9ZLc8s5hLhX8QIx8S3Zrh6vlHEE8KfxwQnxZ7XrRGujqcKWBJ/mQmWvXfmrjhuAHNiaU1wRZwpXiH++++/LwGuX78uANbW1kS9XhcAvu8L13UFQLEsyLLMlJdJkhiAMAzNaDQyh4eHc8E//vhjA3D37l1rgtXz1HO61AB3796VAG+99ZYA6PV6Mo5jmWWZ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDark {
            get {
                return ResourceManager.GetString("BlueDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAzeSURBVHic7Z1fjCTHXcc/Vf1nZm727DvufNjGKBcDinWOAPNHIIf/QhFSpAgi/JaniMjJM3nggYcTD4kESEjwECngBxAChCOR8ICQRSL5JW82UZAdYkfrw8S3d9yt93ZnZ3r6T9WPh+qa6ZmdWd/uzP5Ruj5Subp7unvG/f3Wr35VM1erOCIioo56TROllKxyfWC9PLSYC4Q/jhFmxA9mOHs+UMQ54VcxwbzYk/1ghLPjUAEb4i8ywaLXlt6KWQPIXB1McEYsFc+L//LLL2uAxx57TAFcvHhR9Xo9BZCmqYrjWAH42lNVlTTroigEIMsyGQwGcu/evYngb775pgDcvHkzmGD9HPpMFxrg5s2bGuDG [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLight {
            get {
                return ResourceManager.GetString("BlueLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA2ESURBVHic7Z1LjCRHWoC/iHzVo7un29Nje8HgMbuGXRsBi4VAu2AWsTckBFrNaTkhIYM4cuE4QiAkuMHBB/ANLQjfkLggWWJXawQSNstKNjA27RnbM93jftcrKx8RwSEyq7IePdM9Vf1gMz4plY+qzMrO/4s/HlmdJTgjxhhx1n2qCCHMIvs7lsupgzkn8E8iwkTwnQyXz2ODOBX4RSSYDvZo3YlweTwygJXgz5Ng3msnHopJAczU3ElwSZwYvDL4b775pgS4ceOGAFhdXRXNZlMAhGEofN8XAOW8JM9zU52naWoA4jg23W7X7O7ujgL+/vvvG4Dbt287CZbPI6/pXAFu374tAV566SUBcHh4KJMk [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSky {
            get {
                return ResourceManager.GetString("BlueSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA6ISURBVHic7Z1LjCRHWsd/Efmq6urH9Iw9fg1eWxYSsi3AHCyzi7QckDggrWCFT6y4rUCICzfEabQXJLghceHGCvFYC2mFQOLCAZDY1SJLq2VtYa/cntXY0z2PflZX5TPi4xCZVVndNW3PVHX34IyfFM5HZWan8/+PLyK+rIlSPCIioh71nDZKKVnkfM9y+dxizhH+cYwwI743w+XzmSKeEH4RE5wUe7LtjXB5nClgS/x5Jpj32UMvxawB5MTSm+CSeKh4jfjvvPOOBnj66acVwNramur3+wogjmMVhqECaJYNVVVJe1kUhQCkaSrD4VDu378/Efz9998XgJs3b3oTLJ8zn+lcA9y8eVMDvPrqqwpg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA8dSURBVHic7Z3LjxtHfsc/VdXdbJLzot62bK+8hwSwN9m8EAS7ARzksECAYJEA8X+wSQ655xZE59xyzSnIIQji2/oSBMhhkSAJFrCz67W9srweS7YlzWiGM8PhkP2qRw7dzSFnKMnScGa06vpArepush/g91u/X1U1pyh4Spxz4mmPmUYI4U5yvGexfG0x5wj/LEaYEd+b4fx5oohHhD+JCY6KPdn2Rjg/HivglPjzTDDvtUeeilkDuCOlN8E58UjxavHfeecdCXD58mUBsLy8LNrttgCIokgEQSAA6rJGa+2myzzPHUCSJG44HLqtra2J4B9//LEDuHnzpjfB4nnsZzrXADdv3pQAb7zxhgDY3d2V [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQGAAAEBgB/AMxtQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAzQSURBVHic7Z1NbxvHGcf/Mzv7whdZlFvHiI0aSnopnABtYcBAc4gPCXLIpSd/h36Cnn3uR8i9h8LHAMmtvQQoIMSwUcRBmgJqC1iWVIsiKXJfZndeetid1XJFyZZIkYp3fsBguEvucKX/f5/n2SU5S3BOtNbkvNtUIYToeba3LJY3FnOG8BcxwpT41gyr57Ui1oSfxwR1sctla4TVcaaAFfFnmWDWc6cOhWkD6FpvTbAiThXPiP/48WMKADdu3CAAsLa2RlqtFgEAz/MIY4wAgOkNQghd7dM01QAQx7Eej8f61atXpeDff/+9BoBHjx5ZEyyeM/+nMw3w6NEjCgB3794lADAYDCjnnAohaKfTIQCw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAviSURBVHic7Z1LixzXGYbfc+rS3eqRPcPIjmeiEGURDLIIkTE44ECyNBhCEPbOW5M/oKUXWmkRL/wbDCaGWGA5S0MW2WRnE2Is25IZOcbSjDIajTQ93XU7lyyqvprq6uq59WUmOt8Dh1NV03WZet/znUtXnxI4ItZacdR9qggh7CT7M9Pl0GI2CH8cIwyJz2Y4eQ4UsSb8JCaoi12usxFOjn0FrIjfZIKmv409FIYNYGs5m+CEGCseif/xxx9LAHjuuecEAJw9e1Z0Oh0BAGEYCt/3BQBQTiilbDVP09QCQBRFttfr2c3NzVLwW7duWQC4du0am2D67HtPGw1w7do1CQAXL14UALC9vS2TJJFKKdnt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLight {
            get {
                return ResourceManager.GetString("GrayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAANtAAADbQBgpje6AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA6qSURBVHic7Z3LbxxHfsc/VdXd86TEkShrZckP5bAHG8FuEGwQOI9d5LAIEOwhB/8J/htyWqyuOeacyyKHYAMfggBJLsnNG2ATw0b8XMmw6bVsiZI4Q3I4nOlXPXLo6WHPcChZ4pBi3PUhCtXdw+pu9Pdbv3rMTI3gKXHOiactU0UI4U5S3rNavrWYS4R/FiPMie/N8Px5oogLwp/EBItiz/a9EZ4fjxWwIv4yEyx77dhTMW8At5B7EzwnjhWvFP/tt9+WAFeuXBEAa2trotVqCYAoikQQBAKgzEu01q6aZ1nmAOI4dqPRyG1vb88E//TTTx3ArVu3vAlWz2Of6VID3Lp1SwK89tprAmB3d1emaSq1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA9KSURBVHic7Z3LjyRHXsc/EfmqVz9quudle+21FhZkm5dPaBfBAYkjQgKLIyfEAcSRG2IOnPgrOCGExQVxXYkVAq0EXu0abI/Hnh6PPdOP6a6ud2XlIyI4ZGZVdnf1jGequnuYjI8UnZWZlVGh/H7jF4+sjhI8J8YY8bzXlBFCmGWut6yWby3mAuFfxAgnxLdmuHqeKeIp4ZcxwWmxZ/vWCFfHUwUsib/IBIvOnZsVJw1gTm2tCa6Ic8UrxP/www8lwPXr1wXA2tqaqNfrAsD3feG6rgAotgVpmpryNo5jAxCGoRkOh+bw8HAm+KeffmoA7ty5Y02wep56Txca4M6dOxLgnXfeEQDdbldGUSTTNJXN [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDark {
            get {
                return ResourceManager.GetString("GreenDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA7pSURBVHic7Z3LjxvJfcc/Vf3iazTDnZmVtNJqV4f4sGsEiU/BOkhuPgY5ZJFjTkYuQY65GdY5f4VPgZFFLoavORgGAgPBGvba2h3Jq9GuVponOSSHQzb7UVU5NJtsznBGj+E8oq6PVKjuJrvY6u+3fvUgVS14TYwx4nXPKSKEMOc537JYXlnMOcK/iRFmxLdmuHpeKuIx4c9jguNiT/atEa6OMwUsiD/PBPNeO7UoZg1gjuXWBFfEqeLl4n/22WcSYH19XQAsLS2JarUqAHzfF67rCoA8z0nT1BTzOI4NQBiGpt/vm/39/YngX375pQF48OCBNcHiOfOezjXAgwcPJMBHH30kADqdjoyiSKZpKuv1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkness {
            get {
                return ResourceManager.GetString("GreenDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA12SURBVHic7Z1LbBzJfYe/6ucMh5Q4S+oVyVopCIxAGwQxggCBHCAJEPgYJIe95RRgsc45Z8NCLgGSW3zwwVnAFxuL7C33HBYGAl92Y8uWTMlrSiuv+BBnSA7n0dOPqsqhH+x5kHrM8GF1fYVCdfdMdxf796t/VdcMewSvidZavO4+ZYQQepb9DfPllcWcIvybGGFEfGOGs+elIo4JP4sJxsUu1o0Rzo5jBSyJP80E01478lCMGkCPlcYEZ8SR4uXif/LJJxbApUuXBMDS0pKo1+sCwPM84TiOAMjLnCRJdLmMokgDBEGgu92u3tnZKQR/+PChBrh3754xwfw59ppONcC9e/csgDt37giAvb09KwxD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLight {
            get {
                return ResourceManager.GetString("GreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQJgAAECYBg7ZMFQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA32SURBVHic7Z1LjCTJWcd/EfmqV890zfTs7HpmvbOABewiY9AiLC8IBD4iGyGtuCAhkNByQ0hckUZckOAIFwuD4IIQe0Bw4YA42ELIl8H22rOzOyv3rtcz3T3b3dPd9crKR0RwiMyqrOrq2e3u6u7xZPykmHxUZ1ZN/v/xxRcRVZmCY2KMEcc9pooQwpzmeMdy+dRiLhD+JEaYEd+Z4eL5RBHnhD+NCebFnmw7I1wcTxSwIv4iEyx67chTMWsAM7d0JrggjhSvFP+tt96SANeuXRMAKysrotlsCoAwDIXv+wKgXJbkeW6qyzRNDUAcx6bf75vt7e2J4O+8844BuH37tjPB8nniNV1ogNu3b0uAV155 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA04SURBVHic7Z3LjyzXXcc/59Srex733omfONfxTcAQ2QESAgglICcSCmSDYOENYoWCDGKDxD9wxSYSLBBEIhLgDQuEsNgEpBAQSEEIUCRfTBRbwsaDTeyZe3Nn7jx6uqvrcc6Pxanqrn7M2DPd84jrfKSjU++uqe/3/M6jpk8rTomIqNOe00QpJYuc71ku71vMOcKfxQgT4nszXD7vKeKU8IuYYFrs0bo3wuVxooAN8eeZYN6+Yy/FpAFkKvcmuCSOFa8W/6WXXtIAjzzyiAJYX19X3W5XAcRxrMIwVAB1XlOWpTTzPM8FIE1T6fV6cv/+/ZHgr732mgDcvn3bm2D5nPhM5xrg9u3bGuCZZ55RAHt7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLight {
            get {
                return ResourceManager.GetString("OrangeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQJgAAECYBg7ZMFQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAywSURBVHic7Z1LiBzHGcd/Vf2YHe2upI0kP2LFlowDxg7BMTYEOybB+BiSEDC5GAIGI99CwNeA8MWQHO2L8QNyCSa+5ZJTDs4h5CI/Y8eWyNpxZO3K0mq1O7vT0zPdVTl8XTs9r5VX27O7qOsHRU/3TlfP9v9fX31V3dOj2CHWWrXTfcoopexu9vdUyzcWc4zwN2OEAfG9GfafG4o4JPxuTDAs9ta6N8L+sa2AJfHHmWDc3yZWxaAB7NDSm2CfmCieE//tt9/WACdOnFAA8/PzqtlsKoA4jlUYhgrALR1ZltnystvtWoAkSWyr1bJXrlzZEvyTTz6xAGfPnvUmqJ5tz+lYA5w9e1YDPPDAAwpgdXVV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAzpSURBVHic7Z1NjBzHeYafqurumdlZSmRI0ZKiwLSSwAJlxFF+kEDOPwIjQIAgMaybT0YMJef4kEMORA42kBgIkBwM2NEhgREbkYHYOQSBEBvQxTcphgPJtmSsGNnikiFXy93ZmZ7+qfpyqO6ZntnZpXZn9sfueoBidfd09wz7feurr2qGRcURERF11GuaKKVkmesDq+U9i7lA+OMYYUb8YIaz54Eizgm/jAnmxZ7sByOcHYcK2BB/kQkWvXbgrZg1gMzVwQRnxIHi1eK/+OKLGuCRRx5RABcuXFC9Xk8BJEmioihSAHVdU5alNOs8zwUgTVMZDAZy9+7dieCvv/66ANy4cSOYYPUc+kwXGuDGjRsa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLight {
            get {
                return ResourceManager.GetString("PinkLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQYAAAEGAB/JRN5wAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA6dSURBVHic7Z3LjxzHfcc/Vd3V0/PYF7mUIpGUKQfIQYIhB4aMwEkgwYfAMKBDDvoT/DfkFITXHH32JfAhiKGTgfjk3OwAsQkajiwpkmCvIoXkct87OzvTr3rk0NOzM7OzfM3sLsWuD1Dox0zX9Pb3W796dHet4ClxzomnPWYcIYSb53jPYnliMWcI/yxGmBDfm+HyeayIU8LPY4JpsUfb3giXxyMFHBN/lglmfXZmVkwawE0tvQkuiTPFq8T/4IMPJMC1a9cEwNLSkmg2mwIgiiIRhqEAqJYVWms3vszz3AEkSeJ6vZ7b2dkZCf7JJ584gNu3b3sTLJ5HXtOZBrh9+7YEeOONNwTAwcGBzLJMaq1l [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQYAAAEGAB/JRN5wAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA04SURBVHic7Z3LbxxHfsc/1a+ZIYcWuRJt05JlCQkcQD5kE+QFJwsEQbC3HBLAlxwXMBIguQc5LKxTgP0DFrtG9rALBMECvuaYmxFg4cAGdm1ptYpFr2VZJM3ncDjs6VdVDr+pmZ4HSYkzfEBdH6BQ3TPTD/b3W79fdU2zRvGcGGPU825TRillptneMVueWcwJwp/GCEPiOzNcPCeKOCL8NCYYFbu/7oxwcRwrYEn8SSaY9N6Ru2LYAGakdia4II4Uz4r/wQcfeADLy8sKYGFhQTUaDQUQRZEKgkAB2NqS57kp12maGoA4jk273Tabm5t9we/fv28A7t6960wwe469phMNcPfuXQ/gzp07CmB3d9dL [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAyvSURBVHic7Z3LjxxHHce/Vf2a177iOITExk4ECkoIIg8ilIASJBQpFwSH3DihoMCZf8DiggSnwCFSIJccEMK35JILh0gRkSzZOJETCQctMbJ37exzdnamp7vrweHXNdPT27v2enofuOojlWq6Z7qnt7/f+tWvamZqGfaJ1prt95gijDE9zfGOerljMSuEvxsjTIjvzHD03FbEkvDTmKAs9mjbGeHo2FPAgvhVJqh6btdTYdIAulQ7ExwRu4pnxD9//jwHgJMnTzIAmJmZYc1mkwFAGIbM930GAKY2CCF0sU7TVANAHMe61+vplZWVkeCfffaZBoBz5845E9TPnve00gDnzp3jAPD4448zANjY2OBJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLight {
            get {
                return ResourceManager.GetString("RedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA4wSURBVHic7Z3Lj2XHXcc/VXUe99XtGU88tsFJbIjlZAZBLBQUxYgEKQvYRLDwIht2Ef8AEhsWI3YkaxYgNhYSClgCwQYTCJFJYoWFEUKyI41F24PtmR7P9PP2vedVDxZ1zu1zu2/3ZKZvPzKnPlL1edx7zj19vt/61a+q+9YRPCTOOfGwx7QRQriTHB9YLj+zmAuEfxQjzIkfzHD+PFDEA8KfxAQHxZ5tByOcH8cK2BJ/kQkWvXbkqZg3gDuwDCY4J44UrxH/9ddflwBPPfWUAFhZWRH9fl8AJEkioigSAM2yQWvt2suyLB1AlmVuPB67e/fuzQR/9913HcCNGzeCCZbPsfd0oQFu3LghAa5duyYA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA6DSURBVHic7Z3JjyPXfYC/96pesbh091Azo220jAwkBiQ7SGzDCOwAMnwQYMAIcoj+BCP/QW5B5pybrz4FPgRBdJMvvuQQxIgDARpIiqRISjyyFM309PTCZrPJYlW9JYeqYlez2bOR3T1WvQ8o1EJWsVi/7/3eQrIoeEScc+JR96kjhHDL7O9ZLQ8dzAWBfxwRjgXfy3DxPDCIc4FfRoL5YM/WvQgXx30DWAv+IgkWPXbqoTgugJubewkuiFODVwX/rbfekgBXr14VAGtra6LdbguAKIpEGIYCoJpXaK1dfZ5lmQNIksSNRiO3vb09C/jHH3/sAG7cuOElWD33vaYLBbhx44YEePXVVwXAYDCQaZpK [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA3RSURBVHic7Z3NbxxFn4Cfqv6aT3+NY2dDEkxgiUkgLEJIC++iXSTOq5cDN05IKHDmH4i4IO3e4JAD5LpCy23ve0BCe0tASCAFUBKCHTthxuPxeKanZ7qr9tDT7bY98ZvE44+Xrkcq98e4e9r+PfWrqp6ZGsFjorUWj3tMFiGE3s/xhvHyyMEcEfgnEWFb8I0MR8/fDOKOwO9Hgp3BTreNCEfHngHMBH+UBKMee+ip2C6A3rE0EhwRDw1eEvyvv/5aApw4cUIAVKtVUSwWBYDrusK2bQGQLBPCMNTZZb/f1wC+7+t2u63/+OOPNOA//fSTBrhy5YqRYPzs+T8dKcCVK1ckwIULFwRAs9mUQRDIMAxl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAQYAAAEGAB/JRN5wAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA5BSURBVHic7Z3fa2RHdoC/U/dXt3pamtZ4ZqWNbK3jNXYkYoMDBu8SvIEhsFkWFjYMgRAIJDhvyWMeRf8LeUr8EAIhhDxtIHkJ5GH95CSwJNmdnl2WsR3ZsjUezagltVqtvvdWnTxUt6TRaOzxqPWDvfVBo25JXd3S+erUqbpSlfBkRFUPHrTbbQHodDryBc8JXDDLy8sKsLKychA8EQHQk77/pGAeBH4UdDM/Py+tVkvu3bsnAJubm7K4uAhAt9sNQlwgrVZLAVZXV5mdnVWAubk57Xa7ur6+roAbyyAij0lwPHiiqgeBX1paMmtra1GWZZG11jSbTdPtdk2apgLQbDbP9IcLPB29Xg+APM+11Wq5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA24SURBVHic7Z1LjBxJWsd/EfmoKlf3uBu/dzweG+2i0cyCGFZIaHYRrIQ4suxhxGVPK60GJG5cEBLC4oIAcQGhPcBIXEArBiENe+DEYYWEuMywePEwY+/0eGZttz39cnd1dVY+Ij4OkVmdVV3ddruqu40zflIoK6sqH53/f3zxRWRWtOKQiIg67DZ1lFIyzfae2fLEYk4Q/mmMMCK+N8PJ81gRx4SfxgTjYg/XvRFOjgMFrIk/yQSTPtt3V4waQMaW3gQnxL7iVeK/8847GuDcuXMKYH5+XnU6HQUQx7EKw1ABVMuKoiikvsyyTACSJJFerycrKytDwT/44AMBuH79ujfB7Dnwmk40wPXr1zXAq6++ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDark {
            get {
                return ResourceManager.GetString("YellowDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAO6wAADusBcc2BlQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAzESURBVHic7Z1NjCTJVcd/EflRVd09X+zOeFkv7HqNYZm1bAwCWQsGjJCPyBxWQkJIaGW04gY3S1xGXCwZDmAOFja2LCMhxF4AIQSWjfAB38ZeLHYtD1bvyPbOBzO9Pd3VXVmZlRmPQ0RUZWVV9c50VXW3N+MnRedHVWRm5/vHey8iq6IUj4iIqEetU0cpJcvUD6yWhzbmHMMfRwhTxg9iOH3e1ogNwy8jgqaxx9tBCKfHkQasGX+eCOa9tvBQTAtAGssgglNiofG88V955RUNcPnyZQVw7tw51ev1FECapiqOYwXgl56yLKW+LIpCALIsk36/L/fu3Rsb/PXXXxeAa9euBRGsniPv6VwBXLt2TQNc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLight {
            get {
                return ResourceManager.GetString("YellowLight", resourceCulture);
            }
        }
    }
}
