//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laavor
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SwitchFit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SwitchFit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasePackage.Switches.SwitchFit", typeof(SwitchFit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAycSURBVHic7Zx5bBzVHcc/M7OztnfX+IoJJMEmEYRwNjQmHImBAOFoCAlIkFStkDj+AVXikJCQKAXR0CI1Qi0SQkEqiEIiKs5CSwKItIgiEsBQQkhCHBM7PtfxtV6v13vMvP7x9nnHk7W9CcSzTvKVRnPse7O/N7/j/ebN7/fTOHJojr02zrn7t+MBucaq5djn85wEYGc2y7W3M21sR9ufhNh82yuCdcfefay72uS6x7GK8RTEYOxzUec64GPss7KBNJACkkAic66upckKhHBsh03k4Q5IEewk3swMwAQMVq+u5PrrayktDWGaQQAsS8e2NYTI/q/7/EdDz94XQx4LTd7fznO8uuMhakLIZwzousgq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAArWSURBVHic7Zzfb1xHFcc/99696/WPjX8kboPj0FKkRCFRKLQJCSINVKIIXlocYVqp8kP7xB+QpwKKxI8KiZeqElGlBomHRJVS1IpSkKgaGvFQZMXgSraTujXxryR2kt14vb9/3eFh7nhnb3fX6zTeu5v6K13fHzv3+sycM2fOnJlzDO4ehnY2qtx7f/sioFJdjQrnetpJAI57FD1nxy3jaGXvCbH1llcEm9rZe216ylT6xv2Kah3Eorxd1L0JBChvKwcoAHkgB2Tde/WsQEkghHZsmMiNVkgRrBNvuxWw3ed9wENAF9DpvqsqV0mQ7hFM7buWemaUn9eDI8qvi+pGlDpc3cToHUVntIVsK9Veivkd [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAvGSURBVHic7Zx7bBzFHcc/u3t7ts/n+JGYhDxJVJIAgYYmhKQkPAuUUkqIRBJUhMTjHyok2kqRKlEKolAqgSqoVKFUKoinggLlVQg0agqiFSHEvJo4TxO/H4nt+Hw+n++xN/1jdnzjzdm+BOM9J/5Ko93bm9n9zf4e89uZ3/wMTh2GdjSG+e3970xArr4aOY75vCcBZNzieI4Zt05GqzsmxOZbXxFsakfvuempk+sepyuGUxCLoe9F/TaBAEPfVQZIAykgCSTc3+pamqxACK2cNJEn2yFFsE687XbAltfXVsGP50FZGOxS2dQxIWOA0J7r/f1tYWr3tRTJuYRvJGgvUQj5jgFMkVW4fKD31zEhZULG [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAyLSURBVHic7Zx7jFxVHcc/9znPfcy228e2gLVQLBQQESgEqZoo4iuACWo0xIAmikYTExMTwWh8JEZj9A8lRjHRxEdE41sSH1W0KiLlJaV0l2233e6zO7M7uzNzZ+Y+jn+cOTt3LrPdaWlnZku/yc05d/fcO79zf7/zO7/zO7/z0zh9aKFSW+E++r+XA5r1VWtStvKdBBDULj9SBrU2QajtGSG21faKYD1URut6pE2zd5yrWGmAGDR+F3WvAyaN3yoAPMAFqkCldq/+5lEXCBG6TpnIU+2QIjhMvFXrgAUYpLYMEN98EYaZRtNTAIig1jlR/10RuX/JMNSLNUkWgK41lqshEI11Ncg0Ib93qxCyv0Jo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDark {
            get {
                return ResourceManager.GetString("BlueDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFVQAABVUBJRnLvQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA3QSURBVHic7Zx7cFzVfcc/d+/efa+0u5IsW0IyNsaPOMb4gQlgp6bEUEIekPJIp007pHQa2g510zJ9JEAmQNPOME0mSdOh0ybNNJBMJoROm7GhacK0jhNDMNjGjjGSbVlrrbR67vtxd++9/ePu2b26rKS1sbWyre/MnXP36pyr37m/3/n9fuec3/lJnD8kSynN8Nv+tysB9foq1Skb+U4GoFcuzVbqlTq6pe4FIbbR+oJgh6W03ztsdeq943LFTANEZvp3Eb8dgJPp30oHykAJUIFi5bd4VqYmEIblOmciz7VDgmAr8UqlAwog37Dz7sjGW35judcbDDhlxQ+gaZrDMHTJMIzq/7X/fu9wmO/Vdckk [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLight {
            get {
                return ResourceManager.GetString("BlueLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFVQAABVUBJRnLvQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA2JSURBVHic7ZxpjBzHdcd/fc7szOwxu9xdLU/xWpGUaJIhJVISKZpmaFlhJFFJLPmTgThMEDsJnAMGgiSSA0fOJ8EBjNiBncSBk9hIANsB7MRUEkixJdMhJVMyKVI8Vlwuuefs7szu3Fd3Vz701Exvcy8y0s7w+AONPqaq51W/f72qrn7vKdw8FM9emePc/9udgNnaqsyyX8xzEoBT2Wzf3qmUcTxl3xdhF1teCqx69v5j1Vdmtnvcrpirg2jMfC7yXAV0Zj4rB7CAMlACipVzec2iRgjh2W5YyBttkBTYK7xRaYABaCu2H2nv2fKxNXqwOaIaRhjAcWwV4ShCiNr/+s//31Cr93XFAyEU9/5ike1V [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSky {
            get {
                return ResourceManager.GetString("BlueSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA25SURBVHic7ZxrbBzXdcd/d177JMVdiqIsytbLkiMrlmMrlhxbVuvKcuw0NRygaF0XMRAnCNC4KNIW+lA0Lhr0gRRogSJp2iRokxpI8qGpYyAN4haNE8tu/Yhrqa7CWBJFiRLNx5K7XHLfszsztx9m7+5wxcdKkLi0xD8wmNnde2fPnfOce+85giuHCJzFIp9bf7sRsNBYxQLndp6TBLz64bacvXobL9D2qhDbbntFsBY4t15rLW0Wusf1isUURGf+c1GfNcBg/rPyAAeoAVXArn9W3zk0BUIGjssm8nIHpAgOEm/WB2AC+p6eI8ld0cNbIlo0rmPEADzpahIppPQa/yuRQiKvoiBo6s5CXUuEAJBS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAz3SURBVHic7ZxrbBzXdcd/89w3yeVD1Jui7EhRpMiVHbu2a1euADuwUwSJkzotkLitCwRo+6VfjLZoUwRIWyBo+6EFWqNAUjQuGiCx3abOC2hiJ7GNxLUtx0okmRK9JBWKIpfkkrvLfe/M3H6YvbvD8ZJc2iJnqfgPDGZm9947/3vPuee+j8I7h+K5K2u8+//7ZUC7vCpt7p2UkwCcxmX77k4jjOMJe13IdhpeElY9d/+z6gvTLo0bFWtVEI3V5SLfVUBndVk5gAXUgRpQbbzL3yxaCiE816ZJbjZDkrCXvNHIgAFox/voP5xgJGQQVxRiAI5wMyc83xVi9fu7h+rhqzW+oSoAArWj7yg4zUJUFEe4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA1eSURBVHic7ZxrbBxVlsd/VdXVD7cdu+PYsROb2EPCbh5jO4NZHDBKAhhpYSKiDHxAWjJiAkweEuIlR8SID6uNZKHILLs8FkUgPAqwIhsjlswIGULMQ0vI2EoIxBhMsHGSthPb8bu72l2P/VBd3eVO2+4Ygp3Qf6l0q8pV7Xvv+d9zzz11zxH4aRAiB4A4xSEARuQ5A9Djru3l1QJhintC3Hk8EvWVEXet256ZcR86LvWFCERbKUUOR+SQI6UzUloEALPS1qExsTH2Rl5NiBd6/GF/xoLVB/Z+0gA1UmqRZ+x9aCR4f1pcKgGsSltClwEXkAa4AS+Q5vV6vRs2bCgqLy8vzs/PX5yenp4py7IcDAaV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA0WSURBVHic7VxdjBPXFf7mf+zxrr02y253WcwuBEK9AgUCBQJahATVoihKE0TfGiV9qvrct6aq1B+pUp/bl7ZKeIgUieYBNY3UBKoGhFD4STYixMUYlu462Lv2rv+9Y8/c6cP42tcTezEEbC/wSaO547n3+tw5555z/87h8PDgmDvX4tn57mlAs7ZyTe7tfCcLAKlepuNOqnkIk/eRENtufkowz9ydad6Rp1kdTypadRABjd+FPvMARDR+KwLAAFABUAagV5/pbwbqAmEx1wMT+aANogSzxEvVBkgAhFAo5J+YmAgqiuLhOE4DAEIID4CzLKv2v5ZlNTx/dwi0Zs4mC7AsnrPvXFv/w3GWVU8Tq97J [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA1lSURBVHic7VxrbFPXHf8d3+vrx7UTX9PEToKT8iyMqTwXNgpqJhVQ94mhdlPVadUQVUGrKlQJ9UPXaRJj1SQkPrRCqkRBk9Yv1WilqSKfNjS1oWiDriUJLJhQN4Y4dmzHjq9f1/exD9fHvrl1EvOKHchPurrH9jnX/3P/j/M/j/+f4N5BDHcyy2fzb48DavWV1LjX8540AGr5Ukx3tVxHNdR9IMTWW58SbDHczWWLqU6tZzyqmE1BGMx8L/SzBQCLme9KBSADKAGQABTLn+l3MqoCoRmuuybybjtECTYSby13wAqA6evr8z7zzDM9DofDxTAMDwCKolg0TSOaplX+1/z5/mEBAKiqRmhZ0wgx3ucD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLight {
            get {
                return ResourceManager.GetString("GrayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAw1SURBVHic7ZxrbBzVFcd/M7Mzu95dx68YXMeJSaBJg63wCEkTmhAUCaqgqqIJSkFCqUo/lX5GQqJUSH1IFeUDSBAhQVUigVQCJSKlSKWkUCpAkNBEchLHxrEdx4nteG2v17vrfcxMP8xe793x+km8sw75S6N57J3Zc+ece+6Zc885CouHIu2VGc7dv30bUKyvSpH9fN6TDVi5zXTtrVwbS2p7VYidb3tBsCrt3ceqq02xZ1yrmGmAaBS+F3GuAj4K35UFZIEMkAZSuXNxLUteIGxpWzCRC+2QIFgmXs91QAc0WqhlHc34CaMQynXH6Zwt/a/tOv/GUCV6tdx/qErBfi4oll14bIozOz/g5gEbdap/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAzISURBVHic7Zx5bBzXfcc/b97M7MljKVEHJdlWZMuRz9iObdlwojZA6zhHYTuAkyCBEdgp0LpFAwRIUSAHUqQtULQIkj8SI2gTIAWSBnGLtkkTAzmUuFESx7F8xbIs0pQoUTzFJbnk3nO8/jH7docjkkvq4CwVf4HZmZ19M/t97/d7v3f93k9w4RChs1jhe/S33wcsl1exzHkt5aQAv3F4kbPfSOOH0l4SsmtNrwkboXP02oikWe4dVypWqiCSpeWivxuAydKy8gEXcIA6UGt81/dcWgqhQse6Sa43Q5pwmLzVyIAFyMwu+pI7uVqaZIVBBkD5jcyp1v+qyPeLhxHiKxt/YjTeb6zxf/xWIQpfBWUc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDark {
            get {
                return ResourceManager.GetString("GreenDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAvHSURBVHic7ZxpbFzVFcd/b/Ws3pKQNAnQlDZRCoQlJCUVlBa1pXQRkEgUVJQPVJVaitRPSEhARUVbqVJVwQeIkAAJJGhFqICmEAlKgIJKhQgkVVYbJw7G9tjxNvbs85Z+uO963rzM2OPE8RuH/KXnt/i+N/97z7nnruconD4U31mpcx/83xcBtfKq1Dg3Uk4u4HiHHTg7XhrHl3ZeyDaaXhJWfefgtRpIU+sb5yrqVRCN6nKR9yqgU11WDmABZaAEFL17+cyiohCu75gzyblmSBL2kze8DBiARpxOIlyMRgKFOADudOYqv+vOt4VQfXw1+UypPs8Gx62+tuWNW6lwDZNRvDyKcnI9QbtoOBi4Xnm5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkness {
            get {
                return ResourceManager.GetString("GreenDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAwQSURBVHic7Zx5bBzVHcc/M7OzttdrfCQmISeJSg4INEAICeTgKFBKKSESSVAREsc/VEigSlSVKAVRKJVAFVSqUCoB4lRQoFyFQKOmIFoRQszV3ImJ79iO7Xi9Xu858/rHzNt9nqztdQ7POsl3NXozs29mvm9+x3vzjp/GsUNTUm2IY+9/pwPylVXLkxbyngRgu5vlSW03j63kPSFkC80vCetK6t3XPXny3eNUxVAGYjD4vchjHQgw+F3ZQAZIAykg6R7LcxlyCiGUbdQkR1sgSVglb7oFMAGDVdTwU2ZSQRiTcgAsdGw0hPJc7/FxQ8/dF8PZF7pzf1sv7Dm6nXuJmi2cdwzoiJzBFQC1vBY6aXRs [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLight {
            get {
                return ResourceManager.GetString("GreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA0MSURBVHic7ZxpkFzVdcd/9y29zyoNI0ajkRDRYsKmxWIxwoCMscHEmCoDcaVche2kys4Hu5JyylUJ2OXgfAnJB6ocilSW8kbFTgiuGCMwNgnBTtgECBASGiSN1LP1zPT09HT39PrezYfX9/Wbxyw9E6m7R9a/6tVb+t7X//vOuefcd9+5R7B6CM9eLHLu/+23AQu1VSywr+c5ScCubpZvb1fL2J6yZ4VsveUVYc2z9x9rvjIL3eN8xWIdRGf+c1HnGmAw/1nZQAUoAyWgWD1X1yrUFEJ6thWTXGmDFGEvebPaABPQ79pC9yc2sbktQMwURAEsG80GIWXtf22JkGdVETT3vg49kGjCuabV9T+asN2H [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA3MSURBVHic7ZxpcBzHdcd/M7OzN4DFAiBA8AAJ0dRBSiJNirpInZEUWU5EVmSLZVWSspKqlJMPTlxxSoklObHkpJJS5YOqnCqncsmxlbh8JOXEppREchQdJVokE9I6SIIgQOHcBRbYxZ6zuzOdD7M9O7s4CLJI7PL4Vw3mQPfs63mvX7/ufu8pnD8U11lZ5L7+f1cCFmqrssB5Od9JAFblMOvOVqWM5Sp7QYhdbnlJsOo611+rdWUWesflisU6iEbtd5H3KuCh9ltZQBkoAUXAqNzLZ2WqAiFcxzkTea4NkgS7idcrDdABbe8dW6K/uL2/r8XvC+u6EgIwLUu1BIqwhPO7lhCKEOICCoLmvNcmC4RQ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLight {
            get {
                return ResourceManager.GetString("OrangeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAy7SURBVHic7Zx5bBzVHcc/M7OzXu+u4ysmkASbRBACBRoaE47ElADhaAgJSJBUrZA4/gFV4pCQkCgF0dAiNUItEkJBKohCIirOQksCiLSIIhLAUEIu4pjY8bmOr/V6vefM6x+zb3Y8WdubkOzaib/WaI6dN/699zveb978fj+FY4fi2CtjnLt/OxWQq69Kjn0+4yQAM7MZrr2Zucd03HtciM33fkmw6ti7j1XXPbmecbJiLAXRGD0u8lwFPIweKxNIAykgCSQy5/JamqxACMd21EQebYckwU7i9UwHdEBbw5qqG7ihroyyoI4eADAwVBNTEQj7/7rPfzxU+7kWeSBQFOtafv1VHYOoIIQ1xqCiiqzC [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA3VSURBVHic7Vx7cFzVef+d+9r3aneltV6WFBuwxcPYxsYhxk5NieMSIHFSXp1M0oHSaWg7xE3L9JEAmQBNMsM0maZNh0wKYQIkw0DIJBkbkiZMa0zNw2AbHAOSbVkr7WpX2l3te+/de+/pH3fP3avLSlq5tnYt6zdzdR865+537ved7/vOOd/5CM4cxHIms9zb/3choF5bSZ1zI9+JAtCrh2Y769UyuqXsWSG20fKMYM5ytl9ztjL13rFUMVsH4THzu7B7DoCAmd9KB6ACqABQAMjVe/ZMRU0gqOVYMJELbRAj2Eq8WG2ACIDfffWO0B+tv3bA53J5RYH3AICmaZxOKaGUmr9rv///gzPfy64pJcR4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLight {
            get {
                return ResourceManager.GetString("PinkLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAzgSURBVHic7Zx7bFvXfcc/98nHpSyKsmJPfihyUjueBHt5Lnbt2TAQDw6KokuCbAOGFO3+avd3gQFbhwJ7AMO2PzZgCwa0Q+thAbqkXeFuLdC0WR9BGiRxFhe2o0ihLVdiQkqkxDd1yfvYH5eHvLylZNq1Rcr2l7i4h7znXP7O+f3O73dev5/EzUPy3aV1vgef3Q3oVlepy72XdnIBp3nZgbvTzOP48t4SYnvNLwiWffdgWg7k6faOOxXrdRCFznYR32VApbOtHMACGkAdMJvfxW8WbYFwfdcNE3mjFRIE+4nXmhXQAGWKqcQ+9k2ECMUkJMOrjSMDkovb+l8Xt+P7rw9FvFnyyAIXWfLuUk//I+G6 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAwlSURBVHic7ZxrbBzVFcd/M7OzXu+usZ3ETciTRCUJEGhoQkggDx4FSiklRCIJKkLi8YUKibZSpEqUgiiUSqAKKlUolQriqaBAeRUCjZqCaEUIMa8mztPE79iO7Xi9Xu97bj/cubPjydpeh8S7TvyXRndmdx7n3nPuueeee+7ROHlorlIb4tr739mAfHXV8pSFtJMALPvIekrLvsdy3XtKiC30fkWw7iq957rnnnzvOFMxVAcxGNwu6loHfAxuKwvIAGkgBSTta/VbhpxACNcxaiJHWyFFsJt4066ACRhrYdKPYU4FhE0IISnVLdCE67ve6+8O3XmvJA8EuiZ/0wv6jo7lNKKGJWQbgw4i1+FGhru+ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA2SSURBVHic7ZxrbBzXdcd/89wnxZdoyXrRYmQ9QtWObFmxbMl6uFKq2m0sRLYCBGiQNF/SfkhbIECB1k6ROv1k9EOAtEhRtInbGDXiuIAbxE6TuGj8gF9SIFWWaVGUKJMUd0kuuU8uZ3dmbj8M7+7s8KGVInOXFv/AYB577+y5c84959zHOQo3DsV3Vha4D/52K2C+tirznOv5TgJwZw8ncHZny7i+sjeF2HrLS4JV3zl4rQbKzPeOTyoW6iAatd9F3quATu23cgEbKAMlwJq9l89sqgIhfMd1E3m9DZIE+4k3ZhtgANpjvb0dv9fT090SCsUNRYkBOK6ruqAIISr/6wpRc//bQ/Pei1A8skAIVfH+ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLight {
            get {
                return ResourceManager.GetString("RedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA25SURBVHic7VxpjBvlGX7mHnvs9bGHk2zuJVkWcoekFEIbQCUKRxskChVVWzWVUCl/+FPUHwW1oqVCVCqiUlErWkrVqlUFpaIcAkppuMQd0pAQstldbzbetb2+77Fn5uuP8WfPDvbGCYvtDXmk0Rz+vvH7zfu873e/DM4ejOXMNLm3//Z5QKOyMg3OrXwnAsCoHrrtbFTTGJa0CyJsq+mpwKzlbL9mbWkaveNcRTMD4TD3u9B7FgCPud/KAKABqAAoA1Cr9/SZhjohiOU4YyHPtEBUYKvwQrUAAgBux5Yt/m2bhlc5JNnF8ZwCAIZhsIQQhhBS+1/7/acHW30vmPo1w5hntqX/YRiD1K8JoUbGMCB1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAy3SURBVHic7ZxrbBzXdcd/89wnxeVStFTqQVN2JKskpPoZS5EqQYBVyAiC1DbcFigcJP3U9nOAAm2KAG0DFG0/tEBjBEiKREUNpHbSQHkBdeI2ieEatuVagSTTpFeiQq69S+6S+17u7jzy4fLuzo6W1FKRuEtJf2Awd2bvzJ4759xzzn2co3DzUDxnZY1r/293Azq1Velw7uY7uYCzeti+s7Nax/HUvSXEdltfEqx6zv6y6qvT6R13KtbqIBrt30Veq4BO+7dyAAtoAHWgtnot71m0BML1HBsmcqMNkgR7iTdWG2AAGhMTcfbtGyMQiKIoEdEcRzTOdVv/67rt178xNPliRZAFuKqyequ7/1Hc1kdU [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA3rSURBVHic7VxbbBNXGv5mxmM7vsSJHUMx1NlEBEI3Ld1NCtuGsKXAwi6lhYc2SCut1C0v7UsvUqU+LMuqS1d9QH2oVK3ow0qrFkSl3gRbSKrCakXbTUITRNqGS9I2xI6Dg+PYHl8yY8+cfRifeDLrJCbLZgzhk0YzHp+Z+c75//Of239+BgsHozkzs/zW/7cUUCyvTJFzKeVEACj5Q9adlXwaRZP2lpAtNT0lzGrO+mtWl6bYO+5UzFZBOMwsF/qbBWDCzLJSAOQAZAFIAMT8b3ovh4JCEM1x0yRvNkOUsJY8n88AD4Dbs2ePe+fOnbVOp9PB87wdAGRZZhVFYQgh09/V//7fwU6/V6UHEMIw6r3S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAzHSURBVHic7Zx/bFzVlcc/7715M+OZcfybQBLsJiohUKBh44ZfcUqgAdqUJlQqSdWqEoV/qFairYRUiWWp2LBbqVHVrVRVqbRUXSBi1fKj0JLQquxWXbQJYChpfhHHxIl/juNf4/F4fr539487d+Z6MrbHIfaME3+lp/vem3vfnPvOueeed+49x+DCYWilMc114W+XA4r11ShSlvKeBOBmD6egdLN1XK3uRSG21PqKYFMrC8/NgjrFnnGpYroBYjH1vahrE/Aw9V25QAZIAykgmb1W9zLkBUJox5yJnGuHFME68Xa2AzZg7dhB/X330VJdTci2CQI4DqbrYgiR/9/C608OM/dcSR4IYRrynlnS/5im [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA0rSURBVHic7Zx7cFxVHcc/5969+94mmzbk0Ta1FUorCNTWIthCkZeKSmEUcHR0RBxFHUVnGJlB0FHQP0Qd34MjOjwHH4gjSlFH0MEqIEWBvtPQtEmTbJLdZLO72ee91z/unrs3t3lsapPdlHxn7tzHnnP3d87vd37nd3/nd36CE4dwnMUU9+7fXg+YrK1iknM1/WQCRvnQXWejXMZwlD0pxFZbXhKsOM7ua8VVZrJ3nKqYaoCoTOwXea8AHib2lQGUgCJQAPLle/msREUgTMcxayJn2yBJsJN4rdwADVC3b6PpnW9nVSRAWFMJAeg6imEiTLPyv+77/x+K9V4DYZEHpqkI67+Uqv5HEYbdiUIYptXH [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDark {
            get {
                return ResourceManager.GetString("YellowDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFUQAABVEB2uRMrwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA3FSURBVHic7ZxrkBzVdcd//Zr3rnZnd1mkZVdIyHqBkAVC4iVFWEYEsA0KLydluwrFX3AqNomjlCvmYWOcciokcaUqdtmJY1PBJOXISSqhAAdkl62QkgAhJJD1WD13tI/Z57xnume6Ox967kzPaB8jRd6ZlfZf1XV7Zu7tOfeec8+5fe85R+LiIblKaYrP1b9dCZisr9IkZS3jZANW8TKrSqtYx3LVvSTE1lpfECy7yup7uarOZM+4XDHVBFGoHBfxWQZUKsfKAgpAHjAAvfhZfFegLBC267pgIi+0Q4JgN/FasQMaoDx43y3h3/742sVNIX9IU9UggFkwZcu2Jdu2S/9rWZWf//9QSs91yALbliQA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLight {
            get {
                return ResourceManager.GetString("YellowLight", resourceCulture);
            }
        }
    }
}
