//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laavor
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SwitchCadre {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SwitchCadre() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasePackage.Switches.SwitchCadre", typeof(SwitchCadre).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAALgAAABHCAYAAAC0940LAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAIJwAACCcBF/WOkAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAywSURBVHic7V3PqyxHFf5qZu6LiSFBEcQfBBI3blyIwZ0GMW7cunMriHu32YpLwVVWgv+Am4AbcaUScOkuIII/wIWiEGPMe/dOl4uZM/P1N+dUVffMe/e96fqg6a5Tp3709FfnnjpV3Te9m/N7rwKbDCADGOSM/bWlWS/KyyIz3QxgK/V67dbazJSvae3H1Da9NOtrm3qvtTZBearvtcl5+ly8eqJn6OnWfuvot/fuzXverbzhe7vEM6T8u81rwAsvAZ9veeilmy/pnFO2RKToRms655Z9Vu75cf9erb8pLnDP63ll/7a5A3A348HO/XGmpJ9UuZYDQZrPCNIlpL2+nT0518vyRLpaJwCsMCaZlRn2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAjTSURBVHic7VvNjty4Ef5Ekf03NhwvDGySixEYhmFMghxy3dPCB99y8WP4DfIceYKcfc8hD2AExiZ7MAw7GBsB9rADA4aNsaSRKEo5dH+cEpvqn9mWxxOoAKFLFP9aVfVVsUglb9++Pbl9+/a8aRo0TYO2bUHeOde5D6+2bf1z59xa+1h91ou1D9vG6od1+9pvmlfYnvfb6l7mHewyr8u+g6ZpAKB3bmH7cF5N0xTJx48ffzbGfLupg20DXPfn8gV/jfMb8PmprqoqqqHbOolp6peqw7Jw3uEFYO1+GyVJ0rnatl0rU0r5+k3TrJXJfpqm6e071r9Sau2/hmWHeo/OOXQUoE8RNnW+Lz9Eezn/mPBJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAg2SURBVHic7VvLjtVGED32bc/jDogQIZFkgyKEECJRFtmyiliwy4bP4A/yHfmCrNlnkQ9AESJhgRBEgCJFCiMWgAZfz/Wrs2if2+W+bd8H9gwTdUmWy+1+uav6VHV1O3r5Ur+4eBH7dQ3UNaC1udc1UFXtZ/fS2r6vquXyvvzM5yvvlvXld/N2le/rl1uez6vybjMG6/Rr2zGoawDo7ptb3u1XXSOL3r3Tr5MEl/sqWNXAWX8vB/hT7N+I7w9Vnvs1dFUlPk09qTxMc/vtXsDy8yqKoval9XJaHNv8db2cJuup6+66ffXH8fK3umlDjWNVAS0F6FKEvso35ccoL/vvEz5plSJQIK6wdnaAGzesMH0K [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA+BSURBVHic7VxPry3HUf9Vdfece59tEUJQgBAQPAJCBmXBhkUkBDKSw4YNRmHFF0DwAbLJZ0DiE7CJsLJjwYJFNkgIoZAIIZTYLxZ2FHgYFGL7nnNmpruKRVX39Mw599qQdxxhTlnPt6enu7qn629XdR/69ptPn/zox56/laIQEagoBAIRQRFAVSFi76SVrY0WtfYqKKoQAVQFFZfhgbVXhaqgFO+vNpaqvSuljg3rKwJVtfYqEIW9F0GBQsXGqfMrjl9ErR7e1udr7+Btpc1bVVGyz81xqdh44vNteEUh0DaGaIFqXQOg1DlBIVJ8LF/DYuunjqc4Hi1i40FRpOKq62z4S11D+LyLfYMIAK108XWv [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDark {
            get {
                return ResourceManager.GetString("BlueDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAnKSURBVHic7VxLi2VJEf4i81RVlyONio9RcCHiahQXjQthEEZ64c6Ntj/Ghf4Jf4Gg2Lh2XPgL1G4d0IWMIqKgzYCjM1Nd3bdOZrjIjMzIOJn33q66t8T2BNw6efIR+Yp35im6eM5/mjzOAYAZBTgC8sr5B85prvlSKQ7KS1rjNvikv4haV+Me9a3HV8Yx6LvUlbR0pvJK/6NxsxmLmUNU6cW4427cMqzuuM08F+un5hVt3d6apfqXdBX4HwR8aoGoh/wlL+8Srqr7spUT4ckUGHCmYm/R9kU84o5D4SjpLeNsynE9oE5borxwuYKkGcs8jYAJoFJJNZAOGiQpTVTnL/mlGiecOi1lFvW2PBAwcQSi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLight {
            get {
                return ResourceManager.GetString("BlueLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAs8SURBVHic7Zw7ryRHFYC/U9Uz613ZyDIgm1cAhAY5ICFwhIxkR0S2zC8AEhAxAfsbkJAMyBEBD4ucgICEhMDgEJCFQOaxGFmyjXfvTHdVEVSdrtM13XPn2nfWPPpIc7veVV3nfar6yp230qsPbrmZEkRAnzEBKedTyacEKZZ8aZtSqSO313axtBnH0PGj6VP62fEpaVsfYy63c0UzbmrqbD87N3YdaeYd4rTtXDs7Z9D5Yl231mvdZM52nFj32u7F4hjN/o/73e5Hs68jfmLTznFP3rlIf/eeRw828v8s/5+whvfhne90Q2Kk/EVuMnXtQLNtFzh0lpuuMObcixxwDkVaNHlM+RxIUyflj0olaRqJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSky {
            get {
                return ResourceManager.GetString("BlueSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA48SURBVHic7Vw7ryVHEf6quufc610Dlo0ERrAyD2GBsQicOkKWgADISPgVCImEAKc8IiRHkBHyBxwQkCERGGzJCGQsY69lbBnwe89juqsIqvoxc+YsK3yPEWhKOndm+t1d1VXVVdWX3ngpPX95D9+FrIACKoCq/0TtWwBRAAqgpNUy7Qf4UwWavR66drwNlYV2VCEZQJcG1Un76t+lDYG3k7uxwNuodVo7Iq2vaRlpY/ExANrK12c3D/F2vU5Zozp28bZKmX6t4HPt18LXrs5FO3x4XzJb71qmjltqX2XsyGhtS7emADRjS9u386txoI/1C6aidcBtEHq8GNohbKEMOqRNFqAgQNt3X2axnvd523oz [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA+MSURBVHic7VzNryzHVf+dU1U99z47CQZLBIQEkYNQ4kQIRwghZYW8yA4hUOCP4D9ACk/ZsiPiL2CDFGWPEAuWKIkMEV8KYKwgh2CMnpPY985MV9U5LM6p6pqemetn5Y0joindud1d31Xn1Pnupidv/sfrtx974RYiUBGoKFTFfxUqClEBVKDV88WfVe1XBdBq7aFQEYh43SpQCCBeX+rSf1WIqpdV728YRxWqFZClvahYH22eogA8r2qfn/g8WvuDdQ3toQqp7bku4/p+QGpfk4rY+P5DbXV12S8VoPoewNu3/nSYh9RlT9q66lB33LO67Jm0efd9BBbYWbs2FqpAdFiXLPsDqagiW9r+8Pv/HVL6 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAhFSURBVHic7Vy9btxGEJ7dJXk45CzJjVRZTtTaQAxYcBqVKRKkyFOkT5ciT5FnyAMIcRUEAVyki+AqhYEAQoBAjiMogCCdbVHH/UkhDT0czpK8E0/+ET+AuOX+zXJ2dmZ2diWV5/m+MWbsvQcAgBBC+YuP9I553vvWOlI/tB3Nj7Wh9Jr6lb6Bt4l9Jy1v4ofUB+eHNK6mfpBeG+8l/rfVifE+y7KzxBjzEQBsKKUqjQAAME96l/KkPmJQSoFSqtYXbUffpTrS+Hh9ms/rx8aFdekvLZf6wO/gPJB41kS3DZRnbeOLCQLWsdYeJjGJbNME71oZvlN0YWgTmgSyaXHEhOCq9PikS+9IswsPlVKQWGsr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAgdSURBVHic7VvNjtzGEf7Y3eRqsYYQWQKc5BbotraRQw666GTokFtugp5DVwMrYh9BizyBX8KHPEEO/gF0MQwjCBBB0A9GOkjYHbK7mYOmeos13SRnhrOy7P4AgmT/VP9Usaq6ulksFotfDg8PDwGg67ro5b2HzB97994P5g/RlhchRjdFm5cbog8gSnPKuFJ0eV/H2k7N19i4eN5QP1JjAwDn3Lk5PDw80lp/NtRBpdQggySjAEBrPalOURSTBk7pqb4QiF6MbuoaGx+nPZUu7yvvV4r20Lh43TE6HGNj01o/N1JKx77GqywzlYYc9JTJGUNRFFHaY2VidMb6MUWoxspQ/zYtY5xzo0Q2TZ+T1rZt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAaASURBVHic7VzNjhtFEK6qnl3HEVoRhJafG+IYEAcrh0i5BO2BG7e8DM/BE/ASHHgCEi9ESg5ogxASEkQcEiU49o6nqzngtsrt6u4Ze8a7RP1JI7f7p2p6qrqquqZtvLy8/NUYMwYAcM6BBzNDCN8u+2nlXJ02VvLrSqfLGF/W+O1DL0en7fxi7Tl+bfkEbXO01v4FAB/sc3NvS/t1vKch2xHxedVGm/dlPASNtu19AhHXPGQ51+7LiLi+zzbtYdkj195lPhUzbxCTTK5juS96GlICHI/Hreml+iCiqjz70GRmcM5FxxLRurxYLGA2m61lXqWID12W32P1WttVYLFYrMu5uXmBtO0flncZ07Z869Yt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLight {
            get {
                return ResourceManager.GetString("GrayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAzGSURBVHic7VxPryS1Ef9V2T3z3lsIIVkpfy4oWiEEmyiHHHLhFHHglgtC+RB8g0jkiY8QlE+QCxfuOeQDoAiRIAUhiBYUKRHZbLQL2p2Z1+0/lUO13XZPz7xZMbMoUVerNR7bZbtd5apylbvps/uf3Xn2/NnziIgoESKCKJoOEvR/jEjl+YbWTfUDQo0fp+sHCTlPRCBREFH0VeDk+hjwY6zrikzjS5T8DBl3/FwSIRCEGKqxVXUxGlfcMwcJH8McjPGruiV+nJiDqTmL9XxDsE2bEj/ufq4Y4oa+3Hz5r8Y039vZwIgo43tn+QRDHYyPA9rfVY4D2p9iskPan5jog8e3g0gH4e8i8CH42Ft+13ax [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA+HSURBVHic7ZxPr21LUcB/Vd1r73Muj4iIQUU0+kRj0DBw4oDEaDABJ07E4MgvYPQDOOEzmPgJnBAJMwcOHDAxMcYgxBgDj8eLQNAnGoTHOXuvP13loLp7rb3PPvc95Z5HfNl17z67d69e/aequqq6qtaSr7/+tVff89KP3hY3zAxzB6tlCu6O1WvuFmU3MKO4Y+64Ge4Fw3BzWl+YYUR793atxO86lrvjbhQrMTZ1bDPco72b4UR7MwMvWB2nzc+94Bbl4ga1rfXxfJ1LHcvrGEu912tbM8eJOZZNv+YG9bu44aWNH+3Nyjp2qWNVHJaOP6/9xFjFHDOv/dZ5NTy3/ikd5+Z13dbwTbS3tu6VRt7W [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDark {
            get {
                return ResourceManager.GetString("GreenDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA1+SURBVHic7VxLryVHkf4iMrPOPbdt8ZAlYEYMYnoMQg1iwRZpBPJIFhs27OcP8A/mX4zEL2DNnsUsZolGiIcQQsZut8BIQ8sgA+1TdeqRGbOIzKisOo97G/exNdaJq6uTlRn5jMiIyMioord///bjT33yU9sUE1JKkCRI0HRMESKClPQ5SZrTSJAoii8JUaLWF0Fpq7RT6ooIYozzcxLFl4QY46Lv0laMUfvN+CklRGTcmGx8UaqxxgSB2BxsXLndKNHGLSKIk9a1OeQyG1e9BmV8cZ6TrUGKi74X44qHc0ipWkPk9S5912uQ55CQbN5lrBDM+PHImqc8r2qtKnp19Je//eWPwYfPLIi7GsAB8T9m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkness {
            get {
                return ResourceManager.GetString("GreenDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAhsSURBVHic7ZvPjtzGEcZ/5JAzOysZjgMBTnIxAsEwDCXIIVefAh10y8WP4TfIc+QJcvY9hzyAERhOfDAMOZCFAAHihQ62Ic1whxySOZBfT7GnyZlZD1fagNUHFpv9j13VX1VXk9G39bfP3uGdZUWTamrEl5Sdez/VbVJZv36ovMqF6vt1Q+X9sn31h8bl19f9obI3mYNjxnXTOaioAHrH5tf3x1VRZdEP9Q/fpaTvDjVwqIO7/txO8Js4vhGfXyU5eVBDDzUS0tTbKqM8f9x+AvbuD1HkpZp6Ly8mduUrqr08205F1dt2qP2YeO9d/bxzzWNJSUcB+hRhqPFT+THq2/GHhC86pAgSiC+sOXM+5EMn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLight {
            get {
                return ResourceManager.GetString("GreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAucSURBVHic7ZzNqyVHFcB/Vd1937xJ/I4YP0AkiMgoLrLNKmSRjbjxLxA1CPoXBCH/hGjcugmIexf+ASIhmoVIlBgC4mSY4Acz7765t7uqXNQ51afr9r3vzeTekYQ+UHTdU59d57NOVV+X7v79bZ741DkpklOi5EMAzG9NMQJaN+XfKcgzSZlJQZ6kXK/0k8bxCPLbjJFSxtu5BRmrjCNtYhjnsoM3v5H2IRl8ME9TN8i8UrUGZYzqHXSsyZqZsey87HrFNM6r9LVnzYJpT4TEtL6dW5mfeS8tCwFSvHRp/Z/3aLrPzRK5ZoiPankM83VK+b6yD335nZawzVx2cMEO4B6q3YwkXVXnYLtU1TGJRIZk [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAApvSURBVHic7VxNzyQ3EX6q3PNulg3fERBukFsCygEkLrmA9oCEUE5E/A6uSMmr/AQifgG/AJFFOSDEOYdAJC4IIYQEhCVoE0H2451puzjYZZfd7pmefWcWAV1Sq912ufxR5XK5yjMkD+79Ae7mTQCACADzSHoQYpbmQRKKwUMqD5oXDuDrE/pl+g6pbu5fS1dMWdtnbcP0bdIO6r5O5sCMOzR02zlp+yNh2reqHzD1On2YzLkdvx1TD68ZG3pl/iHJ7uHfQO7zEwK9ie3izL2xAGeODha20cOZ6fOx49g3psei2WHS4rFdgw+zwiEA5O4AHwCH5Y3NSmbbmb0NL2TWQhoWluAsAaLYPsG8ZQFOehek [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLight {
            get {
                return ResourceManager.GetString("OrangeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAesSURBVHic7ZvNjtxEEMd/9ng2mSWID0Xi44JQhBAKiAPXnFAOuXHhMXgDnoMn4MKFOwceACEUyAGhgEKEhASrHAAlM5PdGU9zaJddrmn3eCb2blbqklou9/d0Vf+rutqTud/dA15hxgbYAK56boDSvNvkVHkZaB+qX0ba27ah+rZuV/vYvGz70ow15Br0mdeha7DBU9fcbHs7rw3LzP3r/mbKa9EOdg1w2cvLCx7/4spPCs4Ia+iuTkKael51JM/O2yYC77soM8kF8nJVfxPI0/1sIn2H+s8Dv9XmDbWOJbQVoEsRYp3vy4/R3hneCp+Od0uZKtdCOQLeoxFmSOFiZbrOTI0zVFoCTyPjv6h+/33g [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAnHSURBVHic7VxLjyRHEf4iq2ZmB6MVIB4GiQNCnAzyYeUDkoVktAduXGD5MRzgT/ALkECsOGMO/AJgFyzhAzIIIZBgZQmD7dmZ7a7K4JAZmZGRmd29M12DWFdIPZWVj8hHPDIiMmuIL579GeNwDgBgRgL2gLxy/IFjmnO+VPKd8pTWuA0+6c8j19W4e33r8aVxdPpOdSUtnam81H9v3GzGYubgVboat9+PW4bVHLeZZ7V+al7e1m2tGQOMS+Lt/E8QPlcjaiF/wcubjKvqvmjlRE9GzAw4U7G1aIci7knHsXCk9I5xFuW4HlCjLVFcuFhB0ow6TyNgAihVUg2kgwJJSBPl+Ut+qsYBp05LmUW9Kw+E [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLight {
            get {
                return ResourceManager.GetString("PinkLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAzeSURBVHic7VxLjyRHEf4iMqtnZ9c8bK/E44LQCiHWIA4cfPEJ+eAbF2T5R/APkOzW/gSv+AVcuHDnwA9ACBksGSGDjIWEZfmhtZF3ZrarMiM4RL7q0T1jdnotoGJUqpysfEdkRGREZNODvz945/Tp01MIoKJQVXuLQqP9LyIo39MDgZVN5RHH9UVkuXxs2leFaGo7TvrObUWrm+uLyLis6mJ9USlzKH1P5qWigAISZTy2piziuG47r+ka5PpQlLLT+m3Ztv5sXnvWLM+rrDd0hpu2vqjsnVeUeOFPnzm95Tr3tcUGnA2AhRc7GDXqKqIggBM3J6hUrv2flGb5owlN8ll43IbWsUIAEmsvv6f9zfJU [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAg8SURBVHic7VvNjtRGEP7ssWd3Z0GECIkkFxQhhNAmyiFXThEHbrnwGLxBniNPkDP3HPIAKEIkHBCCCFCkSGG1B0CLxzvjn86h53OX2217ZrB32ahLslzuf7uqv6qubgfq1auXuHx5D2UJlCWgFCq+KOrP9qWUyS+KZn1XeZZz1bfrusrbZdvqd43Lrs/nvrLbfIN1xrXtNyhLAGgfm13fHldZpoF69+4N4vhqZwN9HZz3fPmBP8XxjZd/GGG5dGtoXyMuTT2tMkyzx21fQPO5j4KgfinVTAtDU74sm2mynbJsb9vVfhg239VOG+o7FgXqCtCmCF2Nb8qPUV+O3yV8Up8iUCC2sKZT4NYtI0yXwnXl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAe4SURBVHic7Vu9jtw2EP5ISXs+XGDEsYH8dIE7O0GKFG5cBS7SpTP8HG4DnIV7BB/yBHmJFHmCFE4MuAmCIAgQw/AP1i5s3J1WElNwRxqOSEm7K51jhx8giOLPkNSMZoZDSpnl8k/s7+8DAIzxX3WNTvnQc133l/fRlhfBRzdEm9frow/4aY6ZV4guH+tQ36H3NTQvXtY3jtDcAKCqTlLs7x8gST7uHaDW/QySjAKAJBnXRqlxE6f80FgIRM9HN3QNzY/THkuXj5WPK0S7b1687RAdjqG5JcnTtCOlfRJ73nXG0pCTHvNyhqCUn/ZQHR+doXGMEaqhOjS+DeukqKphIpvmT0lr2z4k48YKAjGV108S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLight {
            get {
                return ResourceManager.GetString("RedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA3USURBVHic7VzNj21Hcf9Vdd8Z+9kGgrBMEhQlIqwclAVbJBTwgl2kCPwPhF0QEmsWfv8CjrxAELIgYsFXlA2giL+AhYElspIoElEwQTzbz2/mvbndVSyqqj/OPXfGDnOfRHJKujN9T39UdddHV1fXufTgrTf+LZ8/8SRUoQAABVShqlC176rxTKDRBAoVbe2hgKhCrdL6o/dXFWsX9eL1gcvbygquaONYAVFHGW3h9QBUbIxoG/Uy0qJtDoAczFeiLMMYTreRLH1N4G2jDRTi84sJqBPQ5tCqor+2ecLXVYxgf6wHbWOssawAVPp8Gi060DKv2SXtHz78JaX03FgxI9OZiHESrTwMOgjQQd8Dhh0T [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAxpSURBVHic7VxNzxxHEX6qumfXa4ePJJb4uCBkIYQD4sAhl5xQDrlxQVZ+BP8AyVn5J8TiF3Dhwp0DPwAhFIgUhAIKERJR5Dh6HRTvrnf6i8NU9dbMzrzva/ldR5ApabS93dWfVV1VXdUz9M+zsw9eXK1WGUAuBaUUZHmS/s8ZWl4fAMXgp2H9nEfxk8krpaBI22nQt5Ynqav1c8493CLlw/pF+k+m76N5lYICIOXcG1sPd1C3N6/hGpg2FXdYv4dr6w/mNblmOi/pA7o+g7Wr9aXdsXnllHb+pdXqRuPcN8YacDp45vEOTKPOECoDyM4ddVrxbH2i43wzoaN85l5e7V/7lfbyWLsjbZZSwDI/nsK1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAKeSURBVHic7dy/ixNBFMDx71tWzMYEjAj+gBRiFxUL28CBpLCzyl/j32GdwjJdimDhX2ChXikiIggaTBGIISDxnsVdJMll101ud/ay8z6QIjeTmcfx8jKzk6yo6mcgwvhoHgLXgFtFR2IKMQqKjsAUKyw6gEMwm80YDoeZjDWdTlksFpmMtRRFEZVKJbZ9MpmgqgC0Wi3a7fa/NkuAFKIootPppOobhiH1ej3niPbX6/UsAXYVBAGNRqPoMDKxrARLSQnwFviSazTGlYfAg20NSQnwRkRe5BOPcUlVX3GWACKy1mYfAQ6oaodi/tcjEXmf1MESwI1QRF67nlRVn23529pzS4BLRFXvAncyGOoK8ClN [rest of string was truncated]&quot;;.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAemSURBVHic7Zu9jhxFEMd/M7t79hkjPmSJjwQhCyFkEAGpI+TAGQmPwRvwHDwBCQk5AQ+AEDI4QAiQQUhIYDkAZO+tffvRBD3/m5rantnZ88ydT+qSWlPT39tV/a/q6tkihN/uwUuHsCGmQM2v3btPwZSvE+1T9dcd7X3bVH1ft61917x8+7Uba8g16DOv067Bhkhtc/Pt/bw2iyKEf/+G2SvdHewa4KKXr895/HMrvz+FY9IauquTlKaeVR3l+Xn7ROJ9FxUuhUReaepvEnm2n01H36n+y8Rv9XlDreMapwBtitDV+b78GO2D473waXn3VJhyK5QD4B1qYaYUrqvM1jk04wyVFsDjjvGfN7//Z+Cb [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAskSURBVHic7ZzNjiRHEYC/yKqe2VmMwcji74KQhRAyiIPFzReQD75xAZ6CN+A5eAIuXLhz4AEQ2AuWsJAxxkJCgpUPNtgzs9PdlcEhI7Kicqp6ZuzpRVgVUqmiMjPyLyIjIiOzW/Tqb+/QPXcGGTQDCmTIGRjG75of3iio5w8jfc1vadTq9DQN7YW2NOYPU3pt++U0Q9N2KBvH5Wk50Dtt7VuoR+f6lefHoMO0T5E+H+pXM64b5yzSM+1Tjn2L45vrV74UHT74F2y+dJjJSwz9tOQPTdoC/actX/LjHt02Eq4zhWe0wKyk3kR3oMxBhs3QTVaO0+mYjtrqaL9vAmkeHXERUAHSmEW2/JhGKJtDNVaP [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDark {
            get {
                return ResourceManager.GetString("YellowDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAAAxCAYAAAASqKEbAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAFqQAABakB/0C8bgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAkISURBVHic7VzLriY3Ef7K3WeSISjAkIiLYIEQq4BYsI2QQLNgl00SHoYFvARPgARixJqw4AlYAFlGEUIIJBgNCUwyl3D+bhcLl+2yu9zd55y/BzFySf/pbrtsV7vKdbP7EPvHfwLG2wAAMBIwq+fqnnV5BN+ot3Ctcs59eDbwd/bNvlHPxntV9DTbxtuVOUljN+hea5f6BsIc7KG76qOYs4qO1pwRPyXm0z8A+oI90BYhz1n9qnA9h/VE90dgBtjZDYpJW+kYLI9rq+MqxK31sYfOuv46QMu2RDIGqb4pXwlVPUo83aw1ZKpvjA8GONbV46uyxXzHeimT+jHc1GoH2M+QRt2VcRp1u3Aseg3glTpA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLight {
            get {
                return ResourceManager.GetString("YellowLight", resourceCulture);
            }
        }
    }
}
