using System;
using System.Reflection;
using Xamarin.Forms;

namespace Laavor
{
    namespace List
    {
        /// <summary>
        /// Class ListColorControl
        /// </summary>
        public class ListColorControl : Image
        {
            private ImageSource internalSource;

            private ColorUI colorUI;

            /// <summary>
            /// Constructor of ListColorControl
            /// </summary>
            /// <param name="hash"></param>
            /// <param name="color"></param>
            public ListColorControl(string hash, ColorUI color)
            {
                if (hash != "__Laavor*+-")
                {
                    throw new Exception("Key in Invalid in Constructor");
                }

                this.colorUI = color;

                Aspect = Aspect.Fill;
                Margin = new Thickness(2, 0, 2, 0);
                HorizontalOptions = LayoutOptions.FillAndExpand;
                VerticalOptions = LayoutOptions.FillAndExpand;

                byte[] imageBytes = Convert.FromBase64String(GetColor(color));
                var streamImage = new System.IO.MemoryStream(imageBytes);

                this.internalSource = ImageSource.FromStream(() => streamImage);
                Source = internalSource;
            }

            /// <summary>
            /// ChangeColor
            /// </summary>
            /// <param name="hash"></param>
            /// <param name="color"></param>
            public void ChangeColor(string hash, ColorUI color)
            {
                if (hash != "__Laavor*+-")
                {
                    throw new Exception("Key in Invalid in ChangeColor");
                }

                colorUI = color;

                byte[] imageBytes = Convert.FromBase64String(GetColor(colorUI));
                var streamImage = new System.IO.MemoryStream(imageBytes);

                this.internalSource = ImageSource.FromStream(() => streamImage);
                Source = internalSource;
            }

            private string GetFilled(ColorUI color)
            {
                string Black = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD3SURBVHic7dgxAQAgDMCwgX/PIGNHEwW9e2bmDQAAAJB1twMAAACAXeYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEfTNYAUVhWHOZAAAAAElFTkSuQmCC";
                string Blue = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD3SURBVHic7dgxAQAgDMCwgX/PQwZHEwW9e2Z2BwAAAMi6vwMAAACAv8wBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIexRSAkRBfPYLAAAAAElFTkSuQmCC";
                string Gray = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD4SURBVHic7dgxAQAgDMAwQPmcgwyOJgp6d8/MXQAAAEDW+R0AAAAA/GUOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABA3ANUagLFuAeAQQAAAABJRU5ErkJggg==";
                string Green = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD4SURBVHic7dgxAQAgDMCwgXKcgwyOJgp6d82ZOwAAAEDW/h0AAAAA/GUOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABA3AM+XgHFGopP9gAAAABJRU5ErkJggg==";
                string Red = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD3SURBVHic7dgxAQAgDMCwgX/PQwZHEwW9e3ZmBwAAAMi6vwMAAACAv8wBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIexZQAkSUdtMjAAAAAElFTkSuQmCC";
                string Yellow = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD5SURBVHic7dgxAQAgDMAwwL80PA0ZHE0U9O6eu2YBAAAAWed3AAAAAPCXOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHEPl9sDEC0VfzsAAAAASUVORK5CYII=";
                string Orange = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD5SURBVHic7dgxAQAgDMAwQCz+HQwZHE0U9O6eu2YBAAAAWed3AAAAAPCXOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHEP1w4CqvhrNnQAAAAASUVORK5CYII=";
                string Pink = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD3SURBVHic7dgxAQAgDMAwwL/nIWNHEwW9e+fMHAAAACDrbQcAAAAAu8wBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACI+/c7A0Nw4wWMAAAAAElFTkSuQmCC";
                string White = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD3SURBVHic7dgxAQAgDMAwwL/nIWNHEwW9e2dmDgAAAJD1tgMAAACAXeYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEfdk0BEK44hBaAAAAAElFTkSuQmCC";
                string BlueLight = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD6SURBVHic7dhBAQAQAMBA9E8ii07E8Nhdgr0397l3AAAAAFnrdwAAAADwlzkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABxDy0yA7pa7MWzAAAAAElFTkSuQmCC";
                string YellowLight = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD6SURBVHic7dhBAQAQAMBA9E8inArE8Nhdgr0379l3AAAAAFnrdwAAAADwlzkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABxDxjLA9yQiHYjAAAAAElFTkSuQmCC";
                string GreenLight = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD3SURBVHic7dgxAQAgDMCwgX/PQwZHEwW9e2ZnBwAAAMi6vwMAAACAv8wBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIexVRAkQ2YqzYAAAAAElFTkSuQmCC";
                string Brown = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD5SURBVHic7dhBAQAQAMBAZJNWSWJ47C7B3ptnjzsAAACArPU7AAAAAPjLHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgLgHoHwCMw+/EtMAAAAASUVORK5CYII=";
                string Purple = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD4SURBVHic7dgxAQAgDMAwQPmcgwyOJgp6d8+auwAAAICs8zsAAAAA+MscAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAuAdJZAJFixRNTQAAAABJRU5ErkJggg==";
                string Turquoise = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD4SURBVHic7dgxAQAgDMAwQPmcgwyOJgp6d6+ZuwAAAICs8zsAAAAA+MscAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAuAdI5AJFTA8OTQAAAABJRU5ErkJggg==";
                string PinkLight = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD6SURBVHic7dhBAQAQAMBA9E8ii07E8Nhdgr037z53AAAAAFnrdwAAAADwlzkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABx5gAAAADEmQMAAAAQZw4AAABAnDkAAAAAceYAAAAAxJkDAAAAEGcOAAAAQJw5AAAAAHHmAAAAAMSZAwAAABBnDgAAAECcOQAAAABxDy26A7r2FL7dAAAAAElFTkSuQmCC";
                string BlueSky = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD5SURBVHic7dhBAQAQAMBAdBROWmJ47C7B3pv73DsAAACArPU7AAAAAPjLHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgLgHgSEDMok08CgAAAAASUVORK5CYII=";
                string RedLight = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD4SURBVHic7dgxAQAgDMAwQPmcgwyOJgp6d9+ZuwAAAICs8zsAAAAA+MscAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAuAcr3ANEt7LNWgAAAABJRU5ErkJggg==";
                string GrayLight = "iVBORw0KGgoAAAANSUhEUgAABAcAAAAjCAYAAADotmNxAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAETgAABE4BQouT/AAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD5SURBVHic7dgxAQAgDMAwwL+0eQIZHE0U9O6embsAAACArPM7AAAAAPjLHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgDhzAAAAAOLMAQAAAIgzBwAAACDOHAAAAIA4cwAAAADizAEAAACIMwcAAAAgzhwAAACAOHMAAAAA4swBAAAAiDMHAAAAIM4cAAAAgLgHuAgDqcMZFsEAAAAASUVORK5CYII=";
                string OrangeLight = "iVBORw0KGgoAAAANSUhEUgAAAtAAAAAYCAYAAADTc8psAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAADAgAAAwIBpjVx6QAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAACYSURBVHic7dZBDcAgAMBAhnI8TSCzQF9kyZ2CPvvsd+0BAAAcmbcDAADgTww0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAg+ACHFwNh1gzGUgAAAABJRU5ErkJggg==";
                string YellowDark = "iVBORw0KGgoAAAANSUhEUgAAAtAAAAAYCAYAAADTc8psAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAADAgAAAwIBpjVx6QAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAACYSURBVHic7dZBDcAwEMCwrvyhjdONQvOqJtkI8swz75oFAAAc2bcDAADgTww0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAg+ADWWgL62gs9MAAAAABJRU5ErkJggg==";
                string GreenDark = "iVBORw0KGgoAAAANSUhEUgAAAtAAAAAYCAYAAADTc8psAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAADAgAAAwIBpjVx6QAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAACZSURBVHic7dZBDcAgAMBAhhQ8zb+UYYG+yJI7BX32We/4BgAAcGTeDgAAgD8x0AAAEBhoAAAIDDQAAAQGGgAAAgMNAACBgQYAgMBAAwBAYKABACAw0AAAEBhoAAAIDDQAAAQGGgAAAgMNAACBgQYAgMBAAwBAYKABACAw0AAAEBhoAAAIDDQAAAQGGgAAAgMNAACBgQYAgGADC0sBplYXJZoAAAAASUVORK5CYII=";
                string BlueDark = "iVBORw0KGgoAAAANSUhEUgAAAtAAAAAYCAYAAADTc8psAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAADAgAAAwIBpjVx6QAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAACZSURBVHic7dZBDcAgAMBAhhQ8zb+UYYG+yJI7BX32Gev9BgAAcGTeDgAAgD8x0AAAEBhoAAAIDDQAAAQGGgAAAgMNAACBgQYAgMBAAwBAYKABACAw0AAAEBhoAAAIDDQAAAQGGgAAAgMNAACBgQYAgMBAAwBAYKABACAw0AAAEBhoAAAIDDQAAAQGGgAAAgMNAACBgQYAgGADCtQBpuQZV88AAAAASUVORK5CYII=";
                string Aqua = "iVBORw0KGgoAAAANSUhEUgAAAtAAAAAYCAYAAADTc8psAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAADAgAAAwIBpjVx6QAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAACWSURBVHic7daxDcAwDMAwt///7L5QTUEA8gKNemZ3BwAA+OU9HQAAADcx0AAAEBhoAAAIDDQAAAQGGgAAAgMNAACBgQYAgMBAAwBAYKABACAw0AAAEBhoAAAIDDQAAAQGGgAAAgMNAACBgQYAgMBAAwBAYKABACAw0AAAEBhoAAAIDDQAAAQGGgAAAgMNAACBgQYAgOADpegDLVPEFLMAAAAASUVORK5CYII=";
                string Tan = "iVBORw0KGgoAAAANSUhEUgAAAtAAAAAYCAYAAADTc8psAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAADAgAAAwIBpjVx6QAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAACaSURBVHic7daxDYAwAMCw0v+3znzAj/SFZkJI9gUZcz33egcAAHBkfh0AAAB/YqABACAw0AAAEBhoAAAIDDQAAAQGGgAAAgMNAACBgQYAgMBAAwBAYKABACAw0AAAEBhoAAAIDDQAAAQGGgAAAgMNAACBgQYAgMBAAwBAYKABACAw0AAAEBhoAAAIDDQAAAQGGgAAAgMNAADBBsX4AwvitScCAAAAAElFTkSuQmCC";
                string GreenDarkness = "iVBORw0KGgoAAAANSUhEUgAAAtAAAAAYCAYAAADTc8psAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAADAgAAAwIBpjVx6QAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAACXSURBVHic7dZBDcAwEMCwW6GUP8eOQvOaJtkI8swze84AAABX1tcBAADwJwYaAAACAw0AAIGBBgCAwEADAEBgoAEAIDDQAAAQGGgAAAgMNAAABAYaAAACAw0AAIGBBgCAwEADAEBgoAEAIDDQAAAQGGgAAAgMNAAABAYaAAACAw0AAIGBBgCAwEADAEBgoAEAIDDQAAAQvFiVAVHp0hpoAAAAAElFTkSuQmCC";
                string BlueViolet = "iVBORw0KGgoAAAANSUhEUgAAAtAAAAAYCAYAAADTc8psAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAADAgAAAwIBpjVx6QAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAACZSURBVHic7dZBDYAwAMDAMTtzikyMMAvri5DcKeiz172edwAAAEfm1wEAAPAnBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABAYaAAACAw0AAAEBhoAAAIDDQAAgYEGAIDAQAMAQGCgAQAgMNAAABBs9VICxouk7A8AAAAASUVORK5CYII=";

                switch (color)
                {
                    case ColorUI.Blue:
                        return Blue;
                    case ColorUI.Gray:
                        return Gray;
                    case ColorUI.Green:
                        return Green;
                    case ColorUI.Red:
                        return Red;
                    case ColorUI.Yellow:
                        return Yellow;
                    case ColorUI.BlueLight:
                        return BlueLight;
                    case ColorUI.GreenLight:
                        return GreenLight;
                    case ColorUI.YellowLight:
                        return YellowLight;
                    case ColorUI.White:
                        return White;
                    case ColorUI.Pink:
                        return Pink;
                    case ColorUI.Orange:
                        return Orange;
                    case ColorUI.Brown:
                        return Brown;
                    case ColorUI.Purple:
                        return Purple;
                    case ColorUI.Turquoise:
                        return Turquoise;
                    case ColorUI.PinkLight:
                        return PinkLight;
                    case ColorUI.BlueSky:
                        return BlueSky;
                    case ColorUI.Black:
                        return Black;
                    case ColorUI.RedLight:
                        return RedLight;
                    case ColorUI.GrayLight:
                        return GrayLight;
                    case ColorUI.OrangeLight:
                        return OrangeLight;
                    case ColorUI.YellowDark:
                        return YellowDark;
                    case ColorUI.GreenDark:
                        return GreenDark;
                    case ColorUI.BlueDark:
                        return BlueDark;
                    case ColorUI.Aqua:
                        return Aqua;
                    case ColorUI.Tan:
                        return Tan;
                    case ColorUI.GreenDarkness:
                        return GreenDarkness;
                    case ColorUI.BlueViolet:
                        return BlueViolet;
                    default:
                        return BlueSky;
                }

            }

            private string GetColor(ColorUI color)
            {
                MethodInfo methodToInvoke = GetType().GetMethod("GetFilled", BindingFlags.NonPublic | BindingFlags.Instance);

                object[] parametersInvoke = { color };

                var returnStringColor = (string)methodToInvoke.Invoke(this, parametersInvoke);
                return returnStringColor;
            }
        }
    }
}
