//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laavor
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CloseFilled {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CloseFilled() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasePackage.Closes.CloseFilled", typeof(CloseFilled).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAvGSURBVHic7Z17sJVVGcZ/e8sRdICEEi+JWJraRU0t5WBOXkgrZLSaNE9Z4pQZTKaYmddqKmwMLBsHMSvTwrQsTTHNC94KKzUpuwDTBZQAndAKiGMcz+6Ph2/cMsDZe3/P+tb6zt6/f5xx9n6+j/O+e613rfWu961Qq3UD3wX2pkM7sQQ4tUKttgjYJ/bbdIjC4gq1Wj9Qif0mHaJQq9IxfjtTqcZ+gw5x6ThAm9NxgDan4wBtTscB2pyOA7Q5Qxr9YBU4D3hFgJf4BTAvgG4Z6AH2N2uuAy4F+hr4bMMO0A8sAn6Mf+Pgk8B44EmzbupMBK4HtjFq1pBTNWJ8aHIKuAWY2ewbNcD2wA+B4QG0U2U3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAykSURBVHic7V1pTFRXG37vZUbUgsogi1TUuqHWtZooLrUYtHWLS7QajU1NWzU21VBDsSlpcGlQq1Zb4x5tTFyjUZEYo1JXMGpNbaOCKzgooAXagogdYJ7vx3xj6vdZmeU999zL3Cd5/s3c877P+3C5c+457yEiiieim0QEkwHFm0QUrxBRHhHFkYlAxE2FiJxEpMiOxIQUQCHX7cBEgEKVHYAJuTANEOAwDRDgMA0Q4DANEOAwDRDgsHj6QVVVKSUlhZo3b84exPnz5ykzM5P9ukbAtGnTqGfPnqzXrKqqovT0dKqtrfXo8x5PH06YMAFOpxPcqKqqQo8ePWRPjWrOxMRE1NbWsmrpdDoxdepUb+Lw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAu6SURBVHic7V17kI7lG77ez65Fu2RZKzlF2ZWQQ8NaJaWDZKiJjKaGqTBMNTtGajKNotmKimqiw8hoKIaS1BiHKNbGpiM5VVjsSqiYteyuvfrj+X2Dfjv2O9zPe7/v933XzP3ffu9z3dd97fs+7/M+BwdgDoD5ADoggXjCHgCjHIC7AGRps0lABbsdgNUAHG0mCaiADkBqs0hADwFtAgnoImGAOEfCAHGOhAHiHAkDxDkSBohzJIX6h4EAMHky0KiRPIlNm4CVK+Wv6weMHAl06SJ7zbIyID8fqKoK6c/JUOOee8jqaoqjrIzs3Dl0HrESAwaQVVWyWlZXkyNGhMMjTNIvvyxLOIidO8nUVP2iuBUt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABFuSURBVHic7Z13XBR3Gsaf3aUXAREEERFUsBvkvKh4Jjn1bMGzIqJgQ410BFEhsWBXmqCLhURUgmgsieVMYizxrLFgLCjFjtJEQEDqsvcHn80RorjlnZ1Z2e+fuvPMAM/OvPP7vYWHzpMGoB5JAOyhpiWRCT5m8GA36T4AB7avRg0rZPCh/ua3ZOz5AHhsX4Ua1uDx2b4CNeyiNkALR22AFo7aAC0ctQFaOGoDtHA0pP0gn8/DonljYWSoR34R56/dx7HT18l1VQH3MYPQu6sNqWbFmyqsTfgedSLRez8rtQHq68W4/+A5DgqDwePRLh34eY5A/wnhuJ3xlFSX6wx17oXdkb4QCOhuxGKxGO6BcVL9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDark {
            get {
                return ResourceManager.GetString("BlueDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAt0SURBVHic7Z1ZXxNpFsafVELYBUG2sBjBRlodbXFre77M9Deb6/4Ocze/XtxbbRGmRWRfBMEYiCHLXJzU/HoQSFXqOfW+RfK/FU5K8lTVec8a++lp+QFK+CeASTSoJ+bg4B+xnx6X3wC4YvpqGhhh1kHjzq9nJh0AMdNX0cAYMcf0FTQwS0MAdU5DAHVOQwB1TkMAdU5DAHVOwusPxgBcGQSa4vyL+PAZWNvj240CYz1AVyvXZrEEzKwD5XL1n/UsgDKATA74YSLAlZ1AsQT86w2wd8C3bTMD54B7aSBGjsT8+s7blw/4fAWs7AKzG7Vc0unEHeDBOJCooxdSaxK4f4n/5c9uAEs73n/e95/85Qqw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLight {
            get {
                return ResourceManager.GetString("BlueLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA0iSURBVHic7Z3pd1TlHcc/MyGEkEAikcWwRFmC7EtEWaIgAu5WK+JWrSjV1qVqtX3TP6DntNbirmiPaK3aKhbFajWCILvsiyAgyhrZAgmEJBCS6Ysnc8RIkrlzv8/ce5P5vPJ45n7nhvnee3/3eX5L6KYXI6MIMRPIJ0lLYisR7goT4lWSP35LJJ8Qr4ZJ/vgtmfwwEPL6LJJ4Rijs9Rkk8ZakAVo4SQO0cJIGaOEkDdDCSRqghdMq1g+GQnD9EGjbWn8SX++DVbv0ukGgsDfkddBqVp2C2Wuhprbpz8ZsgEgE9pbCY5P0CwdXnII/zoZdh8XCPmdQV3jwUggL/0EjwNNzY/vxweEj4MsdMGed85Nq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSky {
            get {
                return ResourceManager.GetString("BlueSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA9fSURBVHic7Z15eBN1Gse/M0nTNG2SNgkIBYGCgCxiAaEclcopR2mp7qO7Lq7Cqvug7nJJAUEUBaQcFcq6j7geoCu7LquPQMupnEVKyyFlPTisQIFyJT3SNm3TJLN/DOWBStsc7y8zafP5u/PLdOY783vnPbkVvS4Ncrlc6zmgG4K0GATgDM/zk3jB5VwXvPktDw7oJric63iAC978FgvXjQfASX0aQSSD46U+gyDSEhRACycogBZOUAAtnKAAWjhBAbRwlO7+IccDA57TQRVB/9V4+bgdBfuryNcNBHokatCqWwjpmrVVAnI/sMLlbPpv3RaA4AIsv9QiZbWJ3HNQO1HAhqeu4cbZWtqFZU7HQWok [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABFUSURBVHic7Z1nXFRXGof/UxhGmhRDkxELYse4Gmt0jcFKNEoXu7ubQhLUxIJoDGABFU1sqJvsGsVCt8W1BXvvsUVZg4CIdKTDMMzshwn+WFSc8t65d2Seb+rc595k/jNz7rnnvC8vvBcGyPn4GYArDDQnUvlyTOfL+dgGw5vfHHGV87GND8Ob35xx5QPgsX0VBliDx2f7CgywiyEAzRxDAJo5hgA0cwwBaOYYAtDMEar6Qh6fj0HTFkBs1pL8IjJvnUPq2V/IvfpAj1EBsOvoRuqUVlXg3LYIyOtkb3ytygFQyOUoSH8A31VJ4PFopw76+n2Fn6b3R96jO6RertO+rzsmhO8Ajy8gcyoUCiQvClDp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA4OSURBVHic7Z3rUxNnG8avDQdDkwYL1NgSWkSJVoq1FYkC0lSQg2kVlBD77e2/0r+jM30/dSQJGmwZQQ0WG0UqOB0LFlNLEKNFxHIwEZqGpB8y21EEks3eT3YX8vuo2WsXcu1y7/PcB+7rr78+HIlE/g/AiDSbCa9KpfqfKhKJfIv0l78ZMUYikW9VSH/5mxmjCgAn9VWkkQxOJfUVpJGWtAE2OWkDbHLSBtjkpA2wyUkbYJOTmegHOY5DdXU11Go1+UVMTk7C6/WS6yqB8vJy6PV6Us1QKASPx4NIJBL3swkbIBqNYmZmBu3t7eA42qWDyspKfPPNN5ienibVlTslJSVobW0l/X1Go1GcO3cuoS8f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAqkSURBVHic7Z3pVuJuEsafBGQREEURZDORPv+5hrmb+d/ZXFCf/tzTp1lEAXEFMRq2MB88mePQLlmq8r4Bfp+lTNsPSaXeqqeUHz9+/NOyrH8D+AtbNolfqqr+S/n+/ftPAP8QfTVbhPAfFdtv/ibzlwpAEX0VW4ShqKKvYItYtgLYcLYC2HC2AthwtgLYcLYC2HCibn64WCwiEomQX8TT0xNGoxF53DCQy+WQTCZJY1qWhaurKyyXyy9/1pUATNNEvV73fGEfYVkWfv78iZeXF/LYMrO3twdN06AotKWYVqvl6D8fcPkIGA6HGAwGni7q04tQVZydnUFVN+eJFIvFoOs6+X/+YDDA/f294593/Rfv [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLight {
            get {
                return ResourceManager.GetString("GrayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALaAAAC2gBrbTBJwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABFUSURBVHic7Z15VFNnGod/CQEiBGRRQCWCiqh1G2tbWapHK2qVYhEIARRF29opPaJtHcdipyOO1lrRnlIPau20rghhdeFoSwF3cKnj1GWQOrKIrAIqIIHEZP7gpIdBxSzvzb0Rnv/a5j739vBL7ne/+33vy8M6eEOF3QA80UtPohh8RPGwFkUARrB9Nb2wwk0+er/5PRlPPgAe21fRC2vw+GxfQS/s0huAHk5vAHo4vQHo4fQGoIfTG4AejkDbD/J5fPzV96/oK+xLfhFnys/gaPFRcq8pEDE2AuOcx5E6W9pbsPHMRihVyud+VusAqNQqFN0rQnpoOng82qmDZa8tg9f3Xrhae5XUy3X8hvph77y9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABGKSURBVHic7Z1nXFRn2of/M0MvAiIIIiIWsBtk3ai4Jll1jRpdKyIqKqIGpAqiQmLBrjRBBzXEShCNJbGsSQxqXGuwxYJSrKA0ERCQOjPvB37jy6LClPvMOSNc35LMuc6TH/8585xznue+eV0mY6AY2A3ADi00J9L5wCxep8l4AMCe7dG0wAppfLR885szdnwAPLZH0QJr8Phsj6AFdmkJQDOnJQDNnJYANHNaAtDMaQlAM0dD1g/yeXzMH7cYhnpG5IO49uACzlw/Qe5VB8YOdkU3mz6kzjeV5Yj7aR1EotomPytzAMQSMR4+fwBh4GHweLSPDty+9MHE0AFIe3aH1Mt1nHoPQ7j3Xgj4AjKnRCKB [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDark {
            get {
                return ResourceManager.GetString("GreenDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABJbSURBVHic7Z1pXBRX1of/3ayiKIsgBJFAEIy4gRuCyYsjatwYREHE4K4RTHDLi4nJuG8ZASdoEEcjRhERWVQwEpFFRtkU0YhGCCooKqgsLkiTbrrnAz/y9mtUejnVVS08H5Oup+7Pe6g6dZdzebDFCIhxAIAdOmhPlIKPOTzY4CYAe7Zb0wErlPBgAzEAHtst6YAVJHx0dH57hsdnuwUdsEtHALRzOgKgndMRAO2cjgBo53QEQDtHU9Yf8vl8rPpsFbrpdyNvxPlL55GSkULuVQf8PPwwoM8AUmfDywZs3b0VomZRm7+VOQDEYjFu3rqJhIgE8Hi0QwdfzPoCzlOdca3kGqmX67i7uuNgyEFoaGiQ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkness {
            get {
                return ResourceManager.GetString("GreenDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAyTSURBVHic7Z15bFVVF8XXe/RR0AJShFZkcgRFRQYDpSqiOAIRjSDBaCQOGImYhlQ0EoOiqQN+ghrAIWo0oBJQRCRGRXAARJwVmVSgQAsIqJCCttDf98ejBLTQN+xzz3v0rfVv39lrr31677n3niEkVCDpFUmnK4P6hNWSbg4JrZTU0beaDLxgVUioWlLIt5IMvICQEL5VZOAPYd8CMvCLTAeo58h0gHqOTAeo58h0gHqOTAeo58iK9Q/DCmuMxqiZmpmL+Fyfa67mmrebDhimYTpH55i2WaEKlahEe7U3hr8mdl7DNVRTjTUqqOBszo5DydHBfvRjL3tNvaymmqEMjV1FvKIf53FTwTVYwQpyyPFe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLight {
            get {
                return ResourceManager.GetString("GreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA2nSURBVHic7Z15nI31Hsff55gxE0aGGhQRIpE2uWi5lT3XkiXMNWUd2+uWNsltvy2U6pKXJWRNlpgKqYioW7q6JS2YImUn+zrNmHP/+DmSbc7y+Z3nOTPn/ZflPJ/nmTmf53l+y3fx+HpRDx8TgarEKEhk4qGLx5fOGqCa01cTwxHWeond+QWZql7A4/RVxHAMj9fpK4jhLDEDFHBiBijgxAxQwIkZoIATM0ABJy7gT3q80PRhOO98/VX89CmsmqfXjQbqpEK5WlrNrEOw4HnIzcnzo4EbwJcL29ZAr9ngES8d3PoPGFwXNn+r1XU71RtC18ngLaTT9PlgfGpAXz4E+wr4OgMWDg3lss5N4SKQPhMS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAyJSURBVHic7Z3rWxTnGcbvWZaTIAooqKAiyIoKHkmMh1harYfYJqk5td+af6V/R68r/dSrORnT1Csao2kSa9LEs4AIiKKIoCDIeXHZ7YdnlxpEdmfnfud9h93fR9i5d2DunX3mfZ+DFfniLzuB8N8ABJAmlWgFfH/2AeEPkL74qUgACH/gQ/ripzIBHwBL91mk0Ybl030GafSSNkCKkzZAipM2QIqTNkCKkzZAiuNP+JWWBVTtBjJz+Gfx+C7Q28rX9QJldUBBKVczNAm0nwMi4bgvTdwAkQgw0gfUvwv60kHFy8C5vwLDD7m6prOkEtjyB/lw0YgAl44ldPEBu18BPS3ArR+SOau5ycgEtr8D+LP4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLight {
            get {
                return ResourceManager.GetString("OrangeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAvHSURBVHic7Z17sJVVGcZ/e8MRZJCEEtRELE3soqaWcjQnvKSVMlJNmpQlTpnJRIqZea2mUsfQsnEQszItCMvSFNO84K2kUtKyCzBdAE3RCa3QOHaOZ/fHwzduiePZ+9vP+tb6zt6/f5xx9n6+j/O+e613rfWu963UqHUD3wF2pUM7sRI4vlKjthyYHPttOkRhRaVGrR+oxH6TDlGoVekYv52pVGO/QYe4dBygzek4QJvTcYA2p+MAbU7HAdqc4Q1/sgqcAbwiwFv8HFgcQLcMzAD2MGs+B1wA9A3+0cYdoB9YDvwI/87BJ4EpwCNm3dQ5FLgGGGbUrCGnasD40OwUcD0wt9k3aoBRwA+A0QG0U2UH [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAt0SURBVHic7Z1ZXxNpFsafLISwCRLZwmIEG2l1tMWtdb7M9Deb6/4Ocze/XtxbbRGmRWRfBMEYiCHLXJxU/7pZq1LPqfctkv+tcFKSp6rOe9ZI5cdnD4DyvwGMo0E9MQNE/xWp/PjkLYArpq+mgRGmo2jc+fXMeBRAxPRVNDBGJGr6ChqYpSGAOqchgDqnIYA6pyGAOqchgDon7vonIwCu9ANNMf5VfPwCrOzw7YaBkW6gs4Vrs1QGplaBSuXUH3UvgAqAbB54OObjyo6hVAb+8xbY2ePbtpm+c8C9DBAhh2J+ee/qywe8vgKWtoHptVou6WRiUeDBKBCvozdSSwK4f4n/5U+vAQtbrn/c+1/81RKw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLight {
            get {
                return ResourceManager.GetString("PinkLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABB7SURBVHic7Z15WFTn2cbvc9hlBEQEDBApChqJmsSFxeVCRVAJhm0YYmI0aZu0yZWlqbHWNKnarI1JvtheNtv3mcRGYYYBXLjEIBAURSL6WUWD1AgiIjsCM4AwnOkfk7HGIMzynDlnYH5/Jue9z4vnnpn3vO+zMFuxNYID9wWAENgYTVSxYNexHLidsD380UgIB24nC9vDH82EsAAYoWdhQzAYVugZ2BAWmwFGOTYDjHJsBhjl2AwwyrEZYJRjb+iFDMtg/h/mw9ndmXwStSW1qDpQRa5rDcxYPQM+M31INfvUfSh5uwSchhv2WoMNoOW0aKlsQaoyFQxDu3Uw7/l5+Dz8czSdayLVFTtB0UFI/CoR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAvHSURBVHic7V1pbFVVF1330VLAFqTQQaQFQWkRBRlMaYsiigNiQzWCDUZDowKBqGkIopEYFExVUHGI4BAkGFAIKNZqCFBBoVSoOFLLoAIF2lqhKk0ptLTr+3HyIvg18IZ97rn3vbeS/a+5Z521V+879wz7WAQyASwHMAARhBP2A5hiEdgLIM00mwiMYJ9FoA2AZZpJBEZAiwBNs4jAHDymCURgFhEDhDkiBghzRAwQ5ogYIMwRMUCYI8rnv/R4gDlzgG7d5Fls3w4UF8s/1w2YPBkYPFj2mY2NQGEhcPbsxf+WAH2Ou+8m29oojsZG8tprfecRKjF2LHn2rKyWbW1kXp7PHPwzAEC+9JIsYS8qK8nY [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAvlSURBVHic7Z3rV1RlG8avGQ5C0GBgUjEUaoyWYZYoimgUhAdK7Vzf3v6V/o7W6v3U6hxWrPAAppFUgqtlYEQmWmiIGocGIYKZ98O99ptymJm99/Xs59nM/D7qzD0b5tqb+7mPgfhbb+1ALPZfABFkSCcGEAz+J4hY7B1kvvx0JIJY7J0gMl9+OhMJAgjovooM2ggEdV9BBr1kBJDmZASQ5mQEkOZkBJDmZASQ5mSn/MpAANi5E8jL41/Fb78BAwN8u36gqgooLeXanJkBOjuBWCzpS1MXQDwO3LgBvPqqiIHJtm3A228DIyNcu6azdi3wwgvc32c8DnzySUpfPmD3T0B/P9DV5eSyEpOTA7zyCpCb [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLight {
            get {
                return ResourceManager.GetString("RedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA7lSURBVHic7Z3XW1pbGsZfmoCixF5iibEX7IAYYyzJ0WT+iTn/09zOc+Z65nJmoim22EDFqGis0STWWGOjiMBcEJ0cYxTY32JvlN9dnrBfVsLL5ttrfUX0z7//zSCG5x8A8hHmLjHvhuivYjHwB8If/l0kXwz8IQY84Q//zuLJFwMQ8b2MMLwhEvO9gjD8EjbAHSdsgDtO2AB3nLAB7jhhA9xxpL6+UCQSIV9TBVmEnHwRu1/XsbHyiVw3FMjIyYc6NoFU03XmxOykGR63+8bX+mwAj8eDo4N9GFpecFrcVbjOytD973/hYH+XXFvIJKVlQNvwDCIR7VbMcM8rnz58wM+fgPXPS5i3jAW0qOuQSKXQ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABAISURBVHic7Z15WFT1Gse/57DLCIgGFJCEgiaplQuIy4NJoE4qIMOQZdp+q6fdzGy5antZ3azH1pumpTDDpukjhmAoiuRyu4qGXBNEVBYBgRlBGGfuHzA9Rggzc97fnDMwnz/1nO85er4z857f7104rFo1CXr9egChsNOfKAXPL+ah16+D/eH3R0Kh16/jYX/4/ZlQHgAn9l3YEQ2OF/sO7IiL3QD9HLsB+jl2A/Rz7Abo59gN0M9xNPVAnuPw8uTJ8HR1Jb+JgooKbCstJde1BRaMHo0xvr6kmtq2NrxbUACdXt/rsSYbQG8woOTiRaQnJYHjaJcOnp44ERHffotjNTWkulInOjgYG+Lj4UD4/2kw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA3nSURBVHic7Z1/TFXlH8c/93pvXpBbAQpcfgiVE9SshoFc1ELUOYcU06JiY2m/1M20MkvTYo1Wyhxmixmz2beWabqyJG3GYlj8ahIl0xAzQ0z5EZcplxDv9Z739w/Xd/r98s177vk854fc13b+Y+d5P5/z4pznnh/PYwLgJKJ/EdF4CjKcOEFEi0wAjhNRstZpgmhCqwmAREQmrZME0QSYKXjwhzMms9YJgmhLUIBhTlCAYU5QgGFOUIBhTlCAYY7F3z+UJIk2btxIFy5cYA8xffp0mj9/Pvt+jcAnn3xCzc3NrPscNWoUrV27liwWPw4vZPD555/DZDKBiFi30NBQNDc3y4lyQ1BZWYkRI0aw1tJk [rest of string was truncated]&quot;;.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAvHSURBVHic7Z17sJVVGcZ/e8MRdNCUEtRELE3soqaWciAnUdIKGakmCcoSp8xkMsXMvFZTYWNo2TiKWZmWBGVpgmle8FZSKWnZBZgugKTohFRAHjvHs/vj4ZtzRODsy7O+tb699+8fZ5y9n+/jvO9e611rvet9S5UKncB3gQNo00qsAE4pVSosA8bEfps2UVheqlToBUqx36RNFCpl2sZvZUrl2G/QJi5tB2hx2g7Q4rQdoMVpO0CL03aAFmdw9R8tA+cBrwjwGr8AFgXQLQLTgYPNmpuAS4GeAT9ZgwP0AsuAH+PfOvgkMBZ4wqybOhOBG4FBRs0KcqqBjQ81TwG3AHNqfaMq2An4ITAsgHaq7A3M [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA1xSURBVHic7Z15dFTlHYafmUwWkpAAgWwQslGwmz2trYq2PbXaWuvh6HFDqSiotYpHxQ0R61r3olb0oNS24o67Vns8PSpqF5fKsba2ClSSEBKSEEgISSDLZKZ/fJeIbJnl/ebeSeb5T5n7zgf3vXO/5bf4wh8ynRDLgamkGEmsxc8cX3gVq4Fpbo8mhSus8YVXEQJ8bo8khSuE/aRu/kjG53d7BCncJWWAEU7KACOclAFGOCkDjHBSBhjhBCL/qB+Kr4S0fP0ouv4GHa/odZOBcbNg1IFazVA3NN8K4eCQH43CACHoWQ3VzyHfOghdCKsPhR0fa3W9Tt5RUPEI+NKEomGonRXRzYdoXwFbX4CWxbGM [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDark {
            get {
                return ResourceManager.GetString("YellowDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALYQAAC2EBW3krpgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAArUSURBVHic7Z3bfhPXFca/GY2k0cgUihMHnIa0gRgHKAQCNKQv07xZr/MOvesvaeKEGEI4uA1tQhKCE7tQW6PTHHqxRyIG25rDt2bvkfS/RbM0WN/sWXvtdbDirY9uwMZfEWMFc2YHCxuI8Bcr3v7oPoCzuu9njhYe2MD8yZ9hVmwAlu67mKMNy9Z9B3P0MhfAjDMXwIwzF8CMMxfAjDMXwIzjpP+oBbhnAavOv4vgF2D4mG+3CjROAbWjXJtxCPTuAYgnfjSDAGIg3AEWPsh/YweaDoGdvwHhM75tk6m/BrSvgx6K6fwDaX58IOsrYPgD0HuQ444mYNWA9g3AyqDHqmO3gPafQP/xew+AwaP0t5H5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLight {
            get {
                return ResourceManager.GetString("YellowLight", resourceCulture);
            }
        }
    }
}
