//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaavorAccordion
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StampFilled {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StampFilled() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccordionConception.StampFilled", typeof(StampFilled).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABK1SURBVHic7Z1rktw2EoSz5yWNrL2H91Ar//UJHLEn2AifwH/tPZR8EFmaR89wf7AzkKwBCYBkk611fhEMvkA0ZzSdqkIVCgcAQNf9C8C/AfwTxhhjAOAzgP/gcPjvAV33CcDve7+RMcZcKD8d0HWfAfwIAB8BfNj3hYwxZne+AviSTv88oOuOAK4B4FcAP+/yWsYYczn8BuCXdPpyQNd1u72NMcZ8B1zt/QLGGHPpWCiNMaaAhdIYYwpYKI0xpoCF0hhjClgojTGmgIXSGGMKWCiNMaaAhdIYYwpYKI0xpoCF0hhjClgojTGmgIXSGGMKWCiNMaaAhdIYYwpYKI0xpoCF0hhjClgojTGmgIXSGGMK [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABRSSURBVHic7Z1LcuPMsYUP+Calf+g9+C7q2tOe34iO8Aoc0SvoqcMr8uj3yKvopvgACQ/kUzpIASwABB99fb4IBPEoFCFKPMqszMoq8M7/AvgLgP+BMcYYAPgdwF8B/L0A8CcAf3vs8xhjzNPy5wLvqvlHAHh9fcVms3nsIxljzIPZbrf48eMHD/9ZACgBTAHg27dv+PLly6OezRhjnoLv37/j69evPDwVAKoHPo8xxjw9k0c/gDHGPDsWSmOMyWChNMaYDBZKY4zJYKE0xpgMFkpjjMlgoTTGmAwWSmOMyWChNMaYDBZKY4zJYKE0xpgMFkpjjMlgoTTGmAwWSmOMyWChNMaYDBZKY4zJYKE0xpgM [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABNJSURBVHic7Z1bkttGEkUT3SSbbLX3MbOokX+1AjtmBROhDdi/9ixKXojU4hvzUXFVF9kFVOFBgD2+JwJBPApFkGpeZVZmZVVmZmb1v8zs32b2TxNCCGFm9sXM/mNW/bcyqz+a2R9LP5EQQtwpP1dm9Rcz+4eZ2cuL2fPzwo8khBAL8/pq9vXrj8O/KrP6bGaPZmafP5t9+rTUowkhxH3w229mv/764/BSmdX1gs8jhBB3z8PSDyCEEPeOhFIIITJIKIUQIoOEUgghMkgohRAig4RSCCEySCiFECKDhFIIITJIKIUQIoOEUgghMkgohRAig4RSCCEySCiFECKDhFIIITJIKIUQIoOEUgghMkgohRAi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAB1QSURBVHic7Z3LkutOct6/ugAg+z+O8EYPoHEoYhx+jnkDzUYhyVuttFGELhtvR/IL2FvFWN5ITyA9hTYareRH0GbmHBKoqtQiK6sAEDeyu8mecf4i+jRJFApodvM7mZVZmQYA8Ls/+yNY/BUI/xWKoigKYPBLJPwc/+/vf2HwX37/j0Hmb199T4qiKF8SQ//d4Mc/+yWAnwDAj95OeDt3L74rRVGU1/Lt+xW/+naRp//qAfyePPsff/r7+JM/+OlLbkxRFOWr8L/+7h/xF3/zd/L09wx+/DN65Q0piqJ8deyrb0BRFOWro0KpKIqygwqloijKDiqUiqIoO6hQKoqi7KBCqSiKsoMKpaIoyg4qlIqi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueDark {
            get {
                return ResourceManager.GetString("BlueDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABMASURBVHic7Z090uS4kYZfoL69wVgKeYqJ0K6x3hxF6+3oHDrBnGMkT3uUWUuGJhQKeYqNNXQDdSFlEAkmkiABsqrI6u73iaiuPwBkVRefL/EfAOCPP8l/I+B3AP4dhBBCAOBnCH74r+/CH8L//CTfS8CPV58RIYS8I0Hw2w+ZIkkAwEcEbvHKUyKEkOu5J+BTmh5LwO8+AHyrb/7HL4BffXPRmRFCyJvwt38Af/p7efpt+OP/ilx4PoQQ8vawok0IIR0oSkII6UBREkJIB4qSEEI6UJSEENKBoiSEkA4UJSGEdKAoCSGkA0VJCCEdKEpCCOlAURJCSAeKkhBCOlCUhBDSgaIkhJAOFCUhhHSgKAkh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueLight {
            get {
                return ResourceManager.GetString("BlueLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABcPSURBVHic7Z1Nkuy4dYUPSFa+txFF2Bp64hVoB+qZ1Zo5tIVeQW/B8kxyaGStQDvQBtReSr8qEvAAOMAlEvzL/2qdLyLfyyRBAMwqnrrAvbhwAPDdf4ffIeAHAP8KIYQQAPATHH783/90/+N++1/he+fwp2f3SAghXpEQ8PvBOfzAA1/fgC/DM7skhBDP59sI/PwR3zuHHwYAv+LJ3/4b8JtfP6lnQgjxIvztH8Bf/p4//sp998cQntgfIYR4ebpnd0AIIV4dCaUQQmwgoRRCiA0klEIIsYGEUgghNpBQCiHEBhJKIYTYQEIphBAbSCiFEGIDCaUQQmwgoRRCiA0klEIIsYGEUgghNpBQCiHEBhJK [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueSky {
            get {
                return ResourceManager.GetString("BlueSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABwmSURBVHic7Z0/jizJcca/yKrumbckIN1gLQISKIOuLN2CnihbtgASPAEhGrwDKYvH4A1oiFi5lC5Ag9h901WZISMis7L+V/fMdM/jfj/gvenuysqq6Zn+JiIjMkIA4D//6c//Kiq/BPCPIIQQAgDfqOivfvHfX/+X/PrHf/4ZIL999B0RQsjHRP+tBcIvAQUAnL8StM/y4JsihJDH0n9WXL5VfxZ+2QL6o3zwn//97/CTn/7wQbdGCCEfgz/+/q/4w2/+4s/0R/LrH/+vbp5BCCHfc8Kjb4AQQj46FEpCCNmBQkkIITtQKAkhZAcKJSGE7EChJISQHSiUhBCyA4WSEEJ2oFASQsgOFEpCCNmBQkkI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAByISURBVHic7Z29kuzAdd//3Y2P2UsqdORYVVYs5i4HfgOmthIFipyoilVKbCpilUNFTFlK9QZM/ABMHNGRQj0Bee8OgO6j4JzT3cAAA8zs7MySPr+qvbszaDQwc3f+e7rPlwOAf/wZ/hsR/gHAX8EwDMMAgN87h1/9r9/hn90vf4b/DsJvXn1HhmEYXxKHv2nAliQAoPv2U7Snb6+8JcMwjJczvn/H8P0P/IDwDw2Av9SD//lv/yd+9vO/e9GtGYZhfA1+9y+/xm//6Rf68C/dL/8a9MobMgzD+Or4V9+AYRjGV8eE0jAMYwcTSsMwjB1MKA3DMHYwoTQMw9jBhNIwDGMHE0rDMIwdTCgNwzB2MKE0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA+XSURBVHic7Z07kuNGEoYTJNg6wR5BEbv++AoZc4zdPcRastSydA6FjjGO5MgaZy0ZitiD8IU1FD87maxCFd7s0fdFIBpAPQB2D//JrKzKaszMfvjhh392Xfedmf3DAADAzOz3pml+/P77739uXl9f/2VmP239RgAAT8q/WzP7TlcvLy92OBw2fB8AgO05nU52PB51+V1rZl/r6ptvvrEPHz5s8mIAAM/C58+f7dOnT7r8unl9fe22fCEAgGdnt/ULAAA8OwglAEABhBIAoABCCQBQAKEEACiAUAIAFEAoAQAKIJQAAAUQSgCAAgglAEABhBIAoABCCQBQAKEEACiAUAIAFEAoAQAKIJQAAAUQSgCA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAvmSURBVHic7d1JbtxYEsbxSKaOoJXhbQHdB8jjlOscPoHPUdXHkfde1NY2DNhXEFmLrpAiQ/EmTo8p/X+AkBKHR2ZK/vwmkicRkYeHh99Pp9NHEfmvAABERL5M0/Tpcrn87/Tw8PDhdDr92fuMAOCIpmn64+7fmqSIiAzDIMMw9DwnAOhuHEcZx1FERE6n08c7EflNV757907u7+97nRsAHMLPnz/l27dv+uNvp8+fP089TwgAjo52NgAUEJQAUEBQAkABQQkABQQlABQQlABQQFACQAFBCQAFBCUAFBCUAFBAUAJAAUEJAAUEJQAUEJQAUEBQAkABQQkABQQlABQQlABQQFACQAFBCQAFBCUAFNz1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrayLight {
            get {
                return ResourceManager.GetString("GrayLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABmASURBVHic7Z27cuxIcob/qgLQ3Zyzph5hIyR/fYUMPYYkd3xFTMQ6q5E1EfsE427sY6yjB1hH1srSU5xDsgFUlYxCJgogrn3ljP7vDGMaQOHCJvtnZmVWpgEA/Cf+BRG/B/APIIQQAgB/g8FP+A/82eBH/CuAPz37iQgh5JPybwWA38vWl+oLXsqXJz4PIYQ8n9fmFV/rr7L5+wLAb2XrD//4B3z/u++f8mCEEPJZ+PmvP+OHv/wgm781+BHxmQ9ECCGfHfvsByCEkM8OhZIQQlagUBJCyAoUSkIIWYFCSQghK1AoCSFkBQolIYSsQKEkhJAVKJSEELIChZIQQlagUBJCyAoUSkIIWYFCSQghK1Ao [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAB1HSURBVHic7Z1LkizLUYb/eGRWdV9hxoQFIAwzMNbBDnQnMh5TjZhgxmPCVMAGYCoTMIEVwCqYII3EEphI51RmRoQz8PDIyKx8VXV3VV/Jv3PPPV2VkZFZ1V1/e7h7uBsA+N1v8acW+FsC/hCKoigKDPCzBPz4f/8dPzW/9wP8GRn85Nk3pSiK8hkxhD833/8WPwPwBwDwev4eXk6vT74tRVGU5/K1+4Ivl1/Kw597AL8vj/7iB3+HH/7xj55yY4qiKJ+Ff/3Pf8I//Otfy8PfN9//FvTMG1IURfns2GffgKIoymdHhVJRFGUHFUpFUZQdVCgVRVF2UKFUFEXZQYVSURRlBxVKRVGUHVQoFUVRdlCh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDark {
            get {
                return ResourceManager.GetString("GreenDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABnJSURBVHic7Z3LjuzIcYb/TN6q+hwB3vgBPNqMX0mApe3sDQzkJ7AwTzBbQYDex6vRSn4Eb2a6i2RevMiKYJLNa3V1V4/0f0CjimTy0nVO/R0ZERlhAAD/hv+AxX8h4t9BCCEEMPgJAf+N/8VfDH6L3yPiz49+JkII+ZQY/MHgG/wE4FsA+Pr0FU/npwc/FSGEPJbnl2f8/PyzbP7N4Bs4AAUA/PDHH/Dd77572MMRQshn4Me//ojv//S9bHqDbxAf+UCEEPLZsY9+AEII+exQKAkhZAMKJSGEbEChJISQDSiUhBCyAYWSEEI2oFASQsgGFEpCCNmAQkkIIRtQKAkhZAMKJSGEbEChJISQDSiUhBCy [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenDarkness {
            get {
                return ResourceManager.GetString("GreenDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABOcSURBVHic7Z1bduPIsUUPxYdIVXkevoO67d8eQa/lEdy1egT9a99BlQdSLfFNf0gndRCVQCZAkGDZZ+ODeCQepMijiIzIyBkA4IL/BfB3AP8DY4wxAPANwP9hhv+f4YJfAPxj6icyxpgH5W8zXPANwF8B4Cu+4gUvEz+TMcZMyyte8R3fufmvGS44ApgDwO/4Hb/i18kezhhjHoE/8Ad+w2/cPM1wwWXKBzLGmEfnaeoHMMaYR8dCaYwxBSyUxhhTwEJpjDEFLJTGGFPAQmmMMQUslMYYU8BCaYwxBSyUxhhTwEJpjDEFLJTGGFPAQmmMMQUslMYYU8BCaYwxBSyUxhhTwEJpjDEFLJTGGFPAQmmM [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenLight {
            get {
                return ResourceManager.GetString("GreenLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABgNSURBVHic7Z1LkuQ4coZ/PiIiq7p1jDEbXWJOoJ3Waq3UmhNIpo22bTYXkMa0mtFauoN0iZqD9HRlBB/QAu6AE0ESIOOVpfk/s7CMIEEQGVX80x0OuFcA4P4Bf4cK/wLgr0EIIQQAvsDhp+o/8J+V+0f8AIc/vHpEhBDyIanw95X7EV8A/BoAcPoeOH5+7aAIIeTVXH4Bzj/rpz+1AH4VTv7NvwK/+e0rhkUIIR+H//k34L//WT/9qnI/wr1yPIQQ8tGpXz0AQgj56FAoCSEkA4WSEEIyUCgJISQDhZIQQjJQKAkhJAOFkhBCMlAoCSEkA4WSEEIyUCgJISQDhZIQQjJQKAkhJAOFkhBCMlAoCSEk [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABSESURBVHic7Z0xsus4doZ/kLrtZUzUVZ58ckcOxztwex0duR31Oma8A086ySROZgEv6CpXzTbeFQkHxAF/gCABUpSo1/1/VXq6IkGA0rv67zk4BwcOAPz//Ne/w/kfAfweQgghAOALvPvZ/dt//rfzf/npBwB/uvqOhBDiTfmPG4Af48vbd0D/cd3tCCHEOzB8Avev9urHG4Dv48nv/wX43R+uuC0hhHgf/vF34Mtf7dX3zv/lJ3/l/QghxLvTXX0DQgjx7kgohRCigoRSCCEqSCiFEKKChFIIISpIKIUQooKEUgghKkgohRCigoRSCCEqSCiFEKKChFIIISpIKIUQooKEUgghKkgohRCigoRSCCEq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrangeLight {
            get {
                return ResourceManager.GetString("OrangeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABK/SURBVHic7Z1dcuQ2EoSzJY1GGnvv4T3Ujl99AkfsCTbCJ/CrvYcaH8Se0U+3uA9kDpPVIAGw2SRnnV8EgyQIgmxJnaoCCoUDADRo/gXg3wD+CWOMMQDwCcB/Djj899Cg+Qjgt63fyBhjdsqPhwbNJwA/AAC+B/Bh0xcyxpjt+Qzgz69nfxwaNEcAtwCAXwD8tMlrGWPMfvgVwM9fz06HBk2z3dsYY8z+udn6BYwxZu9YKI0xJoOF0hhjMlgojTEmg4XSGGMyWCiNMSaDhdIYYzJYKI0xJoOF0hhjMlgojTEmg4XSGGMyWCiNMSaDhdIYYzJYKI0xJoOF0hhjMlgojTEmg4XSGGMyWCiNMSaDhdIY [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABL8SURBVHic7Z090uS4kYZfoD7dQJZivQlFrNaQN0eRvB2dY04w55DW0x5FsmRoQqGQp1CsMTfYLqQMIsFEEiRAVhVZ3f0+EdX1B4Cs6uLzJf4DAMgf//TfQPgewK9ACCEEAH4E5Ifw22//J8j//uk7SPj91WdECCFvSZDffUDC9+WFjwjc4oVnRAghb8A9AZ/S9FjC9x8Aflne/K9fAN/8/JoTI4SQd+EfPwF/+ac++2WQP/5ZrjwfQgh5d1jPJoSQDhQlIYR0oCgJIaQDRUkIIR0oSkII6UBREkJIB4qSEEI6UJSEENKBoiSEkA4UJSGEdKAoCSGkA0VJCCEdKEpCCOlAURJCSAeKkhBCOlCUhBDS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinkLight {
            get {
                return ResourceManager.GetString("PinkLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABj7SURBVHic7Z2/suy4ccY/gOTMOVer0I+gKjvfXKVAj2E7Ve4qVSmxrqKt8hMoVekxNtEDbOJIjvwUq3vPDAnAAdANgEMOyfm/6+93a+oMSRDkzDn8bgPd6DYA8Cf86V8Dwh8A/AsIIYQAwN8NzHd/xB//aj7j878B+Muz74gQQl6Uf28B/EG2dt/s0H3qnng/hBDyfPovPY4/HmXzDy2AX8nWr//z1/j2d98+5cYIIeRV+OHPP+D7338vm78yn/E5PPOGCCHk1bHPvgFCCHl1KJSEELIAhZIQQhagUBJCyAIUSkIIWYBCSQghC1AoCSFkAQolIYQsQKEkhJAFKJSEELIAhZIQQhagUBJCyAIUSkII [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABNPSURBVHic7Z1dcuM4EoSLtixL7p57zB5qZ177BB2xJ9iIPkG/zuyheg7S7da/9gGRi2QZJACSIuWd/CIY4g8IUbaVrkIVCo2Z2dXsn2b2LzP7hwkhhDAz+2Zm/27M/tNczX4zsz+WfiIhhLhTfm+uQTV/NTOzjx/NXl6WfSQhhFia11ez799x9FdzNTuZ2aOZmX35Yvbp01KPJoQQ98HXr2afP+Po3FzNrks+jxBC3DsPSz+AEELcOxJKIYTIIKEUQogMEkohhMggoRRCiAwSSiGEyCChFEKIDBJKIYTIIKEUQogMEkohhMggoRRCiAwSSiGEyCChFEKIDBJKIYTIIKEUQogMEkohhMggoRRCiAwS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA8dSURBVHic7Z07kis3EkWT/dNKFDHjP1+WljGadchSy9I6pFmG5MiRI/kytJNudnMMxhUvk0ABVawP++mciAqyABSq+Ni8LxMJJHYREYfvv/9PHA7fRsS/AwAAIiL+jN3uh9133/1vd3h+/iYiftz6iQAAbpT/PkTEt3+fPj1FPD5u9zgAALfA62vEy4vOvn2IiC//rvzqq4hPn7Z4LACA2+H33yN++UVnX+4Oz8+HLZ8HAODWudv6AQAAbh2EEgCgAUIJANAAoQQAaIBQAgA0QCgBABoglAAADRBKAIAGCCUAQAOEEgCgAUIJANAAoQQAaIBQAgA0QCgBABoglAAADRBKAIAGCCUAQAOEEgCgAUIJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RedLight {
            get {
                return ResourceManager.GetString("RedLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABmsSURBVHic7Z3Pjiu7cca/Ivv4QQwYsAEHyMYbv0bgZZyFswy89xN4n2QZL+wsk7yGN14kgA1cIwb8IBmxKgtWkexW/5M0I8259/tdnDtSN5tNaUafiqxilQDAf/3bv/69if0KwI9ACCEEAL4Rk1//3T/+07/Lf/zmn38ukN++ekSEEPIZMdg/TAL5VRyYvnxBztMrx0QIIS+nlAsub28AAIH8agLwgzj5o7/9Cb7/wx+/amyEEPIp+Ouf/4Q//uH38fQH8p+/+Rd75YAIIeSzk149AEII+exQKAkh5AAKJSGEHEChJISQAyiUhBByAIWSEEIOoFASQsgBFEpCCDmAQkkIIQdQKAkh5AAKJSGEHECh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABhSSURBVHic7Z27jizHkYb/rMrqnjmkzH0EAZJPX5Chx9hdV/4CAuisjiwCegK5Ah+DDh+AjizK2qcgz5muS+YaFZEdlVPX7uoLpf8DGlOXrKzqnul/IjIiIx0A4C9/+U/E+DWA34IQQggA/AjnvsGf//ytw8eP/wXg749+IkIIeVL+2wP4Wve+PBzwoaoe+DyEEPJ4PjUNfqpr3f3aA/i17v3v736HP3711UMejBBCnoW//fAD/vTdd7r7a4ePH+MjH4gQQp6d4tEPQAghzw6FkhBCFqBQEkLIAhRKQghZgEJJCCELUCgJIWQBCiUhhCxAoSSEkAUolIQQsgCFkhBCFqBQEkLIAhRKQghZgEJJCCEL [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABPHSURBVHic7Z1bjttMkoWDupBSwQvpWdT8/eoVGOgVDOAV+LV7FuVeiC1KpFTsB+NkHYaTTN5Eyo3zAYJ4SSYp2ToVkREZmZmZNU3zv2b2DzP7HxNCCGFm9t3M/i/Lsv/Pmqb5y8z+ufUTCSHEi/L3rGma72b2NzOzHz9+2OVy2fiZhBBiW97e3uzTp0/Y/XfWNM3dzPZmZl++fLFv375t9nBCCPEKfP782b5+/YrdR9Y0TbPlAwkhxKuz2/oBhBDi1ZFQCiFEAgmlEEIkkFAKIUQCCaUQQiSQUAohRAIJpRBCJJBQCiFEAgmlEEIkkFAKIUQCCaUQQiSQUAohRAIJpRBCJJBQCiFEAgmlEEIkkFAK [rest of string was truncated]&quot;;.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABK8SURBVHic7Z1rcuTGEYRz+FpyJd9DPpRXf3UCO3wCR+gC9l/Jh1odRNrlY0j4B5DRiWID3XgMgLXyi0Dg1egBuZzcqq7q6hMANA3+BuCfAP4KY4wxAPAZwL9OJ/z31DT4BOCXvd/IGGMOyo+npsFnAD+0598D+LjnCxljzAH4AuB3nvx2ahqcAVy35z8D+GmX1zLGmOPwbwD/4MnrqWnQ7Pg2xhhzeK72fgFjjDk6FkpjjClgoTTGmAIWSmOMKWChNMaYAhZKY4wpYKE0xpgCFkpjjClgoTTGmAIWSmOMKWChNMaYAhZKY4wpYKE0xpgCFkpjjClgoTTGmAIWSmOMKWChNMaYAhZKY4wpYKE0xpgC [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABgASURBVHic7Z1LliQ50YWvFI/MrG5mDFkALKCXQzNlBZzzr+A/hxUwBZbTPS8WwJBhU5WRESExkJlkrnB3yeNdcL9zouIll3tGVtw0k5nMHADEn/B7OPwfgN+BEEIIAHxGxP+7H/B3F3/Cj3D466OviBBCnpKIP7j4Mz4D+C0AwH8P+E+PvShCCHk04QsQftFn/3DxZxwArAAAv/kz8Os/PurSCCHkOfjXX4B//kmfHV38GfGR10MIIc+Of/QFEELIs0OhJISQBhRKQghpQKEkhJAGFEpCCGlAoSSEkAYUSkIIaUChJISQBhRKQghpQKEkhJAGFEpCCGlAoSSEkAYUSkIIaUChJISQBhRKQghpQKEk [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowDark {
            get {
                return ResourceManager.GetString("YellowDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAUoAAACACAYAAABtLSBjAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXoAAAF6AB5m6sFgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABEsSURBVHic7Z1Nsuu2EYUPdG8qydBrcLnKySC7cWZx1pEVeB12Zs5uPIiTcnkL9tB25UrIQGjwoAkS4I9I3ffOV6UnkQJAUE86txsNNAIAxJ+//Rsi/gHgTxBCCAEA3yPgq/DJX/8Z4s//+hIxfn12j4QQ4ikJ4e8h/vTt9wA+v594BfByap+EEOJ8rkB8s4P/vAL4LL/3hz8Dv//0jF4JIcTz8NuPwC/f2dFnIf70bTyzP0II8exczu6AEEI8OxJKIYRoIKEUQogGEkohhGggoRRCiAYSSiGEaCChFEKIBhJKIYRoIKEUQogGEkohhGggoRRCiAYSSiGEaCChFEKIBhJKIYRoIKEUQogGEkohhGgg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YellowLight {
            get {
                return ResourceManager.GetString("YellowLight", resourceCulture);
            }
        }
    }
}
